//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/snippetrunner/SnipRunFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(SnipRunActionComponent, kSnipRunActionComponentImpl)
REGISTER_PMINTERFACE(SnipRunPanelWidgetObserver, kSnipRunPanelWidgetObserverImpl)
REGISTER_PMINTERFACE(SnipRunControlView, kSnipRunControlViewImpl)
REGISTER_PMINTERFACE(SnipRunSuiteASB, kSnipRunSuiteASBImpl)
REGISTER_PMINTERFACE(SnipRunSuiteCSB, kSnipRunSuiteCSBImpl)
REGISTER_PMINTERFACE(SnipRunDialogController, kSnipRunDialogControllerImpl)
REGISTER_PMINTERFACE(SnipRunDialogData, kSnipRunDialogDataImpl)
REGISTER_PMINTERFACE(SnipRunGoSelectionObserver, kSnipRunGoSelectionObserverImpl)
REGISTER_PMINTERFACE(SnipRunGoButtonObserver, kSnipRunGoButtonObserverImpl)
REGISTER_PMINTERFACE(SnpRunnableContextCSB, kSnpRunnableContextCSBImpl)
REGISTER_PMINTERFACE(SnipRunRestoreLogCmd, kSnipRunRestoreLogCmdImpl)
REGISTER_PMINTERFACE(SnipRunParameterUtils, kSnipRunParameterUtilsImpl)
REGISTER_PMINTERFACE(SnipRunScriptProvider, kSnipRunScriptProviderImpl)
REGISTER_PMINTERFACE(SnpRunnableScript, kSnpRunnableScriptImpl)
REGISTER_PMINTERFACE(SnpRunnableScriptProvider, kSnpRunnableScriptProviderImpl)
REGISTER_PMINTERFACE(SnipRunErrorStringService, kSnipRunErrorStringServiceImpl)
REGISTER_PMINTERFACE(SnipRunStartupShutdown, kSnipRunStartupShutdownImpl)
REGISTER_PMINTERFACE(SnipRunQuickApplyService, kSnippetRunnerQuickApplyServiceImpl)

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, SnipRunFactoryList.h.



