//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/inxerrorloggingui/INXErrLogUIID.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __INXErrLogUIID_h__
#define __INXErrLogUIID_h__

#include "SDKDef.h"

// Company:
#define kINXErrLogUICompanyKey	kSDKDefPlugInCompanyKey		// Company name used internally for menu paths and the like. Must be globally unique, only A-Z, 0-9, space and "_".
#define kINXErrLogUICompanyValue	kSDKDefPlugInCompanyValue	// Company name displayed externally.

// Plug-in:
#define kINXErrLogUIPluginName	"INXErrorLoggingUI"			// Name of this plug-in.
#define kINXErrLogUIPrefixNumber	0x125200 		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
#define kINXErrLogUIVersion		kSDKDefPluginVersionString						// Version of this plug-in (for the About Box).
#define kINXErrLogUIAuthor		"Adobe Developer Technologies"					// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kINXErrLogUIPrefixNumber above to modify the prefix.)
#define kINXErrLogUIPrefix		RezLong(kINXErrLogUIPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kINXErrLogUIStringPrefix	SDK_DEF_STRINGIZE(kINXErrLogUIPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// Missing plug-in: (see ExtraPluginInfo resource)
#define kINXErrLogUIMissingPluginURLValue		kSDKDefPartnersStandardValue_enUS // URL displayed in Missing Plug-in dialog
#define kINXErrLogUIMissingPluginAlertValue	kSDKDefMissingPluginAlertValue // Message displayed in Missing Plug-in dialog - provide a string that instructs user how to solve their missing plug-in problem

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kINXErrLogUIPluginID, kINXErrLogUIPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kINXErrLogUIActionComponentBoss, kINXErrLogUIPrefix + 0)

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kINXErrLogUIActionComponentImpl, kINXErrLogUIPrefix + 0 )

// ActionIDs:
DECLARE_PMID(kActionIDSpace, kINXErrLogUIAboutActionID, kINXErrLogUIPrefix + 0)
DECLARE_PMID(kActionIDSpace, kINXErrLogUIToggleActionID, kINXErrLogUIPrefix + 1)

// "About Plug-ins" sub-menu:
#define kINXErrLogUIAboutMenuKey			kINXErrLogUIStringPrefix "kINXErrLogUIAboutMenuKey"
#define kINXErrLogUIAboutMenuPath		kSDKDefStandardAboutMenuPath kINXErrLogUICompanyKey

// "Plug-ins" sub-menu:
#define kINXErrLogUIPluginsMenuKey 		kINXErrLogUIStringPrefix "kINXErrLogUIPluginsMenuKey"
#define kINXErrLogUIPluginsMenuPath		kSDKDefPlugInsStandardMenuPath kINXErrLogUICompanyKey kSDKDefDelimitMenuPath kINXErrLogUIPluginsMenuKey

// Menu item keys:
#define kINXErrLogUIToggleMenuKey kINXErrLogUIStringPrefix "kINXErrLogUIToggleMenuKey"
#define kINXErrLogUIToggleMenuInstallKey kINXErrLogUIStringPrefix "kINXErrLogUIToggleMenuInstallKey"
#define kINXErrLogUIToggleMenuRemoveKey kINXErrLogUIStringPrefix "kINXErrLogUIToggleMenuRemoveKey"


// Other StringKeys:
#define kINXErrLogUIAboutBoxStringKey	kINXErrLogUIStringPrefix "kINXErrLogUIAboutBoxStringKey"
#define kINXErrLogUITargetMenuPath kINXErrLogUIPluginsMenuPath

#define kINXErrLogUIChooseFileStringKey kINXErrLogUIStringPrefix "kINXErrLogUIChooseFileStringKey"

// Menu item positions:
#define kINXErrLogUIToggleMenuItemPosition 1.0

// Initial data format version numbers
#define kINXErrLogUIFirstMajorFormatNumber  RezLong(1)
#define kINXErrLogUIFirstMinorFormatNumber  RezLong(0)

// Data format version numbers for the PluginVersion resource 
#define kINXErrLogUICurrentMajorFormatNumber kINXErrLogUIFirstMajorFormatNumber
#define kINXErrLogUICurrentMinorFormatNumber kINXErrLogUIFirstMinorFormatNumber

#endif // __INXErrLogUIID_h__

//  Code generated by DollyXs code generator
