//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/text/FindChangeID.h $
//  
//  Owner:
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __FindChangeID__
#define __FindChangeID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

#define kFindChangePrefix	RezLong(0x4900)
#define kFindChangePrefix2	RezLong(0x1f300)

#define kFindChangeMetaCharRsrcID		101


// <Start IDC>
// PluginID
#define kFindChangePluginName 			"Find and Change Panel"
DECLARE_PMID(kPlugInIDSpace, kFindChangePluginID, kFindChangePrefix + 1)

// <Class ID>
// Boss IDs
DECLARE_PMID(kClassIDSpace, kFindChangeTestBoss, kFindChangePrefix + 1)
//gap
DECLARE_PMID(kClassIDSpace, kFindPanelWidgetBoss, kFindChangePrefix + 6)
//gap
DECLARE_PMID(kClassIDSpace, kFindPanelRegisterBoss, kFindChangePrefix + 8)
DECLARE_PMID(kClassIDSpace, kFindChangeMenuBoss, kFindChangePrefix + 9)
DECLARE_PMID(kClassIDSpace, kFindChangeEditObserverBoss, kFindChangePrefix + 10)
//gap
DECLARE_PMID(kClassIDSpace, kFindChangeTestMenuBoss, kFindChangePrefix + 14)
DECLARE_PMID(kClassIDSpace, kFindChangeScopeObserverBoss, kFindChangePrefix + 15)
//gap
DECLARE_PMID(kClassIDSpace, kChangeMetaMenuComponentBoss, kFindChangePrefix + 21)
DECLARE_PMID(kClassIDSpace, kFindMetaMenuComponentBoss, kFindChangePrefix + 22)
DECLARE_PMID(kClassIDSpace, kFindChangeListObserverBoss, kFindChangePrefix + 23)
DECLARE_PMID(kClassIDSpace, kFindChangeComboboxObserverBoss, kFindChangePrefix + 24)
DECLARE_PMID(kClassIDSpace, kFindChangeKeyboardShortcutsBoss, kFindChangePrefix + 25)
DECLARE_PMID(kClassIDSpace, kLoadFindTextCmdBoss, kFindChangePrefix + 26)
DECLARE_PMID(kClassIDSpace, kLoadReplaceTextCmdBoss, kFindChangePrefix + 27)
DECLARE_PMID(kClassIDSpace, kOversetObserverBoss, kFindChangePrefix + 28)
DECLARE_PMID(kClassIDSpace, kFindStatusBoxObserverBoss, kFindChangePrefix + 29)
DECLARE_PMID(kClassIDSpace, kChangeStatusBoxObserverBoss, kFindChangePrefix + 30)
DECLARE_PMID(kClassIDSpace, kFindChangeMetaCharButtonWidgetBoss, kFindChangePrefix + 31)

DECLARE_PMID(kClassIDSpace, kKanaWidgetObserverBoss, kFindChangePrefix + 32)
DECLARE_PMID(kClassIDSpace, kWidthWidgetObserverBoss, kFindChangePrefix + 33)
DECLARE_PMID(kClassIDSpace, kFindCharacterTypeObserverBoss, kFindChangePrefix + 35)
DECLARE_PMID(kClassIDSpace, kReplaceCharacterTypeObserverBoss, kFindChangePrefix + 36)
DECLARE_PMID(kClassIDSpace, kFindChangeCommandTestMenuBoss, kFindChangePrefix + 37)
DECLARE_PMID(kClassIDSpace, kKillerFindDialogBoss, kFindChangePrefix + 38)
DECLARE_PMID(kClassIDSpace, kKillerFindWindowBoss, kFindChangePrefix + 39)
DECLARE_PMID(kClassIDSpace, kKillerFindTreeViewWidgetBoss, kFindChangePrefix + 40)
DECLARE_PMID(kClassIDSpace, kKillerFindEditWidgetBoss, kFindChangePrefix + 41)
DECLARE_PMID(kClassIDSpace, kFindChangeSwatchesRIDXNotifierHandlerBoss, kFindChangePrefix + 42)
DECLARE_PMID(kClassIDSpace, kEventOverrideBoss, kFindChangePrefix + 43)
DECLARE_PMID(kClassIDSpace, kApplyStyleServiceBoss, kFindChangePrefix + 44)
DECLARE_PMID(kClassIDSpace, kApplyActionServiceBoss, kFindChangePrefix + 45)
//gap
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogWidgetBoss, kFindChangePrefix + 53)
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogTextPanelBoss, kFindChangePrefix + 54)
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogGrepPanelBoss, kFindChangePrefix + 55)
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogGlyphPanelBoss, kFindChangePrefix + 56)
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogObjectPanelBoss, kFindChangePrefix + 57)
DECLARE_PMID(kClassIDSpace, kFindQueryDropDownBoss, kFindChangePrefix + 58)
//gap
DECLARE_PMID(kClassIDSpace, kIncludeHiddenLayersROButtonWidgetBoss, kFindChangePrefix + 60)
DECLARE_PMID(kClassIDSpace, kIncludeLockedLayersROButtonWidgetBoss, kFindChangePrefix + 61)
DECLARE_PMID(kClassIDSpace, kIncludeLockedStoryROButtonWidgetBoss, kFindChangePrefix + 62)
DECLARE_PMID(kClassIDSpace, kIncludeFootnotesROButtonWidgetBoss, kFindChangePrefix + 63)
DECLARE_PMID(kClassIDSpace, kIncludeMasterPagesROButtonWidgetBoss, kFindChangePrefix + 64)
DECLARE_PMID(kClassIDSpace, kFCWholeWordROButtonWidgetBoss, kFindChangePrefix + 65)
DECLARE_PMID(kClassIDSpace, kFCCaseSensitiveROButtonWidgetBoss, kFindChangePrefix + 66)
DECLARE_PMID(kClassIDSpace, kFCDistinguishKanaROButtonWidgetBoss, kFindChangePrefix + 67)
DECLARE_PMID(kClassIDSpace, kFCDistinguishWidthROButtonWidgetBoss, kFindChangePrefix + 68)
DECLARE_PMID(kClassIDSpace, kFindFormatROButtonObserverBoss, kFindChangePrefix + 69)
DECLARE_PMID(kClassIDSpace, kFindClearROButtonObserverBoss, kFindChangePrefix + 70)
DECLARE_PMID(kClassIDSpace, kChangeFormatROButtonObserverBoss, kFindChangePrefix + 71)
DECLARE_PMID(kClassIDSpace, kChangeClearROButtonObserverBoss, kFindChangePrefix + 72)
DECLARE_PMID(kClassIDSpace, kQuickApplyTreeNodeTextWidgetBoss, kFindChangePrefix + 73)
DECLARE_PMID(kClassIDSpace, kFindGlyphDropDownBoss, kFindChangePrefix + 74)
DECLARE_PMID(kClassIDSpace, kChangeGlyphDropDownBoss, kFindChangePrefix + 75)
DECLARE_PMID(kClassIDSpace, kFindGrepMetaMenuComponentBoss, kFindChangePrefix + 76)
DECLARE_PMID(kClassIDSpace, kChangeGrepMetaMenuComponentBoss, kFindChangePrefix + 77)
DECLARE_PMID(kClassIDSpace, kFindTextPanelModeSwitchButtonWidgetBoss, kFindChangePrefix + 78)
DECLARE_PMID(kClassIDSpace, kTextPanelFindButtonObserverBoss, kFindChangePrefix + 79)
DECLARE_PMID(kClassIDSpace, kTextPanelReplaceButtonObserverBoss, kFindChangePrefix + 80)
DECLARE_PMID(kClassIDSpace, kTextPanelReplaceFindButtonObserverBoss, kFindChangePrefix + 81)
DECLARE_PMID(kClassIDSpace, kTextPanelReplaceAllButtonObserverBoss, kFindChangePrefix + 82)
DECLARE_PMID(kClassIDSpace, kFCSearchBackwardsRadioButtonWidgetBoss, kFindChangePrefix + 83)
DECLARE_PMID(kClassIDSpace, kFCSearchForwardRadioButtonWidgetBoss, kFindChangePrefix + 84)
//gap
DECLARE_PMID(kClassIDSpace, kFCGlyphFontCBEditBoxWidgetBoss, kFindChangePrefix + 86)
DECLARE_PMID(kClassIDSpace, kFCGlyphWindowPopupBoss, kFindChangePrefix + 87)
DECLARE_PMID(kClassIDSpace, kFCGlyphPanelPopupBoss, kFindChangePrefix + 88)
DECLARE_PMID(kClassIDSpace, kFCGlyphIconPopupBoss, kFindChangePrefix + 89)
//gap
DECLARE_PMID(kClassIDSpace, kFCSimpleGlyphGridBoss, kFindChangePrefix + 91)
DECLARE_PMID(kClassIDSpace, kFCFontFamilyWidgetBoss, kFindChangePrefix + 92)
DECLARE_PMID(kClassIDSpace, kFCFontStyleWidgetBoss, kFindChangePrefix + 93)
DECLARE_PMID(kClassIDSpace, kFindGlyphFormatWidgetBoss, kFindChangePrefix + 94)
DECLARE_PMID(kClassIDSpace, kFCGlyphTextEditBoxWidgetBoss, kFindChangePrefix + 95)
DECLARE_PMID(kClassIDSpace, kFCGlyphZoomOutWidgetBoss, kFindChangePrefix + 96)
DECLARE_PMID(kClassIDSpace, kFCGlyphZoomInWidgetBoss, kFindChangePrefix + 97)
DECLARE_PMID(kClassIDSpace, kFCGlyphPanelModeListBoss, kFindChangePrefix + 98)
DECLARE_PMID(kClassIDSpace, kFCSingleGlyphPanelBoss, kFindChangePrefix + 99)

DECLARE_PMID(kClassIDSpace, kGlyphPanelFindButtonObserverBoss, kFindChangePrefix + 100)
DECLARE_PMID(kClassIDSpace, kGlyphPanelReplaceButtonObserverBoss, kFindChangePrefix + 101)
DECLARE_PMID(kClassIDSpace, kGlyphPanelReplaceFindButtonObserverBoss, kFindChangePrefix + 102)
DECLARE_PMID(kClassIDSpace, kGlyphPanelReplaceAllButtonObserverBoss, kFindChangePrefix + 103)
DECLARE_PMID(kClassIDSpace, kGrepPanelFindButtonObserverBoss, kFindChangePrefix + 104)
DECLARE_PMID(kClassIDSpace, kGrepPanelReplaceButtonObserverBoss, kFindChangePrefix + 105)
DECLARE_PMID(kClassIDSpace, kGrepPanelReplaceFindButtonObserverBoss, kFindChangePrefix + 106)
DECLARE_PMID(kClassIDSpace, kGrepPanelReplaceAllButtonObserverBoss, kFindChangePrefix + 107)
//gap

DECLARE_PMID(kClassIDSpace, kObjectIncludeLockedLayersROButtonWidgetBoss, kFindChangePrefix + 109)
DECLARE_PMID(kClassIDSpace, kObjectIncludeHiddenLayersROButtonWidgetBoss, kFindChangePrefix + 110)
DECLARE_PMID(kClassIDSpace, kObjectIncludeLockedStoryROButtonWidgetBoss, kFindChangePrefix + 111)
DECLARE_PMID(kClassIDSpace, kObjectIncludeFootnotesROButtonWidgetBoss, kFindChangePrefix + 112)
DECLARE_PMID(kClassIDSpace, kObjectIncludeMasterPagesROButtonWidgetBoss, kFindChangePrefix + 113)
DECLARE_PMID(kClassIDSpace, kObjectFindFormatROButtonObserverBoss, kFindChangePrefix + 114)
DECLARE_PMID(kClassIDSpace, kObjectFindClearROButtonObserverBoss, kFindChangePrefix + 115)
DECLARE_PMID(kClassIDSpace, kObjectChangeFormatROButtonObserverBoss, kFindChangePrefix + 116)
DECLARE_PMID(kClassIDSpace, kObjectChangeClearROButtonObserverBoss, kFindChangePrefix + 117)
DECLARE_PMID(kClassIDSpace, kObjectFindChangeScopeObserverBoss, kFindChangePrefix + 118)
DECLARE_PMID(kClassIDSpace, kObjectFindChangeTypeObserverBoss, kFindChangePrefix + 119)
DECLARE_PMID(kClassIDSpace, kObjectFindStatusBoxObserverBoss, kFindChangePrefix + 120)
DECLARE_PMID(kClassIDSpace, kObjectChangeStatusBoxObserverBoss, kFindChangePrefix + 121)
DECLARE_PMID(kClassIDSpace, QuickApplyPrefsPopUpBoss, kFindChangePrefix + 122)
DECLARE_PMID(kClassIDSpace, kQuickApplyPrefsActionComponentBoss, kFindChangePrefix + 123)
DECLARE_PMID(kClassIDSpace, kGrepFindChangeListObserverBoss, kFindChangePrefix + 124)
DECLARE_PMID(kClassIDSpace, kGrepFindChangeComboboxObserverBoss, kFindChangePrefix + 125)

DECLARE_PMID(kClassIDSpace, kGlyphPanelClearGlyphsButtonWidgetBoss, kFindChangePrefix + 148)
DECLARE_PMID(kClassIDSpace, kFindChangeGlyphMenuComponentBoss, kFindChangePrefix + 149)
DECLARE_PMID(kClassIDSpace, kFindGlyphFontFamilyWidgetBoss, kFindChangePrefix + 150)
DECLARE_PMID(kClassIDSpace, kFCGlyphROFontsBoss,			kFindChangePrefix + 151)
//gap
DECLARE_PMID(kClassIDSpace, kApplyScriptServiceBoss, kFindChangePrefix + 153)
DECLARE_PMID(kClassIDSpace, kFCSaveQueryDialogBoss, kFindChangePrefix + 154)
DECLARE_PMID(kClassIDSpace, kFindMiniTabbedDialogTransliteratePanelBoss, kFindChangePrefix + 161)
DECLARE_PMID(kClassIDSpace, kTransliteratePanelFindButtonObserverBoss, kFindChangePrefix + 162)
DECLARE_PMID(kClassIDSpace, kTransliteratePanelReplaceButtonObserverBoss, kFindChangePrefix + 163)
DECLARE_PMID(kClassIDSpace, kTransliteratePanelReplaceFindButtonObserverBoss, kFindChangePrefix + 164)
DECLARE_PMID(kClassIDSpace, kTransliteratePanelReplaceAllButtonObserverBoss, kFindChangePrefix + 165)
DECLARE_PMID(kClassIDSpace, kChangeGlyphFormatWidgetBoss, kFindChangePrefix + 166)
DECLARE_PMID(kClassIDSpace, kObjectPanelFindButtonObserverBoss, kFindChangePrefix + 167)
DECLARE_PMID(kClassIDSpace, kObjectPanelReplaceButtonObserverBoss, kFindChangePrefix + 168)
DECLARE_PMID(kClassIDSpace, kObjectPanelReplaceFindButtonObserverBoss, kFindChangePrefix + 169)
DECLARE_PMID(kClassIDSpace, kObjectPanelReplaceAllButtonObserverBoss, kFindChangePrefix + 170)
DECLARE_PMID(kClassIDSpace, kFCLoadQueryWarningCmdBoss, kFindChangePrefix + 171)
DECLARE_PMID(kClassIDSpace, kFCClipboardCharScrapSuiteBoss, kFindChangePrefix + 172)
DECLARE_PMID(kClassIDSpace, kFindChangeErrorStringServiceBoss, kFindChangePrefix + 173)

//gap

DECLARE_PMID(kClassIDSpace, kFCDiacriticsROButtonWidgetBoss, kFindChangePrefix + 182)
DECLARE_PMID(kClassIDSpace, kFCKashidasROButtonWidgetBoss, kFindChangePrefix + 183)


// <Interface ID>
// IIDs
DECLARE_PMID(kInterfaceIDSpace, IID_IFINDCHANGEMSG, kFindChangePrefix + 1		/* protocol id for FindPanel messages */)
DECLARE_PMID(kInterfaceIDSpace, IID_IFINDPANELOBSERVER, kFindChangePrefix + 2		/* is an IID_IOBSERVER */)
DECLARE_PMID(kInterfaceIDSpace, IID_IFINDCHANGESELECTIONSUITE, kFindChangePrefix + 3	 )
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTWALKERSELECTIONUTILS, kFindChangePrefix + 4)
DECLARE_PMID(kInterfaceIDSpace,IID_ITEXTWALKERSUITEHACK, kFindChangePrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_IWALKERSCOPESUITE, kFindChangePrefix + 6)
//gap
DECLARE_PMID(kInterfaceIDSpace, IID_IKILLERFINDEDITBOXOBSERVER, kFindChangePrefix + 8)
DECLARE_PMID(kInterfaceIDSpace,IID_IFINDCHANGESTRINGSERVICE, kFindChangePrefix + 9)
DECLARE_PMID(kInterfaceIDSpace, IID_IQUICKAPPLYSERVICE, kFindChangePrefix + 10)
DECLARE_PMID(kInterfaceIDSpace, IID_IFILTERKEYMANAGER, kFindChangePrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_IQUICKAPPLYDATA, kFindChangePrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCSCROLLBARREFERENCE, kFindChangePrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCGLYPHGRIDPANELDATA, kFindChangePrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCGLYPHGRIDSELDATA, kFindChangePrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCGLYPHGRIDARRAY, kFindChangePrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCASSOCIATEDWIDGET, kFindChangePrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_IQUICKAPPLYITEMTYPEMANAGER, kFindChangePrefix + 18)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCGLYPHMODEDATA, kFindChangePrefix + 19)
DECLARE_PMID(kInterfaceIDSpace, IID_IQUERYSWITCHERFLAG, kFindChangePrefix + 20)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRROFONTS, kFindChangePrefix + 21)
DECLARE_PMID(kInterfaceIDSpace, IID_IQUICKAPPLYFILTERSERVICE, kFindChangePrefix + 22)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCINTLISTDATA, kFindChangePrefix + 23)
DECLARE_PMID(kInterfaceIDSpace, IID_IFCAPPRESUMEOBSERVER, kFindChangePrefix + 24)

// <Implementation ID>
// ImplementationIDs
DECLARE_PMID(kImplementationIDSpace, kFindTestMenuImpl, kFindChangePrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kFindButtonObserverImpl, kFindChangePrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kReplaceButtonObserverImpl, kFindChangePrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kReplaceFindButtonObserverImpl, kFindChangePrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kReplaceAllButtonObserverImpl, kFindChangePrefix + 5)
//gap
//DECLARE_PMID(kImplementationIDSpace, kFindPanelImpl, kFindChangePrefix + 7//available)
DECLARE_PMID(kImplementationIDSpace, kFindChangeMenuImpl, kFindChangePrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kFindChangeObserverImpl, kFindChangePrefix + 9)
//gap
DECLARE_PMID(kImplementationIDSpace, kCaseWidgetObserverImpl, kFindChangePrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kEntireWordWidgetObserverImpl, kFindChangePrefix + 12)

DECLARE_PMID(kImplementationIDSpace, kFindChangeButtonObserverImpl, kFindChangePrefix + 13		/* base class implementation for kFindButtonObserverImpl, kReplaceButtonObserverImpl, kReplaceFindButtonObserverImpl, kReplaceAllButtonObserverImpl */)
DECLARE_PMID(kImplementationIDSpace, kFindPanelObserverImpl, kFindChangePrefix + 14		/* this observer calls the ITextWalker */)
DECLARE_PMID(kImplementationIDSpace, kSearchBackwardsWidgetObserverImpl, kFindChangePrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kFindChangeCheckboxObserverImpl, kFindChangePrefix + 16		/* base class implementation for kFindCaseSensitiveObserverImpl, kFindEntireWordObserverImpl. */)
DECLARE_PMID(kImplementationIDSpace, kFindChangeTestMenuImpl, kFindChangePrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kFindChangeScopeObserverImpl, kFindChangePrefix + 18)
//gap

DECLARE_PMID(kImplementationIDSpace, kFindFormatButtonObserverImpl, kFindChangePrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kFindClearButtonObserverImpl, kFindChangePrefix + 21		/*kFindStyleClearButtonObserverImpl	kFindChangePrefix + 21 */)
DECLARE_PMID(kImplementationIDSpace, kChangeFormatButtonObserverImpl, kFindChangePrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kChangeClearButtonObserverImpl, kFindChangePrefix + 23)

DECLARE_PMID(kImplementationIDSpace, kFindMetaMenuComponentImpl, kFindChangePrefix + 25		)
DECLARE_PMID(kImplementationIDSpace, kChangeMetaMenuComponentImpl, kFindChangePrefix + 26		)
//gap

DECLARE_PMID(kImplementationIDSpace, kFindChangeListObserver, kFindChangePrefix + 28)
//gap
DECLARE_PMID(kImplementationIDSpace, kFCEditboxScrapSuite, kFindChangePrefix + 30		/* this interface is on kFindChangeListObserverBoss boss */)

DECLARE_PMID(kImplementationIDSpace, kFindChangeKeyboardShortcutsImpl, kFindChangePrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kLoadFindTextCmdImpl, kFindChangePrefix + 32)
DECLARE_PMID(kImplementationIDSpace, kLoadReplaceTextCmdImpl, kFindChangePrefix + 33)

DECLARE_PMID(kImplementationIDSpace, kOversetObserverImpl, kFindChangePrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kFCDialogControllerImpl, kFindChangePrefix + 35)
DECLARE_PMID(kImplementationIDSpace, kFindStatusBoxObserverImpl, kFindChangePrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kChangeStatusBoxObserverImpl, kFindChangePrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kKanaWidgetObserverImpl, kFindChangePrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kWidthWidgetObserverImpl, kFindChangePrefix + 39)

DECLARE_PMID(kImplementationIDSpace, kFindCharacterTypeObserverImpl, kFindChangePrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kReplaceCharacterTypeObserverImpl, kFindChangePrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kFindChangeSuiteTextCSBImpl, kFindChangePrefix + 43)
DECLARE_PMID(kImplementationIDSpace, kFindChangeSuiteASBImpl, kFindChangePrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kTextWalkerSelectionUtilsImpl, kFindChangePrefix + 45)
DECLARE_PMID(kImplementationIDSpace, kTextWalkerTerminatorImpl, kFindChangePrefix + 46)
DECLARE_PMID(kImplementationIDSpace, kFindChangeCommandTestMenuImpl, kFindChangePrefix + 47)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeLayoutCSBImpl, kFindChangePrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeCSBSelectionExtImpl, kFindChangePrefix + 49)

//gap

DECLARE_PMID(kImplementationIDSpace, kTextWalkerSuiteHackASBImpl, kFindChangePrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kTextWalkerSuiteHackASBExtImpl, kFindChangePrefix + 52)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeDefaultCSBImpl, kFindChangePrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeTextCSBImpl, kFindChangePrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeTableCSBImpl, kFindChangePrefix + 55)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeASBImpl, kFindChangePrefix + 56)
DECLARE_PMID(kImplementationIDSpace, kWalkerScopeNonSupportingCSBImpl, kFindChangePrefix + 69)

DECLARE_PMID(kImplementationIDSpace, kKillerFindDialogControllerImpl, kFindChangePrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kKillerFindDlgObserverImpl, kFindChangePrefix + 71)
DECLARE_PMID(kImplementationIDSpace, kKillerFindWindowImpl, kFindChangePrefix + 72)
DECLARE_PMID(kImplementationIDSpace, kKillerFindTreeViewWidgetMgrImpl, kFindChangePrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kKillerFindTreeViewAdapterImpl, kFindChangePrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kKillerFindListDataImpl, kFindChangePrefix + 75)
DECLARE_PMID(kImplementationIDSpace, kKillerFindEditBoxEHImpl, kFindChangePrefix + 76)
DECLARE_PMID(kImplementationIDSpace, kKillerFindEditBoxObserverImpl, kFindChangePrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kKillerFindTreeViewEHImpl, kFindChangePrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kFindChangeSwatchesRIDXNotifierHandlerImpl, kFindChangePrefix + 79)

DECLARE_PMID(kImplementationIDSpace, kKillerFindTopEHImpl, kFindChangePrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kApplyStyleServiceImpl, kFindChangePrefix + 81)
//DECLARE_PMID(kImplementationIDSpace, kQuickApplyRegisterProviderImpl, kFindChangePrefix + 82) moved to widgets
//DECLARE_PMID(kImplementationIDSpace, kDefaultQuickApplyRegisterProviderImpl, kFindChangePrefix + 83) moved to widgets
DECLARE_PMID(kImplementationIDSpace, kApplyActionServiceImpl, kFindChangePrefix + 84)
DECLARE_PMID(kImplementationIDSpace, kQuickApplyTaskImpl, kFindChangePrefix + 85)
DECLARE_PMID(kImplementationIDSpace, kFilterKeyManagerImpl, kFindChangePrefix + 86)
//gap
DECLARE_PMID(kImplementationIDSpace, kQuickApplyViewImpl, kFindChangePrefix + 88)
DECLARE_PMID(kImplementationIDSpace, kQuickApplyTreeViewControllerImpl, kFindChangePrefix + 89)

//gap
DECLARE_PMID(kImplementationIDSpace, kQuickApplyDataImpl, kFindChangePrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kDiacWidgetObserverImpl, kFindChangePrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kKashWidgetObserverImpl, kFindChangePrefix + 93)

//gap

DECLARE_PMID(kImplementationIDSpace, kIncludeMasterPagesWidgetObserverImpl, kFindChangePrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kIncludeLockedLayersWidgetObserverImpl, kFindChangePrefix + 102)
DECLARE_PMID(kImplementationIDSpace, kIncludeLockedStoriesWidgetObserverImpl, kFindChangePrefix + 103)
DECLARE_PMID(kImplementationIDSpace, kIncludeHiddenLayersWidgetObserverImpl, kFindChangePrefix + 104)
DECLARE_PMID(kImplementationIDSpace, kIncludeFootnotesWidgetObserverImpl, kFindChangePrefix + 105)
DECLARE_PMID(kImplementationIDSpace, kFindChangeMiniTabbedDialogCreatorImpl, kFindChangePrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kFindChangeMiniTabbedDialogControllerImpl, kFindChangePrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kFindChangeMiniTabbedDialogSwitcherImpl, kFindChangePrefix + 108)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTextPanelCreatorImpl,kFindChangePrefix + 109)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTextPanelObserverImpl,kFindChangePrefix + 110)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTextPanelControllerImpl,kFindChangePrefix + 111)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGrepPanelCreatorImpl,kFindChangePrefix + 112)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGrepPanelObserverImpl,kFindChangePrefix + 113)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGrepPanelControllerImpl,kFindChangePrefix + 114)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGlyphPanelCreatorImpl,kFindChangePrefix + 115)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGlyphPanelObserverImpl,kFindChangePrefix + 116)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogGlyphPanelControllerImpl,kFindChangePrefix + 117)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogObjectPanelCreatorImpl,kFindChangePrefix + 118)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogObjectPanelObserverImpl,kFindChangePrefix + 119)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogObjectPanelControllerImpl,kFindChangePrefix + 120)
DECLARE_PMID(kImplementationIDSpace, kFindModeSwitchButtonObserverImpl,kFindChangePrefix + 121)
DECLARE_PMID(kImplementationIDSpace, kFindChangeDialogButtonTipImpl,kFindChangePrefix + 122)
DECLARE_PMID(kImplementationIDSpace, kFindTextPanelModeSwitchButtonObserverImpl,kFindChangePrefix + 123)
DECLARE_PMID(kImplementationIDSpace, kChangeGrepMetaMenuComponentImpl,kFindChangePrefix + 124)
DECLARE_PMID(kImplementationIDSpace, kFindGrepMetaMenuComponentImpl,kFindChangePrefix + 125)
//gap
DECLARE_PMID(kImplementationIDSpace, kTextPanelReplaceButtonObserverImpl,kFindChangePrefix + 127)
DECLARE_PMID(kImplementationIDSpace, kTextPanelReplaceFindButtonObserverImpl,kFindChangePrefix + 128)
DECLARE_PMID(kImplementationIDSpace, kTextPanelReplaceAllButtonObserverImpl,kFindChangePrefix + 129)

DECLARE_PMID(kImplementationIDSpace, kFCBaseGlyphGridViewImpl,	kFindChangePrefix + 130)
DECLARE_PMID(kImplementationIDSpace, kFCScrollBarReferenceImpl,	kFindChangePrefix + 131)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridPanelDataImpl,	kFindChangePrefix + 132)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridSelDataImpl,	kFindChangePrefix + 133)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridArrayImpl,		kFindChangePrefix + 134)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridPanelEHImpl,	kFindChangePrefix + 135)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridObserverImpl,	kFindChangePrefix + 136)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphGridTipImpl,		kFindChangePrefix + 137)
DECLARE_PMID(kImplementationIDSpace, kChangeGlyphTargetServerImpl,	kFindChangePrefix + 138)
DECLARE_PMID(kImplementationIDSpace, kFindGlyphTargetServerImpl,	kFindChangePrefix + 139)
DECLARE_PMID(kImplementationIDSpace, kFCFontStyleObserverImpl,	kFindChangePrefix + 140)
DECLARE_PMID(kImplementationIDSpace, kFCFontFamilyObserverImpl,	kFindChangePrefix + 141)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphDialogObserverImpl,	kFindChangePrefix + 142)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphEditBoxObserverImpl,	kFindChangePrefix + 143)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphZoomInObserverImpl,	kFindChangePrefix + 144)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphZoomOutObserverImpl,	kFindChangePrefix + 145)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphModeObserverImpl,		kFindChangePrefix + 146)
DECLARE_PMID(kImplementationIDSpace, kFCSingleGlyphViewImpl,		kFindChangePrefix + 147)
DECLARE_PMID(kImplementationIDSpace, kFCSingleGlyphTipImpl,			kFindChangePrefix + 148)

DECLARE_PMID(kImplementationIDSpace, kGlyphPanelFindButtonObserverImpl,kFindChangePrefix + 150)
DECLARE_PMID(kImplementationIDSpace, kGlyphPanelReplaceButtonObserverImpl,kFindChangePrefix + 151)
DECLARE_PMID(kImplementationIDSpace, kGlyphPanelReplaceFindButtonObserverImpl,kFindChangePrefix + 152)
DECLARE_PMID(kImplementationIDSpace, kGlyphPanelReplaceAllButtonObserverImpl,kFindChangePrefix + 153)
DECLARE_PMID(kImplementationIDSpace, kGrepPanelFindButtonObserverImpl,kFindChangePrefix + 154)
DECLARE_PMID(kImplementationIDSpace, kGrepPanelReplaceButtonObserverImpl,kFindChangePrefix + 155)
DECLARE_PMID(kImplementationIDSpace, kGrepPanelReplaceFindButtonObserverImpl,kFindChangePrefix + 156)
DECLARE_PMID(kImplementationIDSpace, kGrepPanelReplaceAllButtonObserverImpl,kFindChangePrefix + 157)
DECLARE_PMID(kImplementationIDSpace, kFindStatusBoxEHImpl, kFindChangePrefix + 158)
DECLARE_PMID(kImplementationIDSpace, kChangeStatusBoxEHImpl, kFindChangePrefix + 159)
DECLARE_PMID(kImplementationIDSpace, kGlyphTypeDropDownObserverImpl, kFindChangePrefix + 160)
DECLARE_PMID(kImplementationIDSpace, kGlyphPanelClearGlyphsButtonObserverImpl, kFindChangePrefix + 161)

DECLARE_PMID(kImplementationIDSpace, kObjectIncludeHiddenLayersWidgetObserverImpl, kFindChangePrefix + 162)
DECLARE_PMID(kImplementationIDSpace, kObjectIncludeLockedLayersWidgetObserverImpl, kFindChangePrefix + 163)
DECLARE_PMID(kImplementationIDSpace, kObjectIncludeLockedStoriesWidgetObserverImpl, kFindChangePrefix + 164)
DECLARE_PMID(kImplementationIDSpace, kObjectIncludeFootnotesWidgetObserverImpl, kFindChangePrefix + 165)
DECLARE_PMID(kImplementationIDSpace, kObjectIncludeMasterPagesWidgetObserverImpl, kFindChangePrefix + 166)
DECLARE_PMID(kImplementationIDSpace, kObjectFindClearButtonObserverImpl, kFindChangePrefix + 167)
DECLARE_PMID(kImplementationIDSpace, kObjectFindFormatButtonObserverImpl, kFindChangePrefix + 168)
DECLARE_PMID(kImplementationIDSpace, kObjectChangeClearButtonObserverImpl, kFindChangePrefix + 169)
DECLARE_PMID(kImplementationIDSpace, kObjectChangeFormatButtonObserverImpl, kFindChangePrefix + 170)
DECLARE_PMID(kImplementationIDSpace, kObjectFindChangeScopeObserverImpl, kFindChangePrefix + 171)
DECLARE_PMID(kImplementationIDSpace, kObjectFindChangeTypeObserverImpl, kFindChangePrefix + 172)
DECLARE_PMID(kImplementationIDSpace, kObjectFindStatusBoxObserverImpl, kFindChangePrefix + 173)
DECLARE_PMID(kImplementationIDSpace, kObjectFindStatusBoxEHImpl, kFindChangePrefix + 174)
DECLARE_PMID(kImplementationIDSpace, kObjectChangeStatusBoxObserverImpl, kFindChangePrefix + 175)
DECLARE_PMID(kImplementationIDSpace, kFindChangeMiniTabbedDialogObserverImpl, kFindChangePrefix + 176)

DECLARE_PMID(kImplementationIDSpace, kFCGlyphFontCBAttributesImpl,	kFindChangePrefix + 193)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphFontEHImpl,			kFindChangePrefix + 194)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphEditBoxEHImpl,			kFindChangePrefix + 195)
DECLARE_PMID(kImplementationIDSpace, kTextAttrROCompareImpl,		kFindChangePrefix + 196)
DECLARE_PMID(kImplementationIDSpace, kTextAttrROFontsImpl,			kFindChangePrefix + 197)
DECLARE_PMID(kImplementationIDSpace, kFindChangeGlyphMenuComponentImpl, kFindChangePrefix + 198)
//gap
DECLARE_PMID(kImplementationIDSpace, kFCGlyphPopupPanelWidgetAttributesImpl,	kFindChangePrefix + 200)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphPanelPopupViewImpl,	kFindChangePrefix + 201)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphWindowPopupViewImpl,	kFindChangePrefix + 202)
DECLARE_PMID(kImplementationIDSpace, kFCAssociatedWidgetImpl,		kFindChangePrefix + 203)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphPanelObserverImpl,		kFindChangePrefix + 204)
DECLARE_PMID(kImplementationIDSpace, kFindGlyphFontFamilyObserverImpl,kFindChangePrefix + 205)
DECLARE_PMID(kImplementationIDSpace, kQuickApplyItemTypeManagerImpl, kFindChangePrefix + 206)
DECLARE_PMID(kImplementationIDSpace, kQuickApplyPrefsMenuActionImpl, kFindChangePrefix + 207)
DECLARE_PMID(kImplementationIDSpace, kFCGlyphModeDataImpl,			kFindChangePrefix + 208)
//gap
DECLARE_PMID(kImplementationIDSpace, kApplyScriptServiceImpl,		kFindChangePrefix + 210)
DECLARE_PMID(kImplementationIDSpace, kFCGrepEditboxScrapSuite,		kFindChangePrefix + 211)
//gap
DECLARE_PMID(kImplementationIDSpace, kFCSaveQueryDialogControllerImpl, kFindChangePrefix + 213)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTransliteratePanelCreatorImpl, kFindChangePrefix + 221)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTransliteratePanelObserverImpl, kFindChangePrefix + 222)
DECLARE_PMID(kImplementationIDSpace, kFindMiniTabbedDialogTransliteratePanelControllerImpl, kFindChangePrefix + 223)
DECLARE_PMID(kImplementationIDSpace, kTransliteratePanelFindButtonObserverImpl, kFindChangePrefix + 224)
DECLARE_PMID(kImplementationIDSpace, kTransliteratePanelReplaceButtonObserverImpl, kFindChangePrefix + 225)
DECLARE_PMID(kImplementationIDSpace, kTransliteratePanelReplaceFindButtonObserverImpl, kFindChangePrefix + 226)
DECLARE_PMID(kImplementationIDSpace, kTransliteratePanelReplaceAllButtonObserverImpl, kFindChangePrefix + 227)
DECLARE_PMID(kImplementationIDSpace, kObjectPanelFindButtonObserverImpl, kFindChangePrefix + 228)
DECLARE_PMID(kImplementationIDSpace, kObjectPanelReplaceButtonObserverImpl, kFindChangePrefix + 229)
DECLARE_PMID(kImplementationIDSpace, kObjectPanelReplaceFindButtonObserverImpl, kFindChangePrefix + 230)
DECLARE_PMID(kImplementationIDSpace, kObjectPanelReplaceAllButtonObserverImpl, kFindChangePrefix + 231)
DECLARE_PMID(kImplementationIDSpace, kFCLoadQueryWarningCmdImpl, kFindChangePrefix + 232)
DECLARE_PMID(kImplementationIDSpace, kFCClipboardCharScrapSuiteImpl, kFindChangePrefix + 233)
DECLARE_PMID(kImplementationIDSpace, kFindChangeErrorStringServiceImpl, kFindChangePrefix + 234)
DECLARE_PMID(kImplementationIDSpace, kFCTextEditboxDragDropTextTargetImpl, kFindChangePrefix + 235)
DECLARE_PMID(kImplementationIDSpace, kFCGREPEditboxDragDropTextTargetImpl, kFindChangePrefix + 236)
DECLARE_PMID(kImplementationIDSpace, kQuickApplyFilterRegisterProviderImpl, kFindChangePrefix + 237)
DECLARE_PMID(kImplementationIDSpace, kQueryDropDownAppResumeObserverImpl, kFindChangePrefix + 238)
DECLARE_PMID(kImplementationIDSpace, kFCIntListDataImpl, kFindChangePrefix + 239)
DECLARE_PMID(kImplementationIDSpace, kFCEditBoxCBAttributesImpl,	kFindChangePrefix + 240)
DECLARE_PMID(kImplementationIDSpace, kFCGrepEditBoxCBAttributesImpl,	kFindChangePrefix + 241)


// <Widget ID>
// WidgetIDs
DECLARE_PMID(kWidgetIDSpace, kFindEditBoxWidgetID, kFindChangePrefix + 1)
DECLARE_PMID(kWidgetIDSpace, kReplaceEditBoxWidgetID, kFindChangePrefix + 2)
DECLARE_PMID(kWidgetIDSpace, kOversetCheckboxWidgetID, kFindChangePrefix + 3)
DECLARE_PMID(kWidgetIDSpace, kCaseSensitiveCheckboxWidgetID, kFindChangePrefix + 5)
DECLARE_PMID(kWidgetIDSpace, kEntireWordCheckboxWidgetID, kFindChangePrefix + 6)
DECLARE_PMID(kWidgetIDSpace, kFindButtonWidgetID, kFindChangePrefix + 7)
DECLARE_PMID(kWidgetIDSpace, kReplaceButtonWidgetID, kFindChangePrefix + 8)
DECLARE_PMID(kWidgetIDSpace, kReplaceFindButtonWidgetID, kFindChangePrefix + 9)
DECLARE_PMID(kWidgetIDSpace, kReplaceAllButtonWidgetID, kFindChangePrefix + 10)
DECLARE_PMID(kWidgetIDSpace, kSearchScopeWidgetID, kFindChangePrefix + 11)
DECLARE_PMID(kWidgetIDSpace, kMoreButtonWidgetID, kFindChangePrefix + 12)
DECLARE_PMID(kWidgetIDSpace, kFindStatusBoxWidgetID, kFindChangePrefix + 13)
DECLARE_PMID(kWidgetIDSpace, kFindFormatButtonWidgetID, kFindChangePrefix + 14)
DECLARE_PMID(kWidgetIDSpace, kClearFindFormatButtonWidgetID, kFindChangePrefix + 15)
DECLARE_PMID(kWidgetIDSpace, kChangeStatusBoxWidgetID, kFindChangePrefix + 16)
DECLARE_PMID(kWidgetIDSpace, kChangeFormatButtonWidgetID, kFindChangePrefix + 17)
DECLARE_PMID(kWidgetIDSpace, kClearChangeFormatButtonWidgetID, kFindChangePrefix + 18)
DECLARE_PMID(kWidgetIDSpace, kFindMetaCharButtonWidgetID, kFindChangePrefix + 19)
DECLARE_PMID(kWidgetIDSpace, kChangeMetaCharButtonWidgetID, kFindChangePrefix + 20)
DECLARE_PMID(kWidgetIDSpace, kFindFormatSetWarningWidgetID, kFindChangePrefix + 21)
DECLARE_PMID(kWidgetIDSpace, kChangeFormatSetWarningWidgetID, kFindChangePrefix + 22)
DECLARE_PMID(kWidgetIDSpace, kFindFormatScrollWidgetID, kFindChangePrefix + 23)
DECLARE_PMID(kWidgetIDSpace, kChangeFormatScrollWidgetID, kFindChangePrefix + 24)
DECLARE_PMID(kWidgetIDSpace, kFindFormatGroupWidgetID, kFindChangePrefix + 25)
DECLARE_PMID(kWidgetIDSpace, kChangeFormatGroupWidgetID, kFindChangePrefix + 26)
DECLARE_PMID(kWidgetIDSpace, kSearchListEditBoxWidgetID, kFindChangePrefix + 27)
DECLARE_PMID(kWidgetIDSpace, kReplaceListEditBoxWidgetID, kFindChangePrefix + 28)
DECLARE_PMID(kWidgetIDSpace, kOversetWidgetID, kFindChangePrefix + 29)

DECLARE_PMID(kWidgetIDSpace, kFindChangeParentWidgetID, kFindChangePrefix + 30)
DECLARE_PMID(kWidgetIDSpace, kFCWhatTextWidgetID, kFindChangePrefix + 31)
DECLARE_PMID(kWidgetIDSpace, kFCChangeTextWidgetID, kFindChangePrefix + 32)
DECLARE_PMID(kWidgetIDSpace, kFCSearchTextWidgetID, kFindChangePrefix + 33)
DECLARE_PMID(kWidgetIDSpace, kFCStyleTextWidgetID, kFindChangePrefix + 34)
DECLARE_PMID(kWidgetIDSpace, kFCChangeStyleTextWidgetID, kFindChangePrefix + 35)
//gap

//DECLARE_PMID(kWidgetIDSpace, kFindChangeGroupWidgetId, kFindChangePrefix + 37)
//DECLARE_PMID(kWidgetIDSpace, kFindChangeGroup2WidgetId, kFindChangePrefix + 38)
DECLARE_PMID(kWidgetIDSpace, kFindChangeGroup3WidgetId, kFindChangePrefix + 39)
DECLARE_PMID(kWidgetIDSpace, kFindChangeGroup4WidgetId, kFindChangePrefix + 40)
DECLARE_PMID(kWidgetIDSpace, kSearchBackwardsRadioWidgetID, kFindChangePrefix + 41)
DECLARE_PMID(kWidgetIDSpace, kSearchForwardRadioWidgetID, kFindChangePrefix + 42)
DECLARE_PMID(kWidgetIDSpace, kFCDirectionWidgetID, kFindChangePrefix + 43)
DECLARE_PMID(kWidgetIDSpace, kFCDirectionChooserWidgetID, kFindChangePrefix + 44)
//gap
DECLARE_PMID(kWidgetIDSpace, kFindChangeTransliterateDropdownWidgetID, kFindChangePrefix + 51)
DECLARE_PMID(kWidgetIDSpace, kFindCharacterTypeDropDownWidgetID, kFindChangePrefix + 52)
DECLARE_PMID(kWidgetIDSpace, kReplaceCharacterTypeDropDownWidgetID, kFindChangePrefix + 53)
DECLARE_PMID(kWidgetIDSpace, kFittedFindTextPanelWidgetID, kFindChangePrefix + 54)
DECLARE_PMID(kWidgetIDSpace, kInTableWidgetID, kFindChangePrefix + 55)
DECLARE_PMID(kWidgetIDSpace, kKillerFindDialogWidgetID, kFindChangePrefix + 56)
DECLARE_PMID(kWidgetIDSpace, kKillerFindDoActionButtonID, kFindChangePrefix + 57)
DECLARE_PMID(kWidgetIDSpace, kKillerFindEditBoxWidgetID, kFindChangePrefix + 58)
DECLARE_PMID(kWidgetIDSpace, kKillerFindTreeListWidgetID, kFindChangePrefix + 59)

DECLARE_PMID(kWidgetIDSpace, kKillerFindTreeBorderWidgetID, kFindChangePrefix + 60)
//gap
DECLARE_PMID(kWidgetIDSpace, kOnHiddenLayerWidgetID, kFindChangePrefix + 65)
DECLARE_PMID(kWidgetIDSpace, kFindLockedLayersIncludeStaticWidgetID, kFindChangePrefix + 66)
DECLARE_PMID(kWidgetIDSpace, kFindHiddenLayersIncludeStaticWidgetID, kFindChangePrefix + 67)
DECLARE_PMID(kWidgetIDSpace, kOnMasterPageWidgetID, kFindChangePrefix + 68)
DECLARE_PMID(kWidgetIDSpace, kOFCFindTypeWidgetID, kFindChangePrefix + 69)

DECLARE_PMID(kWidgetIDSpace, kObjectClearChangeFormatButtonWidgetID, kFindChangePrefix + 70)
DECLARE_PMID(kWidgetIDSpace, kObjectChangeFormatButtonWidgetID, kFindChangePrefix + 71)
DECLARE_PMID(kWidgetIDSpace, kObjectClearFindFormatButtonWidgetID, kFindChangePrefix + 72)
DECLARE_PMID(kWidgetIDSpace, kObjectFindFormatButtonWidgetID, kFindChangePrefix + 73)
DECLARE_PMID(kWidgetIDSpace, kLoadQueryErrorIconWidgetID, kFindChangePrefix + 74)
DECLARE_PMID(kWidgetIDSpace, kDiacriticsCheckboxWidgetID, kFindChangePrefix + 75)
DECLARE_PMID(kWidgetIDSpace, kKashidasCheckboxWidgetID, kFindChangePrefix + 76)

DECLARE_PMID(kWidgetIDSpace, kFindSingleGlyphParentWidgetId, kFindChangePrefix + 77)
DECLARE_PMID(kWidgetIDSpace, kChangeSingleGlyphParentWidgetId, kFindChangePrefix + 78)

//gap

//GREP (regular expression)
DECLARE_PMID(kWidgetIDSpace, kGrepCheckBoxWidgetID, kFindChangePrefix + 100)

// Mini Tabbed Dialog
DECLARE_PMID(kWidgetIDSpace, kFindQueryStaticWidgetID, kFindChangePrefix + 101)
DECLARE_PMID(kWidgetIDSpace, kFindMinITabbedDialogOKButtonWidgetID, kFindChangePrefix + 102)
DECLARE_PMID(kWidgetIDSpace, kFindMiniTabbedDialogTextPanelParentWidgetID, kFindChangePrefix + 103)
DECLARE_PMID(kWidgetIDSpace, kFindMiniTabbedDialogGrepPanelParentWidgetID, kFindChangePrefix + 104)
DECLARE_PMID(kWidgetIDSpace, kFindMiniTabbedDialogGlyphPanelParentWidgetID, kFindChangePrefix + 105)
DECLARE_PMID(kWidgetIDSpace, kFindMiniTabbedDialogObjectPanelParentWidgetID, kFindChangePrefix + 106)
DECLARE_PMID(kWidgetIDSpace, kFCQuerySaveButtonWidgetID, kFindChangePrefix + 107)
DECLARE_PMID(kWidgetIDSpace, kFindQueryDropDownWidgetID, kFindChangePrefix + 108)
//gap
DECLARE_PMID(kWidgetIDSpace, kFCHiddenLayersWidgetId, kFindChangePrefix + 111)
DECLARE_PMID(kWidgetIDSpace, kFCLockedLayersWidgetId, kFindChangePrefix + 112)
DECLARE_PMID(kWidgetIDSpace, kFCLockedStoryWidgetId, kFindChangePrefix + 113)
DECLARE_PMID(kWidgetIDSpace, kFCMasterPagesWidgetId, kFindChangePrefix + 114)
DECLARE_PMID(kWidgetIDSpace, kFCFootnotesWidgetId, kFindChangePrefix + 115)
DECLARE_PMID(kWidgetIDSpace, kFCWholeWordWidgetId, kFindChangePrefix + 116)
DECLARE_PMID(kWidgetIDSpace, kFCCaseSensitiveWidgetId, kFindChangePrefix + 117)
DECLARE_PMID(kWidgetIDSpace, kFCDistinguishKanaWidgetId, kFindChangePrefix + 118)
DECLARE_PMID(kWidgetIDSpace, kFCDistinguishWidthWidgetId, kFindChangePrefix + 119)
DECLARE_PMID(kWidgetIDSpace, kFCFindFormatStaticTextWidgetID, kFindChangePrefix + 120)
DECLARE_PMID(kWidgetIDSpace, kFCChangeFormatStaticTextWidgetID, kFindChangePrefix + 121)
DECLARE_PMID(kWidgetIDSpace, kFCGlyphPopupPanelParentWidgetId, kFindChangePrefix + 122)
DECLARE_PMID(kWidgetIDSpace, kFCQueryDeleteButtonWidgetID, kFindChangePrefix + 123)
DECLARE_PMID(kWidgetIDSpace, kFindMiniTabbedDialogTransliteratePanelParentWidgetID, kFindChangePrefix + 124)
DECLARE_PMID(kWidgetIDSpace, kFCObjectLockedLayerWidgetID, kFindChangePrefix + 125)
DECLARE_PMID(kWidgetIDSpace, kFCObjectHiddenLayerWidgetID, kFindChangePrefix + 126)
DECLARE_PMID(kWidgetIDSpace, kFCObjectLockedStoryWidgetID, kFindChangePrefix + 127)


DECLARE_PMID(kWidgetIDSpace, kFCSaveQueryDialogWidgetID, kFindChangePrefix + 140)
DECLARE_PMID(kWidgetIDSpace, kFCSaveQueryStaticTextWidgetID, kFindChangePrefix + 141)
DECLARE_PMID(kWidgetIDSpace, kFCNewQueryNameWidgetID, kFindChangePrefix + 142)
DECLARE_PMID(kWidgetIDSpace, kFCNewQueryColumen1WidgetID, kFindChangePrefix + 143)
DECLARE_PMID(kWidgetIDSpace, kFCNewQueryColumen2WidgetID, kFindChangePrefix + 144)
DECLARE_PMID(kWidgetIDSpace, kFCNewQueryColumen3WidgetID, kFindChangePrefix + 145)


DECLARE_PMID(kWidgetIDSpace, kClearGlyphsButtonWidgetID, kFindChangePrefix + 199)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphStaticWidgetID, kFindChangePrefix + 200)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphDropDownWidgetID, kFindChangePrefix + 201)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphEditBoxWidgetID, kFindChangePrefix + 202)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphStaticWidgetID, kFindChangePrefix + 203)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphDropDownWidgetID, kFindChangePrefix + 204)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphEditBoxWidgetID, kFindChangePrefix + 205)


DECLARE_PMID(kWidgetIDSpace, kFindGlyphGroupWidgetId, kFindChangePrefix + 220)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphGridWidgetId, kFindChangePrefix + 221)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphScrollWidgetId, kFindChangePrefix + 222)
DECLARE_PMID(kWidgetIDSpace, kFindCharFmtPanelWidgetId, kFindChangePrefix + 223)
DECLARE_PMID(kWidgetIDSpace, kFindFontFamilyLstWidgetId, kFindChangePrefix + 224)
DECLARE_PMID(kWidgetIDSpace, kFindFontStyleLstWidgetId, kFindChangePrefix + 225)
DECLARE_PMID(kWidgetIDSpace, kFindFontFamilyLblWidgetId, kFindChangePrefix + 226)
DECLARE_PMID(kWidgetIDSpace, kFindFontStyleLblWidgetId, kFindChangePrefix + 227)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphZoomOutWidgetId, kFindChangePrefix + 228)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphZoomInWidgetId, kFindChangePrefix + 229)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphPanelModeListWidgetId, kFindChangePrefix + 230)
DECLARE_PMID(kWidgetIDSpace, kFindSingleGlyphWidgetId, kFindChangePrefix + 231)
DECLARE_PMID(kWidgetIDSpace, kFindGlyphPopupButtonWidgetId, kFindChangePrefix + 232)
DECLARE_PMID(kWidgetIDSpace, kFCDisplayFontStaticTextWidgetId, kFindChangePrefix + 233)


DECLARE_PMID(kWidgetIDSpace, kChangeGlyphGroupWidgetId, kFindChangePrefix + 240)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphGridWidgetId, kFindChangePrefix + 241)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphScrollWidgetId, kFindChangePrefix + 242)
DECLARE_PMID(kWidgetIDSpace, kChangeCharFmtPanelWidgetId, kFindChangePrefix + 243)
DECLARE_PMID(kWidgetIDSpace, kChangeFontFamilyLstWidgetId, kFindChangePrefix + 244)
DECLARE_PMID(kWidgetIDSpace, kChangeFontStyleLstWidgetId, kFindChangePrefix + 245)
DECLARE_PMID(kWidgetIDSpace, kChangeFontFamilyLblWidgetId, kFindChangePrefix + 246)
DECLARE_PMID(kWidgetIDSpace, kChangeFontStyleLblWidgetId, kFindChangePrefix + 247)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphZoomOutWidgetId, kFindChangePrefix + 248)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphZoomInWidgetId, kFindChangePrefix + 249)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphPanelModeListWidgetId, kFindChangePrefix + 250)
DECLARE_PMID(kWidgetIDSpace, kChangeSingleGlyphWidgetId, kFindChangePrefix + 251)
DECLARE_PMID(kWidgetIDSpace, kChangeGlyphPopupButtonWidgetId, kFindChangePrefix + 252)

DECLARE_PMID(kWidgetIDSpace, kQuickApplyPrefsPopUpWidgetID, kFindChangePrefix + 253)
DECLARE_PMID(kWidgetIDSpace, kFCDeleteQueryWarningWidgetID, kFindChangePrefix + 254)



// <Message ID>
// Message IDs

DECLARE_PMID(kMessageIDSpace, kFCGridSelectionChangeMessage, kFindChangePrefix + 100)
DECLARE_PMID(kMessageIDSpace, kFCGridFontChangeMessage, kFindChangePrefix + 101)
DECLARE_PMID(kMessageIDSpace, kFindGridSelectionChangeMessage, kFindChangePrefix + 102)
DECLARE_PMID(kMessageIDSpace, kChangeGridSelectionChangeMessage, kFindChangePrefix + 103)
DECLARE_PMID(kMessageIDSpace, kFavoriteGlyphSelectionChangeMessage, kFindChangePrefix + 104)
DECLARE_PMID(kMessageIDSpace, kFindGlyphStoryChangeMessage, kFindChangePrefix + 105)


DECLARE_PMID(kMessageIDSpace, kFindNewFindTextMessage, kFindChangePrefix + 200)			/* New text in find editbox and <return> */
DECLARE_PMID(kMessageIDSpace, kFindNewReplaceTextMessage, kFindChangePrefix + 201)		/* New text in replace editbox and <return> */
DECLARE_PMID(kMessageIDSpace, kFindNewCaseSensitiveMessage, kFindChangePrefix + 202)	/* 'ignore case' check box has been changed  */
DECLARE_PMID(kMessageIDSpace, kFindNewEntireWordMessage, kFindChangePrefix + 203)		/* 'entire word' check box has been changed  */
DECLARE_PMID(kMessageIDSpace, kFindDoFindMessage, kFindChangePrefix + 204)				/* 'Find' button has been pressed  */
DECLARE_PMID(kMessageIDSpace, kFindDoReplaceMessage, kFindChangePrefix + 205)			/* 'Change' button has been pressed */
DECLARE_PMID(kMessageIDSpace, kFindDoReplaceFindMessage, kFindChangePrefix + 206)		/* 'Change/Find' button has been pressed */
DECLARE_PMID(kMessageIDSpace, kFindDoReplaceAllMessage, kFindChangePrefix + 207)		/* 'Change All' button has been pressed */
DECLARE_PMID(kMessageIDSpace, kFindDoMoreMessage, kFindChangePrefix + 208)				/* 'More...' or 'Less...' button has been pressed */
DECLARE_PMID(kMessageIDSpace, kFindFindStyleFormatMessage, kFindChangePrefix + 209)
DECLARE_PMID(kMessageIDSpace, kFindClearFindFormatMessage, kFindChangePrefix + 210)
DECLARE_PMID(kMessageIDSpace, kFindChangeStyleFormatMessage, kFindChangePrefix + 211)
DECLARE_PMID(kMessageIDSpace, kFindClearChangeFormatMessage, kFindChangePrefix + 212)
DECLARE_PMID(kMessageIDSpace, kFindFindTextNotEmptyMessage, kFindChangePrefix + 213)	/* non-zero length search text */
DECLARE_PMID(kMessageIDSpace, kFindFindTextEmptyMessage, kFindChangePrefix + 214)		/* zero length search text */
DECLARE_PMID(kMessageIDSpace, kFindReplaceTextNotEmptyMessage, kFindChangePrefix + 215)	/* non-zero length replace text */
DECLARE_PMID(kMessageIDSpace, kLoadFindStringMsg, kFindChangePrefix + 216)
DECLARE_PMID(kMessageIDSpace, kFindFindDoneMessage, kFindChangePrefix + 217				)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kFindReplaceSuccessMessage, kFindChangePrefix + 218		)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kFindReplaceFindDoneMessage, kFindChangePrefix + 219		)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kFindReplaceAllDoneMessage, kFindChangePrefix + 220		)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kFindFindSuccessMessage, kFindChangePrefix + 221			)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kUpdateFindStatusBoxDoneMessage, kFindChangePrefix + 222	)/* for button enabling/disabling		 */
DECLARE_PMID(kMessageIDSpace, kUpdateChangeStatusBoxDoneMessage, kFindChangePrefix + 223		/* for button enabling/disabling		 */)
DECLARE_PMID(kMessageIDSpace, kFindChangeRefereshWidgetMessage, kFindChangePrefix + 224	)	/* fetch the value from ifindchnage options and refresh the widget*/
DECLARE_PMID(kMessageIDSpace, kFindChangeValueChangedMessage, kFindChangePrefix + 225	)	/*  trigger to the Query dropdown to switch to the custom query */
DECLARE_PMID(kMessageIDSpace, kFindChangeRefereshWidgetLvl0Message, kFindChangePrefix + 226	)	/*  we can referesh the widgets in sequence */

// <Action ID>
DECLARE_PMID(kActionIDSpace, kLoadFindStringActionID, kFindChangePrefix + 1)
DECLARE_PMID(kActionIDSpace, kLoadAndFindActionID, kFindChangePrefix + 2)
DECLARE_PMID(kActionIDSpace, kReplaceFindActionID, kFindChangePrefix + 3)
DECLARE_PMID(kActionIDSpace, kReplaceActionID, kFindChangePrefix + 4)
DECLARE_PMID(kActionIDSpace, kLoadReplaceStringActionID, kFindChangePrefix + 5)
DECLARE_PMID(kActionIDSpace, kFindDialogActionID, kFindChangePrefix + 6)
DECLARE_PMID(kActionIDSpace, kFindNextActionID, kFindChangePrefix + 7)
DECLARE_PMID(kActionIDSpace, kFindAnyPageNumberActionID, kFindChangePrefix + 8)
DECLARE_PMID(kActionIDSpace, kFindCurrentPageNumberActionID, kFindChangePrefix + 9)
DECLARE_PMID(kActionIDSpace, kFindNextPageNumberActionID, kFindChangePrefix + 10)
DECLARE_PMID(kActionIDSpace, kFindPreviousPageNumberActionID, kFindChangePrefix + 11)
DECLARE_PMID(kActionIDSpace, kFindSectionMarkerActionID, kFindChangePrefix + 12)
DECLARE_PMID(kActionIDSpace, kFindPopupSep1ActionID, kFindChangePrefix + 13)
DECLARE_PMID(kActionIDSpace, kFindStandardCarriageReturnActionID, kFindChangePrefix + 14)
DECLARE_PMID(kActionIDSpace, kFindColumnBreakActionID, kFindChangePrefix + 15)
DECLARE_PMID(kActionIDSpace, kFindFrameBreakActionID, kFindChangePrefix + 16)
DECLARE_PMID(kActionIDSpace, kFindPageBreakActionID, kFindChangePrefix + 17)
DECLARE_PMID(kActionIDSpace, kFindActionID, kFindChangePrefix + 18)
DECLARE_PMID(kActionIDSpace, kFindEvenPageBreakActionID, kFindChangePrefix + 19)
DECLARE_PMID(kActionIDSpace, kFindForcedLineBreakActionID, kFindChangePrefix + 20)
DECLARE_PMID(kActionIDSpace, kFindEndOfParagraphActionID, kFindChangePrefix + 21)
DECLARE_PMID(kActionIDSpace, kFindAnchoredObjectActionID, kFindChangePrefix + 22)
DECLARE_PMID(kActionIDSpace, kFindFootnoteReferenceActionID, kFindChangePrefix + 23)
DECLARE_PMID(kActionIDSpace, kFindIndexMarkerActionID, kFindChangePrefix + 24)
DECLARE_PMID(kActionIDSpace, kFindAnyVariableActionID, kFindChangePrefix + 25)
DECLARE_PMID(kActionIDSpace, kFindPageCountActionID, kFindChangePrefix + 26)
DECLARE_PMID(kActionIDSpace, kFindChapterNumberActionID, kFindChangePrefix + 27)
DECLARE_PMID(kActionIDSpace, kFindOutputDateActionID, kFindChangePrefix + 28)
DECLARE_PMID(kActionIDSpace, kFindModificationDateActionID, kFindChangePrefix + 29)
DECLARE_PMID(kActionIDSpace, kFindFileNameActionID, kFindChangePrefix + 30)
DECLARE_PMID(kActionIDSpace, kFindCreationDateActionID, kFindChangePrefix + 31)
DECLARE_PMID(kActionIDSpace, kFindRunningHeaderPSActionID, kFindChangePrefix + 32)
DECLARE_PMID(kActionIDSpace, kFindCustomTextActionID, kFindChangePrefix + 33)
DECLARE_PMID(kActionIDSpace, kFindPopupSep2ActionID, kFindChangePrefix + 34)
DECLARE_PMID(kActionIDSpace, kFindBulletActionID, kFindChangePrefix + 35)
DECLARE_PMID(kActionIDSpace, kFindCaretActionID, kFindChangePrefix + 36)
DECLARE_PMID(kActionIDSpace, kFindCopyRightActionID, kFindChangePrefix + 37)
DECLARE_PMID(kActionIDSpace, kFindEllipsisActionID, kFindChangePrefix + 38)
DECLARE_PMID(kActionIDSpace, kFindParaActionID, kFindChangePrefix + 39)
DECLARE_PMID(kActionIDSpace, kFindRegisterActionID, kFindChangePrefix + 40)
DECLARE_PMID(kActionIDSpace, kFindSectionActionID, kFindChangePrefix + 41)
DECLARE_PMID(kActionIDSpace, kFindTrademarkSymbolActionID, kFindChangePrefix + 42)
DECLARE_PMID(kActionIDSpace, kFindPopupSep3ActionID, kFindChangePrefix + 43)
DECLARE_PMID(kActionIDSpace, kFindEmDashActionID, kFindChangePrefix + 44)
DECLARE_PMID(kActionIDSpace, kFindEnDashActionID, kFindChangePrefix + 45)
DECLARE_PMID(kActionIDSpace, kFindDiscretHyphenActionID, kFindChangePrefix + 46)
DECLARE_PMID(kActionIDSpace, kFindNonBreakHyphenActionID, kFindChangePrefix + 47)
DECLARE_PMID(kActionIDSpace, kFindPopupSep4ActionID, kFindChangePrefix + 48)
DECLARE_PMID(kActionIDSpace, kFindMSpaceActionID, kFindChangePrefix + 49)
DECLARE_PMID(kActionIDSpace, kFindNSpaceActionID, kFindChangePrefix + 50)
DECLARE_PMID(kActionIDSpace, kFindFlushSpaceActionID, kFindChangePrefix + 51)
DECLARE_PMID(kActionIDSpace, kFindHairSpaceActionID, kFindChangePrefix + 52)
DECLARE_PMID(kActionIDSpace, kFindNonBreakSpaceActionID, kFindChangePrefix + 53)
DECLARE_PMID(kActionIDSpace, kFindThinSpaceActionID, kFindChangePrefix + 54)
DECLARE_PMID(kActionIDSpace, kFindFigureSpaceActionID, kFindChangePrefix + 55)
DECLARE_PMID(kActionIDSpace, kFindPunctuationSpaceActionID, kFindChangePrefix + 56)
DECLARE_PMID(kActionIDSpace, kFindPopupSep5ActionID, kFindChangePrefix + 57)
DECLARE_PMID(kActionIDSpace, kFindAnyDoubleQuotationMarksActionID, kFindChangePrefix + 58)
DECLARE_PMID(kActionIDSpace, kFindAnySingleQuotationMarksActionID, kFindChangePrefix + 59)
DECLARE_PMID(kActionIDSpace, kFindPopupSep6ActionID, kFindChangePrefix + 60)
DECLARE_PMID(kActionIDSpace, kFindStraightDoubleQuotationMarksActionID, kFindChangePrefix + 61)
DECLARE_PMID(kActionIDSpace, kFindDoubleLeftQuotationMarksActionID, kFindChangePrefix + 62)
DECLARE_PMID(kActionIDSpace, kFindDoubleRightQuotationMarksActionID, kFindChangePrefix + 63)
DECLARE_PMID(kActionIDSpace, kFindPopupSep7ActionID, kFindChangePrefix + 64)
DECLARE_PMID(kActionIDSpace, kFindStraightSingleQuotationMarksActionID, kFindChangePrefix + 65)
DECLARE_PMID(kActionIDSpace, kFindSingleLeftQuotationMarksActionID, kFindChangePrefix + 66)
DECLARE_PMID(kActionIDSpace, kFindSingleRightQuotationMarksActionID, kFindChangePrefix + 67)
DECLARE_PMID(kActionIDSpace, kFindPopupSep8ActionID, kFindChangePrefix + 68)
DECLARE_PMID(kActionIDSpace, kFindTabActionID, kFindChangePrefix + 69)
DECLARE_PMID(kActionIDSpace, kFindRightEdgeTabActionID, kFindChangePrefix + 70)
DECLARE_PMID(kActionIDSpace, kFindIndentToHereActionID, kFindChangePrefix + 71)
DECLARE_PMID(kActionIDSpace, kFindPopupSep9ActionID, kFindChangePrefix + 72)
DECLARE_PMID(kActionIDSpace, kFindEndNestedStyleHereActionID, kFindChangePrefix + 73)
DECLARE_PMID(kActionIDSpace, kFindPopupSep10ActionID, kFindChangePrefix + 74)
DECLARE_PMID(kActionIDSpace, kFindAnyDigitActionID, kFindChangePrefix + 75)
DECLARE_PMID(kActionIDSpace, kFindAnyLetterActionID, kFindChangePrefix + 76)
DECLARE_PMID(kActionIDSpace, kFindAnyCharActionID, kFindChangePrefix + 77)
DECLARE_PMID(kActionIDSpace, kFindWhiteSpaceActionID, kFindChangePrefix + 78)
DECLARE_PMID(kActionIDSpace, kChangePopupSep6ActionID, kFindChangePrefix + 79)
DECLARE_PMID(kActionIDSpace, kChangeStraightDoubleQuotationMarksActionID, kFindChangePrefix + 80)
DECLARE_PMID(kActionIDSpace, kFindNextFormatActionID, kFindChangePrefix + 81)
DECLARE_PMID(kActionIDSpace, kChangeNextFormatActionID, kFindChangePrefix + 82)
DECLARE_PMID(kActionIDSpace, kKillerFindActionID, kFindChangePrefix + 83 )
DECLARE_PMID(kActionIDSpace, kFindOddPageBreakActionID, kFindChangePrefix + 84)
DECLARE_PMID(kActionIDSpace, kChangeAnyPageNumberActionID, kFindChangePrefix + 85)
DECLARE_PMID(kActionIDSpace, kChangeCurrentPageNumberActionID, kFindChangePrefix + 86)
DECLARE_PMID(kActionIDSpace, kChangeNextPageNumberActionID, kFindChangePrefix + 87)
DECLARE_PMID(kActionIDSpace, kChangePreviousPageNumberActionID, kFindChangePrefix + 88)
DECLARE_PMID(kActionIDSpace, kChangeSectionMarkerActionID, kFindChangePrefix + 89)
DECLARE_PMID(kActionIDSpace, kChangePopupSep1ActionID, kFindChangePrefix + 90)
DECLARE_PMID(kActionIDSpace, kChangeStandardCarriageReturnActionID, kFindChangePrefix + 91)
DECLARE_PMID(kActionIDSpace, kChangeColumnBreakActionID, kFindChangePrefix + 92)
DECLARE_PMID(kActionIDSpace, kChangeFrameBreakActionID, kFindChangePrefix + 93)
DECLARE_PMID(kActionIDSpace, kChangePageBreakActionID, kFindChangePrefix + 94)
DECLARE_PMID(kActionIDSpace, kChangeOddPageBreakActionID, kFindChangePrefix + 95)
DECLARE_PMID(kActionIDSpace, kChangeEvenPageBreakActionID, kFindChangePrefix + 96)
DECLARE_PMID(kActionIDSpace, kChangeForcedLineBreakActionID, kFindChangePrefix + 97)
DECLARE_PMID(kActionIDSpace, kChangeEndOfParagraphActionID, kFindChangePrefix + 98)
DECLARE_PMID(kActionIDSpace, kChangeAnchoredObjectActionID, kFindChangePrefix + 99)
DECLARE_PMID(kActionIDSpace, kChangeClipboardContentsFormattedActionID, kFindChangePrefix + 100)
DECLARE_PMID(kActionIDSpace, kChangeClipboardContentsUnformattedActionID, kFindChangePrefix + 101)
DECLARE_PMID(kActionIDSpace, kChangeFootnoteReferenceActionID, kFindChangePrefix + 102)
DECLARE_PMID(kActionIDSpace, kChangeAnyVariableActionID, kFindChangePrefix + 103)
DECLARE_PMID(kActionIDSpace, kChangePageCountActionID, kFindChangePrefix + 104)
DECLARE_PMID(kActionIDSpace, kChangeChapterNumberActionID, kFindChangePrefix + 105)
DECLARE_PMID(kActionIDSpace, kChangeCurrentDateActionID, kFindChangePrefix + 106)
DECLARE_PMID(kActionIDSpace, kChangeModificationDateActionID, kFindChangePrefix + 107)
DECLARE_PMID(kActionIDSpace, kChangeFileNameActionID, kFindChangePrefix + 108)
DECLARE_PMID(kActionIDSpace, kChangeParagraphStyleActionID, kFindChangePrefix + 109)
DECLARE_PMID(kActionIDSpace, kChangeCharacterStyleActionID, kFindChangePrefix + 110)
DECLARE_PMID(kActionIDSpace, kFindMetadataCaptionActionID, kFindChangePrefix + 111)
DECLARE_PMID(kActionIDSpace, kQuickApplyTreeViewNodeID, kFindChangePrefix + 112)
DECLARE_PMID(kActionIDSpace, kChangeCustomTextActionID, kFindChangePrefix + 113)
DECLARE_PMID(kActionIDSpace, kChangePopupSep2ActionID, kFindChangePrefix + 114)
DECLARE_PMID(kActionIDSpace, kChangeBulletActionID, kFindChangePrefix + 115)
DECLARE_PMID(kActionIDSpace, kChangeCaretActionID, kFindChangePrefix + 116)
DECLARE_PMID(kActionIDSpace, kChangeCopyRightActionID, kFindChangePrefix + 117)
DECLARE_PMID(kActionIDSpace, kChangeEllipsisActionID, kFindChangePrefix + 118)
DECLARE_PMID(kActionIDSpace, kChangeParaActionID, kFindChangePrefix + 119)
DECLARE_PMID(kActionIDSpace, kChangeRegisterActionID, kFindChangePrefix + 120)
DECLARE_PMID(kActionIDSpace, kChangeSectionActionID, kFindChangePrefix + 121)
DECLARE_PMID(kActionIDSpace, kChangeTrademarkSymbolActionID, kFindChangePrefix + 122)
DECLARE_PMID(kActionIDSpace, kChangePopupSep3ActionID, kFindChangePrefix + 123)
DECLARE_PMID(kActionIDSpace, kChangeEmDashActionID, kFindChangePrefix + 124)
DECLARE_PMID(kActionIDSpace, kChangeEnDashActionID, kFindChangePrefix + 125)
DECLARE_PMID(kActionIDSpace, kChangeDiscretHyphenActionID, kFindChangePrefix + 126)
DECLARE_PMID(kActionIDSpace, kChangeNonBreakHyphenActionID, kFindChangePrefix + 127)
DECLARE_PMID(kActionIDSpace, kChangePopupSep4ActionID, kFindChangePrefix + 128)
DECLARE_PMID(kActionIDSpace, kChangeMSpaceActionID, kFindChangePrefix + 129)
DECLARE_PMID(kActionIDSpace, kChangeNSpaceActionID, kFindChangePrefix + 130)
DECLARE_PMID(kActionIDSpace, kChangeFlushSpaceActionID, kFindChangePrefix + 131)
DECLARE_PMID(kActionIDSpace, kChangeHairSpaceActionID, kFindChangePrefix + 132)
DECLARE_PMID(kActionIDSpace, kChangeNonBreakSpaceActionID, kFindChangePrefix + 133)
DECLARE_PMID(kActionIDSpace, kChangeThinSpaceActionID, kFindChangePrefix + 134)
DECLARE_PMID(kActionIDSpace, kChangeFigureSpaceActionID, kFindChangePrefix + 135)
DECLARE_PMID(kActionIDSpace, kChangePunctuationSpaceActionID, kFindChangePrefix + 136)
DECLARE_PMID(kActionIDSpace, kChangePopupSep5ActionID, kFindChangePrefix + 137)
DECLARE_PMID(kActionIDSpace, kChangeAnyDoubleQuotationMarksActionID, kFindChangePrefix + 138)
DECLARE_PMID(kActionIDSpace, kChangeAnySingleQuotationMarksActionID, kFindChangePrefix + 139)

//Grep action id's
DECLARE_PMID(kActionIDSpace, kFindGrepAutoPageNumberActionID,		 	kFindChangePrefix + 140)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyDoubleQuoteActionID,			kFindChangePrefix + 141)
DECLARE_PMID(kActionIDSpace, kFindGrepAnySingleQuoteActionID,			kFindChangePrefix + 142)
DECLARE_PMID(kActionIDSpace, kFindGrepSectionNameActionID,		 		kFindChangePrefix + 143)
DECLARE_PMID(kActionIDSpace, kFindGrepCarriageReturnActionID,		 	kFindChangePrefix + 144)
DECLARE_PMID(kActionIDSpace, kFindGrepNewLineActionID,					kFindChangePrefix + 145)
DECLARE_PMID(kActionIDSpace, kFindGrepAnchoredObjectActionID,		 	kFindChangePrefix + 146)
DECLARE_PMID(kActionIDSpace, kFindGrepFootnoteReferenceActionID,		kFindChangePrefix + 147)
DECLARE_PMID(kActionIDSpace, kFindGrepBulletActionID,				 	kFindChangePrefix + 148)
DECLARE_PMID(kActionIDSpace, kFindGrepCaretActionID,					kFindChangePrefix + 149)
DECLARE_PMID(kActionIDSpace, kFindGrepCopyRightActionID,			 	kFindChangePrefix + 150)
DECLARE_PMID(kActionIDSpace, kFindGrepEllipsisActionID,					kFindChangePrefix + 151)
DECLARE_PMID(kActionIDSpace, kFindGrepParaActionID,					 	kFindChangePrefix + 152)
DECLARE_PMID(kActionIDSpace, kFindGrepRegisterActionID,					kFindChangePrefix + 153)
DECLARE_PMID(kActionIDSpace, kFindGrepSectionActionID,				 	kFindChangePrefix + 154)
DECLARE_PMID(kActionIDSpace, kFindGrepTrademarkSymbolActionID,			kFindChangePrefix + 155)
DECLARE_PMID(kActionIDSpace, kFindGrepEmDashActionID,				 	kFindChangePrefix + 156)
DECLARE_PMID(kActionIDSpace, kFindGrepEnDashActionID,					kFindChangePrefix + 157)
DECLARE_PMID(kActionIDSpace, kFindGrepDiscretHyphenActionID, 		 	kFindChangePrefix + 158)
DECLARE_PMID(kActionIDSpace, kFindGrepNonBreakHyphenActionID,			kFindChangePrefix + 159)
DECLARE_PMID(kActionIDSpace, kFindGrepMSpaceActionID,				 	kFindChangePrefix + 160)
DECLARE_PMID(kActionIDSpace, kFindGrepNSpaceActionID,					kFindChangePrefix + 161)
DECLARE_PMID(kActionIDSpace, kFindGrepFlushSpaceActionID,			 	kFindChangePrefix + 162)
DECLARE_PMID(kActionIDSpace, kFindGrepHairSpaceActionID,				kFindChangePrefix + 163)
DECLARE_PMID(kActionIDSpace, kFindGrepNonBreakSpaceActionID,		 	kFindChangePrefix + 164)
DECLARE_PMID(kActionIDSpace, kFindGrepThinSpaceActionID,				kFindChangePrefix + 165)
DECLARE_PMID(kActionIDSpace, kFindGrepFigureSpaceActionID, 			 	kFindChangePrefix + 166)
DECLARE_PMID(kActionIDSpace, kFindGrepPunctuationSpaceActionID, 		kFindChangePrefix + 167)
DECLARE_PMID(kActionIDSpace, kFindGrepDoubleLeftQuoteActionID,		 	kFindChangePrefix + 168)
DECLARE_PMID(kActionIDSpace, kFindGrepDoubleRightQuoteActionID,			kFindChangePrefix + 169)
DECLARE_PMID(kActionIDSpace, kFindGrepSingleLeftQuoteActionID,		 	kFindChangePrefix + 170)
DECLARE_PMID(kActionIDSpace, kFindGrepSingleRightQuoteActionID,			kFindChangePrefix + 171)
DECLARE_PMID(kActionIDSpace, kFindGrepTabActionID,					 	kFindChangePrefix + 172)
DECLARE_PMID(kActionIDSpace, kFindGrepRightEdgeTabActionID,				kFindChangePrefix + 173)
DECLARE_PMID(kActionIDSpace, kFindGrepIndentToHereActionID,			 	kFindChangePrefix + 174)
DECLARE_PMID(kActionIDSpace, kFindGrepNextFormatActionID,				kFindChangePrefix + 175)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyDigitActionID,				 	kFindChangePrefix + 176)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyLetterActionID, 				kFindChangePrefix + 177)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyCharActionID,				 	kFindChangePrefix + 178)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyWhiteSpaceActionID,			kFindChangePrefix + 179)

DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep1ActionID,				kFindChangePrefix + 180)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep2ActionID,				kFindChangePrefix + 181)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep3ActionID,				kFindChangePrefix + 182)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep4ActionID,				kFindChangePrefix + 183)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep5ActionID,				kFindChangePrefix + 184)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep6ActionID,				kFindChangePrefix + 185)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep7ActionID,				kFindChangePrefix + 186)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep8ActionID,				kFindChangePrefix + 187)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep9ActionID,				kFindChangePrefix + 188)

DECLARE_PMID(kActionIDSpace, kChangeGrepTabActionID,					kFindChangePrefix + 190)
DECLARE_PMID(kActionIDSpace, kChangeGrepCarriageReturnActionID,			kFindChangePrefix + 191)
DECLARE_PMID(kActionIDSpace, kChangeGrepNewLineActionID,				kFindChangePrefix + 192)

DECLARE_PMID(kActionIDSpace, kChangeGrepFound0ActionID,					kFindChangePrefix + 200)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound1ActionID,					kFindChangePrefix + 201)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound2ActionID,					kFindChangePrefix + 202)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound3ActionID,					kFindChangePrefix + 203)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound4ActionID,					kFindChangePrefix + 204)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound5ActionID,					kFindChangePrefix + 205)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound6ActionID,					kFindChangePrefix + 206)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound7ActionID,					kFindChangePrefix + 207)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound8ActionID,					kFindChangePrefix + 208)
DECLARE_PMID(kActionIDSpace, kChangeGrepFound9ActionID,					kFindChangePrefix + 209)

DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep0ActionID,				kFindChangePrefix + 210)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep1ActionID,				kFindChangePrefix + 211)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep2ActionID,				kFindChangePrefix + 212)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep3ActionID,				kFindChangePrefix + 213)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep4ActionID,				kFindChangePrefix + 214)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep5ActionID,				kFindChangePrefix + 215)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep6ActionID,				kFindChangePrefix + 216)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep7ActionID,				kFindChangePrefix + 217)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep8ActionID,				kFindChangePrefix + 218)
DECLARE_PMID(kActionIDSpace, kChangeGrepPopupSep9ActionID,				kFindChangePrefix + 219)

DECLARE_PMID(kActionIDSpace, kFindGrepRepeat0OrMoreActionID,			kFindChangePrefix + 220)
DECLARE_PMID(kActionIDSpace, kFindGrepRepeat1OrMoreActionID,			kFindChangePrefix + 221)
DECLARE_PMID(kActionIDSpace, kFindGrepRepeat0Or1ActionID,				kFindChangePrefix + 222)
DECLARE_PMID(kActionIDSpace, kFindGrepRepeat0OrMoreShortestActionID,	kFindChangePrefix + 223)
DECLARE_PMID(kActionIDSpace, kFindGrepRepeat1OrMoreShortestActionID,	kFindChangePrefix + 224)
DECLARE_PMID(kActionIDSpace, kFindGrepRepeat0Or1ShortestActionID,		kFindChangePrefix + 225)

DECLARE_PMID(kActionIDSpace, kFindGrepBeginingOfWordActionID,			kFindChangePrefix + 226)
DECLARE_PMID(kActionIDSpace, kFindGrepEndOfWordActionID,				kFindChangePrefix + 227)
DECLARE_PMID(kActionIDSpace, kFindGrepBeginingOfParagraphActionID,		kFindChangePrefix + 228)
DECLARE_PMID(kActionIDSpace, kFindGrepEndOfParagraphActionID,			kFindChangePrefix + 229)
DECLARE_PMID(kActionIDSpace, kFindGrepStraightDoubleQuoteActionID,		kFindChangePrefix + 230)
DECLARE_PMID(kActionIDSpace, kFindGrepStraightSingleQuoteActionID,			kFindChangePrefix + 231)
DECLARE_PMID(kActionIDSpace, kFindGrepEndOfLineActionID,			kFindChangePrefix + 232)
DECLARE_PMID(kActionIDSpace, kFindGrepEndOfNestedStyleActionID,			kFindChangePrefix + 233)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyUppercaseActionID,			kFindChangePrefix + 234)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyLowercaseActionID,			kFindChangePrefix + 235)

DECLARE_PMID(kActionIDSpace, kFindGrepOrActionID,						kFindChangePrefix + 236)
DECLARE_PMID(kActionIDSpace, kFindGrepMarkingSubExpressionActionID,		kFindChangePrefix + 237)
DECLARE_PMID(kActionIDSpace, kFindGrepNonMarkingSubExpressionActionID,	kFindChangePrefix + 238)
DECLARE_PMID(kActionIDSpace, kFindGrepCharacterSetActionID,				kFindChangePrefix + 239)
DECLARE_PMID(kActionIDSpace, kFindGrepMinMaxRangeActionID,				kFindChangePrefix + 240)

DECLARE_PMID(kActionIDSpace, kChangeDoubleLeftQuotationMarksActionID, kFindChangePrefix + 241)
DECLARE_PMID(kActionIDSpace, kChangeDoubleRightQuotationMarksActionID, kFindChangePrefix + 242)
DECLARE_PMID(kActionIDSpace, kChangePopupSep7ActionID, kFindChangePrefix + 243)
DECLARE_PMID(kActionIDSpace, kChangeStraightSingleQuotationMarksActionID, kFindChangePrefix + 244)
DECLARE_PMID(kActionIDSpace, kChangeSingleLeftQuotationMarksActionID, kFindChangePrefix + 245)
DECLARE_PMID(kActionIDSpace, kChangeSingleRightQuotationMarksActionID, kFindChangePrefix + 246)
DECLARE_PMID(kActionIDSpace, kChangePopupSep8ActionID, kFindChangePrefix + 247)
DECLARE_PMID(kActionIDSpace, kChangeTabActionID, kFindChangePrefix + 248)
DECLARE_PMID(kActionIDSpace, kChangeRightEdgeTabActionID, kFindChangePrefix + 249)
DECLARE_PMID(kActionIDSpace, kChangeIndentToHereActionID, kFindChangePrefix + 250)
DECLARE_PMID(kActionIDSpace, kChangePopupSep9ActionID, kFindChangePrefix + 251)
DECLARE_PMID(kActionIDSpace, kChangeEndNestedStyleHereActionID, kFindChangePrefix + 252)
DECLARE_PMID(kActionIDSpace, kFindMenuSeparatorActionID, kFindChangePrefix + 253)
DECLARE_PMID(kActionIDSpace, kFindJBulletActionID, kFindChangePrefix + 254)
DECLARE_PMID(kActionIDSpace, kChangeJBulletActionID, kFindChangePrefix + 255)

// More action id's with kFindChangePrefix2

DECLARE_PMID(kActionIDSpace, kChangeGrepBulletActionID,				kFindChangePrefix2 + 0)
DECLARE_PMID(kActionIDSpace, kChangeGrepCaretActionID,				kFindChangePrefix2 + 1)
DECLARE_PMID(kActionIDSpace, kChangeGrepCopyRightActionID,			kFindChangePrefix2 + 2)
DECLARE_PMID(kActionIDSpace, kChangeGrepEllipsisActionID,			kFindChangePrefix2 + 3)
DECLARE_PMID(kActionIDSpace, kChangeGrepParaActionID,				kFindChangePrefix2 + 4)
DECLARE_PMID(kActionIDSpace, kChangeGrepRegisterActionID,			kFindChangePrefix2 + 5)
DECLARE_PMID(kActionIDSpace, kChangeGrepSectionActionID,			kFindChangePrefix2 + 6)
DECLARE_PMID(kActionIDSpace, kChangeGrepTrademarkSymbolActionID,	kFindChangePrefix2 + 7)
DECLARE_PMID(kActionIDSpace, kChangeGrepIndexActionID,				kFindChangePrefix2 + 8)
DECLARE_PMID(kActionIDSpace, kChangeGrepAutoPageNumberActionID,		kFindChangePrefix2 + 9)
DECLARE_PMID(kActionIDSpace, kChangeGrepSectionNameActionID,		kFindChangePrefix2 + 10)
DECLARE_PMID(kActionIDSpace, kChangeGrepAnchoredObjectActionID,		kFindChangePrefix2 + 11)
DECLARE_PMID(kActionIDSpace, kChangeGrepFootnoteReferenceActionID, 	kFindChangePrefix2 + 12)
DECLARE_PMID(kActionIDSpace, kChangeGrepNextFormatActionID,			kFindChangePrefix2 + 13)
DECLARE_PMID(kActionIDSpace, kChangeGrepCurrentPageNumberActionID,	kFindChangePrefix2 + 14)
DECLARE_PMID(kActionIDSpace, kChangeGrepNextPageNumberActionID,		kFindChangePrefix2 + 15)
DECLARE_PMID(kActionIDSpace, kChangeGrepPreviousPageNumberActionID,	kFindChangePrefix2 + 16)
//DECLARE_PMID(kActionIDSpace, kChangeGrepActionID,				kFindChangePrefix2 + 17)
//DECLARE_PMID(kActionIDSpace, kChangeGrepActionID,				kFindChangePrefix2 + 18)
//DECLARE_PMID(kActionIDSpace, kChangeGrepActionID,				kFindChangePrefix2 + 19)

//DECLARE_PMID(kActionIDSpace, kFindGrepPosix1ActionID,				kFindChangePrefix2 + 20)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix2ActionID,				kFindChangePrefix2 + 21)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix3ActionID, 				kFindChangePrefix2 + 22)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix4ActionID,				kFindChangePrefix2 + 23)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix5ActionID, 				kFindChangePrefix2 + 24)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix6ActionID, 				kFindChangePrefix2 + 25)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix7ActionID, 				kFindChangePrefix2 + 26)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix8ActionID, 				kFindChangePrefix2 + 27)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix9ActionID, 				kFindChangePrefix2 + 28)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix10ActionID,				kFindChangePrefix2 + 29)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix11ActionID,				kFindChangePrefix2 + 30)
//DECLARE_PMID(kActionIDSpace, kFindGrepPosix12ActionID,				kFindChangePrefix2 + 31)
DECLARE_PMID(kActionIDSpace, kFindGrepPopupSep10ActionID,			kFindChangePrefix2 + 32)
DECLARE_PMID(kActionIDSpace, kFindGrepCharEquivalenceActionID,		kFindChangePrefix2 + 33)
DECLARE_PMID(kActionIDSpace, kFindGrepOpenParanthesisActionID,		kFindChangePrefix2 + 34)
DECLARE_PMID(kActionIDSpace, kFindGrepCloseParanthesisActionID,		kFindChangePrefix2 + 35)
DECLARE_PMID(kActionIDSpace, kFindGrepOpenBraceActionID,			kFindChangePrefix2 + 36)
DECLARE_PMID(kActionIDSpace, kFindGrepCloseBraceActionID,			kFindChangePrefix2 + 37)
DECLARE_PMID(kActionIDSpace, kFindGrepOpenBracketActionID,			kFindChangePrefix2 + 38)
DECLARE_PMID(kActionIDSpace, kFindGrepCloseBracketActionID,			kFindChangePrefix2 + 39)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyWordActionID,			kFindChangePrefix2 + 40)
DECLARE_PMID(kActionIDSpace, kFindGrepIndexMarkerActionID,			kFindChangePrefix2 + 41)
DECLARE_PMID(kActionIDSpace, kFindNonBreakFixedSpaceActionID, 		kFindChangePrefix2 + 42)
DECLARE_PMID(kActionIDSpace, kFindWhiteSep1ActionID, 				kFindChangePrefix2 + 43)
DECLARE_PMID(kActionIDSpace, kFindWhiteSep2ActionID, 				kFindChangePrefix2 + 44)
DECLARE_PMID(kActionIDSpace, kChangeNonBreakFixedSpaceActionID, 	kFindChangePrefix2 + 45)
DECLARE_PMID(kActionIDSpace, kChangeWhiteSep1ActionID, 			kFindChangePrefix2 + 46)
DECLARE_PMID(kActionIDSpace, kChangeWhiteSep2ActionID, 			kFindChangePrefix2 + 47)
DECLARE_PMID(kActionIDSpace, kFindRunningHeaderCSActionID,			kFindChangePrefix2 + 48)
DECLARE_PMID(kActionIDSpace, kChangeStandardCarriageActionID,		kFindChangePrefix2 + 49)
DECLARE_PMID(kActionIDSpace, kFindZeroWidthNonJoinerActionID,		kFindChangePrefix2 + 50)
DECLARE_PMID(kActionIDSpace, kChangeZeroWidthNonJoinerActionID,		kFindChangePrefix2 + 51)
DECLARE_PMID(kActionIDSpace, kFindGrepDiscLineBreakActionID,		kFindChangePrefix2 + 52)
DECLARE_PMID(kActionIDSpace, kChangeGrepDiscLineBreakActionID,		kFindChangePrefix2 + 53)
DECLARE_PMID(kActionIDSpace, kFindGrepNonBreakSpaceFWActionID,		kFindChangePrefix2 + 54)
DECLARE_PMID(kActionIDSpace, kChangeGrepNonBreakSpaceFWActionID,	kFindChangePrefix2 + 55)
DECLARE_PMID(kActionIDSpace, kFindGrepZeroWidthNonJoinerActionID,	kFindChangePrefix2 + 56)
DECLARE_PMID(kActionIDSpace, kChangeGrepZeroWidthNonJoinerActionID,	kFindChangePrefix2 + 57)
DECLARE_PMID(kActionIDSpace, kFindGrepCurrentPageNumberActionID,	kFindChangePrefix2 + 58)
DECLARE_PMID(kActionIDSpace, kFindGrepNextPageNumberActionID,		kFindChangePrefix2 + 59)
DECLARE_PMID(kActionIDSpace, kFindGrepPreviousPageNumberActionID,	kFindChangePrefix2 + 60)
DECLARE_PMID(kActionIDSpace, kFindGrepStandardCarriageReturnActionID, kFindChangePrefix2 + 61)
DECLARE_PMID(kActionIDSpace, kFindGrepColumnBreakActionID,			kFindChangePrefix2 + 62)
DECLARE_PMID(kActionIDSpace, kFindGrepFrameBreakActionID,			kFindChangePrefix2 + 63)
DECLARE_PMID(kActionIDSpace, kFindGrepPageBreakActionID,			kFindChangePrefix2 + 64)
DECLARE_PMID(kActionIDSpace, kFindGrepOddPageBreakActionID,			kFindChangePrefix2 + 65)
DECLARE_PMID(kActionIDSpace, kFindGrepEvenPageBreakActionID,		kFindChangePrefix2 + 66)

DECLARE_PMID(kActionIDSpace, kFindGrepPageCountActionID,			kFindChangePrefix2 + 68)
DECLARE_PMID(kActionIDSpace, kFindGrepChapterNumberActionID,		kFindChangePrefix2 + 69)
DECLARE_PMID(kActionIDSpace, kFindGrepCreationDateActionID,			kFindChangePrefix2 + 70)
DECLARE_PMID(kActionIDSpace, kFindGrepModificationDateActionID,		kFindChangePrefix2 + 71)
DECLARE_PMID(kActionIDSpace, kFindGrepOutputDateActionID,			kFindChangePrefix2 + 72)
DECLARE_PMID(kActionIDSpace, kFindGrepFileNameActionID,				kFindChangePrefix2 + 73)
DECLARE_PMID(kActionIDSpace, kFindGrepRunningHeaderPSActionID,		kFindChangePrefix2 + 74)
DECLARE_PMID(kActionIDSpace, kFindGrepRunningHeaderCSActionID,		kFindChangePrefix2 + 75)
DECLARE_PMID(kActionIDSpace, kFindGrepCustomTextActionID,			kFindChangePrefix2 + 76)
DECLARE_PMID(kActionIDSpace, kFindGrepBackSlashCharacterActionID,	kFindChangePrefix2 + 77)
DECLARE_PMID(kActionIDSpace, kFindGrepWordBoundaryActionID,			kFindChangePrefix2 + 78)
DECLARE_PMID(kActionIDSpace, kChangeGrepStandardCarriageReturnActionID, kFindChangePrefix2 + 79)
DECLARE_PMID(kActionIDSpace, kChangeGrepColumnBreakActionID,			kFindChangePrefix2 + 80)
DECLARE_PMID(kActionIDSpace, kChangeGrepFrameBreakActionID,			kFindChangePrefix2 + 81)
DECLARE_PMID(kActionIDSpace, kChangeGrepPageBreakActionID,			kFindChangePrefix2 + 82)
DECLARE_PMID(kActionIDSpace, kChangeGrepOddPageBreakActionID,		kFindChangePrefix2 + 83)
DECLARE_PMID(kActionIDSpace, kChangeGrepEvenPageBreakActionID,		kFindChangePrefix2 + 84)
DECLARE_PMID(kActionIDSpace, kFindGrepPositiveLookBehindActionID,	kFindChangePrefix2 + 85)
DECLARE_PMID(kActionIDSpace, kFindGrepNegativeLookBehindActionID,	kFindChangePrefix2 + 86)
DECLARE_PMID(kActionIDSpace, kFindGrepPositiveLookAheadActionID,	kFindChangePrefix2 + 87)
DECLARE_PMID(kActionIDSpace, kFindGrepNegativeLookAheadActionID,	kFindChangePrefix2 + 88)

DECLARE_PMID(kActionIDSpace, kFindGrepCaseSensitiveOnActionID,		kFindChangePrefix2 + 89)
DECLARE_PMID(kActionIDSpace, kFindGrepCaseSensitiveOffActionID,		kFindChangePrefix2 + 90)
DECLARE_PMID(kActionIDSpace, kFindGrepMultilineOnActionID,			kFindChangePrefix2 + 91)
DECLARE_PMID(kActionIDSpace, kFindGrepMultilineOffActionID,			kFindChangePrefix2 + 92)
DECLARE_PMID(kActionIDSpace, kFindGrepSinglelineOnActionID,			kFindChangePrefix2 + 93)
DECLARE_PMID(kActionIDSpace, kFindGrepSinglelineOffActionID,		kFindChangePrefix2 + 94)
DECLARE_PMID(kActionIDSpace, kFindGrepIgnoreWhitespaceOnActionID,	kFindChangePrefix2 + 95)
DECLARE_PMID(kActionIDSpace, kFindGrepIgnoreWhitespaceOffActionID,	kFindChangePrefix2 + 96)

DECLARE_PMID(kActionIDSpace, kFindGrepAlnumActionID,				kFindChangePrefix2 + 97)
DECLARE_PMID(kActionIDSpace, kFindGrepAlphaActionID,				kFindChangePrefix2 + 98)
DECLARE_PMID(kActionIDSpace, kFindGrepDigitActionID,				kFindChangePrefix2 + 99)
DECLARE_PMID(kActionIDSpace, kFindGrepLowerActionID,				kFindChangePrefix2 + 100)
DECLARE_PMID(kActionIDSpace, kFindGrepPunctActionID,				kFindChangePrefix2 + 101)
DECLARE_PMID(kActionIDSpace, kFindGrepSpaceActionID,				kFindChangePrefix2 + 102)
DECLARE_PMID(kActionIDSpace, kFindGrepUpperActionID,				kFindChangePrefix2 + 103)
DECLARE_PMID(kActionIDSpace, kFindGrepWordActionID,					kFindChangePrefix2 + 104)
DECLARE_PMID(kActionIDSpace, kFindGrepXdigitActionID,				kFindChangePrefix2 + 105)
DECLARE_PMID(kActionIDSpace, kFindGrepMetadataCaptionActionID,		kFindChangePrefix2 + 106)
// gap

DECLARE_PMID(kActionIDSpace, kFCPopupSepActionID, kFindChangePrefix2 +111)
DECLARE_PMID(kActionIDSpace, kFindInsertGereshActionID, kFindChangePrefix2 +112)
DECLARE_PMID(kActionIDSpace, kFindInsertGershayimActionID, kFindChangePrefix2 +113)
DECLARE_PMID(kActionIDSpace, kFindInsertMaqafActionID, kFindChangePrefix2 +114)
DECLARE_PMID(kActionIDSpace, kFindInsertKashidaActionID, kFindChangePrefix2 +115)
DECLARE_PMID(kActionIDSpace, kChangeInsertGereshActionID, kFindChangePrefix2 +116)
DECLARE_PMID(kActionIDSpace, kChangeInsertGershayimActionID, kFindChangePrefix2 +117)
DECLARE_PMID(kActionIDSpace, kChangeInsertMaqafActionID, kFindChangePrefix2 +118)
DECLARE_PMID(kActionIDSpace, kChangeInsertKashidaActionID, kFindChangePrefix2 +119)

DECLARE_PMID(kActionIDSpace, kFindGrepInsertGereshActionID, kFindChangePrefix2 +120)
DECLARE_PMID(kActionIDSpace, kFindGrepInsertGershayimActionID, kFindChangePrefix2 +121)
DECLARE_PMID(kActionIDSpace, kFindGrepInsertMaqafActionID, kFindChangePrefix2 +122)
DECLARE_PMID(kActionIDSpace, kFindGrepInsertKashidaActionID, kFindChangePrefix2 +123)
DECLARE_PMID(kActionIDSpace, kChangeGrepInsertGereshActionID, kFindChangePrefix2 +124)
DECLARE_PMID(kActionIDSpace, kChangeGrepInsertGershayimActionID, kFindChangePrefix2 +125)
DECLARE_PMID(kActionIDSpace, kChangeGrepInsertMaqafActionID, kFindChangePrefix2 +126)
DECLARE_PMID(kActionIDSpace, kChangeGrepInsertKashidaActionID, kFindChangePrefix2 +127)
DECLARE_PMID(kActionIDSpace, kFindInsertSofPasukActionID, kFindChangePrefix2 + 128)
DECLARE_PMID(kActionIDSpace, kChangeInsertSofPasukActionID, kFindChangePrefix2 + 129)
DECLARE_PMID(kActionIDSpace, kFindGrepInsertSofPasukActionID, kFindChangePrefix2 + 130)
DECLARE_PMID(kActionIDSpace, kChangeGrepInsertSofPasukActionID, kFindChangePrefix2 + 131)


DECLARE_PMID(kActionIDSpace, kChangeGrepEmDashActionID,				 	kFindChangePrefix2 + 156)
DECLARE_PMID(kActionIDSpace, kChangeGrepEnDashActionID,					kFindChangePrefix2 + 157)
DECLARE_PMID(kActionIDSpace, kChangeGrepDiscretHyphenActionID, 		 	kFindChangePrefix2 + 158)
DECLARE_PMID(kActionIDSpace, kChangeGrepNonBreakHyphenActionID,			kFindChangePrefix2 + 159)
DECLARE_PMID(kActionIDSpace, kChangeGrepMSpaceActionID,				 	kFindChangePrefix2 + 160)
DECLARE_PMID(kActionIDSpace, kChangeGrepNSpaceActionID,					kFindChangePrefix2 + 161)
DECLARE_PMID(kActionIDSpace, kChangeGrepFlushSpaceActionID,			 	kFindChangePrefix2 + 162)
DECLARE_PMID(kActionIDSpace, kChangeGrepHairSpaceActionID,				kFindChangePrefix2 + 163)
DECLARE_PMID(kActionIDSpace, kChangeGrepNonBreakSpaceActionID,		 	kFindChangePrefix2 + 164)
DECLARE_PMID(kActionIDSpace, kChangeGrepThinSpaceActionID,				kFindChangePrefix2 + 165)
DECLARE_PMID(kActionIDSpace, kChangeGrepFigureSpaceActionID, 			kFindChangePrefix2 + 166)
DECLARE_PMID(kActionIDSpace, kChangeGrepPunctuationSpaceActionID, 		kFindChangePrefix2 + 167)
DECLARE_PMID(kActionIDSpace, kChangeGrepDoubleLeftQuoteActionID,		kFindChangePrefix2 + 168)
DECLARE_PMID(kActionIDSpace, kChangeGrepDoubleRightQuoteActionID,		kFindChangePrefix2 + 169)
DECLARE_PMID(kActionIDSpace, kChangeGrepSingleLeftQuoteActionID,		kFindChangePrefix2 + 170)
DECLARE_PMID(kActionIDSpace, kChangeGrepSingleRightQuoteActionID,		kFindChangePrefix2 + 171)

DECLARE_PMID(kActionIDSpace, kChangeGrepRightEdgeTabActionID,			kFindChangePrefix2 + 173)
DECLARE_PMID(kActionIDSpace, kChangeGrepIndentToHereActionID,			kFindChangePrefix2 + 174)

DECLARE_PMID(kActionIDSpace, kFindGrepJBulletActionID,					kFindChangePrefix2 + 175)
DECLARE_PMID(kActionIDSpace, kChangeGrepJBulletActionID,				kFindChangePrefix2 + 176)
DECLARE_PMID(kActionIDSpace, kFindIdeographicSpaceActionID,				kFindChangePrefix2 + 177)
DECLARE_PMID(kActionIDSpace, kFindGrepIdeographicSpaceActionID,			kFindChangePrefix2 + 178)
DECLARE_PMID(kActionIDSpace, kChangeIdeographicSpaceActionID,			kFindChangePrefix2 + 179)
DECLARE_PMID(kActionIDSpace, kChangeGrepIdeographicSpaceActionID,		kFindChangePrefix2 + 180)
DECLARE_PMID(kActionIDSpace, kFindThirdSpaceActionID,					kFindChangePrefix2 + 181)
DECLARE_PMID(kActionIDSpace, kFindGrepThirdSpaceActionID,				kFindChangePrefix2 + 182)
DECLARE_PMID(kActionIDSpace, kChangeThirdSpaceActionID,					kFindChangePrefix2 + 183)
DECLARE_PMID(kActionIDSpace, kChangeGrepThirdSpaceActionID,				kFindChangePrefix2 + 184)
DECLARE_PMID(kActionIDSpace, kFindQuarterSpaceActionID,					kFindChangePrefix2 + 185)
DECLARE_PMID(kActionIDSpace, kFindGrepQuarterSpaceActionID,				kFindChangePrefix2 + 186)
DECLARE_PMID(kActionIDSpace, kChangeQuarterSpaceActionID,				kFindChangePrefix2 + 187)
DECLARE_PMID(kActionIDSpace, kChangeGrepQuarterSpaceActionID,			kFindChangePrefix2 + 188)
DECLARE_PMID(kActionIDSpace, kFindSixthSpaceActionID,					kFindChangePrefix2 + 189)
DECLARE_PMID(kActionIDSpace, kFindGrepSixthSpaceActionID,				kFindChangePrefix2 + 190)
DECLARE_PMID(kActionIDSpace, kChangeSixthSpaceActionID,					kFindChangePrefix2 + 191)
DECLARE_PMID(kActionIDSpace, kChangeGrepSixthSpaceActionID,				kFindChangePrefix2 + 192)
DECLARE_PMID(kActionIDSpace, kFindAnyKanjiActionID,						kFindChangePrefix2 + 193)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyKanjiActionID,					kFindChangePrefix2 + 194)
DECLARE_PMID(kActionIDSpace, kChangeGrepEndOfLineActionID,				kFindChangePrefix2 + 195)
DECLARE_PMID(kActionIDSpace, kChangeGrepEndNestedStyleActionID,			kFindChangePrefix2 + 196)
DECLARE_PMID(kActionIDSpace, kChangeGrepClipboardFormattedActionID,		kFindChangePrefix2 + 197)
DECLARE_PMID(kActionIDSpace, kChangeGrepClipboardUnformattedActionID,	kFindChangePrefix2 + 198)
DECLARE_PMID(kActionIDSpace, kFindGrepAnyVariableActionID,				kFindChangePrefix2 + 199)
DECLARE_PMID(kActionIDSpace, kChangeGrepStraightDoubleQuotationMarksActionID,				kFindChangePrefix2 + 200)
DECLARE_PMID(kActionIDSpace, kChangeGrepStraightSingleQuotationMarksActionID,				kFindChangePrefix2 + 201)
DECLARE_PMID(kActionIDSpace, kFindDiscLineBreakActionID,				kFindChangePrefix2 + 202)
DECLARE_PMID(kActionIDSpace, kChangeDiscLineBreakActionID,				kFindChangePrefix2 + 203)

DECLARE_PMID(kActionIDSpace, kQuickApplyCharacterStylesPrefActionID,	kFindChangePrefix2 + 204)
DECLARE_PMID(kActionIDSpace, kQuickApplyParagraphStylesPrefActionID,	kFindChangePrefix2 + 205)
DECLARE_PMID(kActionIDSpace, kQuickApplyObjectStylesPrefActionID,		kFindChangePrefix2 + 206)
DECLARE_PMID(kActionIDSpace, kQuickApplyMenuActionsPrefActionID,		kFindChangePrefix2 + 207)
DECLARE_PMID(kActionIDSpace, kQuickApplySeperatorActionID,				kFindChangePrefix2 + 208)
DECLARE_PMID(kActionIDSpace, kQuickApplyShowHiddenUIActionID,			kFindChangePrefix2 + 209)
DECLARE_PMID(kActionIDSpace, kQuickApplyScriptsPrefActionID,			kFindChangePrefix2 + 210)

DECLARE_PMID(kActionIDSpace, kLoadFindGlyphActionID,			kFindChangePrefix2 + 211)
DECLARE_PMID(kActionIDSpace, kLoadChangeGlyphActionID,			kFindChangePrefix2 + 212)
DECLARE_PMID(kActionIDSpace, kLoadFindRtMouseGlyphActionID,		kFindChangePrefix2 + 213)
DECLARE_PMID(kActionIDSpace, kLoadChangeRtMouseGlyphActionID,	kFindChangePrefix2 + 214)

DECLARE_PMID(kActionIDSpace, kGrepLoadFindStringActionID,		kFindChangePrefix2 + 215)
DECLARE_PMID(kActionIDSpace, kGrepFindActionID,					kFindChangePrefix2 + 216)
DECLARE_PMID(kActionIDSpace, kGrepLoadAndFindActionID,			kFindChangePrefix2 + 217)
DECLARE_PMID(kActionIDSpace, kGrepReplaceFindActionID,			kFindChangePrefix2 + 218)
DECLARE_PMID(kActionIDSpace, kGrepReplaceActionID,				kFindChangePrefix2 + 219)
DECLARE_PMID(kActionIDSpace, kGrepLoadReplaceStringActionID,	kFindChangePrefix2 + 220)
DECLARE_PMID(kActionIDSpace, kLoadFindGlyphSepActionID,			kFindChangePrefix2 + 221)

DECLARE_PMID(kActionIDSpace, kToggleSearchDirectionActionID,			kFindChangePrefix2 + 222)

DECLARE_PMID(kActionIDSpace, kFindEndnoteReferenceActionID, kFindChangePrefix2 + 223)
DECLARE_PMID(kActionIDSpace, kChangeEndnoteReferenceActionID, kFindChangePrefix2 + 224)
DECLARE_PMID(kActionIDSpace, kFindGrepEndnoteReferenceActionID, kFindChangePrefix2 + 225)
DECLARE_PMID(kActionIDSpace, kChangeGrepEndnoteReferenceActionID, kFindChangePrefix2 + 226)

// <Service ID>
//******SERVICE IDs
DECLARE_PMID(kServiceIDSpace, kFindChangeStringService, kFindChangePrefix + 1)
DECLARE_PMID(kServiceIDSpace, kQuickApplyService, kFindChangePrefix + 2)
DECLARE_PMID(kServiceIDSpace, kFindChangeMiniTabbedDialogService, kFindChangePrefix + 3)
DECLARE_PMID(kServiceIDSpace, kFindChangeInCopyTabbedDialogService, kFindChangePrefix + 4)
DECLARE_PMID(kServiceIDSpace, kQuickApplyFilterService, kFindChangePrefix + 5)

//Errors
DECLARE_PMID(kErrorIDSpace, kFindChangeInvalidClipboardErr,			kFindChangePrefix + 1)
DECLARE_PMID(kErrorIDSpace, kChangeGlyphInvalidFontGroupErr,		kFindChangePrefix + 2)

// Tree Node ID types
#define kKillerFindNodeID	kFindChangePrefix + 1

#endif
		// __FindChangeID__
