//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/text/TextEditorImplID.h $
//  
//  Owner: ???
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __TextEditorImplID__
#define __TextEditorImplID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"
#include "ShuksanID.h"


#define kTextEditorPrefix		RezLong(0x1d300)


// <Widget ID>

DECLARE_PMID(kWidgetIDSpace, kIBeamToolWidgetId, kTextEditorPrefix + 1)
DECLARE_PMID(kWidgetIDSpace, kVerticalTextToolWidgetId, kTextEditorPrefix + 2)
DECLARE_PMID(kWidgetIDSpace, kTextEditorWidgetID, kTextEditorPrefix + 3)

// ----------------------------------------------------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVManageVariablesDialogWidgetID, kTextEditorPrefix + 4)

DECLARE_PMID(kWidgetIDSpace, kTVButtonColumnWidgetID, kTextEditorPrefix + 5)
	DECLARE_PMID(kWidgetIDSpace, kTVInsertVarButtonWidgetID, kTextEditorPrefix + 6)
	DECLARE_PMID(kWidgetIDSpace, kTVNewVarButtonWidgetID, kTextEditorPrefix + 7)
	DECLARE_PMID(kWidgetIDSpace, kTVEditVarButtonWidgetID, kTextEditorPrefix + 8)
	DECLARE_PMID(kWidgetIDSpace, kTVRemoveVarButtonWidgetID, kTextEditorPrefix + 9)
	DECLARE_PMID(kWidgetIDSpace, kTVLoadVarButtonWidgetID, kTextEditorPrefix + 10)
	DECLARE_PMID(kWidgetIDSpace, kTVConvertVarButtonWidgetID, kTextEditorPrefix + 11)

DECLARE_PMID(kWidgetIDSpace, kTVVariablesListAreaWidgetID, kTextEditorPrefix + 12)
	DECLARE_PMID(kWidgetIDSpace, kTVVariablesLabelWidgetID, kTextEditorPrefix + 13)
	DECLARE_PMID(kWidgetIDSpace, kTVVarListBoxWidgetID, kTextEditorPrefix + 14)

DECLARE_PMID(kWidgetIDSpace, kTVPreviewAreaWidgetID, kTextEditorPrefix + 15)
	DECLARE_PMID(kWidgetIDSpace, kTVPreviewLabelWidgetID, kTextEditorPrefix + 16)
	DECLARE_PMID(kWidgetIDSpace, kTVPreviewInfoTextWidgetID, kTextEditorPrefix + 17)

// ----------------------------------------------------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVDeleteVariablesDialogWidgetID, kTextEditorPrefix + 18)
	DECLARE_PMID(kWidgetIDSpace, kTVDescriptionAreaWidgetID, kTextEditorPrefix + 19)
		DECLARE_PMID(kWidgetIDSpace, kTVWarnIconWidgetID, kTextEditorPrefix + 20)
		DECLARE_PMID(kWidgetIDSpace, kTVDescriptionLabelWidgetID, kTextEditorPrefix + 21)
	DECLARE_PMID(kWidgetIDSpace, kTVDeleteControlPanelWidgetID, kTextEditorPrefix + 22)
		DECLARE_PMID(kWidgetIDSpace, kTVDeleteColumnAWidgetID, kTextEditorPrefix + 23)
			DECLARE_PMID(kWidgetIDSpace, kTVDeleteRadioButtonWidgetID, kTextEditorPrefix + 24)
			DECLARE_PMID(kWidgetIDSpace, kTVConvertRadioButtonWidgetID, kTextEditorPrefix + 25)
			DECLARE_PMID(kWidgetIDSpace, kTVExistingVarRadioButtonWidgetID, kTextEditorPrefix + 26)
		DECLARE_PMID(kWidgetIDSpace, kTVDeleteColumnBWidgetID, kTextEditorPrefix + 27)
			DECLARE_PMID(kWidgetIDSpace, kTVExistingVariableComboBoxWidgetID, kTextEditorPrefix + 28)
	DECLARE_PMID(kWidgetIDSpace, kTVDeleteButtonsAreaWidgetID, kTextEditorPrefix + 29)

// ----------------------------------------------------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTextVariableNewEditDialogWidgetID, kTextEditorPrefix + 30)

DECLARE_PMID(kWidgetIDSpace, kTVVarNameAreaWidgetID, kTextEditorPrefix + 31)
	DECLARE_PMID(kWidgetIDSpace, kTVVarNameLabelWidgetID, kTextEditorPrefix + 32)
	DECLARE_PMID(kWidgetIDSpace, kTVVarNameComboBoxWidgetID, kTextEditorPrefix + 33)

DECLARE_PMID(kWidgetIDSpace, kTVVarTypeAreaWidgetID, kTextEditorPrefix + 34)
	DECLARE_PMID(kWidgetIDSpace, kTVVarTypeLabelWidgetID, kTextEditorPrefix + 35)
	DECLARE_PMID(kWidgetIDSpace, kTVVarTypeDropDownWidgetID, kTextEditorPrefix + 36)

DECLARE_PMID(kWidgetIDSpace, kTVVarTypeControlAreaWidgetID, kTextEditorPrefix + 37)
	DECLARE_PMID(kWidgetIDSpace, kTVVarTypeSubAreaWidgetID, kTextEditorPrefix + 38)

// ------------------------------- TEXT -----------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVCustomTextVariablePanelWidgetID, kTextEditorPrefix + 39)
	DECLARE_PMID(kWidgetIDSpace, kTVCustomTextAreaWidgetID, kTextEditorPrefix + 40)
		DECLARE_PMID(kWidgetIDSpace, kTVCustomTextLabelWidgetID, kTextEditorPrefix + 41)
		DECLARE_PMID(kWidgetIDSpace, kTVCustomTextEditBoxWidgetID, kTextEditorPrefix + 42)
		DECLARE_PMID(kWidgetIDSpace, kTVCustomTextMetaMenuAreaWidgetID, kTextEditorPrefix + 43)
			DECLARE_PMID(kWidgetIDSpace, kTVCustomTextMetaMenuPanelWidgetID, kTextEditorPrefix + 44)
				DECLARE_PMID(kWidgetIDSpace, kTVCustomTextMetaMenuButtonWidgetID, kTextEditorPrefix + 45)
	DECLARE_PMID(kWidgetIDSpace, kTVHideFirstAreaWidgetID, kTextEditorPrefix + 46)
	DECLARE_PMID(kWidgetIDSpace, kTVHideLastAreaWidgetID, kTextEditorPrefix + 48)
		DECLARE_PMID(kWidgetIDSpace, kTVHideFirstCheckBoxWidgetID, kTextEditorPrefix + 47)
		DECLARE_PMID(kWidgetIDSpace, kTVHideLastCheckBoxWidgetID, kTextEditorPrefix + 49)

// ------------------------------ FILE NAME --------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVFileNameVariablePanelWidgetID, kTextEditorPrefix + 50)
	DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeAreaWidgetID, kTextEditorPrefix + 51)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeLabelWidgetID, kTextEditorPrefix + 52)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeEditBoxWidgetID, kTextEditorPrefix + 53)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 54)
			DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 55)
				DECLARE_PMID(kWidgetIDSpace, kTVFNTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 56)

	DECLARE_PMID(kWidgetIDSpace, kTVIncludePathAreaWidgetID, kTextEditorPrefix + 57)
	DECLARE_PMID(kWidgetIDSpace, kTVIncludeExtAreaWidgetID, kTextEditorPrefix + 59)
		DECLARE_PMID(kWidgetIDSpace, kTVIncludeExtensionCheckBoxWidgetID, kTextEditorPrefix + 58)
		DECLARE_PMID(kWidgetIDSpace, kTVIncludePathCheckBoxWidgetID, kTextEditorPrefix + 60)

	DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterAreaWidgetID, kTextEditorPrefix + 61)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterLabelWidgetID, kTextEditorPrefix + 62)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterEditBoxWidgetID, kTextEditorPrefix + 63)
		DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 64)
			DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 65)
				DECLARE_PMID(kWidgetIDSpace, kTVFNTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 66)

// ----------------------------- DATE  ------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVDateVariablePanelWidgetID, kTextEditorPrefix + 67)
	DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeAreaWidgetID, kTextEditorPrefix + 68)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeLabelWidgetID, kTextEditorPrefix + 69)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeEditBoxWidgetID, kTextEditorPrefix + 70)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 71)
			DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 72)
				DECLARE_PMID(kWidgetIDSpace, kTVDTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 73)

	DECLARE_PMID(kWidgetIDSpace, kTVDateAreaWidgetID, kTextEditorPrefix + 74)
		DECLARE_PMID(kWidgetIDSpace, kTVDateFormatLabelWidgetID, kTextEditorPrefix + 75)
		DECLARE_PMID(kWidgetIDSpace, kTVDateFormatComboBoxWidgetID, kTextEditorPrefix + 76)
		DECLARE_PMID(kWidgetIDSpace, kTVDDateMetaMenuAreaWidgetID, kTextEditorPrefix + 77)
			//DECLARE_PMID(kWidgetIDSpace, kTVDDateMetaMenuPanelWidgetID, kTextEditorPrefix + 78)
				DECLARE_PMID(kWidgetIDSpace, kTVDDateMetaMenuButtonWidgetID, kTextEditorPrefix + 79)

	DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterAreaWidgetID, kTextEditorPrefix + 80)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterLabelWidgetID, kTextEditorPrefix + 81)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterEditBoxWidgetID, kTextEditorPrefix + 82)
		DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 83)
			DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 84)
				DECLARE_PMID(kWidgetIDSpace, kTVDTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 85)

	DECLARE_PMID(kWidgetIDSpace, kTVDJNumbersAreaWidgetID, kTextEditorPrefix + 86)
		DECLARE_PMID(kWidgetIDSpace, kTVDLabelsAreaWidgetID, kTextEditorPrefix + 87)
		DECLARE_PMID(kWidgetIDSpace, kTVDControlsAreaWidgetID, kTextEditorPrefix + 88)
			DECLARE_PMID(kWidgetIDSpace, kTVDEmperorDateCheckBoxWidgetID, kTextEditorPrefix + 89)

// ----------------------------- CHAPTER ----------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVChapterVariablePanelWidgetID, kTextEditorPrefix + 91)
	DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeAreaWidgetID, kTextEditorPrefix + 92)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeLabelWidgetID, kTextEditorPrefix + 93)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeEditBoxWidgetID, kTextEditorPrefix + 94)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 95)
			DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 96)
				DECLARE_PMID(kWidgetIDSpace, kTVCNTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 97)

	DECLARE_PMID(kWidgetIDSpace, kTVChapterAreaWidgetID, kTextEditorPrefix + 98)
		DECLARE_PMID(kWidgetIDSpace, kTVChapterFormatLabelWidgetID, kTextEditorPrefix + 99)
		DECLARE_PMID(kWidgetIDSpace, kTVChapterFormatComboBoxWidgetID, kTextEditorPrefix + 100)

	DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterAreaWidgetID, kTextEditorPrefix + 101)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterLabelWidgetID, kTextEditorPrefix + 102)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterEditBoxWidgetID, kTextEditorPrefix + 103)
		DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 104)
			DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 105)
				DECLARE_PMID(kWidgetIDSpace, kTVCNTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 106)


DECLARE_PMID(kWidgetIDSpace, XXX_A, kTextEditorPrefix + 112)
DECLARE_PMID(kWidgetIDSpace, XXX_B, kTextEditorPrefix + 113)
DECLARE_PMID(kWidgetIDSpace, XXX_C, kTextEditorPrefix + 114)


// -----------------------------PAGE COUNT ---------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVPageCountVariablePanelWidgetID, kTextEditorPrefix + 115)
	DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeAreaWidgetID, kTextEditorPrefix + 116)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeLabelWidgetID, kTextEditorPrefix + 117)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeEditBoxWidgetID, kTextEditorPrefix + 118)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 119)
			DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 120)
				DECLARE_PMID(kWidgetIDSpace, kTVPCTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 121)

	DECLARE_PMID(kWidgetIDSpace, kTVPageCountAreaWidgetID, kTextEditorPrefix + 122)
		DECLARE_PMID(kWidgetIDSpace, kTVPageCountFormatLabelWidgetID, kTextEditorPrefix + 123)
		DECLARE_PMID(kWidgetIDSpace, kTVPageCountFormatComboBoxWidgetID, kTextEditorPrefix + 124)
	DECLARE_PMID(kWidgetIDSpace, kTVPageCountScopeAreaWidgetID, kTextEditorPrefix + 125)
		DECLARE_PMID(kWidgetIDSpace, kTVScopeLabelWidgetID, kTextEditorPrefix + 126)
		DECLARE_PMID(kWidgetIDSpace, kTVScopeComboBoxWidgetID, kTextEditorPrefix + 127)

	DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterAreaWidgetID, kTextEditorPrefix + 128)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterLabelWidgetID, kTextEditorPrefix + 129)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterEditBoxWidgetID, kTextEditorPrefix + 130)
		DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 131)
			DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 132)
				DECLARE_PMID(kWidgetIDSpace, kTVPCTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 133)

	DECLARE_PMID(kWidgetIDSpace, kTVPCJNumbersAreaWidgetID, kTextEditorPrefix + 134)
		DECLARE_PMID(kWidgetIDSpace, kTVPCLabelsAreaWidgetID, kTextEditorPrefix + 137)
		DECLARE_PMID(kWidgetIDSpace, kTVPCControlsAreaWidgetID, kTextEditorPrefix + 135)
			DECLARE_PMID(kWidgetIDSpace, kTVPCRemoveMojikumiAkiCheckBoxWidgetID, kTextEditorPrefix + 136)
			DECLARE_PMID(kWidgetIDSpace, kTVPCUseOTHWCheckBoxWidgetID, kTextEditorPrefix + 138)
DECLARE_PMID(kWidgetIDSpace, XXX_G, kTextEditorPrefix + 139)
DECLARE_PMID(kWidgetIDSpace, XXX_H, kTextEditorPrefix + 140)
DECLARE_PMID(kWidgetIDSpace, XXX_I, kTextEditorPrefix + 141)

// ------------------------------ STYLE --------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVCPStyleVariablePanelWidgetID, kTextEditorPrefix + 142)
	DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeAreaWidgetID, kTextEditorPrefix + 143)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeLabelWidgetID, kTextEditorPrefix + 144)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeEditBoxWidgetID, kTextEditorPrefix + 145)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 146)
			DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 147)
				DECLARE_PMID(kWidgetIDSpace, kTVCPTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 148)

	DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterAreaWidgetID, kTextEditorPrefix + 149)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterLabelWidgetID, kTextEditorPrefix + 150)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterEditBoxWidgetID, kTextEditorPrefix + 151)
		DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 152)
			DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 153)
				DECLARE_PMID(kWidgetIDSpace, kTVCPTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 154)

	DECLARE_PMID(kWidgetIDSpace, kTVCPAreaWidgetID, kTextEditorPrefix + 155)
			DECLARE_PMID(kWidgetIDSpace, kTVCPStyleFormatLabelWidgetID, kTextEditorPrefix + 156)
			DECLARE_PMID(kWidgetIDSpace, kTVCPStyleAreaWidgetID, kTextEditorPrefix + 157)
				DECLARE_PMID(kWidgetIDSpace, kTVCStyleFormatComboBoxWidgetID, kTextEditorPrefix + 158)
				DECLARE_PMID(kWidgetIDSpace, kTVPStyleFormatComboBoxWidgetID, kTextEditorPrefix + 159)
		DECLARE_PMID(kWidgetIDSpace, kTVCPUseAreaWidgetID, kTextEditorPrefix + 160)
			DECLARE_PMID(kWidgetIDSpace, kTVUseLabelWidgetID, kTextEditorPrefix + 161)
			DECLARE_PMID(kWidgetIDSpace, kTVUseComboBoxWidgetID, kTextEditorPrefix + 162)
		DECLARE_PMID(kWidgetIDSpace, kTVCPOptionsAreaWidgetID, kTextEditorPrefix + 163)
			DECLARE_PMID(kWidgetIDSpace, kTVCPOptionsLabelWidgetID, kTextEditorPrefix + 164)
			DECLARE_PMID(kWidgetIDSpace, kTVCPOptionsWidgetID, kTextEditorPrefix + 165)

// ----------------------------------------------------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaAWidgetID, kTextEditorPrefix + 166)
DECLARE_PMID(kWidgetIDSpace, kTVCPDeleteEndPunctuationWidgetID, kTextEditorPrefix + 167)
DECLARE_PMID(kWidgetIDSpace, kTVCPChangeCaseWidgetID, kTextEditorPrefix + 168)
DECLARE_PMID(kWidgetIDSpace, kTVCPChangeCaseClusterWidgetID, kTextEditorPrefix + 169)
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelEreaAWidgetID, kTextEditorPrefix + 170)
DECLARE_PMID(kWidgetIDSpace, kTVCPHideFirstWidgetID, kTextEditorPrefix + 171)
DECLARE_PMID(kWidgetIDSpace, kTVCPHideLastWidgetID, kTextEditorPrefix + 172)
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaHWidgetID, kTextEditorPrefix + 173)
DECLARE_PMID(kWidgetIDSpace, kTVCPUpperCaseRadioWidgetID, kTextEditorPrefix + 174)
DECLARE_PMID(kWidgetIDSpace, kTVCPLowerCaseRadioWidgetID, kTextEditorPrefix + 175)
DECLARE_PMID(kWidgetIDSpace, kTVCPTitleCaseRadioWidgetID, kTextEditorPrefix + 176)
DECLARE_PMID(kWidgetIDSpace, kTVCPSentenceCaseRadioWidgetID, kTextEditorPrefix + 177)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaMWidgetID, kTextEditorPrefix + 178)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaNWidgetID, kTextEditorPrefix + 179)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaOWidgetID, kTextEditorPrefix + 180)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaPWidgetID, kTextEditorPrefix + 181)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaQWidgetID, kTextEditorPrefix + 182)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaRWidgetID, kTextEditorPrefix + 183)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaSWidgetID, kTextEditorPrefix + 184)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaTWidgetID, kTextEditorPrefix + 185)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaUWidgetID, kTextEditorPrefix + 186)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaVWidgetID, kTextEditorPrefix + 187)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaWWidgetID, kTextEditorPrefix + 188)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaXWidgetID, kTextEditorPrefix + 189)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaYWidgetID, kTextEditorPrefix + 190)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAreaZWidgetID, kTextEditorPrefix + 191)
//
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelAWidgetID, kTextEditorPrefix + 192)
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelBWidgetID, kTextEditorPrefix + 193)
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelCWidgetID, kTextEditorPrefix + 194)
DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelDWidgetID, kTextEditorPrefix + 195)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelEWidgetID, kTextEditorPrefix + 196)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelFWidgetID, kTextEditorPrefix + 197)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelGWidgetID, kTextEditorPrefix + 198)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelHWidgetID, kTextEditorPrefix + 199)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelIWidgetID, kTextEditorPrefix + 200)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelJWidgetID, kTextEditorPrefix + 201)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelKWidgetID, kTextEditorPrefix + 202)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelLWidgetID, kTextEditorPrefix + 203)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelMWidgetID, kTextEditorPrefix + 204)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelNWidgetID, kTextEditorPrefix + 205)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelOWidgetID, kTextEditorPrefix + 206)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelPWidgetID, kTextEditorPrefix + 207)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelQWidgetID, kTextEditorPrefix + 208)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelRWidgetID, kTextEditorPrefix + 209)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelSWidgetID, kTextEditorPrefix + 210)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelTWidgetID, kTextEditorPrefix + 211)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelUWidgetID, kTextEditorPrefix + 212)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelVWidgetID, kTextEditorPrefix + 213)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelWWidgetID, kTextEditorPrefix + 214)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelXWidgetID, kTextEditorPrefix + 215)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelYWidgetID, kTextEditorPrefix + 216)
//DECLARE_PMID(kWidgetIDSpace, kTVEmptyLabelZWidgetID, kTextEditorPrefix + 217)

// ------------------------------ Link Metadata --------------------------------------------------------------------
DECLARE_PMID(kWidgetIDSpace, kTVLinkMetadataVariablePanelWidgetID, kTextEditorPrefix + 218)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDProviderDropDownWidgetID, kTextEditorPrefix + 219)
	
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeAreaWidgetID, kTextEditorPrefix + 220)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeLabelWidgetID, kTextEditorPrefix + 221)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeEditBoxWidgetID, kTextEditorPrefix + 222)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeMetaMenuAreaWidgetID, kTextEditorPrefix + 223)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeMetaMenuPanelWidgetID, kTextEditorPrefix + 224)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextBeforeMetaMenuButtonWidgetID, kTextEditorPrefix + 225)
	
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterAreaWidgetID, kTextEditorPrefix + 226)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterLabelWidgetID, kTextEditorPrefix + 227)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterEditBoxWidgetID, kTextEditorPrefix + 228)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterMetaMenuAreaWidgetID, kTextEditorPrefix + 229)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterMetaMenuPanelWidgetID, kTextEditorPrefix + 230)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDTextAfterMetaMenuButtonWidgetID, kTextEditorPrefix + 231)
	DECLARE_PMID(kWidgetIDSpace, kTVLinkMDProviderLabelWidgetID, kTextEditorPrefix + 232)

DECLARE_PMID(kWidgetIDSpace, kPlaceHolderDialogWidgetID, kTextEditorPrefix + 233)
DECLARE_PMID(kWidgetIDSpace, kPlaceHolderStaticWidgetID, kTextEditorPrefix + 234)
DECLARE_PMID(kWidgetIDSpace, kPlaceHolderDropdownWidgetID, kTextEditorPrefix + 235)


//---------------------------------------------------------------
// Implementation IDs
//---------------------------------------------------------------
DECLARE_PMID(kImplementationIDSpace, kTextEditorImpl, kTextEditorPrefix + 2	)
DECLARE_PMID(kImplementationIDSpace, kFrameItemObserverImpl, kTextEditorPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kFrameEventHandlerImpl, kTextEditorPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kFrameViewFocusImpl, kTextEditorPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kEditorToFrameImpl, kTextEditorPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kFrameViewHelperImpl, kTextEditorPrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kGenericMoveResizeObjectDataImpl, kTextEditorPrefix + 9)

DECLARE_PMID(kImplementationIDSpace, kAnchoredObjectAdornmentImpl, kTextEditorPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kTextEditorUtilsImpl, kTextEditorPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kOpenTypeAdornmentImpl, kTextEditorPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kOpenTypeTipImpl, kTextEditorPrefix + 13)
// OBSOLETE DECLARE_PMID(kImplementationIDSpace, kImpl???, kTextEditorPrefix + 12)
// OBSOLETE DECLARE_PMID(kImplementationIDSpace, kImpl???, kTextEditorPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kTextEditorTrackerRegisterImpl, kTextEditorPrefix + 14)
DECLARE_PMID(kImplementationIDSpace, kFrameListObserverImpl, kTextEditorPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kTextFocusPlaceBehaviorUIImpl, kTextEditorPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kTextCaretThreadImpl, kTextEditorPrefix + 17	)
DECLARE_PMID(kImplementationIDSpace, kTextCaretImpl, kTextEditorPrefix + 18	)
DECLARE_PMID(kImplementationIDSpace, kTextEditorMenuComponentImpl, kTextEditorPrefix + 19	)

DECLARE_PMID(kImplementationIDSpace, kTextCaretSelectionObserverImpl, kTextEditorPrefix + 20	)
DECLARE_PMID(kImplementationIDSpace, kMultiFramePlaceBehaviorUIImpl, kTextEditorPrefix + 21	)
DECLARE_PMID(kImplementationIDSpace, kFrameWidgetCreatorImpl, kTextEditorPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kTextSelectionDataImpl, kTextEditorPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kIBeamToolImpl, kTextEditorPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kIBeamTrackerImpl, kTextEditorPrefix + 25)
DECLARE_PMID(kImplementationIDSpace, kTextFrameILGMoveTrackerImpl, kTextEditorPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kTextSelectTrackerImpl, kTextEditorPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kFrameTrackerImpl, kTextEditorPrefix + 28)

//DECLARE_PMID(kImplementationIDSpace, kTextSelectionSnapshotImpl, kTextEditorPrefix + 30)
//DECLARE_PMID(kImplementationIDSpace, kLinkTrackerEHImpl, kTextEditorPrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kTextSelectionDrawerImpl, kTextEditorPrefix + 32)
//DECLARE_PMID(kImplementationIDSpace, kActivateTextEditorCmdImpl, kTextEditorPrefix + 33)
//DECLARE_PMID(kImplementationIDSpace, kActivateTextEditorCmdImpl, kTextEditorPrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kTypeKeyShortcutsImpl, kTextEditorPrefix + 35)
DECLARE_PMID(kImplementationIDSpace, kTextOffscreenImpl, kTextEditorPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kTextOffscreenObserverImpl, kTextEditorPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kTextOffscreenServiceImpl, kTextEditorPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kTextOffscreenSpriteImpl, kTextEditorPrefix + 39)

//gap
DECLARE_PMID(kImplementationIDSpace, kILGTrackerImpl, kTextEditorPrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kILGMoveTrackerImpl, kTextEditorPrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kILGMoveToolImpl, kTextEditorPrefix + 43)		// currently only used for tracker registration
DECLARE_PMID(kImplementationIDSpace, kILGRotateTrackerImpl, kTextEditorPrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kILGRotateToolImpl, kTextEditorPrefix + 45)		// currently only used for tracker registration
DECLARE_PMID(kImplementationIDSpace, kILGConstrainTrackerImpl, kTextEditorPrefix + 46		)
DECLARE_PMID(kImplementationIDSpace, kILGRotateTrackerDataImpl, kTextEditorPrefix + 47		)
DECLARE_PMID(kImplementationIDSpace, kILGMoveConstrainImpl, kTextEditorPrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kILGRotateConstrainImpl, kTextEditorPrefix + 49)

DECLARE_PMID(kImplementationIDSpace, kAnchObjDragDropTextResponderImpl, kTextEditorPrefix + 50)
DECLARE_PMID(kImplementationIDSpace, kVerticalTextToolImpl, kTextEditorPrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kEyeDropperSuiteTextImpl, kTextEditorPrefix + 52)
DECLARE_PMID(kImplementationIDSpace, kTextKeyboardShortcutsImpl, kTextEditorPrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kHorizontalIBeamCrsrProviderImpl, kTextEditorPrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kVerticalIBeamCrsrProviderImpl, kTextEditorPrefix + 55)
DECLARE_PMID(kImplementationIDSpace, kInlineSelectionFilterImpl, kTextEditorPrefix + 56)
DECLARE_PMID(kImplementationIDSpace, kTableDragDropTextResponderImpl, kTextEditorPrefix + 57)
DECLARE_PMID(kImplementationIDSpace, kScrollViewToCenterFlagImpl, kTextEditorPrefix + 58)
// gap
DECLARE_PMID(kImplementationIDSpace, kComposerTestMenuImpl, kTextEditorPrefix + 60)
DECLARE_PMID(kImplementationIDSpace, kHitTestObjectWithNoneFlagImpl, kTextEditorPrefix + 61)
DECLARE_PMID(kImplementationIDSpace, kApplyStyleShortcutsImpl, kTextEditorPrefix + 62)
DECLARE_PMID(kImplementationIDSpace, kTextFrameShortcutsImpl, kTextEditorPrefix + 63)
DECLARE_PMID(kImplementationIDSpace, kTextSelectionNavigatorImpl, kTextEditorPrefix + 66)
//DECLARE_PMID(kImplementationIDSpace, kTextSelectionNavigatorImpl, kTextEditorPrefix + 67)
//DECLARE_PMID(kImplementationIDSpace, kTextSelectionNavigatorImpl, kTextEditorPrefix + 68)
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionWidgetParentImpl, kTextEditorPrefix + 69)

DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionSubjectImpl, kTextEditorPrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionDrawerImpl, kTextEditorPrefix + 71)
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionNavigator, kTextEditorPrefix + 72)
DECLARE_PMID(kImplementationIDSpace, kFwdTextCaretThreadImpl, kTextEditorPrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kFwdTextCaretImpl, kTextEditorPrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionObserverImpl, kTextEditorPrefix + 75)

DECLARE_PMID(kImplementationIDSpace, kTextVariableNewEditDialogCreatorImpl, kTextEditorPrefix + 76)
DECLARE_PMID(kImplementationIDSpace, kTextVariableObserverImpl, kTextEditorPrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kTextVariableControllerImpl, kTextEditorPrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kTVNewEditDialogCreatorImpl, kTextEditorPrefix + 79)

DECLARE_PMID(kImplementationIDSpace, kOldTextEditorShortcutContextImpl, kTextEditorPrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kIBeamCursorHandlerImpl, kTextEditorPrefix + 81)
//gap
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionDataImpl, kTextEditorPrefix + 85)
DECLARE_PMID(kImplementationIDSpace, kFwdTextSelectionImpl, kTextEditorPrefix + 86)
DECLARE_PMID(kImplementationIDSpace, kCJKTypeKeyShortcutsImpl, kTextEditorPrefix + 87)
DECLARE_PMID(kImplementationIDSpace, kConcreteTextSelectionImpl, kTextEditorPrefix + 88)
DECLARE_PMID(kImplementationIDSpace, kTextEditorShortcutContextImpl, kTextEditorPrefix + 89)

DECLARE_PMID(kImplementationIDSpace, kTextToolEventWatcherImpl, kTextEditorPrefix + 90)
DECLARE_PMID(kImplementationIDSpace, kSelectionDataSuiteTextCSBImpl, kTextEditorPrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kSelectionSnapshotTextCSBImpl, kTextEditorPrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kToolChangeSuiteTextCSBImpl, kTextEditorPrefix + 93)
DECLARE_PMID(kImplementationIDSpace, kContextMenuSuiteTextCSBImpl, kTextEditorPrefix + 94)
DECLARE_PMID(kImplementationIDSpace, kTabPanelSuiteImpl, kTextEditorPrefix + 95)
DECLARE_PMID(kImplementationIDSpace, kPrePlaceTrackerImpl, kTextEditorPrefix + 96)
DECLARE_PMID(kImplementationIDSpace, kPrePlaceTrackerEventHandlerImpl, kTextEditorPrefix + 97)
DECLARE_PMID(kImplementationIDSpace, kTextTrackerRegisterImpl, kTextEditorPrefix + 98)
DECLARE_PMID(kImplementationIDSpace, kTextTestMenuImpl, kTextEditorPrefix + 99)

DECLARE_PMID(kImplementationIDSpace, kCompositionThreadImpl, kTextEditorPrefix + 100)
DECLARE_PMID(kImplementationIDSpace, kCompositionThreadRunningImpl, kTextEditorPrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kTextEditorStartupShutdownImpl, kTextEditorPrefix + 102 )
DECLARE_PMID(kImplementationIDSpace, kShiftReleaseEventWatcherImpl, kTextEditorPrefix + 103 )
DECLARE_PMID(kImplementationIDSpace, kTextSelectionFactoryImpl, kTextEditorPrefix + 104 )
DECLARE_PMID(kImplementationIDSpace, kTextSelectionHighlighterImpl, kTextEditorPrefix + 105)
DECLARE_PMID(kImplementationIDSpace, kDragDropTextSuiteASBImpl, kTextEditorPrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kDragDropTextSuiteTextCSBImpl, kTextEditorPrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kFNCIBeamDataImpl, kTextEditorPrefix + 108 )
DECLARE_PMID(kImplementationIDSpace, kFootnoteTextSelectTrackerImpl, kTextEditorPrefix + 109 )

DECLARE_PMID(kImplementationIDSpace, kTextFrameDragDropSourceImpl, kTextEditorPrefix + 110)
DECLARE_PMID(kImplementationIDSpace, kTextFrameDragDropTargetImpl, kTextEditorPrefix + 111)
DECLARE_PMID(kImplementationIDSpace, kDragDropTextUtilsImpl, kTextEditorPrefix + 112)
DECLARE_PMID(kImplementationIDSpace, kLayoutDDTargetTextFlavorHelperImpl, kTextEditorPrefix + 113)
DECLARE_PMID(kImplementationIDSpace, kGalleyDragDropSourceImpl, kTextEditorPrefix + 114)
DECLARE_PMID(kImplementationIDSpace, kGalleyDragDropTargetImpl, kTextEditorPrefix + 115)
DECLARE_PMID(kImplementationIDSpace, kDragDropTextSuiteGalleyCSBImpl, kTextEditorPrefix + 116)
DECLARE_PMID(kImplementationIDSpace, kTablesDDTargetTextFlavorHelperImpl, kTextEditorPrefix + 117)
DECLARE_PMID(kImplementationIDSpace, kTextFrameDragDropTextHelperImpl, kTextEditorPrefix + 118)
DECLARE_PMID(kImplementationIDSpace, kGalleyDragDropTextHelperImpl, kTextEditorPrefix + 119)

DECLARE_PMID(kImplementationIDSpace, kTOPDragDropTextHelperImpl, kTextEditorPrefix + 120 )
DECLARE_PMID(kImplementationIDSpace, kFootnoteDragDropTextHelperImpl, kTextEditorPrefix + 121 )
DECLARE_PMID(kImplementationIDSpace, kTextSelectionIntegratorSuiteImpl, kTextEditorPrefix + 122 )
DECLARE_PMID(kImplementationIDSpace, kTablesDragDropTextHelperImpl, kTextEditorPrefix + 123 )
DECLARE_PMID(kImplementationIDSpace, kDragDropTextCmdImpl, kTextEditorPrefix + 124)
DECLARE_PMID(kImplementationIDSpace, kDragDropTextSignalDataImpl, kTextEditorPrefix + 125)
DECLARE_PMID(kImplementationIDSpace, kBeforeDragTextSignalResponderServiceImpl, kTextEditorPrefix + 126)
DECLARE_PMID(kImplementationIDSpace, kBeforeDropTextSignalResponderServiceImpl, kTextEditorPrefix + 127)
DECLARE_PMID(kImplementationIDSpace, kAfterDropTextSignalResponderServiceImpl, kTextEditorPrefix + 128)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDragDropTextResponderImpl, kTextEditorPrefix + 129)

DECLARE_PMID(kImplementationIDSpace, kDeletedTextDragDropTextResponderImpl, kTextEditorPrefix + 130)
DECLARE_PMID(kImplementationIDSpace, kFootnoteDragDropTextResponderImpl, kTextEditorPrefix + 131)
DECLARE_PMID(kImplementationIDSpace, kSmartCutPasteDragDropTextResponderImpl, kTextEditorPrefix + 132)
DECLARE_PMID(kImplementationIDSpace, kNoteDragDropTextResponderImpl, kTextEditorPrefix + 133)
DECLARE_PMID(kImplementationIDSpace, kRedlineDragDropTextResponderImpl, kTextEditorPrefix + 134)
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 135 )
DECLARE_PMID(kImplementationIDSpace, kTextSelectionTypeImpl, kTextEditorPrefix + 136 )
DECLARE_PMID(kImplementationIDSpace, kTextParcelListUIImpl, kTextEditorPrefix + 137 )
DECLARE_PMID(kImplementationIDSpace, kTextCSBObserverImpl, kTextEditorPrefix + 138 )
DECLARE_PMID(kImplementationIDSpace, kTextCaretTypeImpl, kTextEditorPrefix + 139 )

DECLARE_PMID(kImplementationIDSpace, kTextOffScreenDocResponderImpl, kTextEditorPrefix + 140 )
DECLARE_PMID(kImplementationIDSpace, kTextVariableNewEditControllerImpl, kTextEditorPrefix + 141)
DECLARE_PMID(kImplementationIDSpace, kTextVariableNewEditObserverImpl, kTextEditorPrefix + 142)
DECLARE_PMID(kImplementationIDSpace, kTextVariableLoadControllerImpl, kTextEditorPrefix + 143)
DECLARE_PMID(kImplementationIDSpace, kTextVariableLoadObserverImpl, kTextEditorPrefix + 144)
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 145 )
DECLARE_PMID(kImplementationIDSpace, kTextCSBSelectionDocumentObserver, kTextEditorPrefix + 146 )
DECLARE_PMID(kImplementationIDSpace, kTextVariableDeleteControllerImpl, kTextEditorPrefix + 147 )
DECLARE_PMID(kImplementationIDSpace, kTextVariableDeleteObserverImpl, kTextEditorPrefix + 148 )
DECLARE_PMID(kImplementationIDSpace, kTextVariableListBoxEHImpl, kTextEditorPrefix + 149 )
DECLARE_PMID(kImplementationIDSpace, kTVNewEditCommonPanelControllerImpl, kTextEditorPrefix + 150 )
DECLARE_PMID(kImplementationIDSpace, kTVNewEditCommonPanelObserverImpl, kTextEditorPrefix + 151 )

DECLARE_PMID(kImplementationIDSpace, kTVMetaMenuComponentImpl, kTextEditorPrefix + 152 )
DECLARE_PMID(kImplementationIDSpace, kTVDynamicMenuComponentImpl, kTextEditorPrefix + 153)
DECLARE_PMID(kImplementationIDSpace, kTVDynamicMenuImpl, kTextEditorPrefix + 154)
DECLARE_PMID(kImplementationIDSpace, kTVDateTimeMetaMenuComponentImpl, kTextEditorPrefix + 155 )

DECLARE_PMID(kImplementationIDSpace, kQuickApplyTextVariablesServiceImpl, kTextEditorPrefix + 156 )
DECLARE_PMID(kImplementationIDSpace, kAnchoredObjectHandleTipImpl, kTextEditorPrefix + 157 )
DECLARE_PMID(kImplementationIDSpace, kAnchorTrackerImpl, kTextEditorPrefix + 158 )
DECLARE_PMID(kImplementationIDSpace, kPlaceHolderOptionsDlgCtrlImpl, kTextEditorPrefix + 159 )
DECLARE_PMID(kImplementationIDSpace, kPageItemTipImpl, kTextEditorPrefix + 160 )

DECLARE_PMID(kImplementationIDSpace, kColorThemeDropperSuiteTextImpl, kTextEditorPrefix + 161 )
DECLARE_PMID(kImplementationIDSpace, kCharacterAlternatesAdornmentImpl, kTextEditorPrefix + 162)
DECLARE_PMID(kImplementationIDSpace, kFrameMouseRollOverImpl, kTextEditorPrefix + 163)
DECLARE_PMID(kImplementationIDSpace, kCharacterAlternatesWindowEHImpl, kTextEditorPrefix + 164)
DECLARE_PMID(kImplementationIDSpace, kTypeContextualControlsPrefsImpl, kTextEditorPrefix + 165)
DECLARE_PMID(kImplementationIDSpace, kSetTypeContextualControlsPrefsCmdImpl, kTextEditorPrefix + 166 )
DECLARE_PMID(kImplementationIDSpace, kTypeContextualUIScriptProviderImpl, kTextEditorPrefix + 167)
DECLARE_PMID(kImplementationIDSpace, kTextEditorDrawEventHandlerImpl, kTextEditorPrefix + 168 )
DECLARE_PMID(kImplementationIDSpace, kTextEditorDrawServiceImpl, kTextEditorPrefix + 169 )
DECLARE_PMID(kImplementationIDSpace, kOpenTypeTrackerImpl, kTextEditorPrefix + 170)
DECLARE_PMID(kImplementationIDSpace, kOpenTypePrefsConversionProviderImpl, kTextEditorPrefix + 171)
DECLARE_PMID(kImplementationIDSpace, kEndnoteAdornmentImpl, kTextEditorPrefix + 172)
DECLARE_PMID(kImplementationIDSpace, kEndnoteTipImpl, kTextEditorPrefix + 173)
DECLARE_PMID(kImplementationIDSpace, kEndnoteTrackerImpl, kTextEditorPrefix + 174)
DECLARE_PMID(kImplementationIDSpace, kTextPDFCommentDrawUtilsImpl, kTextEditorPrefix + 175)
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 176 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 177 )
DECLARE_PMID(kImplementationIDSpace, kLayoutLineLayoutImpl, kTextEditorPrefix + 178)
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 179 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 180 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 181 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 182 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 183 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 184 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 185 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 186 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 187 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 188 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 189 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 190 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 191 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 192 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 193 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 194 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 195 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 196 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 197 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 198 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 199 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 200 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 201 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 202 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 203 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 204 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 205 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 206 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 207 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 208 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 209 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 210 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 211 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 212 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 213 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 214 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 215 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 216 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 217 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 218 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 219 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 220 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 221 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 222 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 223 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 224 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 225 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 226 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 227 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 228 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 229 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 230 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 231 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 232 )
DECLARE_PMID(kImplementationIDSpace, kStoryTextSelectionDrawerImpl, kTextEditorPrefix + 233 ) //SEIssue move this to galley
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 234 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 235 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 236 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 237 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 238 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 239 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 240 )
//DECLARE_PMID(kImplementationIDSpace, kMyFancyNewImpl, kTextEditorPrefix + 241 )
DECLARE_PMID(kImplementationIDSpace, kOpenTypeWidgetHelperImpl, kTextEditorPrefix + 242 )
DECLARE_PMID(kImplementationIDSpace, kShowHideTouchkeyBoardIdleTaskImpl, kTextEditorPrefix + 243)
DECLARE_PMID(kImplementationIDSpace, kSliderSpriteImpl, kTextEditorPrefix + 244 )
DECLARE_PMID(kImplementationIDSpace, kSliderAdornmentUtilsImpl, kTextEditorPrefix + 245)
DECLARE_PMID(kImplementationIDSpace, kFontSliderAdornmentDataImpl, kTextEditorPrefix + 246)
DECLARE_PMID(kImplementationIDSpace, kFontSliderTrackerImpl, kTextEditorPrefix + 247)
DECLARE_PMID(kImplementationIDSpace, kFontSliderTrackerRegisterImpl, kTextEditorPrefix + 248)
DECLARE_PMID(kImplementationIDSpace, kClusterBreakIteratorImpl, kTextEditorPrefix + 249 )
DECLARE_PMID(kImplementationIDSpace, kButterflyEasterEggImpl, kTextEditorPrefix + 250)
DECLARE_PMID(kImplementationIDSpace, kSimpleEggServiceImpl, kTextEditorPrefix + 251)
DECLARE_PMID(kImplementationIDSpace, kButterflyEngineImpl, kTextEditorPrefix + 252 )
DECLARE_PMID(kImplementationIDSpace, kButterflyEventHandlerImpl, kTextEditorPrefix + 253 )
DECLARE_PMID(kImplementationIDSpace, kButterflyIdleTaskImpl, kTextEditorPrefix + 254 )
DECLARE_PMID(kImplementationIDSpace, kFontSliderAdornmentImpl, kTextEditorPrefix + 255)



#endif
		// __TextEditorImplID__
