//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/text/TextAttrID.h $
//  
//  Owner: eric_menninga
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __TextAttrID__
#define __TextAttrID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

#define kTextAttrPrefix	 RezLong(0x1B00)
#define kTextAttrPrefix2 RezLong(0x1Df00)

// <Start IDC>
// PluginID
#define kTextAttrPluginName 	"Text Attributes"
DECLARE_PMID(kPlugInIDSpace, kTextAttrPluginID, kTextAttrPrefix + 1)

// <Ignore>
#define kTextAttrStringsRsrcID		1000
#define kTextAttrStringsNoTransRsrcID		1100


// <Class ID>
// attribute classes
DECLARE_PMID(kClassIDSpace, kTextAttrColorBoss, kTextAttrPrefix + 1)
DECLARE_PMID(kClassIDSpace, kTextAttrFontStyleBoss, kTextAttrPrefix + 2)
DECLARE_PMID(kClassIDSpace, kTextAttrPointSizeBoss, kTextAttrPrefix + 3)
DECLARE_PMID(kClassIDSpace, kTextAttrAlignLastBoss_Obsolete, kTextAttrPrefix + 4)
DECLARE_PMID(kClassIDSpace, kTextAttrAlignBodyBoss_Obsolete, kTextAttrPrefix + 5)
DECLARE_PMID(kClassIDSpace, kTextAttrXGlyphScaleBoss, kTextAttrPrefix + 6)
DECLARE_PMID(kClassIDSpace, kTextAttrPairKernMethodBoss, kTextAttrPrefix + 7)
DECLARE_PMID(kClassIDSpace, kTextAttrLigaturesBoss, kTextAttrPrefix + 8)
DECLARE_PMID(kClassIDSpace, kTextAttrPageNumberTypeBoss, kTextAttrPrefix + 9)
DECLARE_PMID(kClassIDSpace, kTextAttrOutlineBoss, kTextAttrPrefix + 10)

DECLARE_PMID(kClassIDSpace, kTextAttrTrackKernBoss, kTextAttrPrefix + 11)
DECLARE_PMID(kClassIDSpace, kTextAttrComposerBoss, kTextAttrPrefix + 12)
DECLARE_PMID(kClassIDSpace, kTextAttrDropCapCharsBoss, kTextAttrPrefix + 13)
DECLARE_PMID(kClassIDSpace, kTextAttrDropCapLinesBoss, kTextAttrPrefix + 14)
DECLARE_PMID(kClassIDSpace, kTextAttrBaselineGridBoss_Obsolete, kTextAttrPrefix + 15		/* converter only */)
DECLARE_PMID(kClassIDSpace, kTextAttrBLShiftBoss, kTextAttrPrefix + 16)
DECLARE_PMID(kClassIDSpace, kTextAttrCapitalModeBoss, kTextAttrPrefix + 17)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeColorBoss, kTextAttrPrefix + 18)
DECLARE_PMID(kClassIDSpace, kTextAttrPairKernBoss, kTextAttrPrefix + 19)
DECLARE_PMID(kClassIDSpace, kTextAttrHyphenLadderBoss, kTextAttrPrefix + 20)

DECLARE_PMID(kClassIDSpace, kTextAttrYGlyphScaleBoss, kTextAttrPrefix + 21)
DECLARE_PMID(kClassIDSpace, kTextAttrIndentBLBoss, kTextAttrPrefix + 22)
DECLARE_PMID(kClassIDSpace, kTextAttrIndentBRBoss, kTextAttrPrefix + 23)
DECLARE_PMID(kClassIDSpace, kTextAttrIndent1LBoss, kTextAttrPrefix + 24)
DECLARE_PMID(kClassIDSpace, kTextAttrEdgeAlignBoss_Obsolete, kTextAttrPrefix + 25		/* deleted ; USED BY CONVERTER */)
DECLARE_PMID(kClassIDSpace, kTextAttrAutoLeadBoss, kTextAttrPrefix + 26)
DECLARE_PMID(kClassIDSpace, kTextAttrLeadBoss, kTextAttrPrefix + 27)
DECLARE_PMID(kClassIDSpace, kTextAttrConversionBoss, kTextAttrPrefix + 28)
DECLARE_PMID(kClassIDSpace, kTextAttrLanguageBoss, kTextAttrPrefix + 29)
DECLARE_PMID(kClassIDSpace, kTextAttrAutoQuadBoss_Obsolete, kTextAttrPrefix + 30)

DECLARE_PMID(kClassIDSpace, kTextAttrHyphenModeBoss, kTextAttrPrefix + 31)
DECLARE_PMID(kClassIDSpace, kTextAttrMinBeforeBoss, kTextAttrPrefix + 32)
DECLARE_PMID(kClassIDSpace, kTextAttrMinAfterBoss, kTextAttrPrefix + 33)
DECLARE_PMID(kClassIDSpace, kTextAttrHyphenCapBoss, kTextAttrPrefix + 34)
DECLARE_PMID(kClassIDSpace, kTextAttrShortestWordBoss, kTextAttrPrefix + 35)
DECLARE_PMID(kClassIDSpace, kTextAttrNoBreakBoss, kTextAttrPrefix + 36)
DECLARE_PMID(kClassIDSpace, kTextAttrHyphenZoneBoss, kTextAttrPrefix + 37)
DECLARE_PMID(kClassIDSpace, kTextAttrSpaceBeforeBoss, kTextAttrPrefix + 38)
DECLARE_PMID(kClassIDSpace, kTextAttrSpaceAfterBoss, kTextAttrPrefix + 39)

DECLARE_PMID(kClassIDSpace, kTextAttrKeyboardShortcutsBoss, kTextAttrPrefix + 40)
DECLARE_PMID(kClassIDSpace, kTextAttrTabsBoss, kTextAttrPrefix + 41)
DECLARE_PMID(kClassIDSpace, kTextAttrUnderlineBoss, kTextAttrPrefix + 42)
DECLARE_PMID(kClassIDSpace, kTextAttrFontUIDBoss, kTextAttrPrefix + 43)
DECLARE_PMID(kClassIDSpace, kTextAttrFigureStyleBoss, kTextAttrPrefix + 44)
DECLARE_PMID(kClassIDSpace, kTextAttrWordspaceDesBoss, kTextAttrPrefix + 45)
DECLARE_PMID(kClassIDSpace, kTextAttrWordspaceMaxBoss, kTextAttrPrefix + 46)
DECLARE_PMID(kClassIDSpace, kTextAttrWordspaceMinBoss, kTextAttrPrefix + 47)
DECLARE_PMID(kClassIDSpace, kTextAttrLetterspaceDesBoss, kTextAttrPrefix + 48)
DECLARE_PMID(kClassIDSpace, kTextAttrLetterspaceMaxBoss, kTextAttrPrefix + 49)

DECLARE_PMID(kClassIDSpace, kTextAttrLetterspaceMinBoss, kTextAttrPrefix + 50)
DECLARE_PMID(kClassIDSpace, kTextAttrGlyphscaleDesBoss, kTextAttrPrefix + 51)
DECLARE_PMID(kClassIDSpace, kTextAttrGlyphscaleMaxBoss, kTextAttrPrefix + 52)
DECLARE_PMID(kClassIDSpace, kTextAttrGlyphscaleMinBoss, kTextAttrPrefix + 53)
DECLARE_PMID(kClassIDSpace, kTextAttrILGShiftBoss, kTextAttrPrefix + 54)
DECLARE_PMID(kClassIDSpace, kTextAttrBreakBeforeBoss, kTextAttrPrefix + 55)
DECLARE_PMID(kClassIDSpace, kTextAttrKeepTogetherBoss, kTextAttrPrefix + 56)
DECLARE_PMID(kClassIDSpace, kTextAttrKeepWithNextBoss, kTextAttrPrefix + 57)
DECLARE_PMID(kClassIDSpace, kTextAttrKeepFirstNLinesBoss, kTextAttrPrefix + 58)
DECLARE_PMID(kClassIDSpace, kTextAttrKeepLastNLinesBoss, kTextAttrPrefix + 59)

DECLARE_PMID(kClassIDSpace, kTextAttrPositionModeBoss, kTextAttrPrefix + 60)
DECLARE_PMID(kClassIDSpace, kTextAttrStrikethruBoss, kTextAttrPrefix + 61)
DECLARE_PMID(kClassIDSpace, kTextAttrCharacterHangBoss, kTextAttrPrefix + 62)
DECLARE_PMID(kClassIDSpace, kTextAttrAlternateCharBoss, kTextAttrPrefix + 63)
DECLARE_PMID(kClassIDSpace, kTextAttrKeepLinesBoss, kTextAttrPrefix + 64)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeTintBoss, kTextAttrPrefix + 65)
DECLARE_PMID(kClassIDSpace, kTextAttrTintBoss, kTextAttrPrefix + 66)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeOverprintBoss, kTextAttrPrefix + 67)
DECLARE_PMID(kClassIDSpace, kTextAttrOverprintBoss, kTextAttrPrefix + 68)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeGradAngleBoss, kTextAttrPrefix + 69)

DECLARE_PMID(kClassIDSpace, kTextAttrGradAngleBoss, kTextAttrPrefix + 70)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeGradLengthBoss, kTextAttrPrefix + 71)
DECLARE_PMID(kClassIDSpace, kTextAttrGradLengthBoss, kTextAttrPrefix + 72)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeGradCenterBoss, kTextAttrPrefix + 73)
DECLARE_PMID(kClassIDSpace, kTextAttrGradCenterBoss, kTextAttrPrefix + 74)
DECLARE_PMID(kClassIDSpace, kTextAttrSkewAngleBoss, kTextAttrPrefix + 75)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAColorBoss, kTextAttrPrefix + 76)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAStrokeBoss, kTextAttrPrefix + 77)
DECLARE_PMID(kClassIDSpace, kTextAttrPRATintBoss, kTextAttrPrefix + 78)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAOffsetBoss, kTextAttrPrefix + 79)

DECLARE_PMID(kClassIDSpace, kTextAttrPRAIndentLBoss, kTextAttrPrefix + 80)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAIndentRBoss, kTextAttrPrefix + 81)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAModeBoss, kTextAttrPrefix + 82)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBColorBoss, kTextAttrPrefix + 83)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBStrokeBoss, kTextAttrPrefix + 84)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBTintBoss, kTextAttrPrefix + 85)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBOffsetBoss, kTextAttrPrefix + 86)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBIndentLBoss, kTextAttrPrefix + 87)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBIndentRBoss, kTextAttrPrefix + 88)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBModeBoss, kTextAttrPrefix + 89)

DECLARE_PMID(kClassIDSpace, kTextAttrPRAOverprintBoss, kTextAttrPrefix + 90)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBOverprintBoss, kTextAttrPrefix + 91)
DECLARE_PMID(kClassIDSpace, kTextAttrPRARuleOnBoss, kTextAttrPrefix + 92)
DECLARE_PMID(kClassIDSpace, kTextAttrPRBRuleOnBoss, kTextAttrPrefix + 93)
DECLARE_PMID(kClassIDSpace, kTextAttrSpecialGlyphBoss, kTextAttrPrefix + 94)
DECLARE_PMID(kClassIDSpace, kTextAttrHiliteAngleBoss, kTextAttrPrefix + 95)
DECLARE_PMID(kClassIDSpace, kTextAttrHiliteLengthBoss, kTextAttrPrefix + 96)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeHiliteAngleBoss, kTextAttrPrefix + 97)
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeHiliteLengthBoss, kTextAttrPrefix + 98)
DECLARE_PMID(kClassIDSpace, kTextAttrForceVerticalGlyphsBoss, kTextAttrPrefix + 99)

DECLARE_PMID(kClassIDSpace, kTextAttrStrikeoutBoss_obsolete, kTextAttrPrefix + 100)	// converter only
DECLARE_PMID(kClassIDSpace, kTextAttrIndentLastRightBoss, kTextAttrPrefix + 101)
DECLARE_PMID(kClassIDSpace, kTextAdornmentUnderlineBoss, kTextAttrPrefix + 102)
DECLARE_PMID(kClassIDSpace, kTextAdornmentStrikethruBoss, kTextAttrPrefix + 103)
DECLARE_PMID(kClassIDSpace, kTextAttrHyphenLastBoss, kTextAttrPrefix + 104)
DECLARE_PMID(kClassIDSpace, kTextAttrMissingImplBoss, kTextAttrPrefix + 105)
DECLARE_PMID(kClassIDSpace, kTextAttrGotoNextXBoss, kTextAttrPrefix + 106)
DECLARE_PMID(kClassIDSpace, kTextAttrAlignSingleBoss, kTextAttrPrefix + 107)
DECLARE_PMID(kClassIDSpace, kTextAttrOTFOrdinalBoss, kTextAttrPrefix + 108)
DECLARE_PMID(kClassIDSpace, kTextAttrOTFFractionBoss, kTextAttrPrefix + 109)

DECLARE_PMID(kClassIDSpace, kTextAttrOTFDiscLigBoss, kTextAttrPrefix + 110)
DECLARE_PMID(kClassIDSpace, kTextAttrOTFTitlingBoss, kTextAttrPrefix + 111)
DECLARE_PMID(kClassIDSpace, kTextAttrSchemaConversionBoss, kTextAttrPrefix + 112)
DECLARE_PMID(kClassIDSpace, kTextAttrPRAStrokeTypeBoss, kTextAttrPrefix + 113 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRBStrokeTypeBoss, kTextAttrPrefix + 114 )
DECLARE_PMID(kClassIDSpace, kTextAttrBalancedLinesBoss, kTextAttrPrefix + 115 )
DECLARE_PMID(kClassIDSpace, kTextAdornmentUnderlineDataBoss, kTextAttrPrefix + 116 )
DECLARE_PMID(kClassIDSpace, kTextAttrRunInStylesBoss, kTextAttrPrefix + 117 )
DECLARE_PMID(kClassIDSpace, kTextAdornmentStrikethruDataBoss, kTextAttrPrefix + 118 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRAGapColorBoss, kTextAttrPrefix + 119 )

DECLARE_PMID(kClassIDSpace, kTextAttrPRAGapTintBoss, kTextAttrPrefix + 120 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRAGapOverprintBoss, kTextAttrPrefix + 121 )
DECLARE_PMID(kClassIDSpace, kTextAttrOTFStylisticAltBoss, kTextAttrPrefix + 122 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRBGapColorBoss, kTextAttrPrefix + 123 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRBGapTintBoss, kTextAttrPrefix + 124 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRBGapOverprintBoss, kTextAttrPrefix + 125 )
DECLARE_PMID(kClassIDSpace, kTextAttrAlignmentBoss, kTextAttrPrefix + 126 )
DECLARE_PMID(kClassIDSpace, kBlackBoxTextAttrBoss, kTextAttrPrefix + 127 )
DECLARE_PMID(kClassIDSpace, kDropCapDetailBoss, kTextAttrPrefix + 128 )
DECLARE_PMID(kClassIDSpace, kOTPositionalFormsBoss, kTextAttrPrefix + 129 )

DECLARE_PMID(kClassIDSpace, kOTMarkPositioningBoss, kTextAttrPrefix + 130 )
DECLARE_PMID(kClassIDSpace, kTextAttrHyphenWeightBoss, kTextAttrPrefix + 131 )
DECLARE_PMID(kClassIDSpace, kOTLocaleFeatureBoss, kTextAttrPrefix + 132 )
DECLARE_PMID(kClassIDSpace, kTextAttrCrossFrameHyphenBoss, kTextAttrPrefix + 133 )
DECLARE_PMID(kClassIDSpace, kTextAttrPRAKeepInFrameBoss, kTextAttrPrefix + 134 )
DECLARE_PMID(kClassIDSpace, kTextAttrIgnoreEdgeAlignBoss, kTextAttrPrefix + 135 )
DECLARE_PMID(kClassIDSpace, kSlashedZeroOTFBoss, kTextAttrPrefix + 136 )
DECLARE_PMID(kClassIDSpace, kStylisticSetsOTFBoss, kTextAttrPrefix + 137 )
DECLARE_PMID(kClassIDSpace, kHistoricalOTFBoss, kTextAttrPrefix + 138 )
//DECLARE_PMID(kClassIDSpace, kTextAttrDropcapStyleBoss, kTextAttrPrefix + 139 )

DECLARE_PMID(kClassIDSpace, kTextAttrOTFContextAltBoss, kTextAttrPrefix + 140 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineColorBoss, kTextAttrPrefix + 141 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineGapColorBoss, kTextAttrPrefix + 142 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineGapOverprintBoss, kTextAttrPrefix + 143 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineGapTintBoss, kTextAttrPrefix + 144 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineOffsetBoss, kTextAttrPrefix + 145 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineOverprintBoss, kTextAttrPrefix + 146 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineTintBoss, kTextAttrPrefix + 147 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineWeightOffsetBoss, kTextAttrPrefix + 148 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharUnderlineTypeBoss, kTextAttrPrefix + 149 )

DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughColorBoss, kTextAttrPrefix + 150 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughGapColorBoss, kTextAttrPrefix + 151 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughGapOverprintBoss, kTextAttrPrefix + 152 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughGapTintBoss, kTextAttrPrefix + 153 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughOffsetBoss, kTextAttrPrefix + 154 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughOverprintBoss, kTextAttrPrefix + 155 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughTintBoss, kTextAttrPrefix + 156 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughTypeBoss, kTextAttrPrefix + 157 )
DECLARE_PMID(kClassIDSpace, kTextAttrCharStrikeThroughWeightOffsetBoss, kTextAttrPrefix + 158 )
//DECLARE_PMID(kClassIDSpace, kFancyNameBoss, kTextAttrPrefix + 159 )

// rmadala: The following attributes are used for find/change panel.
DECLARE_PMID(kClassIDSpace, kObjectFCStoryOptMarginAlignAttrBoss, kTextAttrPrefix + 160 )
DECLARE_PMID(kClassIDSpace, kObjectFCStoryOptAlignAlignSizeAttrBoss, kTextAttrPrefix + 161 )
DECLARE_PMID(kClassIDSpace, kObjectFCStoryFrameGridOnAttrBoss, kTextAttrPrefix + 162 )
DECLARE_PMID(kClassIDSpace, kObjectFCStoryNamedGridAttrBoss, kTextAttrPrefix + 163 )
DECLARE_PMID(kClassIDSpace, kObjectFCStoryDirectionAttrBoss, kTextAttrPrefix + 164 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFNumberOfColumnsAttrBoss, kTextAttrPrefix + 165 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFColumnWidthAttrBoss, kTextAttrPrefix + 166 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFGutterWidthAttrBoss, kTextAttrPrefix + 167 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFUseFixedWidthAttrBoss, kTextAttrPrefix + 168 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFTopInsetAttrBoss, kTextAttrPrefix + 169 )

DECLARE_PMID(kClassIDSpace, kObjectFCTFBottomInsetAttrBoss, kTextAttrPrefix + 170 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFRightInsetAttrBoss, kTextAttrPrefix + 171 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFLeftInsetAttrBoss, kTextAttrPrefix + 172 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFVJAlignmentAttrBoss, kTextAttrPrefix + 173 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFParaSpaceLimitAttrBoss, kTextAttrPrefix + 174 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFIgnoreTextWrapAttrBoss, kTextAttrPrefix + 175 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOFirstBaselineOffsetAttrBoss, kTextAttrPrefix + 176 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOFirstBaselineOffsetMinimumAttrBoss, kTextAttrPrefix + 177 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOUseCustomBaselineGridAttrBoss, kTextAttrPrefix + 178 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOBaselineGridStartAttrBoss, kTextAttrPrefix + 179 )

DECLARE_PMID(kClassIDSpace, kObjectFCTFBOBaselineGridRelativeToAttrBoss, kTextAttrPrefix + 180 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOBaselineGridIncrementEveryAttrBoss, kTextAttrPrefix + 181 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFBOBaselineGridColorAttrBoss, kTextAttrPrefix + 182 )
DECLARE_PMID(kClassIDSpace, kTextAttrMiterLimitBoss, kTextAttrPrefix + 183 )
DECLARE_PMID(kClassIDSpace, kTextAttrStrokeAlignmentBoss, kTextAttrPrefix + 184 )
DECLARE_PMID(kClassIDSpace, kTextAttrOutlineJoinBoss, kTextAttrPrefix + 185 )
DECLARE_PMID(kClassIDSpace, kTextAttrGrepStylesBoss, kTextAttrPrefix + 186 )
DECLARE_PMID(kClassIDSpace, kTextAttrLineStylesBoss, kTextAttrPrefix + 187 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFVJBalanceColumnsAttrBoss, kTextAttrPrefix + 188 )

DECLARE_PMID(kClassIDSpace, kTextAttrSpanColumnTypeBoss, kTextAttrPrefix + 189 )
DECLARE_PMID(kClassIDSpace, kTextAttrSpanColumnCountBoss, kTextAttrPrefix + 190 )
DECLARE_PMID(kClassIDSpace, kTextAttrSplitColumnInsideGutterBoss, kTextAttrPrefix + 191 )
DECLARE_PMID(kClassIDSpace, kTextAttrSplitColumnOutsideGutterBoss, kTextAttrPrefix + 192 )
DECLARE_PMID(kClassIDSpace, kTextAttrKeepWithPrevBoss, kTextAttrPrefix + 193 )
DECLARE_PMID(kClassIDSpace, kObjectFCWritingDirectionAttrBoss, kTextAttrPrefix + 194 )

DECLARE_PMID(kClassIDSpace, kTextAttrSpanColumnMinSpaceBeforeBoss, kTextAttrPrefix + 195 )
DECLARE_PMID(kClassIDSpace, kTextAttrSpanColumnMinSpaceAfterBoss, kTextAttrPrefix + 196 )

DECLARE_PMID(kClassIDSpace, kObjectFCTFUseFlexibleWidthAttrBoss, kTextAttrPrefix + 197 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFMinColumnWidthAttrBoss, kTextAttrPrefix + 198 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFMaxColumnWidthAttrBoss, kTextAttrPrefix + 199 )

// other classes
DECLARE_PMID(kClassIDSpace, kApplyTextAttrToWorkspaceCmdBoss, kTextAttrPrefix + 200)
//gap

DECLARE_PMID(kClassIDSpace, kTextAttrOTFSwashBoss, kTextAttrPrefix + 202)

DECLARE_PMID(kClassIDSpace, kObjectFCTFASDimensionAttrBoss, kTextAttrPrefix + 203 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASRefPointAttrBoss, kTextAttrPrefix + 204 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASHasMinHeightAttrBoss, kTextAttrPrefix + 205 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASMinHeightValueAttrBoss, kTextAttrPrefix + 206 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASHasMinWidthAttrBoss, kTextAttrPrefix + 207 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASMinWidthValueAttrBoss, kTextAttrPrefix + 208 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFASNoLineBreakAttrBoss, kTextAttrPrefix + 209 )

DECLARE_PMID(kClassIDSpace, kTextAttrPBSFillColorBoss, kTextAttrPrefix + 210 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSFillTintBoss, kTextAttrPrefix + 211 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSFillOverprintBoss, kTextAttrPrefix + 212 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSWidthBoss, kTextAttrPrefix + 213 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSFillOnBoss, kTextAttrPrefix + 214 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSClipToFrameBoss, kTextAttrPrefix + 215 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSSuppressPrintingBoss, kTextAttrPrefix + 216 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSOffsetLBoss, kTextAttrPrefix + 217 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSOffsetRBoss, kTextAttrPrefix + 218 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSOffsetTBoss, kTextAttrPrefix + 219 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSOffsetBBoss, kTextAttrPrefix + 220 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSTopOriginBoss, kTextAttrPrefix + 221)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSBottomOriginBoss, kTextAttrPrefix + 222)

DECLARE_PMID(kClassIDSpace, kObjectFCTFFOEnableOverridesAttrBoss, kTextAttrPrefix + 223 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFFOSpanFootnotesAcrossAttrBoss, kTextAttrPrefix + 224 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFFOMinimumSpacingAttrBoss, kTextAttrPrefix + 225 )
DECLARE_PMID(kClassIDSpace, kObjectFCTFFOSpaceBetweenFootnotesAttrBoss, kTextAttrPrefix + 226 )
//DECLARE_PMID(kClassIDSpace, kFancyNameBoss, kTextAttrPrefix + 227 )
//DECLARE_PMID(kClassIDSpace, kFancyNameBoss, kTextAttrPrefix + 228 )
//DECLARE_PMID(kClassIDSpace, kFancyNameBoss, kTextAttrPrefix + 229 )

// bosses for outputting attribute values
DECLARE_PMID(kClassIDSpace, kTextAttrBaseNumberBoss, kTextAttrPrefix + 230)
DECLARE_PMID(kClassIDSpace, kTextAttrXMeasureBoss, kTextAttrPrefix + 231)
DECLARE_PMID(kClassIDSpace, kTextAttrYMeasureBoss, kTextAttrPrefix + 232)
DECLARE_PMID(kClassIDSpace, kTextAttrTextMeasureBoss, kTextAttrPrefix + 233)
DECLARE_PMID(kClassIDSpace, kTextAttrAngleBoss, kTextAttrPrefix + 234)

DECLARE_PMID(kClassIDSpace, kTextAttrPhase2ConversionBoss, kTextAttrPrefix + 235)
DECLARE_PMID(kClassIDSpace, kTextAttrTextSizeMeasureBoss, kTextAttrPrefix + 236)
DECLARE_PMID(kClassIDSpace, kAttrBossReferencingBoss, kTextAttrPrefix + 237)

DECLARE_PMID(kClassIDSpace, kTextAdornmentParaRulesDataBoss, kTextAttrPrefix + 238)
DECLARE_PMID(kClassIDSpace, kTextAdornmentKentenDataBoss, kTextAttrPrefix + 239)
DECLARE_PMID(kClassIDSpace, kTextAdornmentRubyDataBoss, kTextAttrPrefix + 240)

DECLARE_PMID(kClassIDSpace, kTextAttrIteratorRegBoss, kTextAttrPrefix + 241)
//DECLARE_PMID(kClassIDSpace, kApplyToAttrBossListCmdBoss, kTextAttrPrefix + 242)

DECLARE_PMID(kClassIDSpace, kTextTempGSDescBoss, kTextAttrPrefix + 243 )

DECLARE_PMID(kClassIDSpace, kTextAdornmentParaShadeDataBoss, kTextAttrPrefix + 244 )
DECLARE_PMID(kClassIDSpace, kTextAdornmentParaBorderDataBoss, kTextAttrPrefix + 245 )
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeColorBoss, kTextAttrPrefix + 246)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeTintBoss, kTextAttrPrefix + 247)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeOverprintBoss, kTextAttrPrefix + 248)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeOnBoss, kTextAttrPrefix + 249)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeGapColorBoss, kTextAttrPrefix + 250)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeGapTintBoss, kTextAttrPrefix + 251)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeGapOverprintBoss, kTextAttrPrefix + 252)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeTypeBoss, kTextAttrPrefix + 253)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWeightBoss, kTextAttrPrefix + 254)
//DECLARE_PMID(kClassIDSpace, kFancyNameBoss, kTextAttrPrefix + 255 )

DECLARE_PMID(kClassIDSpace, kTextAttrParaBorderOffsetLBoss, kTextAttrPrefix2 + 1)
DECLARE_PMID(kClassIDSpace, kTextAttrParaBorderOffsetRBoss, kTextAttrPrefix2 + 2)
DECLARE_PMID(kClassIDSpace, kTextAttrParaBorderOffsetTBoss, kTextAttrPrefix2 + 3)
DECLARE_PMID(kClassIDSpace, kTextAttrParaBorderOffsetBBoss, kTextAttrPrefix2 + 4)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeJoinTypeBoss, kTextAttrPrefix2 + 5)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerTypeTLAttrBoss, kTextAttrPrefix2 + 6)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerTypeTRAttrBoss, kTextAttrPrefix2 + 7)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerTypeBLAttrBoss, kTextAttrPrefix2 + 8)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerTypeBRAttrBoss, kTextAttrPrefix2 + 9)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerRadiusTLAttrBoss, kTextAttrPrefix2 + 10)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerRadiusTRAttrBoss, kTextAttrPrefix2 + 11)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerRadiusBLAttrBoss, kTextAttrPrefix2 + 12)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSCornerRadiusBRAttrBoss, kTextAttrPrefix2 + 13)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerTypeTLAttrBoss, kTextAttrPrefix2 + 14)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerTypeTRAttrBoss, kTextAttrPrefix2 + 15)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerTypeBLAttrBoss, kTextAttrPrefix2 + 16)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerTypeBRAttrBoss, kTextAttrPrefix2 + 17)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerRadiusTLAttrBoss, kTextAttrPrefix2 + 18)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerRadiusTRAttrBoss, kTextAttrPrefix2 + 19)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerRadiusBLAttrBoss, kTextAttrPrefix2 + 20)
DECLARE_PMID(kClassIDSpace, kTextAttrPSCornerRadiusBRAttrBoss, kTextAttrPrefix2 + 21)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeCapTypeBoss, kTextAttrPrefix2 + 22)

DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWidthBoss, 		kTextAttrPrefix2 + 23)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeTopOriginBoss, 	kTextAttrPrefix2 + 24)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeBottomOriginBoss, kTextAttrPrefix2 + 25)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWeightTBoss,		kTextAttrPrefix2 + 26)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWeightBBoss,		kTextAttrPrefix2 + 27)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWeightLBoss,		kTextAttrPrefix2 + 28)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSStrokeWeightRBoss,		kTextAttrPrefix2 + 29)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSParagraphFlowBoss,		kTextAttrPrefix2 + 30)
DECLARE_PMID(kClassIDSpace, kTextAttrPBSMergeBorderBoss,		kTextAttrPrefix2 + 31)
DECLARE_PMID(kClassIDSpace, kTextAttrProviderHyphStyleBoss,		kTextAttrPrefix2 + 32)
DECLARE_PMID(kClassIDSpace, kTextAttrSameParaSpacingBoss, 		kTextAttrPrefix2 + 33)

// <Interface ID>
// attribute IIDs
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRUID, kTextAttrPrefix + 1)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRBOOLEAN, kTextAttrPrefix + 2)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRCLASSID, kTextAttrPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRINT32, kTextAttrPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRTABS, kTextAttrPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRREALNUMBER, kTextAttrPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRINT16, kTextAttrPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSTRING, kTextAttrPrefix + 8)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRALIGN, kTextAttrPrefix + 9			/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRCHARHANG, kTextAttrPrefix + 10		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRHYPHENMODE, kTextAttrPrefix + 11		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRCAPITALMODE, kTextAttrPrefix + 12		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRFONT, kTextAttrPrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRBREAKBEFOREMODE, kTextAttrPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPOSITIONMODE, kTextAttrPrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRUNDERLINEMODE, kTextAttrPrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRWIDESTRING, kTextAttrPrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPOINT, kTextAttrPrefix + 18)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPARARULEMODE, kTextAttrPrefix + 19		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSPECIALGLYPH, kTextAttrPrefix + 20)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRDATAPOSITION, kTextAttrPrefix + 21		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRFIGURESTYLE, kTextAttrPrefix + 22		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSTYLELIST, kTextAttrPrefix + 23)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRBALANCESTYLE, kTextAttrPrefix + 24)

DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRDROPCAPDETAIL, kTextAttrPrefix + 25)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTROTPOSITIONFORM, kTextAttrPrefix + 26)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRUIDLIST, kTextAttrPrefix + 27)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPARABORDERSHADINGWIDTH, kTextAttrPrefix + 28		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPARABORDERSHADINGTOPORIGIN, kTextAttrPrefix + 29		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPARABORDERSHADINGBOTTOMORIGIN, kTextAttrPrefix + 30		/* enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSTROKEJOINTYPE, kTextAttrPrefix + 31 	/*enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSTROKECAPTYPE, kTextAttrPrefix + 32 	/*enum */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRPROVIDERHYPHSTYLE, kTextAttrPrefix + 33 	/*enum */)

//gap gap


DECLARE_PMID(kInterfaceIDSpace, IID_ISAVEDTEXTATTRIBUTES, kTextAttrPrefix + 100		/* used by kApplyTextAttrToWorkspaceCmdBoss in Undo() */)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRREALFORMATTER, kTextAttrPrefix + 101)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRMISSINGIMPLDATA, kTextAttrPrefix + 102)
#ifdef DEBUG
DECLARE_PMID(kInterfaceIDSpace, IID_IATTRISREFERENCABLE, kTextAttrPrefix + 103)
#endif
DECLARE_PMID(kInterfaceIDSpace, IID_IPARARULESADORNMENTDATA, kTextAttrPrefix + 104)
DECLARE_PMID(kInterfaceIDSpace, IID_IATTRCOMPARE, kTextAttrPrefix + 105)
DECLARE_PMID(kInterfaceIDSpace, IID_IKENTENADORNMENTDATA, kTextAttrPrefix + 106)
DECLARE_PMID(kInterfaceIDSpace, IID_IRUBYADORNMENTDATA, kTextAttrPrefix + 107)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSCALABLEMEASURE, kTextAttrPrefix + 108)

//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 109)

DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRSTROKETYPE, kTextAttrPrefix + 110 )

DECLARE_PMID(kInterfaceIDSpace, IID_ITASTRIKETHRUUNDERLINEDATA, kTextAttrPrefix + 111 )
DECLARE_PMID(kInterfaceIDSpace, IID_IISBLACKBOXATTR, kTextAttrPrefix + 112 )
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRLINESTYLELIST, kTextAttrPrefix + 113 )
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTATTRGREPSTYLELIST, kTextAttrPrefix + 114 )
DECLARE_PMID(kInterfaceIDSpace, IID_IPARASHADEADORNMENTDATA, kTextAttrPrefix + 115 )
DECLARE_PMID(kInterfaceIDSpace, IID_IPARASHADEHIGHBEAMDATA, kTextAttrPrefix + 116)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARABORDERADORNMENTDATA, kTextAttrPrefix + 117 )
DECLARE_PMID(kInterfaceIDSpace, IID_IPARABORDERHIGHBEAMDATA, kTextAttrPrefix + 118 )
DECLARE_PMID(kInterfaceIDSpace, IID_IPARABORDERSHADECOMMONDATA, kTextAttrPrefix + 119)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARABORDERSHADEHIGHBEAMDATA, kTextAttrPrefix + 120 )
DECLARE_PMID(kInterfaceIDSpace, IID_IPARABORDERSHADECORNEROPTIONSDATA, kTextAttrPrefix + 121 )

//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 122 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 123 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 124 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 125 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 126 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 127 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 128 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 129 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 130 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 131 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 132 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 133 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 134 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 135 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 136 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 137 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 138 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 139 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 140 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 141 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 142 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 143 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 144 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 145 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 146 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 147 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 148 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 149 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 150 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 151 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 152 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 153 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 154 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 155 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 156 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 157 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 158 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 159 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 160 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 161 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 162 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 163 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 164 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 165 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 166 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 167 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 168 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 169 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 170 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 171 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 172 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 173 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 174 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 175 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 176 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 177 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 178 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 179 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 180 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 181 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 182 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 183 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 184 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 185 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 186 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 187 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 188 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 189 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 190 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 191 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 192 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 193 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 194 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 195 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 196 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 197 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 198 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 199 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 200 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 201 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 202 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 203 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 204 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 205 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 206 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 207 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 208 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 209 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 210 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 211 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 212 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 213 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 214 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 215 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 216 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 217 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 218 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 219 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 220 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 221 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 222 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 223 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 224 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 225 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 226 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 227 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 228 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 229 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 230 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 231 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 232 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 233 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 234 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 235 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 236 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 237 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 238 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 239 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 240 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 241 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 242 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 243 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 244 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 245 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 246 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 247 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 248 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 249 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 250 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 251 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 252 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 253 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 254 )
//DECLARE_PMID(kInterfaceIDSpace, IID_IFANCYNAME, kTextAttrPrefix + 255 )

// <Implementation ID>
// in TextAttrImplID.h

// <Widget ID>
// widget IDs and other IDs



#endif		// __TextAttrID__


