//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/basiclocalization/BscL10NActionComponent.cpp $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#include "VCPlugInHeaders.h"

// Interface includes:
#include "ISession.h"
#include "IApplication.h"
#include "IDialogMgr.h"
#include "IDialog.h"

// General includes:
#include "CActionComponent.h"
#include "CAlert.h"
#include "CoreResTypes.h"
#include "LocaleSetting.h"
#include "RsrcSpec.h"

// Project includes:
#include "BscL10NID.h"


/** BscL10NActionComponent
	implements the actions that are executed when the plug-in's
	menu items are selected. 
  
	BscL10NActionComponent implements IActionComponent based on
	the partial implementation CActionComponent. 
	@ingroup basiclocalization
	
*/
class BscL10NActionComponent : public CActionComponent
{
	public:
		/**
			Constructor.
			@param boss interface ptr from boss object on which this interface is aggregated.
		*/
		BscL10NActionComponent(IPMUnknown* boss);

		/** 
			Destructor.
		*/
		~BscL10NActionComponent();

		/**
			The action component should do the requested action.
			This is where the menu item's action is taken.
			When a menu item is selected, the Menu Manager determines
			which plug-in is responsible for it, and calls its DoAction
			with the ID for the menu item chosen. 

			@param actionID identifies the menu item that was selected.
			@see CActionComponent::DoAction
			*/
		void DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint = kInvalidMousePoint, IPMUnknown* widget = nil);

	private:
		/** Pops this plug-in's about box. */
		void DoAbout();

		/** Opens this plug-in's dialog. */
		void DoDialog();
};

/* CREATE_PMINTERFACE
 Binds the C++ implementation class onto its 
 ImplementationID making the C++ code callable by the 
 application.
*/
CREATE_PMINTERFACE(BscL10NActionComponent, kBscL10NActionComponentImpl)

/* BscL10NActionComponent Constructor
*/
BscL10NActionComponent::BscL10NActionComponent(IPMUnknown* boss)
: CActionComponent(boss)
{
}

/* BscL10NActionComponent Destructor
*/
BscL10NActionComponent::~BscL10NActionComponent()
{
	// Add code to delete extra private data, if any.
}


/* DoAction
*/
void BscL10NActionComponent::DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint, IPMUnknown* widget)
{
	switch (actionID.Get())
	{
		case kBscL10NAboutActionID:
		{
			this->DoAbout();
			break;
		}	

		case kBscL10NDialogActionID:
		{
			this->DoDialog();
			break;
		}
			
		default:
		{
			break;
		}
	}
}

/* DoAbout
*/
void BscL10NActionComponent::DoAbout()
{
	CAlert::ModalAlert
	(
	   kBscL10NAboutBoxStringKey,						// Alert string
	   kOKString, 							// OK button
	   kNullString, 						// No second button
	   kNullString, 						// No third button
	   1,									// Set OK button to default
	   CAlert::eInformationIcon				// Information icon.
	);
}

/* DoDialog
*/
void BscL10NActionComponent::DoDialog()
{
	do
	{
		// Get the application interface and the DialogMgr.	
		InterfacePtr<IApplication> application(GetExecutionContextSession()->QueryApplication());
		if (application == nil)
		{
			ASSERT_FAIL("BscL10NActionComponent::DoDialog: application invalid"); 
			break;
		}
		InterfacePtr<IDialogMgr> dialogMgr(application, UseDefaultIID());
		if (dialogMgr == nil)
		{ 
			ASSERT_FAIL("BscL10NActionComponent::DoDialog: dialogMgr invalid"); 
			break;
		}

		// Load the plug-in's resource.
		PMLocaleId nLocale = LocaleSetting::GetLocale();
		RsrcSpec dialogSpec
		(
			nLocale,					// Locale index from PMLocaleIDs.h. 
			kBscL10NPluginID,			// Our Plug-in ID from BscL10NID.h. 
			kViewRsrcType,				// This is the kViewRsrcType.
			kSDKDefDialogResourceID,	// Resource ID for our dialog.
			kTrue						// Initially visible.
		);

		// CreateNewDialog takes the dialogSpec created above, and also
		// the type of dialog being created (kMovableModal).
		IDialog* dialog = dialogMgr->CreateNewDialog(dialogSpec, IDialog::kMovableModal);
		if (dialog == nil)
		{ 
			ASSERT_FAIL("BscL10NActionComponent::DoDialog: can't create dialog"); 
			break;
		}

		// Open the dialog.
		dialog->Open(); 
	
	} while (false);			
}

//  Generated by Dolly build 17: template "Dialog".
// End, BscL10NActionComponent.cpp.






