//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/detailcontrollistsize/DCLSizFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(DCLSizActionComponent, kDCLSizActionComponentImpl)
REGISTER_PMINTERFACE(DCLSizListBoxObserver,	kDCLSizListBoxObserverImpl)
REGISTER_PMINTERFACE(DCLSizPalettePanelView, kDCLSizPalettePanelViewImpl)
REGISTER_PMINTERFACE(DCLSizPanelOptions, kDCLSizPanelOptionsImpl)
REGISTER_PMINTERFACE(DCLSizPanelXMLGenerator, kDCLSizPanelXMLGeneratorImpl)
REGISTER_PMINTERFACE(DCLSizPanelSAXHandler, kDCLSizPanelSAXHandlerImpl)
REGISTER_PMINTERFACE(DCLSizTreeViewWidgetMgr, kDCLSizTreeViewWidgetMgrImpl)
REGISTER_PMINTERFACE(DCLSizTreeViewAdapter, kDCLSizTreeViewAdapterImpl)
//  Generated by Dolly build 12: template "IfPanelMenu".
// End, DCLSizFactoryList.h.

