//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/customactionfilter/CstAFltID.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Defines IDs used by the CstAFlt plug-in.
//  
//========================================================================================

#ifndef __CstAFltID_h__
#define __CstAFltID_h__

#include "SDKDef.h"

// Company:
#define kCstAFltCompanyKey	kSDKDefPlugInCompanyKey		// Company name used internally for menu paths and the like. Must be globally unique, only A-Z, 0-9, space and "_".
#define kCstAFltCompanyValue	kSDKDefPlugInCompanyValue	// Company name displayed externally.

// Plug-in:
#define kCstAFltPluginName	"CustomActionFilter"			// Name of this plug-in.
#define kCstAFltPrefixNumber	0x6BB00 		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
#define kCstAFltVersion		kSDKDefPluginVersionString						// Version of this plug-in (for the About Box).
#define kCstAFltAuthor		"Ken Sadahiro"					// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kCstAFltPrefixNumber above to modify the prefix.)
#define kCstAFltPrefix		RezLong(kCstAFltPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kCstAFltStringPrefix	SDK_DEF_STRINGIZE(kCstAFltPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kCstAFltPluginID, kCstAFltPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kCstAFltActionComponentBoss,	kCstAFltPrefix + 0)
DECLARE_PMID(kClassIDSpace, kCstAFltStringRegisterBoss,	kCstAFltPrefix + 1)
DECLARE_PMID(kClassIDSpace, kCstAFltMenuRegisterBoss,	kCstAFltPrefix + 2)
DECLARE_PMID(kClassIDSpace, kCstAFltActionRegisterBoss,	kCstAFltPrefix + 3)
DECLARE_PMID(kClassIDSpace, kCstAFltActionFilterBoss,	kCstAFltPrefix + 4)
DECLARE_PMID(kClassIDSpace, kCstAFltStartupShutdownBoss,	kCstAFltPrefix + 5)

// InterfaceIDs:
// None in this plug-in.

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kCstAFltActionComponentImpl,	kCstAFltPrefix + 0)
DECLARE_PMID(kImplementationIDSpace, kCstAFltActionFilterImpl,	kCstAFltPrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kCstAFltStartupShutdownImpl,	kCstAFltPrefix + 2)

// ActionIDs:
DECLARE_PMID(kActionIDSpace, kCstAFltAboutActionID,			kCstAFltPrefix + 0)

// WidgetIDs:
 
// "About Plug-ins" sub-menu:
#define kCstAFltAboutMenuKey		kCstAFltStringPrefix "kCstAFltAboutMenuKey"
#define kCstAFltAboutMenuPath		kSDKDefStandardAboutMenuPath kCstAFltCompanyKey

// "Plug-ins" sub-menu:
#define kCstAFltPluginsMenuKey 		kCstAFltStringPrefix "kCstAFltPluginsMenuKey"
#define kCstAFltPluginsMenuPath		kSDKDefPlugInsStandardMenuPath kCstAFltCompanyKey kSDKDefDelimitMenuPath kCstAFltPluginsMenuKey

// Menu item keys:
// none in this plugin

// Other StringKeys:
#define kCstAFltAboutBoxStringKey	kCstAFltStringPrefix "kCstAFltAboutBoxStringKey"
#define kCstAFltOnlineSupportNameStringKey		kCstAFltStringPrefix "kCstAFltOnlineSupportNameStringKey"
#define kCstAFltUpdatesNameStringKey		kCstAFltStringPrefix "kCstAFltUpdatesNameStringKey"
#define kCstAFltRegistrationNameStringKey	kCstAFltStringPrefix "kCstAFltRegistrationNameStringKey"
#define kCstAFltInDesignOnlineNameStringKey		kCstAFltStringPrefix "kCstAFltInDesignOnlineNameStringKey" 

#define kCstAFltTargetMenuPath kCstAFltPluginsMenuPath

// Menu item positions:
#define kCstAFltItemOneMenuItemPosition		1.0
#define kCstAFltItemTwoMenuItemPosition		2.0	
#define kCstAFltItemThreeMenuItemPosition	3.0

// Initial data format version numbers
#define kCstAFltFirstMajorFormatNumber  kSDKDef_30_PersistMajorVersionNumber
#define kCstAFltFirstMinorFormatNumber  kSDKDef_30_PersistMinorVersionNumber

// Data format version numbers for the PluginVersion resource
#define kCstAFltCurrentMajorFormatNumber kCstAFltFirstMajorFormatNumber // most recent major format change
#define kCstAFltCurrentMinorFormatNumber kCstAFltFirstMinorFormatNumber // most recent minor format change


#endif // __CstAFltID_h__
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, CstAFltID.h.


