//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/itksamples/consolelogger/ConLgrID.h $
//  
//  Owner: InDesign Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  ADOBE CONFIDENTIAL
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  All information contained herein is, and remains
//  the property of Adobe Systems Incorporated and its suppliers,
//  if any.  The intellectual and technical concepts contained
//  herein are proprietary to Adobe Systems Incorporated and its
//  suppliers and may be covered by U.S. and Foreign Patents,
//  patents in process, and are protected by trade secret or copyright law.
//  Dissemination of this information or reproduction of this material
//  is strictly forbidden unless prior written permission is obtained
//  from Adobe Systems Incorporated.
//  
//========================================================================================

#ifndef __ConLgrID_h__
#define __ConLgrID_h__

#include "SDKDef.h"

// Company:
#define kConLgrCompanyKey	kSDKDefPlugInCompanyKey		// Company name used internally for menu paths and the like. Must be globally unique, only A-Z, 0-9, space and "_".
#define kConLgrCompanyValue	kSDKDefPlugInCompanyValue	// Company name displayed externally.

// Plug-in:
#define kConLgrPluginName	"ConsoleLogger"			// Name of this plug-in.
#define kConLgrPrefixNumber	RezLong(0xAE800) 		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
#define kConLgrVersion		kSDKDefPluginVersionString						// Version of this plug-in (for the About Box).
#define kConLgrAuthor		"InDesign Developer Technologies"					// Author of this plug-in (for the About Box).
#define kConLgrMajorVersionNumber		RezLong(0x1)					// New plug-in
#define kConLgrMinorVersionNumber		RezLong(0x0)					// New plug-in

// Plug-in Prefix: (please change kConLgrPrefixNumber above to modify the prefix.)
#define kConLgrPrefix		RezLong(kConLgrPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kConLgrStringPrefix	SDK_DEF_STRINGIZE(kConLgrPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kConLgrPluginID, kConLgrPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kConLgrActionComponentBoss, kConLgrPrefix + 0)
DECLARE_PMID(kClassIDSpace, kConLgrDiagnosticLoggerBoss, kConLgrPrefix + 1)


// InterfaceIDs:


// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kConLgrActionComponentImpl, kConLgrPrefix + 0 )
DECLARE_PMID(kImplementationIDSpace, kConLgrDiagnosticLoggerImpl, kConLgrPrefix + 1 )

// ActionIDs:
DECLARE_PMID(kActionIDSpace, kConLgrAboutActionID, kConLgrPrefix + 0)


// WidgetIDs:


// "About Plug-ins" sub-menu:
#define kConLgrAboutMenuKey			kConLgrStringPrefix "kConLgrAboutMenuKey"
#define kConLgrAboutMenuPath			kSDKDefStandardAboutMenuPath kConLgrCompanyKey

// "Plug-ins" sub-menu:
#define kConLgrPluginsMenuKey 		kConLgrStringPrefix "kConLgrPluginsMenuKey"
#define kConLgrPluginsMenuPath		kSDKDefPlugInsStandardMenuPath kConLgrCompanyKey kSDKDefDelimitMenuPath kConLgrPluginsMenuKey

// Menu item keys:

// Other StringKeys:
#define kConLgrAboutBoxStringKey				kConLgrStringPrefix "kConLgrAboutBoxStringKey"
#define kConLgrTriggerCmdKey				kConLgrStringPrefix "kConLgrTriggerCmdKey"
#define kConLgrTargetMenuPath kConLgrPluginsMenuPath

// Menu item positions:


#endif // __ConLgrID_h__

//  Code generated by DollyXs code generator
