//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/transparencyeffectui/TranFxUIActionComponent.cpp $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#include "VCPlugInHeaders.h"

// Interface includes:
#include "ISession.h"
#include "IApplication.h"
#include "IDialogMgr.h"
#include "IDialog.h"

// General includes:
#include "CActionComponent.h"
#include "CAlert.h"
#include "CoreResTypes.h"
#include "LocaleSetting.h"
#include "RsrcSpec.h"

// Project includes:
#include "TranFxUIID.h"


/** Implements an action component, IActionComponent, defining the
	actions that are executed when this plug-in's menu items are
	chosen.
 
	
	@ingroup transparencyeffectui
*/
class TranFxUIActionComponent : public CActionComponent
{
	public:
		/**
			Constructor.
			@param boss interface ptr from boss object on which this interface is aggregated.
		*/
		TranFxUIActionComponent(IPMUnknown* boss);

		/** 
			Destructor.
		*/
		~TranFxUIActionComponent();

		/** Called by the framework when the action is to be performed.
			@param ac context in which the action is to be performed.
			@param actionID identifies the action to be performed.
			@param mousePoint ontains the global mouse location at time of event causing action (e.g. context menus), kInvalidMousePoint otherwise.
			@param widget the widget that invoked the action or nil otherwise
		 */
		virtual void	DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint, IPMUnknown* widget);

	private:
		/** Pops this plug-in's about box. */
		void DoAbout();

		/** Opens this plug-in's dialog. */
		void DoDialog();
};

/* Makes the implementation available to the application.
*/
CREATE_PMINTERFACE(TranFxUIActionComponent, kTranFxUIActionComponentImpl)

/* Constructor
*/
TranFxUIActionComponent::TranFxUIActionComponent(IPMUnknown* boss)
: CActionComponent(boss)
{
}

/* Destructor
*/
TranFxUIActionComponent::~TranFxUIActionComponent()
{
	// Add code to delete extra private data, if any.
}


/*
*/
void TranFxUIActionComponent::DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint, IPMUnknown* widget)
{
	switch (actionID.Get())
	{
		case kTranFxUIAboutActionID:
		{
			this->DoAbout();
			break;
		}	

		case kTranFxUIDialogActionID:
		{
			this->DoDialog();
			break;
		}
			
		default:
		{
			break;
		}
	}
}

/*
*/
void TranFxUIActionComponent::DoAbout()
{
	// Bring up the About box.
	CAlert::ModalAlert
	(
		kTranFxUIAboutBoxStringKey,		// Alert string
		kOKString, 						// OK button
		kNullString, 					// No second button
		kNullString, 					// No third button
		1,								// Set OK button to default
		CAlert::eInformationIcon		// Information icon.
	);
}

/*
*/
void TranFxUIActionComponent::DoDialog()
{
	do
	{
		// Get the application interface and the DialogMgr.	
		InterfacePtr<IApplication> application(GetExecutionContextSession()->QueryApplication());
		if (application == nil)
		{
			ASSERT_FAIL("TranFxUIActionComponent::DoAction: application invalid"); 
			break;
		}
		InterfacePtr<IDialogMgr> dialogMgr(application, UseDefaultIID());
		if (dialogMgr == nil)
		{ 
			ASSERT_FAIL("TranFxUIActionComponent::DoAction: dialogMgr invalid"); 
			break;
		}

		// Load the plug-in's resource.
		PMLocaleId nLocale = LocaleSetting::GetLocale();
		RsrcSpec dialogSpec
		(
			nLocale,					// Locale index from PMLocaleIDs.h. 
			kTranFxUIPluginID,			// Our Plug-in ID from TranFxUIID.h. 
			kViewRsrcType,				// This is the kViewRsrcType.
			kSDKDefDialogResourceID,	// Resource ID for our dialog.
			kTrue						// Initially visible.
		);

		// CreateNewDialog takes the dialogSpec created above, and also
		// the type of dialog being created (kMovableModal).
		IDialog* dialog = dialogMgr->CreateNewDialog(dialogSpec, IDialog::kMovableModal);
		if (dialog == nil)
		{ 
			ASSERT_FAIL("TranFxUIActionComponent::DoAction: can't create dialog"); 
			break;
		}

		// Open the dialog.
		dialog->Open(); 
	
	} while (false);			
}

//  Generated by Dolly build 17: template "Dialog".
// End, TranFxUIActionComponent.cpp.




