//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/xdocbookworkflow/XDocBkXPostImpXMLImportPrefs.cpp $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#include "VCPlugInHeaders.h"

// Interface includes
#include "IXMLImportOptionsPool.h"

// General includes
#include "CXMLImportPreferences.h"
// Project includes
#include "XDocBkID.h"

/** Implementation of IXMLImportPreferences,
	stores preferences relating to our post-import iterator (IXMLPostImportIteration)

	@ingroup xdocbookworkflow

*/
class XDocBkXPostImpXMLImportPrefs : public CXMLImportPreferences
{
public:	
	XDocBkXPostImpXMLImportPrefs(IPMUnknown *boss);
	
	// Use this to set each piece of data listed below
	virtual void Initialize(IXMLImportOptionsPool *pool);
};

CREATE_PMINTERFACE(XDocBkXPostImpXMLImportPrefs, kXDocBkXPostImpXMLImportPrefsImpl)


XDocBkXPostImpXMLImportPrefs::XDocBkXPostImpXMLImportPrefs(IPMUnknown *boss) :
CXMLImportPreferences(boss)
{}

void XDocBkXPostImpXMLImportPrefs::Initialize(IXMLImportOptionsPool *pool)
{
	if (fPool != pool)
	{
		// fPool is nil first time in, that's OK
		// First initialize the fPool member for later access.
		fPool.reset(pool);
		ASSERT(fPool);
		if(fPool != nil) {
			fPool->AddRef();
		}
		CXMLImportPreferences::AddPreference(WideString(kXDocBkXPostImpXMLImportPrefsKey), IXMLImportPreferences::kBool16, -1, kTrue);		
		CXMLImportPreferences::AddPreference(WideString(kXDocBkStrucTableIterXMLImportPrefsKey), IXMLImportPreferences::kBool16, -1, kTrue);		
		CXMLImportPreferences::AddPreference(WideString(kXDocBkTaggingTableIterXMLImportPrefsKey), IXMLImportPreferences::kBool16, -1, kFalse);			
	}
}

//  Code generated by DollyXS code generator
