//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/preflightrule/PreflightRuleID.h $
//  
//  Owner: InDesign Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __PreflightID_h__
#define __PreflightID_h__

#include "SDKDef.h"
// Company:
#define kPreflightCompanyKey	kSDKDefPlugInCompanyKey		// Company name used internally for menu paths and the like. Must be globally unique, only A-Z, 0-9, space and "_".
#define kPreflightCompanyValue	kSDKDefPlugInCompanyValue	// Company name displayed externally.

// Plug-in:
#define kPreflightPluginName	"PreflightRule"			// Name of this plug-in.
#define kPreflightPrefixNumber	0x12ac00 		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
#define kPreflightVersion		kSDKDefPluginVersionString						// Version of this plug-in (for the About Box).
#define kPreflightAuthor		"InDesign Developer Technologies"					// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kPreflightPrefixNumber above to modify the prefix.)
#define kPreflightPrefix		RezLong(kPreflightPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kPreflightStringPrefix	SDK_DEF_STRINGIZE(kPreflightPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// Missing plug-in: (see ExtraPluginInfo resource)
#define kPreflightMissingPluginURLValue		kSDKDefPartnersStandardValue_enUS // URL displayed in Missing Plug-in dialog
#define kPreflightMissingPluginAlertValue	kSDKDefMissingPluginAlertValue // Message displayed in Missing Plug-in dialog - provide a string that instructs user how to solve their missing plug-in problem

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kPreflightPluginID, kPreflightPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kPreflightRuleBoss, kPreflightPrefix + 1)
DECLARE_PMID(kClassIDSpace, kPreflightDisallowFontRuleBoss, kPreflightPrefix + 2)
DECLARE_PMID(kClassIDSpace, kPreflightBlackOverprintRuleBoss, kPreflightPrefix + 3)
DECLARE_PMID(kClassIDSpace, kPreflightRuleSPBoss, kPreflightPrefix + 4)


// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kPreflightRuleServiceImpl, kPreflightPrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kPreflightFontVisitorImpl, kPreflightPrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kPreflightBlackOverprintVisitorImpl, kPreflightPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kPreflightSDKRuleUtilitiesImpl, kPreflightPrefix + 4)


// Other StringKeys:
#define kPreflightAboutBoxStringKey			kPreflightStringPrefix	"kPreflightAboutBoxStringKey"
#define kPreflightNotUsedColorSpaceStringKey	kPreflightStringPrefix	"kPreflightNotUsedColorSpaceStringKey"


#define kProblemMessageKey				kPreflightStringPrefix	"kProblemMessageKey"
#define kFixMessageKey					kPreflightStringPrefix	"kFixMessageKey"

// Rule description key
#define kCategorySDKKey					kPreflightStringPrefix	"kCategorySDKKey"

#define kSDKFontRuleDescriptionKey		kPreflightStringPrefix	"kSDKFontRuleDescriptionKey"

#define kSDKBlackOverprintRuleDescKey	kPreflightStringPrefix	"kSDKBlackOverprintRuleDescKey"


#define kSDKBlackOverprintCategoryKey	kPreflightStringPrefix	"kSDKBlackOverprintCategoryKey"

#define kSDKBlackOverprintRuleProblem	kPreflightStringPrefix	"kSDKBlackOverprintRuleProblem ^1"
#define kSDKBlackOverprintRuleFix		kPreflightStringPrefix	"kSDKBlackOverprintRuleFix"


// Initial data format version numbers
#define kPreflightFirstMajorFormatNumber  RezLong(1)
#define kPreflightFirstMinorFormatNumber  RezLong(0)

// Data format version numbers for the PluginVersion resource 
#define kPreflightCurrentMajorFormatNumber kPreflightFirstMajorFormatNumber
#define kPreflightCurrentMinorFormatNumber kPreflightFirstMinorFormatNumber
#endif // __PreflightID_h__

//  Code generated by DollyXs code generator
