//========================================================================================
//  Owner: Adobe Systems Inc.
//  
//  Copyright 1997-2012 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __DigitalPublishingID_h__
#define __DigitalPublishingID_h__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

// Plug-in:
#define kDigitalPublishingPluginName		"DigitalPublishing"
#define kDigitalPublishingPrefixNumber		0x21900
#define kDigitalPublishingPrefix			RezLong(kDigitalPublishingPrefixNumber)

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kDigitalPublishingPluginID, kDigitalPublishingPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kDigitalPublishingScriptProviderBoss, kDigitalPublishingPrefix + 1)
DECLARE_PMID(kClassIDSpace, kDigPubRasterizerViewPortBoss, kDigitalPublishingPrefix + 2)
DECLARE_PMID(kClassIDSpace, kDigPubFPOSuppressorDEHBoss, kDigitalPublishingPrefix + 3)
DECLARE_PMID(kClassIDSpace,	kDigitalPublishingDEHBoss, kDigitalPublishingPrefix + 4)
DECLARE_PMID(kClassIDSpace, kDigPubNativeOverlaySetupProviderBoss, kDigitalPublishingPrefix + 5)
DECLARE_PMID(kClassIDSpace, kDigPubFPOOverlaySetupProviderBoss, kDigitalPublishingPrefix + 6)
DECLARE_PMID(kClassIDSpace, kDigitalPublishingErrorStringServiceBoss, kDigitalPublishingPrefix + 7)
DECLARE_PMID(kClassIDSpace, kDigPubOverlayScriptProviderBoss, kDigitalPublishingPrefix + 8)
DECLARE_PMID(kClassIDSpace, kDigPubDataImageStreamBoss, kDigitalPublishingPrefix + 9)
DECLARE_PMID(kClassIDSpace, kDigPubPageItemSuppressorDEHBoss, kDigitalPublishingPrefix + 10)
DECLARE_PMID(kClassIDSpace, kDigitalPublishingStartupShutdownBoss, kDigitalPublishingPrefix + 11)
DECLARE_PMID(kClassIDSpace, kDigPubPGTMediaExportHandlerBoss, kDigitalPublishingPrefix + 12)
DECLARE_PMID(kClassIDSpace, kDPSHTMLPGTExportBoss, kDigitalPublishingPrefix + 13)
DECLARE_PMID(kClassIDSpace, kDigPubBeforePackageDocResponderBoss, kDigitalPublishingPrefix + 14)
DECLARE_PMID(kClassIDSpace, kDigPubAfterPackageDocResponderBoss, kDigitalPublishingPrefix + 15)
DECLARE_PMID(kClassIDSpace, kDigPubBeforePackageBookDocResponderBoss, kDigitalPublishingPrefix + 16)
DECLARE_PMID(kClassIDSpace, kDigPubAfterPackageBookDocResponderBoss, kDigitalPublishingPrefix + 17)
DECLARE_PMID(kClassIDSpace, kDigPubBeforePackageBookResponderBoss, kDigitalPublishingPrefix + 18)
DECLARE_PMID(kClassIDSpace, kDigPubAfterPackageBookResponderBoss, kDigitalPublishingPrefix + 19)
DECLARE_PMID(kClassIDSpace, kDigPubAfterOpenDocResponderBoss, kDigitalPublishingPrefix + 20)
DECLARE_PMID(kClassIDSpace, kDigPubAfterNewDocResponderBoss, kDigitalPublishingPrefix + 21)
DECLARE_PMID(kClassIDSpace, kDigPubPGTImageSequenceExportHandlerBoss, kDigitalPublishingPrefix + 22)
DECLARE_PMID(kClassIDSpace, kDigPubPGTSlideshowExportHandlerBoss, kDigitalPublishingPrefix + 23)
DECLARE_PMID(kClassIDSpace, kDigPubPGTEffectInitializeHandlerBoss, kDigitalPublishingPrefix + 24)
DECLARE_PMID(kClassIDSpace, kDPS_PDFExportItemsCmdBoss, kDigitalPublishingPrefix + 25)
DECLARE_PMID(kClassIDSpace, kDPS_PDFExportCommandBoss, kDigitalPublishingPrefix + 26)
DECLARE_PMID(kClassIDSpace, kDigPubPGTUnsupportedOverlayHandlerBoss, kDigitalPublishingPrefix + 27)
DECLARE_PMID(kClassIDSpace, kDPSArticleExportProviderBoss,	kDigitalPublishingPrefix + 28)
DECLARE_PMID(kClassIDSpace,	kSetDPSArticleExportPrefsCommandBoss, kDigitalPublishingPrefix + 29)
DECLARE_PMID(kClassIDSpace, kDigitalPublishingSchemaConversionBoss, kDigitalPublishingPrefix + 30)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGFACADE, kDigitalPublishingPrefix + 0)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGPUBFPOSUPPRESSORDATA, kDigitalPublishingPrefix + 1)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGSETUPPROVIDER, kDigitalPublishingPrefix + 2)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGDEHDATA, kDigitalPublishingPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGPUBDATAIMAGESTREAMDATA, kDigitalPublishingPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGPUBEXPORTFOLIOWARNINGDATA, kDigitalPublishingPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGPUBPGTEXPORTDATA, kDigitalPublishingPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGFACADE2, kDigitalPublishingPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGSETUPPROVIDER2, kDigitalPublishingPrefix + 8)
DECLARE_PMID(kInterfaceIDSpace, IID_IDPS_PDFEXPORTDATA, kDigitalPublishingPrefix + 9)
DECLARE_PMID(kInterfaceIDSpace, IID_IDPS_PDFEXPORTCONTROLLER, kDigitalPublishingPrefix + 10)
DECLARE_PMID(kInterfaceIDSpace, IID_IDPS_INTERNALSETUPPROVIDERDATA, kDigitalPublishingPrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGRASTERIZERFACADE, kDigitalPublishingPrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGVECTOREXPORTFACADE, kDigitalPublishingPrefix + 13)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGSIDELOADINGFACADE, kDigitalPublishingPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGFACADE3, kDigitalPublishingPrefix + 15)
// gap
DECLARE_PMID(kInterfaceIDSpace, IID_IDPSARTICLEEXPORTPREFS, kDigitalPublishingPrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_ISETDPSARTICLEEXPORTPREFSCMDDATA,	kDigitalPublishingPrefix + 18)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 19)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 20)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 21)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 22)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 23)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 24)
//DECLARE_PMID(kInterfaceIDSpace, IID_IDIGITALPUBLISHINGINTERFACE, kDigitalPublishingPrefix + 25)


// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingScriptProviderImpl, kDigitalPublishingPrefix + 0 )
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingFacadeImpl, kDigitalPublishingPrefix + 1 )
DECLARE_PMID(kImplementationIDSpace, kDigPubRasterizerViewPortAttrImpl, kDigitalPublishingPrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kDigPubFPOSuppressorDEHImpl, kDigitalPublishingPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kDigPubFPOSuppressorDataImpl, kDigitalPublishingPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingSetupProviderImpl, kDigitalPublishingPrefix + 5)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingDEHImpl, kDigitalPublishingPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingDEHDataImpl, kDigitalPublishingPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kDigPubNativeOverlaySetupProviderImpl, kDigitalPublishingPrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kDigPubFPOOverlaySetupProviderImpl, kDigitalPublishingPrefix + 9)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingErrorStringServiceImpl, kDigitalPublishingPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kDigPubOverlayScriptProviderImpl, kDigitalPublishingPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kDigPubDataImageStreamImpl, kDigitalPublishingPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kDigPubDataImageStreamDataImpl, kDigitalPublishingPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kDigPubIntListDataImpl, kDigitalPublishingPrefix + 14)
DECLARE_PMID(kImplementationIDSpace, kDigPubPageItemSuppressorDEHImpl, kDigitalPublishingPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingStartupShutdownImpl, kDigitalPublishingPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTMediaExportHandlerImpl, kDigitalPublishingPrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTExportDataImpl, kDigitalPublishingPrefix + 18)
DECLARE_PMID(kImplementationIDSpace, kDPSPGTExtensionsImpl, kDigitalPublishingPrefix + 19)
DECLARE_PMID(kImplementationIDSpace, kDigPubIDPackageResponderImpl, kDigitalPublishingPrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kDigPubIDDocResponderImpl, kDigitalPublishingPrefix + 21)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTImageSequenceExportHandlerImpl, kDigitalPublishingPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTSlideshowExportHandlerImpl, kDigitalPublishingPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTEffectInitializeHandlerImpl, kDigitalPublishingPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kDPS_PDFExportItemsCmdImpl, kDigitalPublishingPrefix + 25)
DECLARE_PMID(kImplementationIDSpace, kDPS_PDFExportDataImpl, kDigitalPublishingPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kDPS_PDFExportCommandImpl, kDigitalPublishingPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kDPS_PDFExportControllerImpl, kDigitalPublishingPrefix + 28)
DECLARE_PMID(kImplementationIDSpace, kDPS_InternalSetupProviderDataImpl, kDigitalPublishingPrefix + 29)
DECLARE_PMID(kImplementationIDSpace, kDigPubPGTUnsupportedOverlayHandlerImpl, kDigitalPublishingPrefix + 30)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingRasterizerFacadeImpl, kDigitalPublishingPrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingVectorExportFacadeImpl, kDigitalPublishingPrefix + 32)
//DECLARE_PMID(kImplementationIDSpace, kDigitalPublishingSideloadingFacadeImpl, kDigitalPublishingPrefix + 33)
// gap
// gap
DECLARE_PMID(kImplementationIDSpace, kDPSArticleExportPrefsImpl, kDigitalPublishingPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kDPSArticleExportProviderImpl,	kDigitalPublishingPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kSetDPSArticleExportPrefsCommandImpl, kDigitalPublishingPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kSetDPSArticleExportPrefsCmdDataImpl, kDigitalPublishingPrefix + 39)

// ActionIDs:
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingAboutActionID, kDigitalPublishingPrefix + 0)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 5)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 6)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 7)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 8)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 9)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 10)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 11)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 12)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 13)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 14)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 15)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 16)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 17)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 18)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 19)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 20)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 21)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 22)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 23)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 24)
//DECLARE_PMID(kActionIDSpace, kDigitalPublishingActionID, kDigitalPublishingPrefix + 25)


// WidgetIDs:
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 2)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 3)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 4)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 5)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 6)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 7)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 8)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 9)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 10)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 11)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 12)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 13)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 14)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 15)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 16)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 17)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 18)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 19)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 20)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 21)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 22)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 23)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 24)
//DECLARE_PMID(kWidgetIDSpace, kDigitalPublishingWidgetID, kDigitalPublishingPrefix + 25)

//Error code
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidHeightDimension, kDigitalPublishingPrefix + 1)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidWidthDimension, kDigitalPublishingPrefix + 2)
DECLARE_PMID(kErrorIDSpace, kMiniExport_InvalidJPEGQuality, kDigitalPublishingPrefix + 3)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidParameter, kDigitalPublishingPrefix + 4)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidOperation, kDigitalPublishingPrefix + 5)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAsset, kDigitalPublishingPrefix + 6)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAssetLocation, kDigitalPublishingPrefix + 7)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidOverlayProxyInfo, kDigitalPublishingPrefix + 8)
DECLARE_PMID(kErrorIDSpace, kDigPub_DuplicateOverlayIDs, kDigitalPublishingPrefix + 9)
DECLARE_PMID(kErrorIDSpace, kDigPub_OperationCanceled, kDigitalPublishingPrefix + 10)
DECLARE_PMID(kErrorIDSpace, kDigPub_IOError, kDigitalPublishingPrefix + 11)
DECLARE_PMID(kErrorIDSpace, kMiniExport_InvalidSmoothScrolling, kDigitalPublishingPrefix + 12)
DECLARE_PMID(kErrorIDSpace, kMiniExport_InvalidNavtoURL, kDigitalPublishingPrefix + 13)
DECLARE_PMID(kErrorIDSpace, kMiniExport_InvalidSpreadRange, kDigitalPublishingPrefix + 14)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidHyperlinkParameters, kDigitalPublishingPrefix + 15)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidMSOSlideshowParameters, kDigitalPublishingPrefix + 16)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidStackID, kDigitalPublishingPrefix + 17)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidTOCFile, kDigitalPublishingPrefix + 18)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAssetDependency, kDigitalPublishingPrefix + 19)
DECLARE_PMID(kErrorIDSpace, kDigPub_MultiplePageSizesNotSupported, kDigitalPublishingPrefix + 20)
DECLARE_PMID(kErrorIDSpace, kDigPub_ConflictingStackAssets, kDigitalPublishingPrefix + 21)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorCreatingFolioErr, kDigitalPublishingPrefix + 22)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorOpeningFolioErr, kDigitalPublishingPrefix + 23)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorAddingToFolioErr, kDigitalPublishingPrefix + 24)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorParsingFolioErr, kDigitalPublishingPrefix + 25)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorClosingFolioErr, kDigitalPublishingPrefix + 26)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToGetImageAssetPathsErr, kDigitalPublishingPrefix + 27)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToExtractCoverImageErr, kDigitalPublishingPrefix + 28)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToGetCSIDErr, kDigitalPublishingPrefix + 29)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorCreatingManifestErr, kDigitalPublishingPrefix + 30)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorAccessingManifestErr, kDigitalPublishingPrefix + 31)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorCreatingPListErr, kDigitalPublishingPrefix + 32)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorAccessingArticleDirErr, kDigitalPublishingPrefix + 33)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorCopyingArticleFileErr, kDigitalPublishingPrefix + 34)
DECLARE_PMID(kErrorIDSpace, kDigPub_MetadataDoesNotExistErr, kDigitalPublishingPrefix + 35)
DECLARE_PMID(kErrorIDSpace, kDigPub_FolioDoesNotExistErr, kDigitalPublishingPrefix + 36)
DECLARE_PMID(kErrorIDSpace, kDigPub_MiniFolioDoesNotExistErr, kDigitalPublishingPrefix + 37)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToCreateTempFileErr, kDigitalPublishingPrefix + 38)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToCreateTempDirErr, kDigitalPublishingPrefix + 39)
DECLARE_PMID(kErrorIDSpace, kDigPub_ContentStackIDEmptyErr, kDigitalPublishingPrefix + 40)
DECLARE_PMID(kErrorIDSpace, kDigPub_MagazineTitleMissingErr, kDigitalPublishingPrefix + 41)
DECLARE_PMID(kErrorIDSpace, kDigPub_FolioNumberMissingErr, kDigitalPublishingPrefix + 42)
DECLARE_PMID(kErrorIDSpace, kDigPub_DirectoryDoesNotExistErr, kDigitalPublishingPrefix + 43)
DECLARE_PMID(kErrorIDSpace, kDigPub_DirectoryNotDirectoryErr, kDigitalPublishingPrefix + 44)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToCreateDirErr, kDigitalPublishingPrefix + 45)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToCopyFileErr, kDigitalPublishingPrefix + 46)
DECLARE_PMID(kErrorIDSpace, kDigPub_SmoothScrollMultiPage, kDigitalPublishingPrefix + 47)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidScrubberThumbnailErr, kDigitalPublishingPrefix + 48)
DECLARE_PMID(kErrorIDSpace, kDigPub_CustomFolioDescriptorEmptyErr, kDigitalPublishingPrefix + 49)
DECLARE_PMID(kErrorIDSpace, kDigPub_MultiplePagesPerSpreadNotSupported, kDigitalPublishingPrefix + 50)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnableToCreateTOC, kDigitalPublishingPrefix + 51)
DECLARE_PMID(kErrorIDSpace, kDigPub_ImagePanBoundsErr, kDigitalPublishingPrefix + 52)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnsupportedAssetTypeError, kDigitalPublishingPrefix + 53)
DECLARE_PMID(kErrorIDSpace, kDigPub_AssetExportFailureError, kDigitalPublishingPrefix + 54)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidNavtoLinkError, kDigitalPublishingPrefix + 55)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAspectRatioError, kDigitalPublishingPrefix + 56)
DECLARE_PMID(kErrorIDSpace, kDigPub_FolioOrientationMismatchErr, kDigitalPublishingPrefix + 57)
DECLARE_PMID(kErrorIDSpace, kDigPub_StackOrientationMismatchErr, kDigitalPublishingPrefix + 58)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidURLForStreamingMedia, kDigitalPublishingPrefix + 59)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidURLForWebView, kDigitalPublishingPrefix + 60)
DECLARE_PMID(kErrorIDSpace, kDigPub_DuplicateContentStackIDs, kDigitalPublishingPrefix + 61)
DECLARE_PMID(kErrorIDSpace, kDigPub_IllegalCharsInContentStackID, kDigitalPublishingPrefix + 62)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidScrollContentImagePosition, kDigitalPublishingPrefix + 63)
DECLARE_PMID(kErrorIDSpace, kDigPub_FolioTargetDimMismatchErr, kDigitalPublishingPrefix + 64)
DECLARE_PMID(kErrorIDSpace, kDigPub_StackTargetDimMismatchErr, kDigitalPublishingPrefix + 65)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidNarrowDimension, kDigitalPublishingPrefix + 66)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidWideDimension, kDigitalPublishingPrefix + 67)
DECLARE_PMID(kErrorIDSpace, kDigPub_ErrorFailedToDetermineFolioSize, kDigitalPublishingPrefix + 68)
DECLARE_PMID(kErrorIDSpace, kDigPub_HyperlinkDestinationPageMissingErr, kDigitalPublishingPrefix + 69)
DECLARE_PMID(kErrorIDSpace, kDigPub_OutputDirectoryAccessErr, kDigitalPublishingPrefix + 70)
DECLARE_PMID(kErrorIDSpace, kDigPub_MatchingOverlaysIDWithDifferentDefinitionErr, kDigitalPublishingPrefix + 71)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingGenericErr, kDigitalPublishingPrefix + 72)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingDeviceNotFoundErr, kDigitalPublishingPrefix + 73)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingInvalidNameErr, kDigitalPublishingPrefix + 74)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingNoDirErr, kDigitalPublishingPrefix + 75)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingNoCopyErr, kDigitalPublishingPrefix + 76)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingNoProxyErr, kDigitalPublishingPrefix + 77)
DECLARE_PMID(kErrorIDSpace, kDigPub_SideloadingNoAppErr, kDigitalPublishingPrefix + 78)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidPortraitLayoutNameErr, kDigitalPublishingPrefix + 79)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidLandscapeLayoutNameErr, kDigitalPublishingPrefix + 80)
DECLARE_PMID(kErrorIDSpace, kDigPub_MultiplePageSizesNotSupportedInLayout, kDigitalPublishingPrefix + 81)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidButtonParameters, kDigitalPublishingPrefix + 82)
DECLARE_PMID(kErrorIDSpace, kDigPub_ContainerContentRasterHasNoMarksWarning, kDigitalPublishingPrefix + 83)
DECLARE_PMID(kErrorIDSpace, kDigPub_SmoothScrollingWithPGTErr, kDigitalPublishingPrefix + 84)
DECLARE_PMID(kErrorIDSpace, kDigPub_FlattenedStackWithPGTErr, kDigitalPublishingPrefix + 85)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidLayoutNameErr, kDigitalPublishingPrefix + 86)
DECLARE_PMID(kErrorIDSpace, kDigPub_FontSubsettingErr, kDigitalPublishingPrefix + 87)
DECLARE_PMID(kErrorIDSpace, kDigPub_FontEmbeddingErr, kDigitalPublishingPrefix + 88)
DECLARE_PMID(kErrorIDSpace, kDigPub_MissingFontErr, kDigitalPublishingPrefix + 89)
DECLARE_PMID(kErrorIDSpace, kDigPubIDPackageMissingAssetsDontShowAgainID, kDigitalPublishingPrefix + 90)
DECLARE_PMID(kErrorIDSpace, kDigPubIDPackageBookMissingAssetsDontShowAgainID, kDigitalPublishingPrefix + 91)
// Note: This is returned if the content format requested cannot be produced with the given scripting API
// E.g., PGT export is unsupported using the older, deprecated exportMiniFolio API.
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidFormatForAPIErr, kDigitalPublishingPrefix + 92)
DECLARE_PMID(kErrorIDSpace, kDigPub_MissingLiquidLayoutPolicy, kDigitalPublishingPrefix + 93)
DECLARE_PMID(kErrorIDSpace, kDigPub_VersionStringInvalid, kDigitalPublishingPrefix + 94)
DECLARE_PMID(kErrorIDSpace, kDigPub_TargetViewerVersionUnsupported, kDigitalPublishingPrefix + 95)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAlternateResolutionAssetsErr, kDigitalPublishingPrefix + 96)
DECLARE_PMID(kErrorIDSpace, kDigPub_InvalidAlternateResolutionAssetSizeErr, kDigitalPublishingPrefix + 97)
DECLARE_PMID(kErrorIDSpace, kDigPub_UnsupportedOverlayTypeError, kDigitalPublishingPrefix + 98)
DECLARE_PMID(kErrorIDSpace, kDigPub_PageClickEventNotSupportedError, kDigitalPublishingPrefix + 99)
DECLARE_PMID(kErrorIDSpace, kDigPub_MetadataKeyNotSupportedForThisStackTypeError, kDigitalPublishingPrefix + 100)

// article builder errors (+20 gap)
DECLARE_PMID(kErrorIDSpace, kArticleBuilderUI_Export_FileDataError, kDigitalPublishingPrefix + 120)
DECLARE_PMID(kErrorIDSpace, kArticleBuilderUI_Export_DocumentNotDefined, kDigitalPublishingPrefix + 121)
DECLARE_PMID(kErrorIDSpace, kArticleBuilderUI_Export_CreateDialogError, kDigitalPublishingPrefix + 122)

//Script Element IDs

DECLARE_PMID(kScriptInfoIDSpace, kDigPubCheckForFPOMethodScriptElement, kDigitalPublishingPrefix + 1)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportMiniFolioMethodScriptElement, kDigitalPublishingPrefix + 2)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubRasterizeDocumentPageElement, kDigitalPublishingPrefix + 3)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubRasterizePageParamTypeDefScriptElement, kDigitalPublishingPrefix + 4)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportMiniFolioParamTypeDefScriptElement, kDigitalPublishingPrefix + 5)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportMiniFolioSmoothScrollEnumScriptElement, kDigitalPublishingPrefix + 6)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioOrientationEnumScriptElement, kDigitalPublishingPrefix + 7)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioToPackageMethodScriptElement, kDigitalPublishingPrefix + 8)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioToDirectoryMethodScriptElement, kDigitalPublishingPrefix + 9)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioMetaDataTypeDefScriptElement, kDigitalPublishingPrefix + 10)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetAllOverlaysPropertyScriptElement, kDigitalPublishingPrefix + 11)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioToDirectoryPackageMethodScriptElement, kDigitalPublishingPrefix + 12)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioCSIDMapTypeDefScriptElement, kDigitalPublishingPrefix + 13)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubCreateCustomMiniFolioMethodScriptElement, kDigitalPublishingPrefix + 14)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubDictionaryTypeDefScriptElement, kDigitalPublishingPrefix + 15)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubDictionaryValueTypeDefScriptElement, kDigitalPublishingPrefix + 16)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubArrayOfDictionaryTypeDefScriptElement, kDigitalPublishingPrefix + 17)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubDictionaryEntryTypeDefScriptElement, kDigitalPublishingPrefix + 18)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubTileImageMethodScriptElement, kDigitalPublishingPrefix + 19)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubTileDataScriptElement, kDigitalPublishingPrefix + 20)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExtractLabelsMethodScriptElement, kDigitalPublishingPrefix + 21)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioBindingDirectionEnumScriptElement, kDigitalPublishingPrefix + 22) // Right Edge Binding
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportFolioParamTypeDefScriptElement, kDigitalPublishingPrefix + 23)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubArePathsEquivalentMethodScriptElement, kDigitalPublishingPrefix + 24)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubResetOverlayDefaultsMethodScriptElement, kDigitalPublishingPrefix + 25) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubVersionEnumScriptElement, kDigitalPublishingPrefix + 26) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetVersionMethodScriptElement, kDigitalPublishingPrefix + 27) 
DECLARE_PMID(kScriptInfoIDSpace, kAllowDigPubMethodsWithModalDialogMetadataScriptElement, kDigitalPublishingPrefix + 28) 
DECLARE_PMID(kScriptInfoIDSpace, kAllowDigPubMethodsWithModalDialogMetadataScriptElement1, kDigitalPublishingPrefix + 29) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubAttachedDeviceInfoScriptElement, kDigitalPublishingPrefix + 30) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubAttachedDevicesEnumScriptElement, kDigitalPublishingPrefix + 31) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetAttachedDevicesMethodScriptElement, kDigitalPublishingPrefix + 32) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubSideloadFolioMethodScriptElement, kDigitalPublishingPrefix + 33) 
DECLARE_PMID(kScriptInfoIDSpace, kAllowDigPubMethodsWithModalDialogAndHideMetadataScriptElement2, kDigitalPublishingPrefix + 34) 
DECLARE_PMID(kScriptInfoIDSpace, kAllowDigPubMethodsWithModalDialogMetadataScriptElement3, kDigitalPublishingPrefix + 35) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubAltLayoutInfoScriptElement, kDigitalPublishingPrefix + 36) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetAltLayoutsMethodScriptElement, kDigitalPublishingPrefix + 37) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetDocumentsIdsMethodScriptElement, kDigitalPublishingPrefix + 38) 
DECLARE_PMID(kScriptInfoIDSpace, kHideDigPubMethodsFromDOMMetadataScriptElement, kDigitalPublishingPrefix + 39) 
DECLARE_PMID(kScriptInfoIDSpace, kHideDigPub70MethodsFromDOMMetadataScriptElement, kDigitalPublishingPrefix + 40) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubWriteAllOverlaysToXMLMethodScriptElement, kDigitalPublishingPrefix + 41) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubWriteVersionToXMLMethodScriptElement, kDigitalPublishingPrefix + 42) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubInsertLabelMethodScriptElement, kDigitalPublishingPrefix + 43) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubLabelPropertyScriptElement, kDigitalPublishingPrefix + 44)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetSupportedViewerVersionsMethodScriptElement, kDigitalPublishingPrefix + 45)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubRasterizePageItemsElement, kDigitalPublishingPrefix + 46)
DECLARE_PMID(kScriptInfoIDSpace, kHideDigPub70MethodsFromDOMMetadataScriptElement2, kDigitalPublishingPrefix + 47) 

DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetSupportedArticleViewerVersionsMethodScriptElement, kDigitalPublishingPrefix + 246)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubArticleVersionEnumScriptElement, kDigitalPublishingPrefix + 247) 
DECLARE_PMID(kScriptInfoIDSpace, kDigPubGetArticleVersionMethodScriptElement, kDigitalPublishingPrefix + 248)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportDPSArticleParamTypeDefScriptElement, kDigitalPublishingPrefix + 249)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportDPSArticleMethodScriptElement, kDigitalPublishingPrefix + 250)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubExportArticleFolioMethodScriptElement, kDigitalPublishingPrefix + 251)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubOverlayDataValueTypeDefScriptElement, kDigitalPublishingPrefix + 252)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubOverlayDataTypeDefScriptElement, kDigitalPublishingPrefix + 253)
DECLARE_PMID(kScriptInfoIDSpace, kDigPubOverlayInfoTypeDefScriptElement, kDigitalPublishingPrefix + 254)

DECLARE_PMID(kServiceIDSpace, kDigitalPublishingSetupService, kDigitalPublishingPrefix + 0)

// "About Plug-ins" sub-menu:
//#define kDigitalPublishingAboutMenuKey			kDigitalPublishingStringPrefix "kDigitalPublishingAboutMenuKey"
//#define kDigitalPublishingAboutMenuPath		kSDKDefStandardAboutMenuPath kDigitalPublishingCompanyKey

// "Plug-ins" sub-menu:
//#define kDigitalPublishingPluginsMenuKey 		kDigitalPublishingStringPrefix "kDigitalPublishingPluginsMenuKey"
//#define kDigitalPublishingPluginsMenuPath		kSDKDefPlugInsStandardMenuPath kDigitalPublishingCompanyKey kSDKDefDelimitMenuPath kDigitalPublishingPluginsMenuKey

// Menu item keys:

// Other StringKeys:
//#define kDigitalPublishingAboutBoxStringKey	kDigitalPublishingStringPrefix "kDigitalPublishingAboutBoxStringKey"
//#define kDigitalPublishingTargetMenuPath kDigitalPublishingPluginsMenuPath

// Menu item positions:

#endif // __DigitalPublishingID_h__

//  Code generated by DollyXs code generator
