//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/persistentlistui/PstLstUIFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(PstLstUIActionComponent, kPstLstUIActionComponentImpl)
REGISTER_PMINTERFACE(PstLstUIDlgController, kPstLstUIDlgControllerImpl)
REGISTER_PMINTERFACE(PstLstUITVHierarchyAdapter, kPstLstUITVHierarchyAdapterImpl)
REGISTER_PMINTERFACE(PstLstUITVWidgetMgr, kPstLstUITVWidgetMgrImpl)
//REGISTER_PMINTERFACE(PstLstUIDataPersist, kPstLstUIDataPersistImpl)
//REGISTER_PMINTERFACE(PstLstUILayoutCSB, kPstLstUILayoutCSBImpl)
//REGISTER_PMINTERFACE(PstLstUIASB, kPstLstUIASBImpl)
REGISTER_PMINTERFACE(PstLstUISelectionObserver, kPstLstUISelectionObserverImpl)
//REGISTER_PMINTERFACE(PstLstUINewDataCmd, kPstLstUINewDataCmdImpl)
//REGISTER_PMINTERFACE(PstLstUISelectDataCmd, kPstLstUISelectDataCmdImpl)
//REGISTER_PMINTERFACE(PstLstUIModifyDataCmd, kPstLstUIModifyDataCmdImpl)
//REGISTER_PMINTERFACE(PstLstUIDeleteDataCmd, kPstLstUIDeleteDataCmdImpl)
//REGISTER_PMINTERFACE(PstLstUIDeletePageItemCmd, kPstLstUIDeletePageItemCmdImpl)
//REGISTER_PMINTERFACE(PstLstUIDocObserver, kPstLstUIDocObserverImpl)
//REGISTER_PMINTERFACE(PstLstUIDocResponder, kPstLstUIDocResponderImpl)
//REGISTER_PMINTERFACE(PstLstUIDocServiceProvider, kPstLstUIDocServiceProviderImpl)
//REGISTER_PMINTERFACE(PstLstUIReferenceConverter, kPstLstUIReferenceConverterImpl)
//REGISTER_PMINTERFACE(SelectionExt<PstLstUIASB>, kPstLstUISuiteASBSelectionExtImpl)
//REGISTER_PMINTERFACE(SelectionExt<PstLstUILayoutCSB>, kPstLstUISuiteLayoutSelectionExtImpl)
//REGISTER_PMINTERFACE(PstLstUIScriptProvider, kPstLstUIScriptProviderImpl)
//REGISTER_PMINTERFACE(PstLstUIScript, kPstLstUIScriptImpl)
//REGISTER_PMINTERFACE(PstLstUIErrorStringService, kPstLstUIErrorStringServiceImpl)

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PstLstUIFactoryList.h.
