//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/gotolasttextedit/GTTxtEdtFactoryList.h $
//  
//  Owner: Adrian O'Lenskie
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(GTTxtEdtActionComponent, kGTTxtEdtActionComponentImpl)
REGISTER_PMINTERFACE(GTTxtEdtControlStripRegister, kGTTxtEdtControlStripRegisterImpl)
REGISTER_PMINTERFACE(GTTxtEdtSnapshotInterface, kGTTxtEdtSnapshotInterfaceImpl)
REGISTER_PMINTERFACE(GTTxtEdtControlStripSuite, kGTTxtEdtControlStripSuiteImpl)
REGISTER_PMINTERFACE(GTTxtEdtUtils, kGTTxtEdtUtilsImpl)
REGISTER_PMINTERFACE(GTTxtEdtStoryObserver, kGTTxtEdtStoryObserverImpl)
REGISTER_PMINTERFACE(GTTxtEdtServiceProvider, kGTTxtEdtServiceProviderImpl)
REGISTER_PMINTERFACE(GTTxtEdtResponder, kGTTxtEdtResponderImpl)
REGISTER_PMINTERFACE(GTTxtEdtGoToTextButtonObserver, kGTTxtEdtGoToTextButtonObserverImpl)
REGISTER_PMINTERFACE(GTTxtEdtNewDeleteStoryObserver, kGTTxtEdtNewDeleteStoryObserverImpl)



//  Code generated by DollyXs code generator
