//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/customconditionaltext/CusCondTxtFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(CustomConditionTag, kCusCondTxtTagImpl)
REGISTER_PMINTERFACE(CusCondTxtTagChangeCmd, kCusCondTxtTagChangeCmdImpl)
REGISTER_PMINTERFACE(CusCondTxtSuiteASB, kCusCondTxtSuiteASBImpl)
REGISTER_PMINTERFACE(CusCondTxtSuiteTextCSB, kCusCondTxtSuiteTextCSBImpl)
REGISTER_PMINTERFACE(CusCondTxtScriptProvider, kCusCondTxtScriptProviderImpl)
REGISTER_PMINTERFACE(CusCondTxtServiceProvider, kCusCondTxtServiceProviderImpl)
REGISTER_PMINTERFACE(CusCondTxtResponder, kCusCondTxtResponderImpl)
REGISTER_PMINTERFACE(CusCondTxtPrintSetupProvider, kCusCondTxtPrintSetupProviderImpl)
REGISTER_PMINTERFACE(CusCondTxtFacade, kCusCondTxtFacadeImpl)

//  Code generated by DollyXs code generator
