//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/basicme/BscMEID.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __BscMEID_h__
#define __BscMEID_h__

#include "SDKDef.h"

// Company:
#define kBscMECompanyKey	kSDKDefPlugInCompanyKey		// Company name used internally for menu paths and the like. Must be globally unique, only A-Z, 0-9, space and "_".
#define kBscMECompanyValue	kSDKDefPlugInCompanyValue	// Company name displayed externally.

// Plug-in:
#define kBscMEPluginName	"BasicME.sdk"			// Name of this plug-in.
#define kBscMEPrefixNumber	0x144000 		// Unique prefix number for this plug-in(*Must* be obtained from Adobe Developer Support).
#define kBscMEVersion		kSDKDefPluginVersionString						// Version of this plug-in (for the About Box).
#define kBscMEAuthor		"Zhiyan Fan"					// Author of this plug-in (for the About Box).

// Plug-in Prefix: (please change kBscMEPrefixNumber above to modify the prefix.)
#define kBscMEPrefix		RezLong(kBscMEPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kBscMEStringPrefix	SDK_DEF_STRINGIZE(kBscMEPrefixNumber)	// The string equivalent of the unique prefix number for  this plug-in.

// Missing plug-in: (see ExtraPluginInfo resource)
#define kBscMEMissingPluginURLValue		kSDKDefPartnersStandardValue_enUS // URL displayed in Missing Plug-in dialog
#define kBscMEMissingPluginAlertValue	kSDKDefMissingPluginAlertValue // Message displayed in Missing Plug-in dialog - provide a string that instructs user how to solve their missing plug-in problem

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kBscMEPluginID, kBscMEPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kBscMEScriptProviderBoss, kBscMEPrefix + 3)
DECLARE_PMID(kClassIDSpace, kBscMEScriptObjectBoss, kBscMEPrefix + 4)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_IBSCMEINVERTFACADE, kBscMEPrefix + 1)

// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kBscMEScriptProviderImpl, kBscMEPrefix + 0 )
DECLARE_PMID(kImplementationIDSpace, kBscMEScriptImpl, kBscMEPrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kBscMEInvertFacadeImpl, kBscMEPrefix + 2)

//Script Element IDs
DECLARE_PMID(kScriptInfoIDSpace, kBscMEMethodScriptElement, kBscMEPrefix + 1)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEPropertyScriptElement, kBscMEPrefix + 2)
DECLARE_PMID(kScriptInfoIDSpace, kBscMECreateDocumentMethodScriptElement, kBscMEPrefix + 3)
DECLARE_PMID(kScriptInfoIDSpace, kBscMESuiteScriptElement, kBscMEPrefix + 4)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEObjectScriptElement, kBscMEPrefix + 5)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEObjectPropertyScriptElement, kBscMEPrefix + 6)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEDirectionEnumElement, kBscMEPrefix + 7)
DECLARE_PMID(kScriptInfoIDSpace, kBscMECreateTextFrameMethodScriptElement, kBscMEPrefix + 8)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEChangeParagraphAttrMethodScriptElement, kBscMEPrefix + 9)
DECLARE_PMID(kScriptInfoIDSpace, kBscMELanguageEnumElement, kBscMEPrefix + 10)
DECLARE_PMID(kScriptInfoIDSpace, kBscMEInvertDocumentMethodScriptElement, kBscMEPrefix + 11)

// "About Plug-ins" sub-menu:
#define kBscMEAboutMenuKey			kBscMEStringPrefix "kBscMEAboutMenuKey"
#define kBscMEAboutMenuPath		kSDKDefStandardAboutMenuPath kBscMECompanyKey

// "Plug-ins" sub-menu:
#define kBscMEPluginsMenuKey 		kBscMEStringPrefix "kBscMEPluginsMenuKey"
#define kBscMEPluginsMenuPath		kSDKDefPlugInsStandardMenuPath kBscMECompanyKey kSDKDefDelimitMenuPath kBscMEPluginsMenuKey

// Menu item keys:

// Other StringKeys:
#define kBscMEAboutBoxStringKey	kBscMEStringPrefix "kBscMEAboutBoxStringKey"
#define kBscMETargetMenuPath kBscMEPluginsMenuPath

// Menu item positions:


// Initial data format version numbers
#define kBscMEFirstMajorFormatNumber kSDKDef_70_PersistMajorVersionNumber
#define kBscMEFirstMinorFormatNumber kSDKDef_70_PersistMinorVersionNumber

// Data format version numbers for the PluginVersion resource 
#define kBscMECurrentMajorFormatNumber kBscMEFirstMajorFormatNumber
#define kBscMECurrentMinorFormatNumber kBscMEFirstMinorFormatNumber

#endif // __BscMEID_h__

//  Code generated by DollyXs code generator
