//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/basicme/BscMEScriptingDefs.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __BscMEScriptingDefs_h__
#define __BscMEScriptingDefs_h__

// Note: 4-char IDs below must be unique.
// See ScriptingDefs.h for further information.
#define kBscME_CLSID {0xc219de83, 0x4e02, 0x4cb5, { 0x99, 0xee, 0x33, 0x60, 0xeb, 0xc3, 0x90, 0xab} }

#define s_BscMESuite 'sBms'
#define c_BscME 'cBme'

// Method IDs
enum BscMEScriptMethods
{
	e_BscMECreateDoc	= 'eCrd',
	e_BscMECreateTextFrame = 'eCrf',
	e_BscMEChangeParagraphAttr = 'eCpa',
	e_BscMEInvertDocument = 'eIvd',
};

// Property IDs
enum BscMEScriptProperties
{
	p_BscMEDirection = 'pSed',
	p_BscME	= 'pBme',
	p_BscMEDocument = 'pBmd',
	p_BscMEPage = 'pBpg',
	p_BscMEPara = 'pBpa',
	p_BscMELang = 'pBln',
	p_BscMEFont = 'pBfo',
	p_BscMEInvertStories = 'pIvs',
	p_BscMEChangeTableDir = 'pCtr',
	p_BscMEMovePageItem = 'pMpi',
	p_BscMEFlipObjectAngle = 'pFoa',
};

enum BscMeScriptEnum
{
	en_BscMEDirection	= 'bsdi',
	en_BscMEDefault		= 'bsda',
	en_BscMELeftToRight	= 'bsdl',
	en_BscMERightToLeft	= 'bsdr',
	en_BscMElanguage = 'bsln',
	en_BscMeArabic = 'bsla',
	en_BscMEHebrew = 'bslh',
	en_BscMERoman = 'bslr',
};

#endif // __BscMEScriptingDefs_h__

//  Code generated by DollyXs code generator
