//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/customdatalink/CusDtLnkFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(CusDtLnkScriptProvider, kCusDtLnkScriptProviderImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResponder, kCusDtLnkLinkResponderImpl)
//REGISTER_PMINTERFACE(CusDtLnkUpdateLinkService, kCusDtLnkUpdateLinkServiceImpl)
REGISTER_PMINTERFACE(CusDtLnkChangeOptionsCmd, kCusDtLnkChangeOptionsCmdImpl)
REGISTER_PMINTERFACE(CusDtLnkOptions, kCusDtLnkOptionsImpl)
REGISTER_PMINTERFACE(CusDtLnkFacade, kCusDtLnkFacadeImpl)
REGISTER_PMINTERFACE(CusDtLnkRespServiceProvider, kCusDtLnkRespServiceProviderImpl)
REGISTER_PMINTERFACE(CusDtLnkAliasedDataLink, kCusDtLnkAliasedDataLinkImpl)
REGISTER_PMINTERFACE(CusDtLnkAliasedDataLinkAction, kCusDtLnkAliasedDataLinkActionImpl)
REGISTER_PMINTERFACE(CusDtLnkAliasedLinkedStream, kCusDtLnkAliasedLinkedStreamImpl)
REGISTER_PMINTERFACE(CusDtLnkDocResponder, kCusDtLnkDocResponderImpl)
REGISTER_PMINTERFACE(CusDtLnkDocRespServiceProvider, kCusDtLnkDocRespServiceProviderImpl)
REGISTER_PMINTERFACE(CusDtLnkAdornmentShape, kCusDtLnkAdornmentShapeImpl)
REGISTER_PMINTERFACE(CusDtLnkDelimTextReader, kCusDtLnkDelimTextReaderImpl)
//REGISTER_PMINTERFACE(CusDtLnkReferenceConverter, kCusDtLnkReferenceConverterImpl)
REGISTER_PMINTERFACE(CusDtLnkScript, kCusDtLnkScriptImpl)
REGISTER_PMINTERFACE(CusDtLnkDocObserver, kCusDtLnkDocObserverImpl)
REGISTER_PMINTERFACE(CusDtLnkOptionScriptProvider, kCusDtLnkOptionScriptProviderImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResourceHandler, kCusDtLnkLinkResourceHandlerImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResourceFactory, kCusDtLnkLinkResourceFactoryImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResourceStateUpdater, kCusDtLnkLinkResourceStateUpdaterImpl)
//REGISTER_PMINTERFACE(CusDtLnkLinkResourceStateProcessorFactory, kCusDtLnkLinkResourceStateProcessorFactoryImpl)
REGISTER_PMINTERFACE(CusDtLnkPhase2Conversion, kCusDtLnkPhase2ConversionImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkAssetConverter, kCusDtLnkLinkAssetConverterImpl)
REGISTER_PMINTERFACE(CusDtLnkImportLinkConverter, kCusDtLnkImportLinkConverterImpl)
REGISTER_PMINTERFACE(CusDtLnkNewLinkConverter, kCusDtLnkNewLinkConverterImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkInfoProvider, kCusDtLnkLinkInfoProviderImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResourceStateUpdaterIdleTask, kCusDtLnkLinkResourceStateUpdaterIdleTaskImpl)
REGISTER_PMINTERFACE(CusDtLnkStateUpdateProcessor, kCusDtLnkStateUpdateProcessorImpl)
REGISTER_PMINTERFACE(CusDtLnkStartupShutdown, kCusDtLnkStartupShutdownImpl)
REGISTER_PMINTERFACE(CusDtLnkLinkResourceHelperHandler, kCusDtLnkLinkResourceHelperHandlerImpl)

//  Code generated by DollyXs code generator
