//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/candlechart/CdlChartFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(CdlChartData, kCdlChartDataImpl)
REGISTER_PMINTERFACE(CdlChartFacade, kCdlChartFacadeImpl)
REGISTER_PMINTERFACE(CdlChartShape, kCdlChartShapeImpl)
REGISTER_PMINTERFACE(CdlChartSuiteASB, kCdlChartSuiteASBImpl)
REGISTER_PMINTERFACE(CdlChartSuiteLayoutCSB, kCdlChartSuiteLayoutCSBImpl)
REGISTER_PMINTERFACE(NewCdlChartCmd, kNewCdlChartCmdImpl)
REGISTER_PMINTERFACE(CdlChartScript, kCdlChartScriptImpl)
REGISTER_PMINTERFACE(CdlChartScriptProvider, kCdlChartScriptProviderImpl)
REGISTER_PMINTERFACE(CdlStockScript, kCdlStockScriptImpl )
REGISTER_PMINTERFACE(CdlStockScriptProvider, kCdlStockScriptProviderImpl )
REGISTER_PMINTERFACE(CdlChartErrorStringService, kCdlChartErrorStringServiceImpl)
REGISTER_PMINTERFACE(ModifyCdlChartCmd, kModifyCdlChartCmdImpl)


//  Code generated by DollyXS code generator
