//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/xmlmarkupinjector/XMLMrkFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(XMLMrkActionComponent, kXMLMrkActionComponentImpl)
REGISTER_PMINTERFACE(XMLMrkSuiteASB, kXMLMrkSuiteASBImpl)
REGISTER_PMINTERFACE(XMLMrkSuiteTextCSB, kXMLMrkSuiteTextCSBImpl)

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, XMLMrkFactoryList.h.



