//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/chlinguistic/CHLFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//  REGISTER_PMINTERFACE(CHLActionComponent,		kCHLActionComponentImpl)// kept here for record keeping purposes (Do not reuse this ID!)
//  
//========================================================================================

REGISTER_PMINTERFACE(CHLServiceProvider, 		kCHLServiceProviderImpl)
REGISTER_PMINTERFACE(CHLFileNameTable, 			kCHLFileNameTableImpl)
REGISTER_PMINTERFACE(CHLSpellingMgr,			kCHLSpellingMgrImpl)
REGISTER_PMINTERFACE(CHLSpelling,				kCHLSpellingServiceImpl)
REGISTER_PMINTERFACE(CHLUserDictMgr,			kCHLUserDictMgrImpl)
REGISTER_PMINTERFACE(CHLUserDictService,		kCHLUserDictServiceImpl)
REGISTER_PMINTERFACE(CHLUserDict,				kCHLUserDictImpl)
REGISTER_PMINTERFACE(CHLUserDictIterator,		kCHLUserDictIteratorImpl)
REGISTER_PMINTERFACE(CHLUserDictUtils,			kCHLUserDictUtilsImpl)
REGISTER_PMINTERFACE(CHLUserDictContentHandler, kCHLUserDictContentHandlerImpl)
REGISTER_PMINTERFACE(CHLData,					kCHLDataImpl)
REGISTER_PMINTERFACE(CHLThesaurusMgr,			kCHLThesaurusMgrImpl)
REGISTER_PMINTERFACE(CHLThesaurus,				kCHLThesaurusImpl)
REGISTER_PMINTERFACE(CHLErrorStringService,		kCHLErrorStringServiceImpl)

//  Generated by Dolly build 17: template "Dialog".
// End, CHLFactoryList.h.


