//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/paneltreeview/PnlTrvFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(PnlTrvActionComponent, kPnlTrvActionComponentImpl)
REGISTER_PMINTERFACE(PnlTrvTreeObserver, kPnlTrvTreeObserverImpl)
REGISTER_PMINTERFACE(PnlTrvTVHierarchyAdapter, kPnlTrvTVHierarchyAdapterImpl)
REGISTER_PMINTERFACE(PnlTrvTVWidgetMgr, kPnlTrvTVWidgetMgrImpl)
REGISTER_PMINTERFACE(PnlTrvNodeEH, kPnlTrvNodeEHImpl)
REGISTER_PMINTERFACE(PnlTrvChangeOptionsCmd,	kPnlTrvChangeOptionsCmdImpl)
REGISTER_PMINTERFACE(PnlTrvChangeOptionsCmdData, kPnlTrvChangeOptionsCmdDataImpl)
REGISTER_PMINTERFACE(kPnlTrvOptionsImpl,		kPnlTrvOptionsImpl)
REGISTER_PMINTERFACE(PnlTrvNodeObserver, kPnlTrvNodeObserverImpl)
REGISTER_PMINTERFACE(PnlTrvIdleTaskImpl,kPnlTrvIdleTaskImpl)
REGISTER_PMINTERFACE(PnlTrvStartupShutdown,kPnlTrvStartupShutdownImpl)
REGISTER_PMINTERFACE(PnlTrvCustomView, kPnlTrvCustomViewImpl)
REGISTER_PMINTERFACE(PnlTrvDragDropSource, kPnlTrvDragDropSourceImpl)
REGISTER_PMINTERFACE(PnlTrvDataModel, kPnlTrvDataModelImpl)
REGISTER_PMINTERFACE(PnlTrvScriptProvider, kPnlTrvScriptProviderImpl)
REGISTER_PMINTERFACE(PnlTrvErrorStringService, kPnlTrvErrorStringServiceImpl)
//  Generated by Dolly build 17: template "IfPanelMenu".
// End, PnlTrvFactoryList.h.

