//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/basickit/BscKitActionComponent.cpp $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#include "VCPlugInHeaders.h"

// Interface includes:

// General includes:
#include "CActionComponent.h"
#include "CAlert.h"

// Project includes:
#include "BscKitID.h"


/** Implements the actions that are executed when the plug-in's
	menu items are selected.

	
	@ingroup basickit
*/
class BscKitActionComponent : public CActionComponent
{
	public:
		/**
			Constructor.
			@param boss interface ptr from boss object on which this interface is aggregated.
		*/
		BscKitActionComponent(IPMUnknown* boss);

		/**
			The action component should do the requested action.
			This is where the menu item's action is taken.
			When a menu item is selected, the Menu Manager determines
			which plug-in is responsible for it, and calls its DoAction
			with the ID for the menu item chosen.

			@param ac active context
			@param actionID identifies the menu item that was selected.
			@param mousePoint where widget was clicked
			@param widget which widget was clicked

			@see CActionComponent::DoAction
			*/
		virtual void DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint = kInvalidMousePoint, IPMUnknown* widget = nil);

	private:
		/** Encapsulates functionality for the about menu item. */
		void DoAbout();

};

/* CREATE_PMINTERFACE
 Binds the C++ implementation class onto its
 ImplementationID making the C++ code callable by the
 application.
*/
CREATE_PMINTERFACE(BscKitActionComponent, kBscKitActionComponentImpl)

/* BscKitActionComponent Constructor
*/
BscKitActionComponent::BscKitActionComponent(IPMUnknown* boss)
: CActionComponent(boss)
{
}

/* DoAction
*/
void BscKitActionComponent::DoAction(IActiveContext* ac, ActionID actionID, GSysPoint mousePoint, IPMUnknown* widget)
{
	switch (actionID.Get())
	{
		case kBscKitPopupAboutThisActionID:
		case kBscKitAboutActionID:
		{
			this->DoAbout();
			break;
		}

		default:
		{
			break;
		}
	}
}

/* DoAbout
*/
void BscKitActionComponent::DoAbout()
{
	CAlert::ModalAlert(kBscKitAboutBoxStringKey,	// Alert string
	   kOKString, 							// OK button
	   kNullString, 						// No second button
	   kNullString, 						// No third button
	   1,									// Set OK button to default
	   CAlert::eInformationIcon				// Information icon.
	);
}

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, BscKitActionComponent.cpp.





