//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/open/interfaces/layout/HyperlinkPanelID.h $
//  
//  Owner: Brendan O'Shea
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Contains IDs used by the hyperlink panel plug-in
//  
//========================================================================================

#ifndef __HyperlinkPanelID__
#define __HyperlinkPanelID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

#define kHyperlinkPanelPrefix	RezLong(0x13600)

// <Start IDC>
// PluginID
#define kHyperlinkPanelPluginName 	"Hyperlink Panel"
DECLARE_PMID(kPlugInIDSpace, kHyperlinkPanelPluginID, kHyperlinkPanelPrefix + 1)

// Conversion
// For pub conversion constants see HyperlinkPanelConversionID.h

// <Class ID>
//========================================================================================
// ----- ClassIDs -----
//========================================================================================
DECLARE_PMID(kClassIDSpace, kHyperlinkPanelBoss,					kHyperlinkPanelPrefix + 1)
DECLARE_PMID(kClassIDSpace, kHyperlinkListBoxBoss,					kHyperlinkPanelPrefix + 2)
DECLARE_PMID(kClassIDSpace, kGotoHyperlinkSourceButtonBoss,			kHyperlinkPanelPrefix + 3)
DECLARE_PMID(kClassIDSpace, kGotoHyperlinkDestButtonBoss,			kHyperlinkPanelPrefix + 4)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkButtonBoss,				kHyperlinkPanelPrefix + 5)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkButtonBoss,				kHyperlinkPanelPrefix + 6)
DECLARE_PMID(kClassIDSpace, kHyperlinkListElementNameBoss,			kHyperlinkPanelPrefix + 7)
DECLARE_PMID(kClassIDSpace, kHyperlinkListElementBoss,				kHyperlinkPanelPrefix + 8)
DECLARE_PMID(kClassIDSpace, kOpenDocumentDropDownWidgetBoss,		kHyperlinkPanelPrefix + 9)
//gap
DECLARE_PMID(kClassIDSpace, kEditHyperlinkDialogBoss,				kHyperlinkPanelPrefix + 11)
DECLARE_PMID(kClassIDSpace, kHyperlinkPanelActionComponentBoss,		kHyperlinkPanelPrefix + 12)
DECLARE_PMID(kClassIDSpace, kHyperlinkListDEHandlerBoss,			kHyperlinkPanelPrefix + 13)
//gap
DECLARE_PMID(kClassIDSpace, kEditHyperlinkDestDlgBoss,				kHyperlinkPanelPrefix + 17)
DECLARE_PMID(kClassIDSpace, kEditAllHyperlinkDestsDlgBoss,			kHyperlinkPanelPrefix + 18)
DECLARE_PMID(kClassIDSpace, kEditDestinationButtonObserverBoss,		kHyperlinkPanelPrefix + 19)
DECLARE_PMID(kClassIDSpace, kDeleteDestinationButtonObserverBoss,	kHyperlinkPanelPrefix + 20)
DECLARE_PMID(kClassIDSpace, kDestinationIconViewBoss,				kHyperlinkPanelPrefix + 21)
DECLARE_PMID(kClassIDSpace, kEditHyperlinkDestDlgSelectableBoss,	kHyperlinkPanelPrefix + 22)
DECLARE_PMID(kClassIDSpace, kDestinationTypeDDListWidgetBoss,		kHyperlinkPanelPrefix + 23)
DECLARE_PMID(kClassIDSpace, kDestinationTypePanelWidgetBoss,		kHyperlinkPanelPrefix + 24)
DECLARE_PMID(kClassIDSpace, kURLDestinationDialogBoss,				kHyperlinkPanelPrefix + 25)
DECLARE_PMID(kClassIDSpace, kTextDestinationDialogBoss,				kHyperlinkPanelPrefix + 26)
DECLARE_PMID(kClassIDSpace, kPageDestinationDialogBoss,				kHyperlinkPanelPrefix + 27)
DECLARE_PMID(kClassIDSpace, kApplyURLDestinationDialogBoss,			kHyperlinkPanelPrefix + 28)
DECLARE_PMID(kClassIDSpace, kApplyTextDestinationDialogBoss,		kHyperlinkPanelPrefix + 29)
DECLARE_PMID(kClassIDSpace, kApplyPageDestinationDialogBoss,		kHyperlinkPanelPrefix + 30)
DECLARE_PMID(kClassIDSpace, kApplyAllTypesDestinationDialogBoss,	kHyperlinkPanelPrefix + 31)
DECLARE_PMID(kClassIDSpace, kPrivateSetHyperlinkSortOrderCmdBoss,	kHyperlinkPanelPrefix + 32)
DECLARE_PMID(kClassIDSpace, kAutoNameCheckBoxWidgetBoss,			kHyperlinkPanelPrefix + 33)
DECLARE_PMID(kClassIDSpace, kShowPageItemCommandBoss, 				kHyperlinkPanelPrefix + 34)
DECLARE_PMID(kClassIDSpace, kHyperlinkTestMenuBoss, 				kHyperlinkPanelPrefix + 35)
DECLARE_PMID(kClassIDSpace, kHyperlinkLayoutActionBoss, 			kHyperlinkPanelPrefix + 36)

DECLARE_PMID(kClassIDSpace, kURLDestinationUIServiceBoss, 			kHyperlinkPanelPrefix + 37)
DECLARE_PMID(kClassIDSpace, kTextDestinationUIServiceBoss, 			kHyperlinkPanelPrefix + 38)
DECLARE_PMID(kClassIDSpace, kPageDestinationUIServiceBoss, 			kHyperlinkPanelPrefix + 39)
DECLARE_PMID(kClassIDSpace, kExternalPageDestinationUIServiceBoss, 	kHyperlinkPanelPrefix + 40)
DECLARE_PMID(kClassIDSpace, kHyperlinkPanelOpenAppResponderBoss, 	kHyperlinkPanelPrefix + 41)

DECLARE_PMID(kClassIDSpace, kTextSourceUIServiceBoss, 				kHyperlinkPanelPrefix + 42)
DECLARE_PMID(kClassIDSpace, kPageItemSourceUIServiceBoss, 			kHyperlinkPanelPrefix + 43)
DECLARE_PMID(kClassIDSpace, kApplyEmailDestinationDialogBoss,		kHyperlinkPanelPrefix + 44)
DECLARE_PMID(kClassIDSpace, kApplyFileDestinationDialogBoss,		kHyperlinkPanelPrefix + 45)
DECLARE_PMID(kClassIDSpace, kApplyNamedDestinationDialogBoss,		kHyperlinkPanelPrefix + 46)
DECLARE_PMID(kClassIDSpace, kApplyParagraphDestinationDialogBoss,	kHyperlinkPanelPrefix + 47)
DECLARE_PMID(kClassIDSpace, kDefineXRefFormatsDialogBoss,			kHyperlinkPanelPrefix + 48)
DECLARE_PMID(kClassIDSpace, kNewXRefButtonBoss,						kHyperlinkPanelPrefix + 49)
DECLARE_PMID(kClassIDSpace, kUpdateXRefsButtonBoss,					kHyperlinkPanelPrefix + 50)

DECLARE_PMID(kClassIDSpace, kURLEditBoxWidgetBoss,					kHyperlinkPanelPrefix + 51)
DECLARE_PMID(kClassIDSpace, kRenameHyperlinkDialogBoss,				kHyperlinkPanelPrefix + 52)

DECLARE_PMID(kClassIDSpace, kHyperlinkSourceLinkBoss,				kHyperlinkPanelPrefix + 53)
DECLARE_PMID(kClassIDSpace, kHyperlinksUIColumnHeaderWidgetBoss,	kHyperlinkPanelPrefix + 54)
DECLARE_PMID(kClassIDSpace, kHyperlinkColumnHeaderIconWidgetBoss,	kHyperlinkPanelPrefix + 55)

DECLARE_PMID(kClassIDSpace, kUpdateURLStatusButtonBoss,				kHyperlinkPanelPrefix + 56)
DECLARE_PMID(kClassIDSpace, kXrefTreeViewBoss,						kHyperlinkPanelPrefix + 57)

DECLARE_PMID(kClassIDSpace, kSetHyperlinkCharStylePrefCmdBoss,		kHyperlinkPanelPrefix + 58)
DECLARE_PMID(kClassIDSpace, kURLComboBoxWidgetBoss,                 kHyperlinkPanelPrefix + 59)
DECLARE_PMID(kClassIDSpace, kURLDestinationEditBoxWidgetBoss,		kHyperlinkPanelPrefix + 60)

DECLARE_PMID(kClassIDSpace, kXRefTextListSearchBoxBoss,				kHyperlinkPanelPrefix + 61)
DECLARE_PMID(kClassIDSpace, kPageItemDestinationUIServiceBoss,		kHyperlinkPanelPrefix + 62)

// <Interface ID>
//========================================================================================
// ----- Interface IDs -----
//========================================================================================
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKOPTIONDATA,				kHyperlinkPanelPrefix + 1) // Using IntDataImplementation
//DECLARE_PMID(kInterfaceIDSpace, IID_IUIDREFLISTDATA,					kHyperlinkPanelPrefix + 2)

DECLARE_PMID(kInterfaceIDSpace, IID_IDOCUMENTUIDLIST,					kHyperlinkPanelPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_IDESTINATIONUIDLIST,				kHyperlinkPanelPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_ICLOSEDDOCUMENTUIDLIST,				kHyperlinkPanelPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_IDESTINATIONTYPEPANELATTRIBUTES,	kHyperlinkPanelPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_IEDITLIST,							kHyperlinkPanelPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKIEWMODE,					kHyperlinkPanelPrefix + 8)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKLAYOUTOBSERVER, 			kHyperlinkPanelPrefix + 9)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHSTYLES, 					kHyperlinkPanelPrefix + 10)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHSTORIES, 					kHyperlinkPanelPrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHSTARTS, 					kHyperlinkPanelPrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_IDELETEDFORMATS, 					kHyperlinkPanelPrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_ICHARACTERSTYLES, 					kHyperlinkPanelPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_RECREATEDESTINATION, 				kHyperlinkPanelPrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_REFRESHXREFFORMATS, 				kHyperlinkPanelPrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_FORMATUIDS, 						kHyperlinkPanelPrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_FORMATNAMES, 						kHyperlinkPanelPrefix + 18)
DECLARE_PMID(kInterfaceIDSpace, IID_ILASTCREATEDDEST, 					kHyperlinkPanelPrefix + 19)
DECLARE_PMID(kInterfaceIDSpace, IID_UPDATEMODEL, 						kHyperlinkPanelPrefix + 20)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHS, 						kHyperlinkPanelPrefix + 21)
DECLARE_PMID(kInterfaceIDSpace, IID_CLEARCURRENTSELECTION,				kHyperlinkPanelPrefix + 22)
DECLARE_PMID(kInterfaceIDSpace, IID_TYPINGINURLEDITBOX,					kHyperlinkPanelPrefix + 23)
DECLARE_PMID(kInterfaceIDSpace, IID_IREBUILDHIERARCHY,					kHyperlinkPanelPrefix + 24)
DECLARE_PMID(kInterfaceIDSpace, IID_IAUTOUPDATEURLSTATUSBOOLDATA,		kHyperlinkPanelPrefix + 25)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKCHARSTYLENAMEDATA,		kHyperlinkPanelPrefix + 26)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAZYGOTODESTINATION,				kHyperlinkPanelPrefix + 27)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKEXTERNALCACHE,			kHyperlinkPanelPrefix + 28)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHSTORIES2,					kHyperlinkPanelPrefix + 29)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHSTARTS2,					kHyperlinkPanelPrefix + 30)
DECLARE_PMID(kInterfaceIDSpace, IID_IPARAGRAPHINDEX,					kHyperlinkPanelPrefix + 31)
DECLARE_PMID(kInterfaceIDSpace, IID_IATTACHTOFIRSTRESULT,				kHyperlinkPanelPrefix + 32)


// <Implementation ID>
//========================================================================================
// ----- Implementation IDs -----
//========================================================================================
//gap
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelObserverImpl,					kHyperlinkPanelPrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkButtonObserverImpl,				kHyperlinkPanelPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkButtonObserverImpl,			kHyperlinkPanelPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelActionCompImpl,					kHyperlinkPanelPrefix + 5)
DECLARE_PMID(kImplementationIDSpace, kOpenDocsDDObserverImpl,						kHyperlinkPanelPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListElementViewImpl,					kHyperlinkPanelPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListElementDataImpl,					kHyperlinkPanelPrefix + 8)
//gap
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkDlgControllerImpl,				kHyperlinkPanelPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kParagraphStyleListWidgetID,					kHyperlinkPanelPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kParagraphTextListWidgetID,					kHyperlinkPanelPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListDragDropSourceImpl,				kHyperlinkPanelPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListDragDropTargetImpl,				kHyperlinkPanelPrefix + 14)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListDragEvtHandlerImpl,				kHyperlinkPanelPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDeleteDragDropTargetImpl,			kHyperlinkPanelPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelResizeRuleImpl,					kHyperlinkPanelPrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPalettePanelImpl,					kHyperlinkPanelPrefix + 18)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkElementResizeRuleImpl,				kHyperlinkPanelPrefix + 19)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkElementViewImpl,						kHyperlinkPanelPrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkWidgetTipImpl,						kHyperlinkPanelPrefix + 21)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkCellWidgetFactoryImpl,				kHyperlinkPanelPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNameEditObserverImpl,				kHyperlinkPanelPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkCellWidgetControllerImpl,			kHyperlinkPanelPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkWidgetListBoxHelperImpl,				kHyperlinkPanelPrefix + 25)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelElementObserverImpl,			kHyperlinkPanelPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNameEHImpl,							kHyperlinkPanelPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kEditHyperlinkDestDlgContImpl,					kHyperlinkPanelPrefix + 28)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkOptionsDlgObserverImpl,				kHyperlinkPanelPrefix + 29)
DECLARE_PMID(kImplementationIDSpace, kDocumentUIDListDataImpl,						kHyperlinkPanelPrefix + 30)
DECLARE_PMID(kImplementationIDSpace, kDestinationUIDListDataImpl,					kHyperlinkPanelPrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kClosedDocumentUIDListDataImpl,				kHyperlinkPanelPrefix + 32)
DECLARE_PMID(kImplementationIDSpace, kEditAllHyperlinkDestsDlgImpl,					kHyperlinkPanelPrefix + 33)
DECLARE_PMID(kImplementationIDSpace, kEditAllHyperlinkDestsDlgObserverImpl,			kHyperlinkPanelPrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kGotoHyperlinkSourceButtonObserverImpl,		kHyperlinkPanelPrefix + 35)
DECLARE_PMID(kImplementationIDSpace, kGotoHyperlinkDestButtonObserverImpl,			kHyperlinkPanelPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kDestinationIconViewImpl,						kHyperlinkPanelPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestinationDialogSwitcherImpl,		kHyperlinkPanelPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 39)
DECLARE_PMID(kImplementationIDSpace, kDestinationTypePanelAttributesImpl,			kHyperlinkPanelPrefix + 40)
DECLARE_PMID(kImplementationIDSpace, kDestinationTypePanelImpl,						kHyperlinkPanelPrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kApplyPageDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kApplyTextDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 43)
DECLARE_PMID(kImplementationIDSpace, kApplyURLDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDialogCreatorImpl,					kHyperlinkPanelPrefix + 45)
DECLARE_PMID(kImplementationIDSpace, kPageDestinationDialogControllerImpl,			kHyperlinkPanelPrefix + 46)
DECLARE_PMID(kImplementationIDSpace, kPageDestinationDialogCreatorImpl,				kHyperlinkPanelPrefix + 47)
DECLARE_PMID(kImplementationIDSpace, kTextDestinationDialogControllerImpl,			kHyperlinkPanelPrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kTextDestinationDialogCreatorImpl,				kHyperlinkPanelPrefix + 49)
DECLARE_PMID(kImplementationIDSpace, kURLDestinationDialogControllerImpl,			kHyperlinkPanelPrefix + 50)
DECLARE_PMID(kImplementationIDSpace, kURLDestinationDialogCreatorImpl,				kHyperlinkPanelPrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kApplyPageDestinationDialogControllerImpl,		kHyperlinkPanelPrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kApplyPageDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 55)
DECLARE_PMID(kImplementationIDSpace, kApplyTextDestinationDialogControllerImpl,		kHyperlinkPanelPrefix + 56)
DECLARE_PMID(kImplementationIDSpace, kApplyTextDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 57)
DECLARE_PMID(kImplementationIDSpace, kApplyURLDestinationDialogControllerImpl,		kHyperlinkPanelPrefix + 58)
DECLARE_PMID(kImplementationIDSpace, kApplyURLDestinationDialogCreatorImpl,			kHyperlinkPanelPrefix + 59)
DECLARE_PMID(kImplementationIDSpace, kApplyAllTypesDestinationDialogCreatorImpl,	kHyperlinkPanelPrefix + 60)
DECLARE_PMID(kImplementationIDSpace, kApplyAllTypesDestinationDialogObserverImpl,	kHyperlinkPanelPrefix + 61)
DECLARE_PMID(kImplementationIDSpace, kApplyAllTypesDestinationDialogControllerImpl,	kHyperlinkPanelPrefix + 62)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestinationListDialogCreatorImpl,	kHyperlinkPanelPrefix + 63)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkViewModeDataImpl,					kHyperlinkPanelPrefix + 64)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelDetailControllerImpl,			kHyperlinkPanelPrefix + 65)
DECLARE_PMID(kImplementationIDSpace, kPrivateSetHyperlinkSortOrderCmdImpl,			kHyperlinkPanelPrefix + 66)
DECLARE_PMID(kImplementationIDSpace, kPageDestinationAutoNameObserverImpl,			kHyperlinkPanelPrefix + 67)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelXMLGeneratorImpl,				kHyperlinkPanelPrefix + 68)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelSAXHandlerImpl,					kHyperlinkPanelPrefix + 69)
DECLARE_PMID(kImplementationIDSpace, kIntListImpl,									kHyperlinkPanelPrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkLayoutObserverImpl, 					kHyperlinkPanelPrefix + 71)
// gap
DECLARE_PMID(kImplementationIDSpace, kShowPageItemCommandImpl, 						kHyperlinkPanelPrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTestMenuImpl, 						kHyperlinkPanelPrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkLayoutActionImpl,				 	kHyperlinkPanelPrefix + 75)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelOpenAppResponderImpl,			kHyperlinkPanelPrefix + 76)
DECLARE_PMID(kImplementationIDSpace, kApplyNamedDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kApplyNamedDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kApplyNamedDestinationDialogControllerImpl,	kHyperlinkPanelPrefix + 79)
DECLARE_PMID(kImplementationIDSpace, kURLDestinationUIServiceImpl,				 	kHyperlinkPanelPrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kURLDestinationUIImpl,				 			kHyperlinkPanelPrefix + 81)
DECLARE_PMID(kImplementationIDSpace, kTextDestinationUIServiceImpl,				 	kHyperlinkPanelPrefix + 82)
DECLARE_PMID(kImplementationIDSpace, kTextDestinationUIImpl,				 		kHyperlinkPanelPrefix + 83)
DECLARE_PMID(kImplementationIDSpace, kPageDestinationUIServiceImpl,				 	kHyperlinkPanelPrefix + 84)
DECLARE_PMID(kImplementationIDSpace, kPageDestinationUIImpl,				 		kHyperlinkPanelPrefix + 85)
DECLARE_PMID(kImplementationIDSpace, kExternalPageDestinationUIServiceImpl,			kHyperlinkPanelPrefix + 86)
DECLARE_PMID(kImplementationIDSpace, kExternalPageDestinationUIImpl,				kHyperlinkPanelPrefix + 87)
DECLARE_PMID(kImplementationIDSpace, kTextSourceUIServiceImpl,				 		kHyperlinkPanelPrefix + 88)
DECLARE_PMID(kImplementationIDSpace, kTextSourceUIImpl,				 				kHyperlinkPanelPrefix + 89)
DECLARE_PMID(kImplementationIDSpace, kPageItemSourceUIServiceImpl,				 	kHyperlinkPanelPrefix + 90)
DECLARE_PMID(kImplementationIDSpace, kPageItemSourceUIImpl,				 			kHyperlinkPanelPrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteDefaultCSBImpl,					kHyperlinkPanelPrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kApplyParagraphDestinationDialogCreatorImpl,	kHyperlinkPanelPrefix + 93)
DECLARE_PMID(kImplementationIDSpace, kApplyParagraphDestinationDialogObserverImpl,	kHyperlinkPanelPrefix + 94)
DECLARE_PMID(kImplementationIDSpace, kApplyParagraphDestinationDialogControllerImpl,kHyperlinkPanelPrefix + 95)
DECLARE_PMID(kImplementationIDSpace, kParagraphStoriesImpl,							kHyperlinkPanelPrefix + 96)
DECLARE_PMID(kImplementationIDSpace, kParagraphStartsImpl,							kHyperlinkPanelPrefix + 97)
DECLARE_PMID(kImplementationIDSpace, kDefineXRefFormatsDialogCreatorImpl,			kHyperlinkPanelPrefix + 98)
DECLARE_PMID(kImplementationIDSpace, kDefineXRefFormatsControllerImpl,				kHyperlinkPanelPrefix + 99)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPanelPendingUpdateControllerImpl,	kHyperlinkPanelPrefix + 100)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkListBoxControlViewImpl,				kHyperlinkPanelPrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kApplyEmailDestinationDialogControllerImpl,	kHyperlinkPanelPrefix + 102)
DECLARE_PMID(kImplementationIDSpace, kApplyEmailDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 103)
DECLARE_PMID(kImplementationIDSpace, kApplyEmailDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 104)
DECLARE_PMID(kImplementationIDSpace, kApplyFileDestinationDialogControllerImpl,		kHyperlinkPanelPrefix + 105)
DECLARE_PMID(kImplementationIDSpace, kApplyFileDestinationDialogCreatorImpl,		kHyperlinkPanelPrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kApplyFileDestinationDialogObserverImpl,		kHyperlinkPanelPrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kDefineXRefFormatsObserverImpl,				kHyperlinkPanelPrefix + 108)
DECLARE_PMID(kImplementationIDSpace, kDeleteFormatsList,							kHyperlinkPanelPrefix + 109)
DECLARE_PMID(kImplementationIDSpace, kCharacterStylesList,							kHyperlinkPanelPrefix + 110)
DECLARE_PMID(kImplementationIDSpace, kNewXRefButtonObserverImpl,					kHyperlinkPanelPrefix + 111)
DECLARE_PMID(kImplementationIDSpace, kUpdateXRefsButtonObserverImpl,				kHyperlinkPanelPrefix + 112)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestTipImpl,							kHyperlinkPanelPrefix + 115)
DECLARE_PMID(kImplementationIDSpace, kURLEditBoxObserverImpl,						kHyperlinkPanelPrefix + 116)
DECLARE_PMID(kImplementationIDSpace, kFormatUIDListData,							kHyperlinkPanelPrefix + 117)
DECLARE_PMID(kImplementationIDSpace, kFormatNames,									kHyperlinkPanelPrefix + 118)
DECLARE_PMID(kImplementationIDSpace, kLastCreatedDestImpl,							kHyperlinkPanelPrefix + 119)
DECLARE_PMID(kImplementationIDSpace, kParagraphStylesImpl,							kHyperlinkPanelPrefix + 120)
DECLARE_PMID(kImplementationIDSpace, kParagraphsImpl,								kHyperlinkPanelPrefix + 121)
DECLARE_PMID(kImplementationIDSpace, kURLComboBoxObserverImpl,						kHyperlinkPanelPrefix + 122)
DECLARE_PMID(kImplementationIDSpace, kRenameHyperlinkDlgControllerImpl,				kHyperlinkPanelPrefix + 126)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSourceLinkEHImpl,					kHyperlinkPanelPrefix + 127)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestLinkEHImpl,						kHyperlinkPanelPrefix + 128)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSourceLinkStaticTextViewImpl,		kHyperlinkPanelPrefix + 129)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSourceCursorProviderImpl,			kHyperlinkPanelPrefix + 130)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkStatusIdleTaskImpl,					kHyperlinkPanelPrefix + 131)
DECLARE_PMID(kImplementationIDSpace, kHyperlinksColumnHeaderObserverImpl,			kHyperlinkPanelPrefix + 132)
DECLARE_PMID(kImplementationIDSpace, kUpdateURLStatusButtonObserverImpl,			kHyperlinkPanelPrefix + 133)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageTipImpl,							kHyperlinkPanelPrefix + 134)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTreeViewAdapterImpl,					kHyperlinkPanelPrefix + 135)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTreeViewWidgetMgrImpl,				kHyperlinkPanelPrefix + 136)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNameILEEditingAttributesImpl,		kHyperlinkPanelPrefix + 137)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNameTextValidationImpl,				kHyperlinkPanelPrefix + 138)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTreeViewControllerImpl,				kHyperlinkPanelPrefix + 139)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkCharStyleDataImpl,					kHyperlinkPanelPrefix + 140)
DECLARE_PMID(kImplementationIDSpace, kSetHyperlinkCharStylePrefCmdImpl,				kHyperlinkPanelPrefix + 141)
DECLARE_PMID(kImplementationIDSpace, kURLComboBoxTextDataValidationImpl,			kHyperlinkPanelPrefix + 142)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExternalCacheImpl,					kHyperlinkPanelPrefix + 143)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTreeViewMgrImpl,						kHyperlinkPanelPrefix + 144)
DECLARE_PMID(kImplementationIDSpace, kXRefTextListSearchBoxObsImpl,					kHyperlinkPanelPrefix + 145)
DECLARE_PMID(kImplementationIDSpace, kXRefSearchBoxDialogControllerImpl,			kHyperlinkPanelPrefix + 146)
DECLARE_PMID(kImplementationIDSpace, kXRefSearchBoxDialogCreatorImpl,				kHyperlinkPanelPrefix + 147)
DECLARE_PMID(kImplementationIDSpace, kCRSearchStringImpl,							kHyperlinkPanelPrefix + 148)
DECLARE_PMID(kImplementationIDSpace, kPageItemDestinationUIServiceImpl,				kHyperlinkPanelPrefix + 149)


// <Widget ID>
//========================================================================================
// ----- Widget IDs -----
//========================================================================================

DECLARE_PMID(kWidgetIDSpace, kHyperlinkPanelWidgetID,				kHyperlinkPanelPrefix + 1)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListWidgetID,				kHyperlinkPanelPrefix + 2)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDeleteButtonWidgetID,		kHyperlinkPanelPrefix + 3)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNewButtonWidgetID,			kHyperlinkPanelPrefix + 4)
//gap
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListElementNameWidgetID,		kHyperlinkPanelPrefix + 6)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkControlStripWidgetID,		kHyperlinkPanelPrefix + 7)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanelWidgetID,			kHyperlinkPanelPrefix + 8)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkGotoSourceButtonWidgetID,	kHyperlinkPanelPrefix + 9)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkGotoDestButtonWidgetID,		kHyperlinkPanelPrefix + 10)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestinationIconWidgetID,		kHyperlinkPanelPrefix + 11)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkSpacerWidgetID,				kHyperlinkPanelPrefix + 12)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkSpacer2WidgetID,				kHyperlinkPanelPrefix + 13)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkList2WidgetID,				kHyperlinkPanelPrefix + 14)
//gap
DECLARE_PMID(kWidgetIDSpace, kLargeRowsSplitterWidgetID,			kHyperlinkPanelPrefix + 16)
DECLARE_PMID(kWidgetIDSpace, kSmallRowsSplitterWidgetID,			kHyperlinkPanelPrefix + 17)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkSourcePageWidgetID,			kHyperlinkPanelPrefix + 18)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameColWidgetID,				kHyperlinkPanelPrefix + 19)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkPageColWidgetID,				kHyperlinkPanelPrefix + 20)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkStatusColWidgetID,			kHyperlinkPanelPrefix + 21)
DECLARE_PMID(kWidgetIDSpace, kXRefPanelWidgetID,					kHyperlinkPanelPrefix + 22)

// IDs for the New Hyperlink dialog
DECLARE_PMID(kWidgetIDSpace, kNewXRefParentWidgetID,						kHyperlinkPanelPrefix + 24)
DECLARE_PMID(kWidgetIDSpace, kNewHyperlinkParentWidgetID,						kHyperlinkPanelPrefix + 25)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameWidgetID,							kHyperlinkPanelPrefix + 26)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameStaticWidgetID,						kHyperlinkPanelPrefix + 27)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestinationTextWidgetID,					kHyperlinkPanelPrefix + 28)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestinationWidgetID,						kHyperlinkPanelPrefix + 29)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentTextWidgetID,					kHyperlinkPanelPrefix + 30)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentNamedWidgetID,					kHyperlinkPanelPrefix + 31)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestinationStaticWidgetID,				kHyperlinkPanelPrefix + 32)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkSettingsPanelID,							kHyperlinkPanelPrefix + 33)
DECLARE_PMID(kWidgetIDSpace, kHyperlinksButtonsAreaPanelID,						kHyperlinkPanelPrefix + 34)
DECLARE_PMID(kWidgetIDSpace, kSpacer1WidgetID,									kHyperlinkPanelPrefix + 35)
DECLARE_PMID(kWidgetIDSpace, kSpacer2WidgetID,									kHyperlinkPanelPrefix + 36)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkLinkToPanelID,							kHyperlinkPanelPrefix + 37)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkStyleGroupWidgetID,						kHyperlinkPanelPrefix + 38)
DECLARE_PMID(kWidgetIDSpace, kCharacterStyleGroupStaticWidgetID,				kHyperlinkPanelPrefix + 39)
DECLARE_PMID(kWidgetIDSpace, kCharStylePanel1ID,								kHyperlinkPanelPrefix + 40)
DECLARE_PMID(kWidgetIDSpace, kCharStylePanel2ID,								kHyperlinkPanelPrefix + 41)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkCharacterStyleWidgetID,					kHyperlinkPanelPrefix + 42)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkCharacterStyleStaticWidgetID,			kHyperlinkPanelPrefix + 43)
DECLARE_PMID(kWidgetIDSpace, kSpacer3WidgetID,									kHyperlinkPanelPrefix + 44)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestination2WidgetID,					kHyperlinkPanelPrefix + 45)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentParagraphWidgetID,				kHyperlinkPanelPrefix + 46)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentParagraphStaticWidgetID,			kHyperlinkPanelPrefix + 47)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentNamedStaticWidgetID,				kHyperlinkPanelPrefix + 48)
DECLARE_PMID(kWidgetIDSpace, kParagraphSplitterWidgetID,						kHyperlinkPanelPrefix + 49)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAppearanceWidgetID,						kHyperlinkPanelPrefix + 50)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAppearanceStaticWidgetID,				kHyperlinkPanelPrefix + 51)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkTypeStaticWidgetID,						kHyperlinkPanelPrefix + 52)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkTypeWidgetID,							kHyperlinkPanelPrefix + 53)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkHighlightStaticWidgetID,					kHyperlinkPanelPrefix + 54)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkHighlightWidgetID,						kHyperlinkPanelPrefix + 55)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkWidthStaticWidgetID,						kHyperlinkPanelPrefix + 56)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkWidthWidgetID,							kHyperlinkPanelPrefix + 57)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkColorStaticWidgetID,						kHyperlinkPanelPrefix + 58)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkColorWidgetID,							kHyperlinkPanelPrefix + 59)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkStyleStaticWidgetID,						kHyperlinkPanelPrefix + 60)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkStyleWidgetID,							kHyperlinkPanelPrefix + 61)
DECLARE_PMID(kWidgetIDSpace, kHyperlinksGenericId,								kHyperlinkPanelPrefix + 62)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkColorDropDownWidgetID,					kHyperlinkPanelPrefix + 63)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkFormatGroupWidgetID,						kHyperlinkPanelPrefix + 64)
DECLARE_PMID(kWidgetIDSpace, kHyperlinksGenericWidgetId,						kHyperlinkPanelPrefix + 65)
DECLARE_PMID(kWidgetIDSpace, kPDFAppearancePanel1ID,							kHyperlinkPanelPrefix + 66)
DECLARE_PMID(kWidgetIDSpace, kPDFAppearancePanel2ID,							kHyperlinkPanelPrefix + 67)
DECLARE_PMID(kWidgetIDSpace, kPDFAppearancePanel3ID,							kHyperlinkPanelPrefix + 68)
DECLARE_PMID(kWidgetIDSpace, kPDFAppearancePanel4ID,							kHyperlinkPanelPrefix + 69)
DECLARE_PMID(kWidgetIDSpace, kFormatGroupStaticWidgetID,						kHyperlinkPanelPrefix + 70)
//gap
DECLARE_PMID(kWidgetIDSpace, kXRefFormatStaticWidgetID,							kHyperlinkPanelPrefix + 72)
//gap
DECLARE_PMID(kWidgetIDSpace, kXRefFormatWidgetID,								kHyperlinkPanelPrefix + 74)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestParentWidgetID,						kHyperlinkPanelPrefix + 75)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkPageNameWidgetID,							kHyperlinkPanelPrefix + 76)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkTextNameWidgetID,							kHyperlinkPanelPrefix + 77)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkURLNameWidgetID,								kHyperlinkPanelPrefix + 78)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestNameStaticWidgetID,						kHyperlinkPanelPrefix + 79)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestinationGroupWidgetID,				kHyperlinkPanelPrefix + 80)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestinationGroupTitleTextWidgetID,		kHyperlinkPanelPrefix + 81)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestinationTypeGroupWidgetID,			kHyperlinkPanelPrefix + 82)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestinationTypeGroupTitleTextWidgetID,	kHyperlinkPanelPrefix + 83)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDestinationTypeClusterWidgetId,			kHyperlinkPanelPrefix + 84)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkPageDestinationTypeRadioWidgetID,		kHyperlinkPanelPrefix + 85)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkAnchorDestinationTypeRadioWidgetID,		kHyperlinkPanelPrefix + 86)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkURLDestinationTypeRadioWidgetID,			kHyperlinkPanelPrefix + 87)
DECLARE_PMID(kWidgetIDSpace, kDestinationTypeGroupWidgetID,							kHyperlinkPanelPrefix + 88)
DECLARE_PMID(kWidgetIDSpace, kAllTypesDestinationDialogWidgetID,					kHyperlinkPanelPrefix + 89)
DECLARE_PMID(kWidgetIDSpace, kDestinationTypeStaticTextWidgetID,					kHyperlinkPanelPrefix + 90)
DECLARE_PMID(kWidgetIDSpace, kDestinationTypePopupWidgetID,							kHyperlinkPanelPrefix + 91)
DECLARE_PMID(kWidgetIDSpace, kDestinationTypePanelWidgetId,							kHyperlinkPanelPrefix + 92)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestPageNumberStaticWidgetID,				kHyperlinkPanelPrefix + 93)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkZoomFactorStaticWidgetID,				kHyperlinkPanelPrefix + 94)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestURLStaticWidgetID,						kHyperlinkPanelPrefix + 95)
DECLARE_PMID(kWidgetIDSpace, kPageDestinationDialogWidgetID,						kHyperlinkPanelPrefix + 96)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationDialogWidgetID,						kHyperlinkPanelPrefix + 97)
DECLARE_PMID(kWidgetIDSpace, kURLDestinationDialogWidgetID,							kHyperlinkPanelPrefix + 98)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestTextCheckBoxWidgetID,					kHyperlinkPanelPrefix + 99)

DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDocumentTextWidgetID,				kHyperlinkPanelPrefix + 100)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkDocumentPopupWidgetID,				kHyperlinkPanelPrefix + 101)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkToPageNumberWidgetID,				kHyperlinkPanelPrefix + 102)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkPageDestinationTypeTextWidgetID,		kHyperlinkPanelPrefix + 103)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkZoomFactorWidgetID,					kHyperlinkPanelPrefix + 104)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkURLWidgetID,							kHyperlinkPanelPrefix + 105)

// IDs for the Edit All Hyperlink Destinations dialog
DECLARE_PMID(kWidgetIDSpace, kEditButton_WidgetID,								kHyperlinkPanelPrefix + 106)
DECLARE_PMID(kWidgetIDSpace, kDeleteButton_WidgetID,							kHyperlinkPanelPrefix + 107)
DECLARE_PMID(kWidgetIDSpace, kDeleteAllButton_WidgetID,							kHyperlinkPanelPrefix + 108)

DECLARE_PMID(kWidgetIDSpace, kPageDestinationPageNumberNudgeWidgetId,			kHyperlinkPanelPrefix + 109)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkPageDestNameStaticWidgetID,				kHyperlinkPanelPrefix + 110)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestAutoNameCheckBoxWidgetID,			kHyperlinkPanelPrefix + 111)
DECLARE_PMID(kWidgetIDSpace, kColorListElementWidgetID,							kHyperlinkPanelPrefix + 112)
DECLARE_PMID(kWidgetIDSpace, kColorElementNameStaticWidgetID,					kHyperlinkPanelPrefix + 113)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel1WidgetID,					kHyperlinkPanelPrefix + 114)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel2WidgetID,					kHyperlinkPanelPrefix + 115)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel3WidgetID,					kHyperlinkPanelPrefix + 116)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel4WidgetID,					kHyperlinkPanelPrefix + 117)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel5WidgetID,					kHyperlinkPanelPrefix + 118)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel6WidgetID,					kHyperlinkPanelPrefix + 119)
//gap
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel8WidgetID,					kHyperlinkPanelPrefix + 121)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAddDestToDocumentCheckboxWidgetID,		kHyperlinkPanelPrefix + 122)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentPageWidgetID,					kHyperlinkPanelPrefix + 123)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentTextPopupWidgetID,				kHyperlinkPanelPrefix + 124)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDocumentPagePopupWidgetID,				kHyperlinkPanelPrefix + 125)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAddDestToDocument2CheckboxWidgetID,		kHyperlinkPanelPrefix + 126)
DECLARE_PMID(kWidgetIDSpace, kEmailDestinationDialogWidgetID,					kHyperlinkPanelPrefix + 127)
DECLARE_PMID(kWidgetIDSpace, kFileDestinationDialogWidgetID,					kHyperlinkPanelPrefix + 128)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel9WidgetID,					kHyperlinkPanelPrefix + 129)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel10WidgetID,					kHyperlinkPanelPrefix + 130)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel11WidgetID,					kHyperlinkPanelPrefix + 131)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel12WidgetID,					kHyperlinkPanelPrefix + 132)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestEmailAddressStaticWidgetID,			kHyperlinkPanelPrefix + 133)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestSubjectStaticWidgetID,				kHyperlinkPanelPrefix + 134)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkEmailAddressWidgetID,				kHyperlinkPanelPrefix + 135)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkSubjectWidgetID,						kHyperlinkPanelPrefix + 136)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAddDestToDocument3CheckboxWidgetID,		kHyperlinkPanelPrefix + 137)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkAddDestToDocument4CheckboxWidgetID,		kHyperlinkPanelPrefix + 138)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkFilePathWidgetID,					kHyperlinkPanelPrefix + 139)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestFilePathStaticWidgetID,				kHyperlinkPanelPrefix + 140)
DECLARE_PMID(kWidgetIDSpace, kSpacer4WidgetID,									kHyperlinkPanelPrefix + 141)
DECLARE_PMID(kWidgetIDSpace, kNamedDestinationDialogWidgetID,					kHyperlinkPanelPrefix + 142)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel13WidgetID,					kHyperlinkPanelPrefix + 143)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel14WidgetID,					kHyperlinkPanelPrefix + 144)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestTypeStaticWidgetID,					kHyperlinkPanelPrefix + 145)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkDestValueStaticWidgetID,					kHyperlinkPanelPrefix + 146)
DECLARE_PMID(kWidgetIDSpace, kBrowseButtonWidgetID,								kHyperlinkPanelPrefix + 147)
DECLARE_PMID(kWidgetIDSpace, kParagraphDestinationDialogWidgetID,				kHyperlinkPanelPrefix + 148)
//gap
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel16WidgetID,					kHyperlinkPanelPrefix + 150)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel17WidgetID,					kHyperlinkPanelPrefix + 151)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatPopupWidgetID,							kHyperlinkPanelPrefix + 152)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatsDialogWidgetID,					kHyperlinkPanelPrefix + 154)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatsPanelID,							kHyperlinkPanelPrefix + 155)
DECLARE_PMID(kWidgetIDSpace, kSaveXRefFormatsButtonWidgetId,					kHyperlinkPanelPrefix + 156)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatsButtonsAreaPanelID,					kHyperlinkPanelPrefix + 157)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel1WidgetID,					kHyperlinkPanelPrefix + 158)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel2WidgetID,					kHyperlinkPanelPrefix + 159)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel3WidgetID,					kHyperlinkPanelPrefix + 160)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel4WidgetID,					kHyperlinkPanelPrefix + 161)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel5WidgetID,					kHyperlinkPanelPrefix + 162)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel6WidgetID,					kHyperlinkPanelPrefix + 163)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel7WidgetID,					kHyperlinkPanelPrefix + 164)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel8WidgetID,					kHyperlinkPanelPrefix + 165)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel9WidgetID,					kHyperlinkPanelPrefix + 166)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel10WidgetID,					kHyperlinkPanelPrefix + 167)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel11WidgetID,					kHyperlinkPanelPrefix + 168)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel12WidgetID,					kHyperlinkPanelPrefix + 169)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel13WidgetID,					kHyperlinkPanelPrefix + 170)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatsListWidgetID,							kHyperlinkPanelPrefix + 171)
DECLARE_PMID(kWidgetIDSpace, kAddXRefFormatWidgetID,							kHyperlinkPanelPrefix + 172)
DECLARE_PMID(kWidgetIDSpace, kRemoveXRefFormatWidgetID,							kHyperlinkPanelPrefix + 173)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatNameStaticWidgetID,						kHyperlinkPanelPrefix + 174)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatNameWidgetID,							kHyperlinkPanelPrefix + 175)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatDefinitionStaticWidgetID,				kHyperlinkPanelPrefix + 176)
DECLARE_PMID(kWidgetIDSpace, kXRefFormatDefinitionWidgetID,						kHyperlinkPanelPrefix + 177)
DECLARE_PMID(kWidgetIDSpace, kXRefInsertBlockWidgetID,							kHyperlinkPanelPrefix + 178)
DECLARE_PMID(kWidgetIDSpace, kXRefInsertSpecialWidgetID,						kHyperlinkPanelPrefix + 179)
DECLARE_PMID(kWidgetIDSpace, kEnableCharacterStylesWidgetID,					kHyperlinkPanelPrefix + 180)
DECLARE_PMID(kWidgetIDSpace, kXRefCharacterStyleWidgetID,						kHyperlinkPanelPrefix + 181)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanel1WidgetID,						kHyperlinkPanelPrefix + 182)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanel2WidgetID,						kHyperlinkPanelPrefix + 183)
//gap
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanel4WidgetID,						kHyperlinkPanelPrefix + 185)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListLabel1WidgetID,						kHyperlinkPanelPrefix + 186)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListLabel2WidgetID,						kHyperlinkPanelPrefix + 187)
//gap
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListLabel4WidgetID,						kHyperlinkPanelPrefix + 189)
DECLARE_PMID(kWidgetIDSpace, kFormatWarningWidgetID,							kHyperlinkPanelPrefix + 190)
DECLARE_PMID(kWidgetIDSpace, kFormatWarningStaticWidgetID,						kHyperlinkPanelPrefix + 191)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel14WidgetID,					kHyperlinkPanelPrefix + 192)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatPanel15WidgetID,					kHyperlinkPanelPrefix + 193)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkUpdateXrefsButtonWidgetID,				kHyperlinkPanelPrefix + 194)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNewXRefButtonWidgetID,					kHyperlinkPanelPrefix + 195)
DECLARE_PMID(kWidgetIDSpace, kEnableHyperlinkCharacterStylesWidgetID,			kHyperlinkPanelPrefix + 196)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkLargeURLStaticWidgetID,					kHyperlinkPanelPrefix + 197)
DECLARE_PMID(kWidgetIDSpace, kEditHyperlinkLargeURLEditBoxWidgetID,				kHyperlinkPanelPrefix + 198)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanel5WidgetID,						kHyperlinkPanelPrefix + 199)
//gap
DECLARE_PMID(kWidgetIDSpace, kHyperlinkListPanel6WidgetID,						kHyperlinkPanelPrefix + 202)
DECLARE_PMID(kWidgetIDSpace, kDefineXRefFormatsWidgetID,						kHyperlinkPanelPrefix + 203)
DECLARE_PMID(kWidgetIDSpace, kDialogGroupPanelWidget2ID,						kHyperlinkPanelPrefix + 204)
DECLARE_PMID(kWidgetIDSpace, kTextDestPanel1ID,									kHyperlinkPanelPrefix + 205)
DECLARE_PMID(kWidgetIDSpace, kTextDestPanel2ID,									kHyperlinkPanelPrefix + 206)
DECLARE_PMID(kWidgetIDSpace, kPageDestPanel1ID,									kHyperlinkPanelPrefix + 207)
DECLARE_PMID(kWidgetIDSpace, kPageDestPanel2ID,									kHyperlinkPanelPrefix + 208)
DECLARE_PMID(kWidgetIDSpace, kURLDestPanel1ID,									kHyperlinkPanelPrefix + 209)
DECLARE_PMID(kWidgetIDSpace, kURLDestPanel2ID,									kHyperlinkPanelPrefix + 210)
DECLARE_PMID(kWidgetIDSpace, kPageNumNudgeHolder,								kHyperlinkPanelPrefix + 211)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkPageDestFillerStaticWidgetID,			kHyperlinkPanelPrefix + 212)
DECLARE_PMID(kWidgetIDSpace, kRenameHyperlinkDialogWidgetID,					kHyperlinkPanelPrefix + 213)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameLabelWidgetID,						kHyperlinkPanelPrefix + 214)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameTextWidgetID,						kHyperlinkPanelPrefix + 215)
DECLARE_PMID(kWidgetIDSpace, kHyperlinksColumnHeaderWidgetID,					kHyperlinkPanelPrefix + 216)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkUpdateStatusButtonWidgetID,				kHyperlinkPanelPrefix + 217)
DECLARE_PMID(kWidgetIDSpace, kHyperlinkNameILEWidgetID,							kHyperlinkPanelPrefix + 218)
DECLARE_PMID(kWidgetIDSpace, kXRefDeleteButtonWidgetID,							kHyperlinkPanelPrefix + 219)
DECLARE_PMID(kWidgetIDSpace, kXRefBorderWidgetID,								kHyperlinkPanelPrefix + 220)
DECLARE_PMID(kWidgetIDSpace, kXRefSerachPanelWidgetId,							kHyperlinkPanelPrefix + 221)
DECLARE_PMID(kWidgetIDSpace, kXRefTextListSearchWidgetID,						kHyperlinkPanelPrefix + 222)
DECLARE_PMID(kWidgetIDSpace, kParagraphStyleListTextWidgetID,					kHyperlinkPanelPrefix + 223)
DECLARE_PMID(kWidgetIDSpace, kParagraphTextListTextWidgetID,					kHyperlinkPanelPrefix + 224)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel18WidgetID,					kHyperlinkPanelPrefix + 225)
DECLARE_PMID(kWidgetIDSpace, kTextDestinationPanel19WidgetID,					kHyperlinkPanelPrefix + 226)

// <Service ID>
// ---------------------------------------------------------------
//  Services
// ---------------------------------------------------------------
DECLARE_PMID(kServiceIDSpace, kEditDestinationDialogServiceImpl, kHyperlinkPanelPrefix  + 1)
DECLARE_PMID(kServiceIDSpace, kApplyDestinationDialogServiceImpl, kHyperlinkPanelPrefix  + 2)
DECLARE_PMID(kServiceIDSpace, kApplyXrefDestinationDialogServiceImpl, kHyperlinkPanelPrefix  + 3)


// <Action ID>
//========================================================================================
// ----- Action IDs -----
//========================================================================================
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelActionID,					kHyperlinkPanelPrefix + 1)
DECLARE_PMID(kActionIDSpace, kNewHyperlinkActionID,						kHyperlinkPanelPrefix + 2)
DECLARE_PMID(kActionIDSpace, kDeleteHyperlinkActionID,					kHyperlinkPanelPrefix + 3)
DECLARE_PMID(kActionIDSpace, kResetHyperlinkSourceActionID,				kHyperlinkPanelPrefix + 4)
DECLARE_PMID(kActionIDSpace, kEditAllHyperlinkDestinationsActionID,		kHyperlinkPanelPrefix + 5)
DECLARE_PMID(kActionIDSpace, kNewHyperlinkDestinationActionID,			kHyperlinkPanelPrefix + 6)
DECLARE_PMID(kActionIDSpace, kGoToHyperlinkDestinationActionID,			kHyperlinkPanelPrefix + 7)
DECLARE_PMID(kActionIDSpace, kGoToHyperlinkSourceActionID,				kHyperlinkPanelPrefix + 8)
DECLARE_PMID(kActionIDSpace, kHyperlinkSmallPaletteRowsActionID,		kHyperlinkPanelPrefix + 9)
DECLARE_PMID(kActionIDSpace, kEditHyperlinkActionID,					kHyperlinkPanelPrefix + 10)
DECLARE_PMID(kActionIDSpace, kCreateLinkFromSelectionActionID,			kHyperlinkPanelPrefix + 11)
DECLARE_PMID(kActionIDSpace, kShowHyperlinksActionID,					kHyperlinkPanelPrefix + 12)
DECLARE_PMID(kActionIDSpace, kUpdateHyperlinkDestinationInfoActionID,	kHyperlinkPanelPrefix + 13)
DECLARE_PMID(kActionIDSpace, kHyperlinkSortManuallyActionID,			kHyperlinkPanelPrefix + 14)
DECLARE_PMID(kActionIDSpace, kHyperlinkSortByNameActionID,				kHyperlinkPanelPrefix + 15)
DECLARE_PMID(kActionIDSpace, kHyperlinkSortByTypeActionID,				kHyperlinkPanelPrefix + 16)
DECLARE_PMID(kActionIDSpace, kNewXRefActionID,							kHyperlinkPanelPrefix + 17)
DECLARE_PMID(kActionIDSpace, kEditXRefActionID,							kHyperlinkPanelPrefix + 18)
DECLARE_PMID(kActionIDSpace, kDefineXRefFormatsActionID,				kHyperlinkPanelPrefix + 19)
DECLARE_PMID(kActionIDSpace, kEditXRefFormatActionID,					kHyperlinkPanelPrefix + 20)
DECLARE_PMID(kActionIDSpace, kCreateXRefFormatActionID,					kHyperlinkPanelPrefix + 21)
DECLARE_PMID(kActionIDSpace, kXRefPanelActionID,						kHyperlinkPanelPrefix + 22)
DECLARE_PMID(kActionIDSpace, kUpdateXRefActionID,						kHyperlinkPanelPrefix + 23)
DECLARE_PMID(kActionIDSpace, kRelinkXRefActionID,						kHyperlinkPanelPrefix + 24)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep1ActionID,				kHyperlinkPanelPrefix + 25)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep2ActionID,				kHyperlinkPanelPrefix + 26)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep3ActionID,				kHyperlinkPanelPrefix + 27)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep4ActionID,				kHyperlinkPanelPrefix + 28)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep5ActionID,				kHyperlinkPanelPrefix + 29)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep6ActionID,				kHyperlinkPanelPrefix + 30)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep7ActionID,				kHyperlinkPanelPrefix + 31)
DECLARE_PMID(kActionIDSpace, kLoadXRefFormatsActionID,					kHyperlinkPanelPrefix + 32)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugPageNumberActionID,			kHyperlinkPanelPrefix + 33)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugParagraphNumberActionID,	kHyperlinkPanelPrefix + 34)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugParagraphTextActionID,		kHyperlinkPanelPrefix + 35)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugFullParagraphActionID,		kHyperlinkPanelPrefix + 36)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugPartialParagraphActionID,	kHyperlinkPanelPrefix + 37)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugBookmarkNameActionID,		kHyperlinkPanelPrefix + 38)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugChapterNumberActionID,		kHyperlinkPanelPrefix + 39)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugFileNameActionID,			kHyperlinkPanelPrefix + 40)
DECLARE_PMID(kActionIDSpace, kXRefFormatSlugCharacterStyleActionID,		kHyperlinkPanelPrefix + 41)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaEmDashActionID,				kHyperlinkPanelPrefix + 42)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaEnDashActionID,				kHyperlinkPanelPrefix + 43)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSep1ActionID,				kHyperlinkPanelPrefix + 44)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaMSpaceActionID,				kHyperlinkPanelPrefix + 45)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaNSpaceActionID,				kHyperlinkPanelPrefix + 46)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaHairSpaceActionID,			kHyperlinkPanelPrefix + 47)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSixthSpaceActionID,			kHyperlinkPanelPrefix + 48)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaThinSpaceActionID,			kHyperlinkPanelPrefix + 49)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaQuarterSpaceActionID,		kHyperlinkPanelPrefix + 50)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaThirdSpaceActionID,			kHyperlinkPanelPrefix + 51)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaPunctuationSpaceActionID,	kHyperlinkPanelPrefix + 52)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaFigureSpaceActionID,		kHyperlinkPanelPrefix + 53)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaFlushSpaceActionID,			kHyperlinkPanelPrefix + 54)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSep2ActionID,				kHyperlinkPanelPrefix + 55)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaNonBreakActionID,			kHyperlinkPanelPrefix + 56)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaNonBreakFixedActionID,		kHyperlinkPanelPrefix + 57)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaNonBreakHyphActionID,		kHyperlinkPanelPrefix + 58)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSep3ActionID,				kHyperlinkPanelPrefix + 59)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaDoubleLeftActionID,			kHyperlinkPanelPrefix + 60)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaDoubleRightActionID,		kHyperlinkPanelPrefix + 61)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSingleActionID,				kHyperlinkPanelPrefix + 62)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSingleLeftActionID,			kHyperlinkPanelPrefix + 63)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSep4ActionID,				kHyperlinkPanelPrefix + 64)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaBulletActionID,				kHyperlinkPanelPrefix + 65)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaParaActionID,				kHyperlinkPanelPrefix + 66)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSectionActionID,			kHyperlinkPanelPrefix + 67)
DECLARE_PMID(kActionIDSpace, kPasteXRefActionID,						kHyperlinkPanelPrefix + 68)
DECLARE_PMID(kActionIDSpace, kHLSep1ActionID,							kHyperlinkPanelPrefix + 69)
DECLARE_PMID(kActionIDSpace, kHLSep2ActionID,							kHyperlinkPanelPrefix + 70)
DECLARE_PMID(kActionIDSpace, kUpdateAllXRefsBookPopupMenuActionID,		kHyperlinkPanelPrefix + 71)
DECLARE_PMID(kActionIDSpace, kShowXRefPanelActionID,					kHyperlinkPanelPrefix + 72)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaSep5ActionID,				kHyperlinkPanelPrefix + 73)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaTabActionID,				kHyperlinkPanelPrefix + 74)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaForcedBreakActionID,		kHyperlinkPanelPrefix + 75)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaEndNestedActionID,			kHyperlinkPanelPrefix + 76)
DECLARE_PMID(kActionIDSpace, kHyperlinkPanelSep8ActionID,				kHyperlinkPanelPrefix + 77)
DECLARE_PMID(kActionIDSpace, kXRefFormatMetaNonJoinerActionID,			kHyperlinkPanelPrefix + 78)
DECLARE_PMID(kActionIDSpace, kRenameHyperlinkActionID,					kHyperlinkPanelPrefix + 79)
DECLARE_PMID(kActionIDSpace, kDeleteXRefActionID,						kHyperlinkPanelPrefix + 80)
DECLARE_PMID(kActionIDSpace, kHyperlinkAutoUpdateURLsActionID,			kHyperlinkPanelPrefix + 81)
DECLARE_PMID(kActionIDSpace, kDeleteUnusedDestinationsActionID,			kHyperlinkPanelPrefix + 82)
DECLARE_PMID(kActionIDSpace, kGoToCrossReferenceDestinationActionID,	kHyperlinkPanelPrefix + 83)
DECLARE_PMID(kActionIDSpace, kGoToCrossReferenceSourceActionID,			kHyperlinkPanelPrefix + 84)
DECLARE_PMID(kActionIDSpace, kDeleteHyperlinkFromPropsPanelActionID,    kHyperlinkPanelPrefix + 85)

DECLARE_PMID(kMessageIDSpace, kNilMessageID,							kHyperlinkPanelPrefix + 1)
DECLARE_PMID(kMessageIDSpace, kTypingInURLEditBoxMessage,				kHyperlinkPanelPrefix + 2)

DECLARE_PMID(kErrorIDSpace, kHyperlinkDeleteUnusedDestinationWarning,	kHyperlinkPanelPrefix + 1) 

#endif // __HyperlinkPanelID__

