//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/tables/TabStyUIID.h $
//  
//  Owner: stanley
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

#ifndef __TabStyUIID_h__
#define __TabStyUIID_h__

// Plug-in:
#define kTabStyUIPluginName	"TableStylesUI"			// Name of this plug-in.

// This was registered
#define kTabStyUIPrefixNumber_Obsolete	0xe1500
#define kTabStyUIPrefixNumber	0x20400 		// Unique prefix number for this plug-in.

#define kTabStyUIPrefixNumber2	0x1ff00			// Second prefix ID for our widgets

// Plug-in Prefix: (please change kTabStyUIPrefixNumber above to modify the prefix.)
#define kTabStyUIPrefix_Obsolete		RezLong(kTabStyUIPrefixNumber_Obsolete)				
#define kTabStyUIPrefix		RezLong(kTabStyUIPrefixNumber)				// The unique numeric prefix for all object model IDs for this plug-in.
#define kTabStyUIPrefix2	RezLong(kTabStyUIPrefixNumber2)

// PluginID:
DECLARE_PMID(kPlugInIDSpace, kTabStyUIPluginID_Obsolete, kTabStyUIPrefix_Obsolete + 0)
DECLARE_PMID(kPlugInIDSpace, kTabStyUIPluginID, kTabStyUIPrefix + 0)

// ClassIDs:
DECLARE_PMID(kClassIDSpace, kTablesDDTargetCellStyleHelperBoss,         kTabStyUIPrefix + 0)
DECLARE_PMID(kClassIDSpace, kRegionalCellStyleStaticTextBoss,           kTabStyUIPrefix + 1)
DECLARE_PMID(kClassIDSpace, kCellStyleActionComponentBoss,              kTabStyUIPrefix + 2)
DECLARE_PMID(kClassIDSpace, kTableStyleActionComponentBoss,             kTabStyUIPrefix + 3)
DECLARE_PMID(kClassIDSpace, kTableStyleTreeViewBoss,                    kTabStyUIPrefix + 4)
DECLARE_PMID(kClassIDSpace, kCellStyleTreeViewBoss,                     kTabStyUIPrefix + 5)
DECLARE_PMID(kClassIDSpace, kTableStyleQuickApplyServiceBoss,           kTabStyUIPrefix + 6)
DECLARE_PMID(kClassIDSpace, kDeleteTableStyleDialogBoss,                kTabStyUIPrefix + 7)
DECLARE_PMID(kClassIDSpace, kCellShortCutIconBoss,                      kTabStyUIPrefix + 8)
DECLARE_PMID(kClassIDSpace, kTableShortCutIconBoss,                     kTabStyUIPrefix + 9)
DECLARE_PMID(kClassIDSpace, kTableStyleContextMenuActionComponentBoss,  kTabStyUIPrefix + 10)
DECLARE_PMID(kClassIDSpace, kCellStyleListDEHandlerBoss,                kTabStyUIPrefix + 11)
DECLARE_PMID(kClassIDSpace, kTableStyleListDEHandlerBoss,               kTabStyUIPrefix + 12)
DECLARE_PMID(kClassIDSpace, kTableStyleListElementBoss,                 kTabStyUIPrefix + 13)
DECLARE_PMID(kClassIDSpace, kCellStyleListElementBoss,                  kTabStyUIPrefix + 14)
DECLARE_PMID(kClassIDSpace, kNewCellStyleGroupButtonBoss,               kTabStyUIPrefix + 15)
DECLARE_PMID(kClassIDSpace, kCellStylePanelBoss,                        kTabStyUIPrefix + 16)
DECLARE_PMID(kClassIDSpace, kDeleteCellStyleButtonBoss,                 kTabStyUIPrefix + 17)
DECLARE_PMID(kClassIDSpace, kDeleteTableStyleButtonBoss,                kTabStyUIPrefix + 18)
DECLARE_PMID(kClassIDSpace, kLayoutDDTargetCellStyleHelperBoss,         kTabStyUIPrefix + 19)
DECLARE_PMID(kClassIDSpace, kNewTableStyleGroupButtonBoss,              kTabStyUIPrefix + 20)
DECLARE_PMID(kClassIDSpace, kNewTableStyleButtonBoss,                   kTabStyUIPrefix + 21)
DECLARE_PMID(kClassIDSpace, kNewCellStyleButtonBoss,                    kTabStyUIPrefix + 22)
DECLARE_PMID(kClassIDSpace, kCellStyleDDListBoss,                       kTabStyUIPrefix + 23)
DECLARE_PMID(kClassIDSpace, kTableStyleDDListBoss,                      kTabStyUIPrefix + 24)
DECLARE_PMID(kClassIDSpace, kAppliedTableStyleStaticTextBoss,           kTabStyUIPrefix + 25)
DECLARE_PMID(kClassIDSpace, kAppliedCellStyleStaticTextBoss,            kTabStyUIPrefix + 26)
DECLARE_PMID(kClassIDSpace, kTableStylePanelBoss,                       kTabStyUIPrefix + 27)
DECLARE_PMID(kClassIDSpace, kLayoutDDTargetTableStyleHelperBoss,        kTabStyUIPrefix + 28)
DECLARE_PMID(kClassIDSpace, kEditableCellStyleNameWidgetBoss,           kTabStyUIPrefix + 29)
DECLARE_PMID(kClassIDSpace, kTableStyleViewBoss,                        kTabStyUIPrefix + 30)
DECLARE_PMID(kClassIDSpace, kCellStyleViewBoss,                         kTabStyUIPrefix + 31)
DECLARE_PMID(kClassIDSpace, kTableStyleControlStripRegisterBoss,        kTabStyUIPrefix + 32)
DECLARE_PMID(kClassIDSpace, kCellStyleContextMenuActionComponentBoss,   kTabStyUIPrefix + 33)
DECLARE_PMID(kClassIDSpace, kTableStyleControlSetBoss,                  kTabStyUIPrefix + 34)
DECLARE_PMID(kClassIDSpace, kLoadTableStyleDialogBoss,                  kTabStyUIPrefix + 35)
DECLARE_PMID(kClassIDSpace, kLoadTableStyleListElementWidgetBoss,       kTabStyUIPrefix + 36)
DECLARE_PMID(kClassIDSpace, kEditableTableStyleNameWidgetBoss,          kTabStyUIPrefix + 37)
DECLARE_PMID(kClassIDSpace, kTabStyUIQuickApplyActionComponentBoss,     kTabStyUIPrefix + 38)
DECLARE_PMID(kClassIDSpace, kCellStyleIconButtonBoss,					kTabStyUIPrefix + 39)
DECLARE_PMID(kClassIDSpace, kTableStyleIconButtonBoss,					kTabStyUIPrefix + 40)
DECLARE_PMID(kClassIDSpace, kTablesDDTargetTableStyleHelperBoss,        kTabStyUIPrefix + 41)
DECLARE_PMID(kClassIDSpace, kTabStyUIStyleShortCutObserverBoss,         kTabStyUIPrefix + 42)
DECLARE_PMID(kClassIDSpace, kTableStyleBasedOnObserverBoss,				kTabStyUIPrefix + 43)
DECLARE_PMID(kClassIDSpace, kCellStyleParaStyleObserverBoss,			kTabStyUIPrefix + 44)
DECLARE_PMID(kClassIDSpace, kRegionalCellStyleObserverBoss,				kTabStyUIPrefix + 45)
DECLARE_PMID(kClassIDSpace, kTableStyleNameObserverBoss,				kTabStyUIPrefix + 46)
DECLARE_PMID(kClassIDSpace, kTableImportedTypeIconBoss,					kTabStyUIPrefix + 47)
DECLARE_PMID(kClassIDSpace, kCellImportedTypeIconBoss,					kTabStyUIPrefix + 48)
DECLARE_PMID(kClassIDSpace, kTableStyleGroupQuickApplyServiceBoss,		kTabStyUIPrefix + 49)
DECLARE_PMID(kClassIDSpace, kCellStyleStrokeSelectionBoss,				kTabStyUIPrefix + 50)
DECLARE_PMID(kClassIDSpace, kCellStyleSelectableDialogBoss,				kTabStyUIPrefix + 51)
DECLARE_PMID(kClassIDSpace, kCellStyleGeneralPanelBoss,					kTabStyUIPrefix + 52)
DECLARE_PMID(kClassIDSpace, kCellStyleTextPanelBoss,					kTabStyUIPrefix + 53)
DECLARE_PMID(kClassIDSpace, kCellStyleStrokeFillPanelBoss,				kTabStyUIPrefix + 54)
DECLARE_PMID(kClassIDSpace, kCellStyleDiagLinesPanelBoss,				kTabStyUIPrefix + 55)
DECLARE_PMID(kClassIDSpace, kCellStyleGraphicPanelBoss,					kTabStyUIPrefix + 56)
//gap
DECLARE_PMID(kClassIDSpace, kTableStyleSelectableDialogBoss,			kTabStyUIPrefix + 61)
DECLARE_PMID(kClassIDSpace, kTableStyleGeneralPanelBoss,				kTabStyUIPrefix + 62)
DECLARE_PMID(kClassIDSpace, kTableStyleSetupPanelBoss,					kTabStyUIPrefix + 63)
DECLARE_PMID(kClassIDSpace, kTableStyleAltFillPanelBoss,				kTabStyUIPrefix + 64)
DECLARE_PMID(kClassIDSpace, kTableStyleAltColStrokePanelBoss,			kTabStyUIPrefix + 65)
DECLARE_PMID(kClassIDSpace, kTableStyleAltRowStrokePanelBoss,			kTabStyUIPrefix + 66)
//gap
DECLARE_PMID(kClassIDSpace, kCellStyleDiagLinePushButtonWidgetBoss,		kTabStyUIPrefix + 68)

// InterfaceIDs:
DECLARE_PMID(kInterfaceIDSpace, IID_ICONTROLSTRIPTABLESTABLETYLESUITE,  kTabStyUIPrefix + 0)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLESTYLECONTROLSTRIPSTYLESUITE,  kTabStyUIPrefix + 1)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUITABLESTYEDIALOGOBSERVER,   kTabStyUIPrefix + 2)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUICELLSTYEDIALOGOBSERVER,    kTabStyUIPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLESTYLEPANELWIDGETOBSERVER,     kTabStyUIPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLESTYLESUIFACADE,				kTabStyUIPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_IUSEBODYCLASSIDDATA,				kTabStyUIPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_IAPPLIEDCELLSTYLEWIDGETBOOLDATA,	kTabStyUIPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_IAPPLIEDTABLESTYLEWIDGETBOOLDATA,	kTabStyUIPrefix + 8)

DECLARE_PMID(kInterfaceIDSpace, IID_ITABLETARGETSERVER,					kTabStyUIPrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLETARGETOBSERVER,				kTabStyUIPrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_ISAVEDTABLEATTRIBUTES,				kTabStyUIPrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_ISAVEDSTYLEINFO2,					kTabStyUIPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLETARGETATTRIBUTES,				kTabStyUIPrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_IATTRIBUTECHANGEMSG,				kTabStyUIPrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_ITABLESTYLESDLGUTILS,				kTabStyUIPrefix + 17)

//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 18)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 19)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 20)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 21)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 22)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 23)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 24)
//DECLARE_PMID(kInterfaceIDSpace, IID_ITABSTYUIINTERFACE, kTabStyUIPrefix + 25)


// ImplementationIDs:
DECLARE_PMID(kImplementationIDSpace, kTableStyleControlStripRegisterImpl,       kTabStyUIPrefix + 0)
DECLARE_PMID(kImplementationIDSpace, kCellStyleDDListObserverImpl,              kTabStyUIPrefix + 1 )
DECLARE_PMID(kImplementationIDSpace, kTableStyleDDListObserverImpl,             kTabStyUIPrefix + 2 )
DECLARE_PMID(kImplementationIDSpace, kCellStyleContextMenuActionComponentImpl,  kTabStyUIPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kCellStylesPanelObserverImpl,              kTabStyUIPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kCellStyleNameInLineEditObserverImpl,      kTabStyUIPrefix + 5)
DECLARE_PMID(kImplementationIDSpace, kTabStyUILoadStyleDialogObserverImpl,      kTabStyUIPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kTableStyleContextMenuActionComponentImpl, kTabStyUIPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kTableStyleControlStripSuiteImpl,          kTabStyUIPrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kTableStylesUIFacadeImpl,					kTabStyUIPrefix + 9)
DECLARE_PMID(kImplementationIDSpace, kTableStyleActionComponentImpl,            kTabStyUIPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kCellStyleActionComponentImpl,             kTabStyUIPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTreeViewAdapterImpl,             kTabStyUIPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kTableStyleTreeViewAdapterImpl,            kTabStyUIPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTreeViewWidgetMgrImpl,           kTabStyUIPrefix + 14)
DECLARE_PMID(kImplementationIDSpace, kTableStyleTreeViewWidgetMgrImpl,          kTabStyUIPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kTableStyleShortCutViewImpl,               kTabStyUIPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kTableCellLoadStyleDialogControllerImpl,   kTabStyUIPrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kTableStyleTreeViewTypeAheadImpl,          kTabStyUIPrefix + 18)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTreeViewTypeAheadImpl,           kTabStyUIPrefix + 19)
DECLARE_PMID(kImplementationIDSpace, kNextTableStyleDDTargetImpl,               kTabStyUIPrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kNextCellStyleDDTargetImpl,                kTabStyUIPrefix + 21)
DECLARE_PMID(kImplementationIDSpace, kLayoutDDTargetTableStyleFlavorHelperImpl, kTabStyUIPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kTableCellLoadStyleDialogObserverImpl,     kTabStyUIPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kDeleteTableStyleDialogControllerImpl,     kTabStyUIPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kDeleteTableStyleDialogObserverImpl,       kTabStyUIPrefix + 25)
DECLARE_PMID(kImplementationIDSpace, kTabStyUIStyleNameTextValidationImpl,      kTabStyUIPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kTableStyleQuickApplyServiceImpl,          kTabStyUIPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kTabStyUIQuickApplyActionComponentImpl,    kTabStyUIPrefix + 28)
DECLARE_PMID(kImplementationIDSpace, kLayoutDDTargetCellStyleFlavorHelperImpl,  kTabStyUIPrefix + 29)
DECLARE_PMID(kImplementationIDSpace, kIntoTableStyleDDTargetImpl,               kTabStyUIPrefix + 30)
DECLARE_PMID(kImplementationIDSpace, kIntoCellStyleDDTargetImpl,                kTabStyUIPrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kNewButtonCellDragDropTargetImpl,          kTabStyUIPrefix + 32)
DECLARE_PMID(kImplementationIDSpace, kNewButtonTableDragDropTargetImpl,         kTabStyUIPrefix + 33)
DECLARE_PMID(kImplementationIDSpace, kNewCellStyleGroupButtonDragDropTargetImpl, kTabStyUIPrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kNewTableStyleGroupButtonDragDropTargetImpl, kTabStyUIPrefix + 35)
DECLARE_PMID(kImplementationIDSpace, kTablesDDTargetCellStyleFlavorHelperImpl,  kTabStyUIPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kTablesDDTargetTableStyleFlavorHelperImpl, kTabStyUIPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kDeleteButtonTableDragDropTargetImpl,      kTabStyUIPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kDeleteButtonCellDragDropTargetImpl,       kTabStyUIPrefix + 39)
DECLARE_PMID(kImplementationIDSpace, kTableStylesPanelObserverImpl,             kTabStyUIPrefix + 40)
DECLARE_PMID(kImplementationIDSpace, kTableStyleNameInLineEditObserverImpl,     kTabStyUIPrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kTableStyleListElementEHImpl,              kTabStyUIPrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kCellStyleListElementEHImpl,               kTabStyUIPrefix + 43)
DECLARE_PMID(kImplementationIDSpace, kTableStyleOverridesToolTipImpl,           kTabStyUIPrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kCellStyleOverridesToolTipImpl,            kTabStyUIPrefix + 45)
DECLARE_PMID(kImplementationIDSpace, kCellStyleListDragDropSourceImpl,          kTabStyUIPrefix + 46)
DECLARE_PMID(kImplementationIDSpace, kTableStyleListDragDropSourceImpl,         kTabStyUIPrefix + 47)
DECLARE_PMID(kImplementationIDSpace, kTableStylePanelViewImpl,                  kTabStyUIPrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kTableStyleListDEHandlerImpl,              kTabStyUIPrefix + 49)
DECLARE_PMID(kImplementationIDSpace, kCellStyleListDEHandlerImpl,               kTabStyUIPrefix + 50)
DECLARE_PMID(kImplementationIDSpace, kTableStyleNameILEEditingAttributesImpl,   kTabStyUIPrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kCellStyleNameILEEditingAttributesImpl,    kTabStyUIPrefix + 52)
DECLARE_PMID(kImplementationIDSpace, kTableStyleViewImpl,                       kTabStyUIPrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kCellStyleViewImpl,                        kTabStyUIPrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kCellStyleShortCutViewImpl,                kTabStyUIPrefix + 55)
DECLARE_PMID(kImplementationIDSpace, kCellStyleSelectableDialogControllerImpl,  kTabStyUIPrefix + 56)
DECLARE_PMID(kImplementationIDSpace, kTableStyleSelectableDialogControllerImpl, kTabStyUIPrefix + 57)
DECLARE_PMID(kImplementationIDSpace, kTabStyUIStyleShortCutObserverImpl,        kTabStyUIPrefix + 58)
DECLARE_PMID(kImplementationIDSpace, kTableStyleGroupQuickApplyServiceImpl,        kTabStyUIPrefix + 59)
DECLARE_PMID(kImplementationIDSpace, kTableCellStyleSelectableDialogObserverImpl,    kTabStyUIPrefix + 60)
DECLARE_PMID(kImplementationIDSpace, kTableStyleBasedOnObserverImpl,			kTabStyUIPrefix + 61)
DECLARE_PMID(kImplementationIDSpace, kRegionalCellStyleObserverImpl,			kTabStyUIPrefix + 62)
DECLARE_PMID(kImplementationIDSpace, kCellStyleParaStyleObserverImpl,			kTabStyUIPrefix + 63)
DECLARE_PMID(kImplementationIDSpace, kTableStyleNameObserverImpl,				kTabStyUIPrefix + 64)
DECLARE_PMID(kImplementationIDSpace, kTableStyleNameValidationImpl,				kTabStyUIPrefix + 65)
DECLARE_PMID(kImplementationIDSpace, kTableImportedTypeIconViewImpl,			kTabStyUIPrefix + 66)
DECLARE_PMID(kImplementationIDSpace, kCellImportedTypeIconViewImpl,				kTabStyUIPrefix + 67)
DECLARE_PMID(kImplementationIDSpace, kAppliedTableStyleEHImpl,					kTabStyUIPrefix + 68)
DECLARE_PMID(kImplementationIDSpace, kAppliedCellStyleEHImpl,					kTabStyUIPrefix + 69)
DECLARE_PMID(kImplementationIDSpace, kCellStyleStrokeSelectionWidgetImpl,		kTabStyUIPrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kTableStyleSelectableDialogCreatorImpl,	kTabStyUIPrefix + 71)
DECLARE_PMID(kImplementationIDSpace, kTableStyleSetupPanelCreatorImpl,			kTabStyUIPrefix + 72)
DECLARE_PMID(kImplementationIDSpace, kTableStyleSetupPanelObserverImpl,			kTabStyUIPrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kTableStyleSetupPanelControllerImpl,		kTabStyUIPrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kTableStyleGeneralPanelCreatorImpl,		kTabStyUIPrefix + 75)
DECLARE_PMID(kImplementationIDSpace, kTableStyleGeneralPanelObserverImpl,		kTabStyUIPrefix + 76)
// DECLARE_PMID(kImplementationIDSpace, kTableStyleGeneralPanelControllerImpl,		kTabStyUIPrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltFillPanelCreatorImpl,		kTabStyUIPrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltFillPanelObserverImpl,		kTabStyUIPrefix + 79)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltFillPanelControllerImpl,		kTabStyUIPrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltRowStrokePanelCreatorImpl,	kTabStyUIPrefix + 81)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltColStrokePanelCreatorImpl,	kTabStyUIPrefix + 82)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltStrokePanelControllerImpl,	kTabStyUIPrefix + 83)
DECLARE_PMID(kImplementationIDSpace, kTableStyleAltStrokePanelObserverImpl,		kTabStyUIPrefix + 84)
//gap
DECLARE_PMID(kImplementationIDSpace, kCellStyleSelectableDialogCreatorImpl,		kTabStyUIPrefix + 90)
DECLARE_PMID(kImplementationIDSpace, kTableStyleTargetServerImpl,				kTabStyUIPrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kTableTargetAttributesImpl,				kTabStyUIPrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kStyleInfoImpl2,							kTabStyUIPrefix + 93)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTextPanelCreatorImpl,			kTabStyUIPrefix + 94)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTextPanelObserverImpl,			kTabStyUIPrefix + 95)
DECLARE_PMID(kImplementationIDSpace, kCellStyleStrokeFillPanelCreatorImpl,		kTabStyUIPrefix + 96)
DECLARE_PMID(kImplementationIDSpace, kCellStyleStrokeFillPanelObserverImpl,		kTabStyUIPrefix + 97)
DECLARE_PMID(kImplementationIDSpace, kCellStyleStrokeFillPanelTargetImpl,		kTabStyUIPrefix + 98)
DECLARE_PMID(kImplementationIDSpace, kCellStyleDiagLinesPanelCreatorImpl,		kTabStyUIPrefix + 99)
DECLARE_PMID(kImplementationIDSpace, kCellStyleDiagLinesPanelObserverImpl,		kTabStyUIPrefix + 100)
DECLARE_PMID(kImplementationIDSpace, kCellStyleGeneralPanelCreatorImpl,			kTabStyUIPrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kCellStyleGeneralPanelObserverImpl,		kTabStyUIPrefix + 102)
DECLARE_PMID(kImplementationIDSpace, kCellStyleTriStateControlEHImpl,			kTabStyUIPrefix + 103)
DECLARE_PMID(kImplementationIDSpace, kTableStylesDlgUtilsImpl,					kTabStyUIPrefix + 104)
DECLARE_PMID(kImplementationIDSpace, kTableCellStyleNameInLineEditControllerImpl,kTabStyUIPrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kCellStyleDiagLineButtonViewImpl,			kTabStyUIPrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kCellStyleGraphicPanelCreatorImpl,			kTabStyUIPrefix + 108)
DECLARE_PMID(kImplementationIDSpace, kCellStyleGraphicPanelObserverImpl,		kTabStyUIPrefix + 109)

// ActionIDs:
DECLARE_PMID(kActionIDSpace, kTabStyUINewTableStyleActionID,                    kTabStyUIPrefix + 0)
DECLARE_PMID(kActionIDSpace, kTableStylesPanelActionID,                         kTabStyUIPrefix + 1)
DECLARE_PMID(kActionIDSpace, kTabStyUIDuplicateTableStyleActionID,              kTabStyUIPrefix + 2)
DECLARE_PMID(kActionIDSpace, kTabStyUIPopupAboutThisActionID,                   kTabStyUIPrefix + 3)
DECLARE_PMID(kActionIDSpace, kTabStyUIDeleteTableStyleActionID,                 kTabStyUIPrefix + 4)
DECLARE_PMID(kActionIDSpace, kCellStylesPanelActionID,                          kTabStyUIPrefix + 5)
DECLARE_PMID(kActionIDSpace, kTabStyUIRedefineTableStyleActionID,               kTabStyUIPrefix + 6)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator2ActionID,                       kTabStyUIPrefix + 7)
DECLARE_PMID(kActionIDSpace, kTabStyUITableStyleOptionsActionID,                kTabStyUIPrefix + 8)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator3ActionID,                       kTabStyUIPrefix + 9)
DECLARE_PMID(kActionIDSpace, kTabStyUIClearTableOverridesActionID,              kTabStyUIPrefix + 10)
DECLARE_PMID(kActionIDSpace, kTabStyUIBreakLinkWithTableStyleActionID,          kTabStyUIPrefix + 11)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator4ActionID,                       kTabStyUIPrefix + 12)
DECLARE_PMID(kActionIDSpace, kTabStyUILoadTableStylesActionID,                  kTabStyUIPrefix + 13)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator5ActionID,                       kTabStyUIPrefix + 14)
DECLARE_PMID(kActionIDSpace, kTabStyUISelectAllUnusedTableStylesActionID,       kTabStyUIPrefix + 15)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator6ActionID,                       kTabStyUIPrefix + 16)
DECLARE_PMID(kActionIDSpace, kTabStyUISortTableStylesByNameActionID,            kTabStyUIPrefix + 17)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator7ActionID,                       kTabStyUIPrefix + 18)
DECLARE_PMID(kActionIDSpace, kTabStyUITableStylesSmallPaletteRowsActionID,      kTabStyUIPrefix + 19)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClickEditTableStyleActionID,            kTabStyUIPrefix + 20)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkDuplicateTableStyleActionID,         kTabStyUIPrefix + 21)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkDeleteTableStyleActionID,            kTabStyUIPrefix + 22)
DECLARE_PMID(kActionIDSpace, kTabStyUITableStyleCreateGroupFromStylesActionID,  kTabStyUIPrefix + 23)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkSeparator1ActionID,                  kTabStyUIPrefix + 24)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyTableStyleActionID,             kTabStyUIPrefix + 25)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyTableStyleAndClearOverridesActionID, kTabStyUIPrefix + 26)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator1ActionID,                       kTabStyUIPrefix + 27)
DECLARE_PMID(kActionIDSpace, kTabStyUINewCellStyleActionID,                     kTabStyUIPrefix + 28)
DECLARE_PMID(kActionIDSpace, kTabStyUIDeleteCellStyleActionID,                  kTabStyUIPrefix + 29)
DECLARE_PMID(kActionIDSpace, kTabStyUIRedefineCellStyleActionID,                kTabStyUIPrefix + 30)
DECLARE_PMID(kActionIDSpace, kTabStyUICellStyleOptionsActionID,                 kTabStyUIPrefix + 31)
DECLARE_PMID(kActionIDSpace, kTabStyUIClearCellOverridesActionID,               kTabStyUIPrefix + 32)
DECLARE_PMID(kActionIDSpace, kTabStyUIBreakLinkToCellStyleActionID,             kTabStyUIPrefix + 33)
DECLARE_PMID(kActionIDSpace, kTabStyUILoadCellStylesActionID,                   kTabStyUIPrefix + 34)
DECLARE_PMID(kActionIDSpace, kTabStyUISelectAllUnusedCellStylesActionID,        kTabStyUIPrefix + 35)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyCellStyleAndClearOverridesActionID, kTabStyUIPrefix + 36)
DECLARE_PMID(kActionIDSpace, kTabStyUISortCellStylesByNameActionID,             kTabStyUIPrefix + 37)
DECLARE_PMID(kActionIDSpace, kTabStyUICellStylesSmallPaletteRowsActionID,       kTabStyUIPrefix + 38)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkEditCellStyleActionID,               kTabStyUIPrefix + 39)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkDuplicateCellStyleActionID,          kTabStyUIPrefix + 40)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkDeleteCellStyleActionID,             kTabStyUIPrefix + 41)
DECLARE_PMID(kActionIDSpace, kTabStyUICellStyleCreateGroupFromStylesActionID,   kTabStyUIPrefix + 42)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyCellStyleActionID,              kTabStyUIPrefix + 43)
DECLARE_PMID(kActionIDSpace, kTabStyUIDuplicateCellStyleActionID,               kTabStyUIPrefix + 44)
DECLARE_PMID(kActionIDSpace, kTabStyTableStyleNewStyleGroupActionID,            kTabStyUIPrefix + 45)
DECLARE_PMID(kActionIDSpace, kTabStyCellStyleNewStyleGroupActionID,             kTabStyUIPrefix + 46)
DECLARE_PMID(kActionIDSpace, kTabStyCellStyleOpenAllGroupsActionID,             kTabStyUIPrefix + 47)
DECLARE_PMID(kActionIDSpace, kTabStyTableStyleOpenAllGroupsActionID,            kTabStyUIPrefix + 48)
DECLARE_PMID(kActionIDSpace, kTabStyTableStyleCloseAllGroupsActionID,           kTabStyUIPrefix + 49)
DECLARE_PMID(kActionIDSpace, kTabStyCellStyleCloseAllGroupsActionID,            kTabStyUIPrefix + 50)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator8ActionID,                       kTabStyUIPrefix + 51)
DECLARE_PMID(kActionIDSpace, kTabStyUISeparator9ActionID,                       kTabStyUIPrefix + 52)
DECLARE_PMID(kActionIDSpace, kTabStyUITableStyleCopyToGroupActionID,            kTabStyUIPrefix + 53)
DECLARE_PMID(kActionIDSpace, kTabStyUICellStyleCopyToGroupActionID,             kTabStyUIPrefix + 54)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkRedefineTableStyleActionID,          kTabStyUIPrefix + 55)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkRedefineCellStyleActionID,           kTabStyUIPrefix + 56)
DECLARE_PMID(kActionIDSpace, kQuickApplyTableStylesPrefActionID,                kTabStyUIPrefix + 57)
DECLARE_PMID(kActionIDSpace, kQuickApplyCellStylesPrefActionID,                 kTabStyUIPrefix + 58)
DECLARE_PMID(kActionIDSpace, kCellStylesCopyToGroupActionID,                    kTabStyUIPrefix + 59)
DECLARE_PMID(kActionIDSpace, kTableStylesCopyToGroupActionID,                   kTabStyUIPrefix + 60)
DECLARE_PMID(kActionIDSpace, kTableStylesGroupOptionsActionID,                  kTabStyUIPrefix + 61)
DECLARE_PMID(kActionIDSpace, kCellStylesGroupOptionsActionID,                   kTabStyUIPrefix + 62)
DECLARE_PMID(kActionIDSpace, kTableStylesDuplicateGroupActionID,                kTabStyUIPrefix + 63)
DECLARE_PMID(kActionIDSpace, kCellStylesDuplicateGroupActionID,                 kTabStyUIPrefix + 64)
DECLARE_PMID(kActionIDSpace, kTableStylesDeleteGroupActionID,                   kTabStyUIPrefix + 65)
DECLARE_PMID(kActionIDSpace, kCellStylesDeleteGroupActionID,                    kTabStyUIPrefix + 66)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyTableStyleClearCellStylesActionID, kTabStyUIPrefix + 67)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkApplyTableStyleClearAllActionID,     kTabStyUIPrefix + 68)
DECLARE_PMID(kActionIDSpace, kTabStyUITableLoadAllStylesActionID,               kTabStyUIPrefix + 69)
DECLARE_PMID(kActionIDSpace, kTabStyUICellLoadAllStylesActionID,                kTabStyUIPrefix + 70)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClickNewTableStyleActionID,                kTabStyUIPrefix + 71)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClickNewCellStyleActionID,                kTabStyUIPrefix + 72)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkSeparator2ActionID,					kTabStyUIPrefix + 73)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkSeparator3ActionID,					kTabStyUIPrefix + 74)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkNewGroupFromTableStylesActionID,		kTabStyUIPrefix + 75)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkNewGroupFromCellStylesActionID,		kTabStyUIPrefix + 76)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkTableStylesCopyToGroupActionID,		kTabStyUIPrefix + 77)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkCellStylesCopyToGroupActionID,		kTabStyUIPrefix + 78)
DECLARE_PMID(kActionIDSpace, kQuickApplyTableStyleGroupsPrefActionID,           kTabStyUIPrefix + 79)
DECLARE_PMID(kActionIDSpace, kQuickApplyCellStyleGroupsPrefActionID,            kTabStyUIPrefix + 80)
DECLARE_PMID(kActionIDSpace, kApplyStyleAndClearAllOverridesActionID,            kTabStyUIPrefix + 81)
DECLARE_PMID(kActionIDSpace, kRtClkApplyStyleAndClearAllOverridesActionID,            kTabStyUIPrefix + 82)
DECLARE_PMID(kActionIDSpace, kClearAttributesNotDefinedByCellStyleActionID,            kTabStyUIPrefix + 83)
DECLARE_PMID(kActionIDSpace, kTabStyUIRtClkSeparator4ActionID,            kTabStyUIPrefix + 84)
DECLARE_PMID(kActionIDSpace, kTabStyUINewTableStyleDuringDialogActionID,		kTabStyUIPrefix + 85)
DECLARE_PMID(kActionIDSpace, kTabStyUINewCellStyleDuringDialogActionID,			kTabStyUIPrefix + 86)



// WidgetIDs:
DECLARE_PMID(kWidgetIDSpace, kTabStyUITableStylePanelWidgetID,                  kTabStyUIPrefix + 0)
DECLARE_PMID(kWidgetIDSpace, kTabStyUITableQuickApplyBttnWidgetID,              kTabStyUIPrefix + 1)
DECLARE_PMID(kWidgetIDSpace, kTableStyleListParentWidgetID,                     kTabStyUIPrefix + 2)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIDeleteStyleDialogWidgetID,                kTabStyUIPrefix + 3)
DECLARE_PMID(kWidgetIDSpace, kTabStyDeleteStyleWarningIconWidgetID,             kTabStyUIPrefix + 4)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIReplaceWithStyleLabelWidgetID,            kTabStyUIPrefix + 5)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIStyleDDListWidgetID,                      kTabStyUIPrefix + 6)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIPreserveFormattingWidgetID,               kTabStyUIPrefix + 7)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIApplyToAllWidgetID,                       kTabStyUIPrefix + 8)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIRemoveStyleLabelWidgetID,                 kTabStyUIPrefix + 9)
DECLARE_PMID(kWidgetIDSpace, kTableStyleControlStripWidgetID,                   kTabStyUIPrefix + 10)
DECLARE_PMID(kWidgetIDSpace, kClearCellOverridesButtonWidgetID,                 kTabStyUIPrefix + 11)
DECLARE_PMID(kWidgetIDSpace, kLoadTableStyleListElementWidgetID,                kTabStyUIPrefix + 12)
DECLARE_PMID(kWidgetIDSpace, kLoadTableStyleDialogWidgetID,                     kTabStyUIPrefix + 13)
DECLARE_PMID(kWidgetIDSpace, kTableStyleTreeViewWidgetID,                       kTabStyUIPrefix + 14)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIAppliedStyleStripWidgetID,                kTabStyUIPrefix + 15)
DECLARE_PMID(kWidgetIDSpace, kTabStyUICellStylePanelWidgetID,                   kTabStyUIPrefix + 16)
DECLARE_PMID(kWidgetIDSpace, kCellRunInStyleWidgetID,                           kTabStyUIPrefix + 17)
DECLARE_PMID(kWidgetIDSpace, kCellStylePanelCtrlSetWidgetID,                    kTabStyUIPrefix + 18)
DECLARE_PMID(kWidgetIDSpace, kTableStyleListElementShortCutWidgetID,            kTabStyUIPrefix + 19)
DECLARE_PMID(kWidgetIDSpace, kAppliedCellStyleStripWidgetID,                    kTabStyUIPrefix + 20)
DECLARE_PMID(kWidgetIDSpace, kCellStyleTypeIconWidgetID,                        kTabStyUIPrefix + 21)
DECLARE_PMID(kWidgetIDSpace, kCellStyleTreeViewWidgetID,                        kTabStyUIPrefix + 22)
DECLARE_PMID(kWidgetIDSpace, kTableStyleGroupIconWidgetID,                      kTabStyUIPrefix + 23)
DECLARE_PMID(kWidgetIDSpace, kTabStyUILoadOptionsWidgetID,                      kTabStyUIPrefix + 24)
DECLARE_PMID(kWidgetIDSpace, kTableStyleListNameILEWidgetID,                    kTabStyUIPrefix + 25)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIStyleGroupIconWidgetID,                   kTabStyUIPrefix + 26)
DECLARE_PMID(kWidgetIDSpace, kTableStyleIconWidgetID,                           kTabStyUIPrefix + 27)
DECLARE_PMID(kWidgetIDSpace, kCellStyleIconWidgetID,                            kTabStyUIPrefix + 28)
DECLARE_PMID(kWidgetIDSpace, kDeleteCellStyleButtonWidgetID,                    kTabStyUIPrefix + 29)
DECLARE_PMID(kWidgetIDSpace, kNewCellStyleButtonWidgetID,                       kTabStyUIPrefix + 30)
DECLARE_PMID(kWidgetIDSpace, kNewCellStyleGroupButtonWidgetID,                  kTabStyUIPrefix + 31)
DECLARE_PMID(kWidgetIDSpace, kCellStyleDDListWidgetID,                          kTabStyUIPrefix + 32)
DECLARE_PMID(kWidgetIDSpace, kTabStyUICellAttributesScrollBarWidgetID,          kTabStyUIPrefix + 33)
DECLARE_PMID(kWidgetIDSpace, kTableStyleDDListWidgetID,                         kTabStyUIPrefix + 34)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIClearAllOverridesButtonWidgetID,          kTabStyUIPrefix + 35)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIControlStripWidgetID,                     kTabStyUIPrefix + 36)
DECLARE_PMID(kWidgetIDSpace, kTabStyUICellShortcutEditBoxWidgetID,              kTabStyUIPrefix + 37)
DECLARE_PMID(kWidgetIDSpace, kDeleteTableStyleButtonWidgetID,                   kTabStyUIPrefix + 38)
DECLARE_PMID(kWidgetIDSpace, kTableRunInStyleWidgetID,                          kTabStyUIPrefix + 39)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIAppliedTableStyleTextWidgetID,            kTabStyUIPrefix + 40)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIAppliedCellStyleTextWidgetID,             kTabStyUIPrefix + 41)
DECLARE_PMID(kWidgetIDSpace, kNewTableStyleGroupButtonWidgetID,                 kTabStyUIPrefix + 42)
DECLARE_PMID(kWidgetIDSpace, kClearTableOverridesButtonWidgetID,                kTabStyUIPrefix + 43)
DECLARE_PMID(kWidgetIDSpace, kNewTableStyleButtonWidgetID,                      kTabStyUIPrefix + 44)
DECLARE_PMID(kWidgetIDSpace, kCellStyleListParentWidgetID,                      kTabStyUIPrefix + 45)
DECLARE_PMID(kWidgetIDSpace, kCellStyleListNameILEWidgetID,                     kTabStyUIPrefix + 46)
DECLARE_PMID(kWidgetIDSpace, kTableStyleTypeIconWidgetID,                       kTabStyUIPrefix + 47)
DECLARE_PMID(kWidgetIDSpace, kCellStyleListElementShortCutWidgetID,             kTabStyUIPrefix + 48)
DECLARE_PMID(kWidgetIDSpace, kCellStyleGroupIconWidgetID,                       kTabStyUIPrefix + 49)
DECLARE_PMID(kWidgetIDSpace, kRegionalCellStyleTextWidgetID,                    kTabStyUIPrefix + 50)
DECLARE_PMID(kWidgetIDSpace, kTabStyUIAppliedStyleStripWidgetId,                kTabStyUIPrefix + 51)
DECLARE_PMID(kWidgetIDSpace, kTabStyUICurrentActionLabelWidgetID,               kTabStyUIPrefix + 52)
DECLARE_PMID(kWidgetIDSpace, kTabStyUICurrentActionTextWidgetID,                kTabStyUIPrefix + 53)
DECLARE_PMID(kWidgetIDSpace, kCellStyleListElementImportedTypeWidgetID,         kTabStyUIPrefix + 54)
DECLARE_PMID(kWidgetIDSpace, kTableStyleListElementImportedTypeWidgetID,        kTabStyUIPrefix + 55)
// Moved here to allow table/cell style icons in the load style dialog
//Watson #2401465: ODFRC has a 16bit limitation on resource ids ids like kTableStylesIconRsrcID just sliently cast to 16 bits
//need to use 16 bits of these ids in M/WIconSuiteButtonView
DECLARE_PMID(kWidgetIDSpace, kTableStylesIconRsrcID,							kTabStyUIPrefix + 56)
DECLARE_PMID(kWidgetIDSpace, kCellStylesIconRsrcID,								kTabStyUIPrefix + 57)

DECLARE_PMID(kWidgetIDSpace, kClearAllCellOverridesButtonWidgetID,				kTabStyUIPrefix + 58)

//gap
//Table Options Dialog
DECLARE_PMID(kWidgetIDSpace, kTabStyUIWidgetID,									kTabStyUIPrefix + 69)
//Table General Panel
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesGroupWidgetID,					kTabStyUIPrefix + 70)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesBorderWidgetID,					kTabStyUIPrefix + 71)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesStaticTextID,						kTabStyUIPrefix + 72)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesHeaderStyleDDWidgetID,			kTabStyUIPrefix + 73)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesFooterStyleDDWidgetID,			kTabStyUIPrefix + 74)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesBodyRowsStyleDDWidgetID,			kTabStyUIPrefix + 75)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesLeftColStyleDDWidgetID,			kTabStyUIPrefix + 76)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellStylesRightColStyleDDWidgetID,			kTabStyUIPrefix + 77)

//Table Setup Panel
DECLARE_PMID(kWidgetIDSpace, kTabStySetupWidgetPanelID,							kTabStyUIPrefix + 82)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGroupWidgetID,						kTabStyUIPrefix + 83)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderBorderWidgetID,						kTabStyUIPrefix + 84)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderWeightStaticTextID,					kTabStyUIPrefix + 85)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderWeightComboWidgetId,					kTabStyUIPrefix + 86)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderWeightNudgeWidgetId,					kTabStyUIPrefix + 87)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderLineDDWidgetID,						kTabStyUIPrefix + 88)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderTypeTextWidgetID,						kTabStyUIPrefix + 89)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderColorDDWidgetID,						kTabStyUIPrefix + 90)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderColorDDTextWidgetID,					kTabStyUIPrefix + 91)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderTintTextWidgetID,						kTabStyUIPrefix + 92)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderTintWidgetID,							kTabStyUIPrefix + 93)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderOverprintCheckBoxWidgetID,			kTabStyUIPrefix + 94)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapColorDDWidgetID,					kTabStyUIPrefix + 95)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapColorDDTextWidgetID,				kTabStyUIPrefix + 96)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapTintTextWidgetID,					kTabStyUIPrefix + 97)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapTintWidgetID,						kTabStyUIPrefix + 98)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapTintNudgeWidgetID,					kTabStyUIPrefix + 99)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderGapOverprintCheckBoxWidgetID,			kTabStyUIPrefix + 100)
//DECLARE_PMID(kWidgetIDSpace, kTabStySetupPreserveOverridesWidgetID,			kTabStyUIPrefix + 101)
DECLARE_PMID(kWidgetIDSpace, kTabStySetupSpaceGroupWidgetID,					kTabStyUIPrefix + 102)
DECLARE_PMID(kWidgetIDSpace, kTabStySetupSpaceBorderWidgetID,					kTabStyUIPrefix + 103)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceBeforeStaticTextID,					kTabStyUIPrefix + 104)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceBeforeEditWidgetId,					kTabStyUIPrefix + 105)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceBeforeNudgeWidgetId,					kTabStyUIPrefix + 106)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceAfterStaticTextID,						kTabStyUIPrefix + 107)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceAfterEditWidgetId,						kTabStyUIPrefix + 108)
DECLARE_PMID(kWidgetIDSpace, kTabStySpaceAfterNudgeWidgetId,					kTabStyUIPrefix + 109)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeOrderGroupWidgetID,					kTabStyUIPrefix + 110)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeOrderBorderWidgetID,					kTabStyUIPrefix + 111)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeOrderDDWidgetID,						kTabStyUIPrefix + 112)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeOrderDDTextWidgetID,					kTabStyUIPrefix + 113)
DECLARE_PMID(kWidgetIDSpace, kTabStyBorderTintNudgeWidgetID,					kTabStyUIPrefix + 114)
//gap
//Table fill panel
DECLARE_PMID(kWidgetIDSpace, kTabStyAltFillPanelWidgetID,						kTabStyUIPrefix + 121)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipFirstTextWidgetID,				kTabStyUIPrefix + 122)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipFirstWidgetID,					kTabStyUIPrefix + 123)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipLastTextWidgetID,				kTabStyUIPrefix + 124)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipLastWidgetID,					kTabStyUIPrefix + 125)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstGroupWidgetID,					kTabStyUIPrefix + 126)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstGroupBorderTextWidgetID,		kTabStyUIPrefix + 127)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstContainsWidgetTextID,			kTabStyUIPrefix + 128)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstContainsWidgetID,				kTabStyUIPrefix + 129)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstWidgetTextID,					kTabStyUIPrefix + 130)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstColorDDTextWidgetID,			kTabStyUIPrefix + 131)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstColorDDWidgetID,				kTabStyUIPrefix + 132)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstTintTextWidgetID,				kTabStyUIPrefix + 133)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstTintWidgetID,					kTabStyUIPrefix + 134)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstOverprintCheckBoxWidgetID,		kTabStyUIPrefix + 135)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondGroupWidgetID,					kTabStyUIPrefix + 136)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondGroupBorderTextWidgetID,		kTabStyUIPrefix + 137)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondContainsWidgetTextID,			kTabStyUIPrefix + 138)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondContainsWidgetID,				kTabStyUIPrefix + 139)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondWidgetTextID,					kTabStyUIPrefix + 140)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondColorDDTextWidgetID,			kTabStyUIPrefix + 141)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondColorDDWidgetID,				kTabStyUIPrefix + 142)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondTintTextWidgetID,				kTabStyUIPrefix + 143)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondTintWidgetID,					kTabStyUIPrefix + 144)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondOverprintCheckBoxWidgetID,		kTabStyUIPrefix + 145)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingAlternatingPatternDDWidgetID,		kTabStyUIPrefix + 146)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingGrpBorderWidgetID,					kTabStyUIPrefix + 147)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstContainsNudgeWidgetID,			kTabStyUIPrefix + 148)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingFirstTintNudgeWidgetID,				kTabStyUIPrefix + 149)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondContainsNudgeWidgetID,			kTabStyUIPrefix + 150)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSecondTintNudgeWidgetID,				kTabStyUIPrefix + 151)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipFirstStaticTextWidgetID,			kTabStyUIPrefix + 152)
DECLARE_PMID(kWidgetIDSpace, kAltFilShadingSkipLastStaticTextWidgetID,			kTabStyUIPrefix + 153)
//gap
//Table Style - Row Stroke panel
DECLARE_PMID(kWidgetIDSpace, kTabStyAltRowStrokePanelWidgetID,					kTabStyUIPrefix + 161)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowAlternatingPatternDDWidgetID,			kTabStyUIPrefix + 162)
DECLARE_PMID(kWidgetIDSpace, kAltRowStrokeGrpBorderWidgetID,					kTabStyUIPrefix + 163)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowGroupWidgetID,						kTabStyUIPrefix + 164)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowShadeByDDWidgetID,					kTabStyUIPrefix + 165)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstContainsWidgetTextID,			kTabStyUIPrefix + 166)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstContainsNudgeWidgetID,			kTabStyUIPrefix + 167)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstContainsWidgetID,				kTabStyUIPrefix + 168)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstWidgetTextID,					kTabStyUIPrefix + 169)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstWeightTextWidgetID,				kTabStyUIPrefix + 170)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstWeightComboWidgetID,				kTabStyUIPrefix + 171)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstWeightComboNudgeWidgetID,		kTabStyUIPrefix + 172)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstLineStyleDDTextWidgetID,			kTabStyUIPrefix + 173)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstLineStyleDDWidgetID,				kTabStyUIPrefix + 174)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstColorDDTextWidgetID,				kTabStyUIPrefix + 175)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstColorDDWidgetID,					kTabStyUIPrefix + 176)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstTintTextWidgetID,				kTabStyUIPrefix + 177)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstTintNudgeWidgetID,				kTabStyUIPrefix + 178)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstTintWidgetID,					kTabStyUIPrefix + 179)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstOverprintCheckBoxWidgetID,		kTabStyUIPrefix + 180)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapColorDDTextWidgetID,			kTabStyUIPrefix + 181)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapColorDDWidgetID,				kTabStyUIPrefix + 182)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapTintTextWidgetID,				kTabStyUIPrefix + 183)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapTintNudgeWidgetID,			kTabStyUIPrefix + 184)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapTintWidgetID,					kTabStyUIPrefix + 185)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowFirstGapOverprintCheckBoxWidgetID,	kTabStyUIPrefix + 186)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGroupWidgetID,					kTabStyUIPrefix + 187)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGroupBorderTextWidgetID,		kTabStyUIPrefix + 188)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondContainsWidgetTextID,			kTabStyUIPrefix + 189)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondContainsWidgetID,				kTabStyUIPrefix + 190)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondWidgetTextID,					kTabStyUIPrefix + 191)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondCellStrokeGroupWidgetID,		kTabStyUIPrefix + 192)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondWeightTextWidgetID,				kTabStyUIPrefix + 193)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondWeightComboWidgetID,			kTabStyUIPrefix + 194)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondLineStyleDDTextWidgetID,		kTabStyUIPrefix + 195)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondLineStyleDDWidgetID,			kTabStyUIPrefix + 196)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondColorDDTextWidgetID,			kTabStyUIPrefix + 197)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondColorDDWidgetID,				kTabStyUIPrefix + 198)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondTintTextWidgetID,				kTabStyUIPrefix + 199)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondTintWidgetID,					kTabStyUIPrefix + 200)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondContainsNudgeWidgetID,			kTabStyUIPrefix + 201)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondTintNudgeWidgetID,				kTabStyUIPrefix + 202)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondOverprintCheckBoxWidgetID,		kTabStyUIPrefix + 203)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapColorDDWidgetID,				kTabStyUIPrefix + 204)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapOverprintCheckBoxWidgetID,	kTabStyUIPrefix + 205)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondWeightComboNudgeWidgetID,		kTabStyUIPrefix + 206)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapColorDDTextWidgetID,			kTabStyUIPrefix + 207)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapTintTextWidgetID,			kTabStyUIPrefix + 208)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapTintWidgetID,				kTabStyUIPrefix + 209)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSecondGapTintNudgeWidgetID,			kTabStyUIPrefix + 210)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipFirstTextWidgetID,				kTabStyUIPrefix + 211)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipFirstWidgetID,					kTabStyUIPrefix + 212)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipLastTextWidgetID,					kTabStyUIPrefix + 213)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipLastWidgetID,						kTabStyUIPrefix + 214)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipFirstNudgeWidgetID,				kTabStyUIPrefix + 215)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipLastNudgeWidgetID,				kTabStyUIPrefix + 216)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipFirstStaticTextWidgetID,			kTabStyUIPrefix + 217)
DECLARE_PMID(kWidgetIDSpace, kAltRulingRowSkipLastStaticTextWidgetID,			kTabStyUIPrefix + 218)
//gap
//Table Style - Col Stroke panel
DECLARE_PMID(kWidgetIDSpace, kAltTableAltColumnStrokePanelWidgetID,				kTabStyUIPrefix + 225)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnAlternatingPatternDDWidgetID,		kTabStyUIPrefix + 226)
DECLARE_PMID(kWidgetIDSpace, kAltColumnStrokeGrpBorderWidgetID,					kTabStyUIPrefix + 227)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnGroupWidgetID,						kTabStyUIPrefix + 228)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnShadeByDDWidgetID,					kTabStyUIPrefix + 229)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstWidgetTextID,					kTabStyUIPrefix + 230)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstContainsWidgetTextID,			kTabStyUIPrefix + 231)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstContainsNudgeWidgetID,		kTabStyUIPrefix + 232)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstContainsWidgetID,				kTabStyUIPrefix + 233)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstWeightTextWidgetID,			kTabStyUIPrefix + 234)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstWeightComboNudgeWidgetID,		kTabStyUIPrefix + 235)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstWeightComboWidgetID,			kTabStyUIPrefix + 236)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstLineStyleDDTextWidgetID,		kTabStyUIPrefix + 237)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstLineStyleDDWidgetID,			kTabStyUIPrefix + 238)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstColorDDTextWidgetID,			kTabStyUIPrefix + 239)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstColorDDWidgetID,				kTabStyUIPrefix + 240)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstTintTextWidgetID,				kTabStyUIPrefix + 241)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstTintNudgeWidgetID,			kTabStyUIPrefix + 242)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstTintWidgetID,					kTabStyUIPrefix + 243)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstOverprintCheckBoxWidgetID,	kTabStyUIPrefix + 244)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapColorDDTextWidgetID,		kTabStyUIPrefix + 245)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapColorDDWidgetID,			kTabStyUIPrefix + 246)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapTintTextWidgetID,			kTabStyUIPrefix + 247)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapTintNudgeWidgetID,			kTabStyUIPrefix + 248)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapTintWidgetID,				kTabStyUIPrefix + 249)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnFirstGapOverprintCheckBoxWidgetID,	kTabStyUIPrefix + 250)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGroupWidgetID,				kTabStyUIPrefix2 + 1)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGroupBorderTextWidgetID,		kTabStyUIPrefix2 + 2)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondContainsWidgetTextID,		kTabStyUIPrefix2 + 3)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondContainsWidgetID,			kTabStyUIPrefix2 + 4)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondWidgetTextID,				kTabStyUIPrefix2 + 5)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondWeightTextWidgetID,			kTabStyUIPrefix2 + 6)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondWeightComboWidgetID,			kTabStyUIPrefix2 + 7)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondLineStyleDDTextWidgetID,		kTabStyUIPrefix2 + 8)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondLineStyleDDWidgetID,			kTabStyUIPrefix2 + 9)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondColorDDTextWidgetID,			kTabStyUIPrefix2 + 10)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondColorDDWidgetID,				kTabStyUIPrefix2 + 11)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondTintTextWidgetID,			kTabStyUIPrefix2 + 12)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondTintWidgetID,				kTabStyUIPrefix2 + 13)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondOverprintCheckBoxWidgetID,	kTabStyUIPrefix2 + 14)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondContainsNudgeWidgetID,		kTabStyUIPrefix2 + 15)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondTintNudgeWidgetID,			kTabStyUIPrefix2 + 16)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondWeightComboNudgeWidgetID,	kTabStyUIPrefix2 + 17)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapColorDDTextWidgetID,		kTabStyUIPrefix2 + 18)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapColorDDWidgetID,			kTabStyUIPrefix2 + 19)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapTintTextWidgetID,			kTabStyUIPrefix2 + 20)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapTintWidgetID,				kTabStyUIPrefix2 + 21)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapTintNudgeWidgetID,		kTabStyUIPrefix2 + 22)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSecondGapOverprintCheckBoxWidgetID,kTabStyUIPrefix2 + 23)
//DECLARE_PMID(kWidgetIDSpace, kAltColumnStrokePreserveOverridesWidgetID,		kTabStyUIPrefix2 + 24)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipFirstStaticTextWidgetID,		kTabStyUIPrefix2 + 25)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipLastStaticTextWidgetID,		kTabStyUIPrefix2 + 26)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipFirstTextWidgetID,				kTabStyUIPrefix2 + 27)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipFirstNudgeWidgetID,			kTabStyUIPrefix2 + 28)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipFirstWidgetID,					kTabStyUIPrefix2 + 29)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipLastTextWidgetID,				kTabStyUIPrefix2 + 30)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipLastNudgeWidgetID,				kTabStyUIPrefix2 + 31)
DECLARE_PMID(kWidgetIDSpace, kAltRulingColumnSkipLastWidgetID,					kTabStyUIPrefix2 + 32)
DECLARE_PMID(kWidgetIDSpace, kDummyTabStyOverprintCheckBoxWidgetID,				kTabStyUIPrefix2 + 33)
//gap
DECLARE_PMID(kWidgetIDSpace, kTabStyUISelectWidgetID,							kTabStyUIPrefix2 + 40)
//Cell Style - Text
DECLARE_PMID(kWidgetIDSpace, kTabStyTextAttrPanelWidgetID,						kTabStyUIPrefix2 + 41)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellInsetsGroupWidgetId,					kTabStyUIPrefix2 + 42)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellInsetsBorderWidgetID,					kTabStyUIPrefix2 + 43)
DECLARE_PMID(kWidgetIDSpace, kTabStyTopInsetTextWidgetID,						kTabStyUIPrefix2 + 44)
DECLARE_PMID(kWidgetIDSpace, kTabStyTopInsetEditBoxWidgetID,					kTabStyUIPrefix2 + 45)
DECLARE_PMID(kWidgetIDSpace, kTabStyTopInsetNudgeWidget,						kTabStyUIPrefix2 + 46)
DECLARE_PMID(kWidgetIDSpace, kTabStyBottomInsetTextWidgetID,					kTabStyUIPrefix2 + 47)
DECLARE_PMID(kWidgetIDSpace, kTabStyBottomInsetEditBoxWidgetID,					kTabStyUIPrefix2 + 48)
DECLARE_PMID(kWidgetIDSpace, kTabStyBottomInsetNudgeWidget,						kTabStyUIPrefix2 + 49)
DECLARE_PMID(kWidgetIDSpace, kTabStyLeftInsetTextWidgetID,						kTabStyUIPrefix2 + 50)
DECLARE_PMID(kWidgetIDSpace, kTabStyLeftInsetEditBoxWidgetID,					kTabStyUIPrefix2 + 51)
DECLARE_PMID(kWidgetIDSpace, kTabStyLeftInsetNudgeWidget,						kTabStyUIPrefix2 + 52)
DECLARE_PMID(kWidgetIDSpace, kTabStyRightInsetTextWidgetID,						kTabStyUIPrefix2 + 53)
DECLARE_PMID(kWidgetIDSpace, kTabStyRightInsetEditBoxWidgetID,					kTabStyUIPrefix2 + 54)
DECLARE_PMID(kWidgetIDSpace, kTabStyRightInsetNudgeWidget,						kTabStyUIPrefix2 + 55)
DECLARE_PMID(kWidgetIDSpace, kTabStyTextRotationGroupWidgetId,					kTabStyUIPrefix2 + 56)
DECLARE_PMID(kWidgetIDSpace, kTabStyTextRotationTitleWidgetId,					kTabStyUIPrefix2 + 57)
DECLARE_PMID(kWidgetIDSpace, kTabStyTextRotationDropdownWidgetId,				kTabStyUIPrefix2 + 58)
DECLARE_PMID(kWidgetIDSpace, kTabStyTextRotationWidgetID,						kTabStyUIPrefix2 + 59)
DECLARE_PMID(kWidgetIDSpace, kTabStyVerticalTextGroupWidgetId,					kTabStyUIPrefix2 + 60)
DECLARE_PMID(kWidgetIDSpace, kTabStyVerticalTextTitleWidgetId,					kTabStyUIPrefix2 + 61)
DECLARE_PMID(kWidgetIDSpace, kTabStyVerticalTextDropdownWidgetId,				kTabStyUIPrefix2 + 62)
DECLARE_PMID(kWidgetIDSpace, kTabStyVerticalTextWidgetID,						kTabStyUIPrefix2 + 63)
DECLARE_PMID(kWidgetIDSpace, kTabStyParagraphSpacingTextWidgetId,				kTabStyUIPrefix2 + 64)
DECLARE_PMID(kWidgetIDSpace, kTabStyParagraphSpacingWidgetId,					kTabStyUIPrefix2 + 65)
DECLARE_PMID(kWidgetIDSpace, kTabStyParagraphSpacingNudgeWidget,				kTabStyUIPrefix2 + 66)
DECLARE_PMID(kWidgetIDSpace, kTabStyFirstBaselineGroupWidgetId,					kTabStyUIPrefix2 + 67)
DECLARE_PMID(kWidgetIDSpace, kTabStyFirstBaselineTitleTextWidgetID,				kTabStyUIPrefix2 + 68)
DECLARE_PMID(kWidgetIDSpace, kTabStyOffsetDropdownWidgetID,						kTabStyUIPrefix2 + 69)
DECLARE_PMID(kWidgetIDSpace, kTabStyOffsetWidgetID,								kTabStyUIPrefix2 + 70)
DECLARE_PMID(kWidgetIDSpace, kTabStyOffsetEditWidgetID,							kTabStyUIPrefix2 + 71)
DECLARE_PMID(kWidgetIDSpace, kTabStyMinOffsetWidgetID,							kTabStyUIPrefix2 + 72)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellClippingGroupWidgetId,					kTabStyUIPrefix2 + 73)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellClippingTitleWidgetId,					kTabStyUIPrefix2 + 74)
DECLARE_PMID(kWidgetIDSpace, kTabStyCellClippingCheckBoxWidgetID,				kTabStyUIPrefix2 + 75)
DECLARE_PMID(kWidgetIDSpace, kTabStyGraphicAttrPanelWidgetID,					kTabStyUIPrefix2 + 76)
// gap
DECLARE_PMID(kWidgetIDSpace, kTabStyInsetChainWidgetID,							kTabStyUIPrefix2 + 78)
DECLARE_PMID(kWidgetIDSpace, kTabStyTTAChainControlsWidgetID,					kTabStyUIPrefix2 + 79)
//gap
//Cell Style - Strokes and Fills
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeFillWidgetID,							kTabStyUIPrefix2 + 85)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeGroupWidgetID,						kTabStyUIPrefix2 + 86)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeBorderWidgetID,						kTabStyUIPrefix2 + 87)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeStaticTextID,							kTabStyUIPrefix2 + 88)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeWeightComboWidgetId,					kTabStyUIPrefix2 + 89)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeWeightNudgeWidgetId,					kTabStyUIPrefix2 + 90)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeSelectionWidgetID,					kTabStyUIPrefix2 + 91)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeLineDDWidgetID,						kTabStyUIPrefix2 + 92)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeTypeTextWidgetID,						kTabStyUIPrefix2 + 93)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeColorDDWidgetID,						kTabStyUIPrefix2 + 94)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeColorDDTextWidgetID,					kTabStyUIPrefix2 + 95)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeTintTextWidgetID,						kTabStyUIPrefix2 + 96)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeTintWidgetID,							kTabStyUIPrefix2 + 97)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeSelectionSpace1WidgetID,				kTabStyUIPrefix2 + 98)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeOverprintCheckBoxWidgetID,			kTabStyUIPrefix2 + 99)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeGapTintWidgetID,						kTabStyUIPrefix2 + 100)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeGapColorDDWidgetID,					kTabStyUIPrefix2 + 101)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeGapOverprintCheckBoxWidgetID,			kTabStyUIPrefix2 + 102)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillGroupWidgetID,							kTabStyUIPrefix2 + 103)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillGrpBorderWidgetID,						kTabStyUIPrefix2 + 104)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillColorDDWidgetID,						kTabStyUIPrefix2 + 105)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillStaticWidgetID,							kTabStyUIPrefix2 + 106)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillTintTextWidgetID,						kTabStyUIPrefix2 + 107)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillTintWidgetID,							kTabStyUIPrefix2 + 108)
DECLARE_PMID(kWidgetIDSpace, kTabStyStrokeSelectionSpace2WidgetID,				kTabStyUIPrefix2 + 109)
DECLARE_PMID(kWidgetIDSpace, kTabStyFillOverprintCheckBoxWidgetID,				kTabStyUIPrefix2 + 110)
//gap
//Cell Style - Diagonal Lines
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesPanelWidgetID,						kTabStyUIPrefix2 + 111)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesIconTypeSelectGroupWidgetID,		kTabStyUIPrefix2 + 112)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesDrawInFrontWidgetID,				kTabStyUIPrefix2 + 113)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGroupWidgetID,				kTabStyUIPrefix2 + 114)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesGroupBorderWidgetID,				kTabStyUIPrefix2 + 115)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeStaticTextID,				kTabStyUIPrefix2 + 116)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeWeightComboWidgetId,			kTabStyUIPrefix2 + 117)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeWeightNudgeWidgetId,			kTabStyUIPrefix2 + 118)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeLineDDWidgetID,				kTabStyUIPrefix2 + 119)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeTypeTextWidgetID,			kTabStyUIPrefix2 + 120)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeColorDDWidgetID,				kTabStyUIPrefix2 + 121)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeColorDDTextWidgetID,			kTabStyUIPrefix2 + 122)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeTintTextWidgetID,			kTabStyUIPrefix2 + 123)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeTintWidgetID,				kTabStyUIPrefix2 + 124)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeDrawDDTextWidgetID,			kTabStyUIPrefix2 + 125)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeOverprintCheckBoxWidgetID,	kTabStyUIPrefix2 + 126)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeTintNudgeWidgetID,			kTabStyUIPrefix2 + 127)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapColorDDWidgetID,			kTabStyUIPrefix2 + 128)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapColorDDTextWidgetID,		kTabStyUIPrefix2 + 129)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapTintTextWidgetID,			kTabStyUIPrefix2 + 130)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapTintWidgetID,				kTabStyUIPrefix2 + 131)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapTintNudgeWidgetID,		kTabStyUIPrefix2 + 132)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesStrokeGapOverprintCheckBoxWidgetID,kTabStyUIPrefix2 + 133)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesBothIconWidgetID,					kTabStyUIPrefix2 + 134)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesNoneIconWidgetID,					kTabStyUIPrefix2 + 135)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesULeftToLRightIconWidgetID,			kTabStyUIPrefix2 + 136)
DECLARE_PMID(kWidgetIDSpace, kTabStyDiagLinesLLeftToURightIconWidgetID,			kTabStyUIPrefix2 + 137)
//gap
//General Panel
DECLARE_PMID(kWidgetIDSpace, kTabStyGeneralPanelWidgetID,						kTabStyUIPrefix2 + 141)
DECLARE_PMID(kWidgetIDSpace, kTabStyStyleInfoGroupWidgetID,						kTabStyUIPrefix2 + 142)
DECLARE_PMID(kWidgetIDSpace, kTabStyStyleInfoBorderWidgetID,					kTabStyUIPrefix2 + 143)
DECLARE_PMID(kWidgetIDSpace, kTabStyStyleNameTextWidgetID,						kTabStyUIPrefix2 + 144)
DECLARE_PMID(kWidgetIDSpace, kTabStyStyleNameEditWidgetId,						kTabStyUIPrefix2 + 145)
DECLARE_PMID(kWidgetIDSpace, kTabStyBasedOnDDTextWidgetID,						kTabStyUIPrefix2 + 146)
DECLARE_PMID(kWidgetIDSpace, kTabStyBasedOnDDWidgetID,							kTabStyUIPrefix2 + 147)
DECLARE_PMID(kWidgetIDSpace, kTabStyShortcutTextWidgetID,						kTabStyUIPrefix2 + 148)
DECLARE_PMID(kWidgetIDSpace, kTabStyShortcutEditWidgetId,						kTabStyUIPrefix2 + 149)
DECLARE_PMID(kWidgetIDSpace, kTabStySettingsTextWidgetID,						kTabStyUIPrefix2 + 150)
DECLARE_PMID(kWidgetIDSpace, kTabStySettingsMultilineWidgetID,					kTabStyUIPrefix2 + 151)
DECLARE_PMID(kWidgetIDSpace, kTabStySettingsScrollBarWidgetID,					kTabStyUIPrefix2 + 152)
DECLARE_PMID(kWidgetIDSpace, kTabStyParaGroupWidgetID,							kTabStyUIPrefix2 + 153)
DECLARE_PMID(kWidgetIDSpace, kTabStyParaBorderWidgetID,							kTabStyUIPrefix2 + 154)
DECLARE_PMID(kWidgetIDSpace, kTabStyParaDDTextWidgetID,							kTabStyUIPrefix2 + 155)
DECLARE_PMID(kWidgetIDSpace, kTabStyParaDDWidgetID,								kTabStyUIPrefix2 + 156)
DECLARE_PMID(kWidgetIDSpace, kTabStyCurrentLocationLabelWidgetID,				kTabStyUIPrefix2 + 157)
DECLARE_PMID(kWidgetIDSpace, kTabStyCurrentLocationTextWidgetID,				kTabStyUIPrefix2 + 158)
DECLARE_PMID(kWidgetIDSpace, kTabStyTextOrientationCheckboxWidgetId,			kTabStyUIPrefix2 + 159)
DECLARE_PMID(kWidgetIDSpace, kCellStyleDiagLineTypeLabelWidgetID,				kTabStyUIPrefix2 + 160)


// Messages ID
DECLARE_PMID(kMessageIDSpace, kUpdateDeleteCellStyleButtonMsg,		kTabStyUIPrefix + 1)
DECLARE_PMID(kMessageIDSpace, kUpdateDeleteTableStyleButtonMsg,		kTabStyUIPrefix + 2)
DECLARE_PMID(kMessageIDSpace, kCreateTargetMsg,						kTabStyUIPrefix + 3)
DECLARE_PMID(kMessageIDSpace, kCallBackWidgetToTargetMsg,			kTabStyUIPrefix + 4)
DECLARE_PMID(kMessageIDSpace, kCallBackTargetToWidgetMsg,			kTabStyUIPrefix + 5)
DECLARE_PMID(kMessageIDSpace, kWidgetToTargetMsg,					kTabStyUIPrefix + 6)
DECLARE_PMID(kMessageIDSpace, kTargetToWidgetMsg,					kTabStyUIPrefix + 7)
DECLARE_PMID(kMessageIDSpace, kSetupWidgetMsg,						kTabStyUIPrefix + 8)
DECLARE_PMID(kMessageIDSpace, kResetAttributeMsg,					kTabStyUIPrefix + 9)

// Service ID
DECLARE_PMID(kServiceIDSpace, kTableStyleSelectableDialogService,	kTabStyUIPrefix + 1)
DECLARE_PMID(kServiceIDSpace, kCellStyleSelectableDialogService,	kTabStyUIPrefix + 2)

//
// Conversion IDs
//

// Initial data format version numbers
#define kTabStyUIFirstMajorFormatNumber  RezLong(1)
#define kTabStyUIFirstMinorFormatNumber  RezLong(0)

// Cobalt
#define kTabStyUICobaltMajorVersionNumber kCobaltMajorFormatNumber
#define kTabStyUIRenumberPluginChange	kCobaltInitialMinorFormatNumber

#define kTabStyUILastMajorFormatNumber  kTabStyUICobaltMajorVersionNumber
#define kTabStyUILastMinorFormatNumber  kTabStyUIRenumberPluginChange

// Data format version numbers for the PluginVersion resource 
#define kTabStyUICurrentMajorFormatNumber kTabStyUILastMajorFormatNumber
#define kTabStyUICurrentMinorFormatNumber kTabStyUILastMinorFormatNumber

#endif // __TabStyUIID_h__

//  Code generated by DollyXs code generator
