//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/sdksamples/hostadapter/IDHAScriptingDefs.h $
//  
//  Owner: Lea Savage
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2008 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================


#ifndef __IDHAScriptingDefs_h__
#define __IDHAScriptingDefs_h__

#define kCPrefs_CLSID { 0x8d448fe0, 0x8194, 0x11d3, { 0xa6, 0x53, 0x0, 0xe0, 0x98, 0x71, 0xa, 0x6f } }
DECLARE_GUID(CPrefs_CLSID, kCPrefs_CLSID);

// Note: 4-char IDs below must be unique.
// See ScriptingDefs.h for further information.

// Event IDs
enum IDHAScriptEvents
{
	// Page Item Events
	e_GeometryChangedEvent = 'geoC',
	e_ContentChangedEvent = 'conC',
	e_FormatChangedEvent = 'forC',

	// Layer Events
	e_LayerCreatedEvent = 'lyCr',
	e_LayerAddedEvent = 'lyAd',
	e_LayerChangedEvent = 'lyCh',
	e_LayerVisibleChangedEvent = 'lyVC',
	e_LayerLockChangedEvent = 'lyLC',
	e_LayerOrderChangedEvent = 'lyOC',

	// Style Events
	e_StyleListChangedEvent = 'stLC',
	e_ParaStyleListChangedEvent = 'psLC',
	e_CharStyleListChangedEvent = 'csLC',
	e_SpreadListChangedEvent = 'spLC',
	e_ObjectStyleListChangedEvent = 'obLC',
	e_TableStyleListChangedEvent = 'tbLC',
	e_CellStyleListChangedEvent = 'clLC',

	// Drag/Drop events
	e_DropEvent = 'drEV',

	// Keyboard Events (some way for people to implement shortcuts easily)
	e_KeyDownEvent = 'kyDn',
	e_KeyUpEvent = 'kyUp',
	e_KeyPressedEvent = 'kyPr',

	// Other possibilities
	e_MasterPageAppliedEvent = 'mpAp',
	e_OverrideMasterPageItemEvent = 'ovMP',
	e_DetachFromMasterPageEvent = 'dfMP',
	e_CreateObjectEvent = 'creO',
	e_ModifyObjectEvent = 'modO',
};

// Property IDs
enum IDHAScriptProperties
{
	//p_Said		= 'pSed',
	p_XMPString		= 'pXst'
};


#endif // __IDHAScriptingDefs_h__

//  Code generated by DollyXs code generator
