//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/layout/HyperlinkID.h $
//  
//  Owner: Brendan O'Shea
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Contains IDs used by the hyperlink plug-in
//  
//========================================================================================

#ifndef __HyperlinksID__
#define __HyperlinksID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

#define kHyperlinksPrefix	 RezLong(0x13500)

// <Start IDC>
// PluginID
#define kHyperlinkPluginName			"Hyperlinks"
DECLARE_PMID(kPlugInIDSpace, kHyperlinkPluginID, kHyperlinksPrefix + 1)

// Conversion
// For pub conversion constants see HyperlinkConversionID.h

// <Class ID>
// ClassIDs
DECLARE_PMID(kClassIDSpace, kHyperlinkBoss, kHyperlinksPrefix + 1)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextSourceBoss, kHyperlinksPrefix + 2)
DECLARE_PMID(kClassIDSpace, kHyperlinkPageItemSourceBoss, kHyperlinksPrefix + 3)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextDestinationBoss, kHyperlinksPrefix + 4)
DECLARE_PMID(kClassIDSpace, kHyperlinkPageDestinationBoss, kHyperlinksPrefix + 5)
DECLARE_PMID(kClassIDSpace, kHyperlinkURLDestinationBoss, kHyperlinksPrefix + 6)
//DECLARE_PMID(kClassIDSpace, kTextHyperlinkOwnedItemDataBoss, kHyperlinksPrefix + 7)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextMarkerBoss_Obsolete, kHyperlinksPrefix + 8)
DECLARE_PMID(kClassIDSpace, kPageItemHyperlinkAdornmentBoss, kHyperlinksPrefix + 10)
DECLARE_PMID(kClassIDSpace, kTextHyperlinkAdornmentBoss, kHyperlinksPrefix + 11)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkCmdBoss, kHyperlinksPrefix + 12)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkCmdBoss, kHyperlinksPrefix + 13)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkCmdBoss, kHyperlinksPrefix + 14)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkPgItemSourceCmdBoss, kHyperlinksPrefix + 15)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkTextSourceCmdBoss, kHyperlinksPrefix + 16)
DECLARE_PMID(kClassIDSpace, kHyperlinkDrawEventServicesBoss, kHyperlinksPrefix + 17)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkSourceCmdBoss, kHyperlinksPrefix + 18)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkTextDestCmdBoss, kHyperlinksPrefix + 19)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkPageDestCmdBoss, kHyperlinksPrefix + 20)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkURLDestCmdBoss, kHyperlinksPrefix + 21)
DECLARE_PMID(kClassIDSpace, kHyperlinkAttributeBoss,			kHyperlinksPrefix + 22)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkDestinationCmdBoss, kHyperlinksPrefix + 23)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextSourceMementoBoss, kHyperlinksPrefix + 24)
DECLARE_PMID(kClassIDSpace, kHyperlinkNewDocResponderBoss, kHyperlinksPrefix + 25)
DECLARE_PMID(kClassIDSpace, kHyperlinkErrorStringServiceBoss, kHyperlinksPrefix + 26)
DECLARE_PMID(kClassIDSpace, kHyperlinkScriptProviderBoss, kHyperlinksPrefix + 27)
DECLARE_PMID(kClassIDSpace, kHyperlinksActionRegisterBoss, kHyperlinksPrefix + 28)
DECLARE_PMID(kClassIDSpace, kMoveHyperlinksCmdBoss, kHyperlinksPrefix + 29)
DECLARE_PMID(kClassIDSpace, kCubitsBoss, kHyperlinksPrefix + 30)
DECLARE_PMID(kClassIDSpace, kBaseHyperlinkSourceBoss, kHyperlinksPrefix + 31)
DECLARE_PMID(kClassIDSpace, kBaseHyperlinkDestinationBoss, kHyperlinksPrefix + 32)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextSourceScriptProviderBoss, kHyperlinksPrefix + 33)
DECLARE_PMID(kClassIDSpace, kHyperlinkPageItemSourceScriptProviderBoss, kHyperlinksPrefix + 34)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextDestScriptProviderBoss, kHyperlinksPrefix + 35)
DECLARE_PMID(kClassIDSpace, kHyperlinkPageDestScriptProviderBoss, kHyperlinksPrefix + 36)
DECLARE_PMID(kClassIDSpace, kHyperlinkURLDestScriptProviderBoss, kHyperlinksPrefix + 37)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkTextSourceCmdBoss, kHyperlinksPrefix + 38)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkPgItemSourceCmdBoss, kHyperlinksPrefix + 39)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkTextDestCmdBoss, kHyperlinksPrefix + 40)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkPageDestCmdBoss, kHyperlinksPrefix + 41)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkURLDestCmdBoss, kHyperlinksPrefix + 42)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkTextToPageCmdBoss, kHyperlinksPrefix + 43)
DECLARE_PMID(kClassIDSpace, kSetShowHyperlinksPrefsCmdBoss, kHyperlinksPrefix + 44)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkTextSrcCmdBoss, kHyperlinksPrefix + 45)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkPgItemSrcCmdBoss, kHyperlinksPrefix + 46)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkTextDestCmdBoss, kHyperlinksPrefix + 47)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkPageDestCmdBoss, kHyperlinksPrefix + 48)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkURLDestCmdBoss, kHyperlinksPrefix + 49)
DECLARE_PMID(kClassIDSpace, kHyperlinkOpenAppResponderBoss, kHyperlinksPrefix + 50)
DECLARE_PMID(kClassIDSpace, kCopyHyperlinkTextMarkerCmdBoss, kHyperlinksPrefix + 52)
DECLARE_PMID(kClassIDSpace, kHyperLinkSuiteRegisterBoss, kHyperlinksPrefix + 53)
DECLARE_PMID(kClassIDSpace, kHyperlinkRefConverterBoss, kHyperlinksPrefix + 54)
DECLARE_PMID(kClassIDSpace, kDuplicateHyperlinkCmdBoss, kHyperlinksPrefix + 55)
DECLARE_PMID(kClassIDSpace, kDupHyperlinkPgItemSourceCmdBoss, kHyperlinksPrefix + 56)
DECLARE_PMID(kClassIDSpace, kUpdateHyperlinkDestinationInfoCmdBoss, kHyperlinksPrefix + 57)
DECLARE_PMID(kClassIDSpace, kDupHyperlinkTextSourceCmdBoss, kHyperlinksPrefix + 58)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextSourceEndMarkerBoss_Obsolete, kHyperlinksPrefix + 59)
DECLARE_PMID(kClassIDSpace, kHyperlinkTextDestinationMarkerBoss, kHyperlinksPrefix + 60)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkDestinationCmdBoss, kHyperlinksPrefix + 61)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkDestinationCmdBoss, kHyperlinksPrefix + 62)
DECLARE_PMID(kClassIDSpace, kHyperlinkDeletePageItemServiceBoss, kHyperlinksPrefix + 63)
DECLARE_PMID(kClassIDSpace, kHyperlinkStripCharServiceBoss, kHyperlinksPrefix + 64)
DECLARE_PMID(kClassIDSpace, kHyperlinkStartOwnedItemMementoBoss, kHyperlinksPrefix + 65)
DECLARE_PMID(kClassIDSpace, kHyperlinkConversionProviderBoss, kHyperlinksPrefix + 66)
DECLARE_PMID(kClassIDSpace, kHyperlinkDestOwnedItemMementoBoss, kHyperlinksPrefix + 67)
DECLARE_PMID(kClassIDSpace, kHyperlinkEndOwnedItemMementoBoss, kHyperlinksPrefix + 68)
DECLARE_PMID(kClassIDSpace, kHyperlinkExtraScrapDataBoss, kHyperlinksPrefix + 69)
DECLARE_PMID(kClassIDSpace, kDupHyperlinkPageDestCmdBoss, kHyperlinksPrefix + 70)
DECLARE_PMID(kClassIDSpace, kDupHyperlinkTextDestCmdBoss, kHyperlinksPrefix + 71)
//DECLARE_PMID(kClassIDSpace, kMyFancyNewBoss, kHyperlinksPrefix + 72)
DECLARE_PMID(kClassIDSpace, kHyperlinkEndAttributeBoss, kHyperlinksPrefix + 73)
//DECLARE_PMID(kClassIDSpace, kClearHyperlinkOwnedItemCmdBoss, kHyperlinksPrefix + 74)
DECLARE_PMID(kClassIDSpace, kHyperlinkPhase2ConversionBoss, kHyperlinksPrefix + 75)
DECLARE_PMID(kClassIDSpace, kBookmarkBoss, kHyperlinksPrefix + 76)
DECLARE_PMID(kClassIDSpace, kNewBookmarkCmdBoss, kHyperlinksPrefix + 77)
DECLARE_PMID(kClassIDSpace, kDeleteBookmarkCmdBoss, kHyperlinksPrefix + 78)
DECLARE_PMID(kClassIDSpace, kChangeBookmarkCmdBoss, kHyperlinksPrefix + 79)
DECLARE_PMID(kClassIDSpace, kMoveBookmarkCmdBoss, kHyperlinksPrefix + 80)
DECLARE_PMID(kClassIDSpace, kBookmarkScriptProviderBoss, kHyperlinksPrefix + 81)
DECLARE_PMID(kClassIDSpace, kHyperlinkExternalPageDestinationBoss, kHyperlinksPrefix + 82)
DECLARE_PMID(kClassIDSpace, kNewHyperlinkExternalPageDestCmdBoss, kHyperlinksPrefix + 83)
DECLARE_PMID(kClassIDSpace, kDeleteHyperlinkExternalPageDestCmdBoss, kHyperlinksPrefix + 84)
DECLARE_PMID(kClassIDSpace, kChangeHyperlinkExternalPageDestCmdBoss, kHyperlinksPrefix + 85)
DECLARE_PMID(kClassIDSpace, kDupHyperlinkExternalPageDestCmdBoss, kHyperlinksPrefix + 86)
DECLARE_PMID(kClassIDSpace, kHyperlinkExternalPageDestScriptProviderBoss, kHyperlinksPrefix + 87)
DECLARE_PMID(kClassIDSpace, kSortBookmarksCmdBoss, kHyperlinksPrefix + 88)
DECLARE_PMID(kClassIDSpace, kSetOwnedItemCmdBoss, kHyperlinksPrefix + 89)
DECLARE_PMID(kClassIDSpace, kHyperlinkCodeConversionBoss, kHyperlinksPrefix + 90)
DECLARE_PMID(kClassIDSpace, kUpdateXRefTextSourceCmdBoss, kHyperlinksPrefix + 91)
DECLARE_PMID(kClassIDSpace, kHyperlinkNewLinkConverterBoss, kHyperlinksPrefix + 92)
DECLARE_PMID(kClassIDSpace, kChangeXRefFormatCmdBoss, kHyperlinksPrefix + 93)
DECLARE_PMID(kClassIDSpace, kXRefFormatBoss, kHyperlinksPrefix + 94)
DECLARE_PMID(kClassIDSpace, kNewXRefFormatCmdBoss, kHyperlinksPrefix + 95)
DECLARE_PMID(kClassIDSpace, kDeleteXRefFormatCmdBoss, kHyperlinksPrefix + 96)
DECLARE_PMID(kClassIDSpace, kXRefFormatScriptProviderBoss, kHyperlinksPrefix + 97)
DECLARE_PMID(kClassIDSpace, kXRefBuildingBlockScriptProviderBoss, kHyperlinksPrefix + 98)
DECLARE_PMID(kClassIDSpace, kXRefBuildingBlockScriptObjectBoss, kHyperlinksPrefix + 99)
DECLARE_PMID(kClassIDSpace, kLoadXRefFormatCmdBoss, kHyperlinksPrefix + 100)
DECLARE_PMID(kClassIDSpace, kXRefFormatSyncServiceBoss, kHyperlinksPrefix + 101)
DECLARE_PMID(kClassIDSpace, kBookUpdateXRefCmdBoss, kHyperlinksPrefix + 102)
DECLARE_PMID(kClassIDSpace, kCheckXRefStatusCmdBoss, kHyperlinksPrefix + 103)
DECLARE_PMID(kClassIDSpace, kHyperlinkOpenDocResponderBoss, kHyperlinksPrefix + 104)
DECLARE_PMID(kClassIDSpace, kHyperlinkCloseDocResponderBoss, kHyperlinksPrefix + 105)
DECLARE_PMID(kClassIDSpace, kMarkXRefsForStoryChangeCmdBoss, kHyperlinksPrefix + 106)
DECLARE_PMID(kClassIDSpace, kMarkXRefNeedStatusCheckCmdBoss, kHyperlinksPrefix + 107)
DECLARE_PMID(kClassIDSpace, kXRefFormatContentHandlerBoss, kHyperlinksPrefix + 108)
DECLARE_PMID(kClassIDSpace, kHyperlinksRIDXNotifierHandlerBoss, kHyperlinksPrefix + 109)
DECLARE_PMID(kClassIDSpace, kSaveDocChangeCountCmdBoss, kHyperlinksPrefix + 110)
DECLARE_PMID(kClassIDSpace, kTextDestHyperlinkAdornmentBoss, kHyperlinksPrefix + 111)
DECLARE_PMID(kClassIDSpace, kHyperlinkTDSM2MListenerServiceBoss, kHyperlinksPrefix + 112)
DECLARE_PMID(kClassIDSpace, kUpdateXRefStatusCmdBoss, kHyperlinksPrefix + 113)
DECLARE_PMID(kClassIDSpace, kHyperlinkAfterSaveAsDocResponderBoss, kHyperlinksPrefix + 114)
DECLARE_PMID(kClassIDSpace, kHyperlinkAfterOpenDocResponderBoss, kHyperlinksPrefix + 115)
DECLARE_PMID(kClassIDSpace, kTextHyperlinkAdornmentForExportBoss, kHyperlinksPrefix + 116)
DECLARE_PMID(kClassIDSpace, kHyperlinkSetIconCmdBoss, kHyperlinksPrefix + 117)

// <Interface ID>
// IIDs
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTABLE, kHyperlinksPrefix + 1)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINK, kHyperlinksPrefix + 2)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKDESTINATION, kHyperlinksPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKSOURCE, kHyperlinksPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_ITEXTHYPERLINKOWNEDITEMDATA, kHyperlinksPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKCMDDATA, kHyperlinksPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKPAGEUIDDATA, kHyperlinksPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTMARKER, kHyperlinksPrefix + 8)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTSOURCEDATA_OBSOLETE, kHyperlinksPrefix + 9)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKPAGEITEMSOURCEDATA, kHyperlinksPrefix + 10)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKPAGEITEMDATA, kHyperlinksPrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKNAMEDATA, kHyperlinksPrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTDESTINATIONDATA, kHyperlinksPrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKPAGEDESTINATIONDATA, kHyperlinksPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKSUITE, kHyperlinksPrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_ISHOWHYPERLINKSPREFERENCES, kHyperlinksPrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_IBOOKMARKDATA, kHyperlinksPrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKAPPEARANCEDATA, kHyperlinksPrefix + 18)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKOBSERVER, kHyperlinksPrefix + 19)
DECLARE_PMID(kInterfaceIDSpace, IID_IDESTINFODATA, kHyperlinksPrefix + 22)
DECLARE_PMID(kInterfaceIDSpace, IID_IDUPHYPERLINKTEXTSOURCEDATA, kHyperlinksPrefix + 23)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKEXTRASCRAPDATA, kHyperlinksPrefix + 24)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKMARKERTARGETSTORY, kHyperlinksPrefix + 25)
DECLARE_PMID(kInterfaceIDSpace, IID_IINTLIST, kHyperlinksPrefix + 26)
DECLARE_PMID(kInterfaceIDSpace, IID_IMANUALNAME, kHyperlinksPrefix + 27)
DECLARE_PMID(kInterfaceIDSpace, IID_IBOOKMARKUTILS, kHyperlinksPrefix + 28)
DECLARE_PMID(kInterfaceIDSpace, IID_ILINKEDBOOKMARKDATA, kHyperlinksPrefix + 29)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGEINDEXDATA, kHyperlinksPrefix + 30)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKUTILS, kHyperlinksPrefix + 31)
DECLARE_PMID(kInterfaceIDSpace, IID_ICLEANUPTEXTDATA, kHyperlinksPrefix + 32)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKDESTINATIONUI, kHyperlinksPrefix + 33)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKSOURCEUI, kHyperlinksPrefix + 34)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKCHANGE, kHyperlinksPrefix + 35)
DECLARE_PMID(kInterfaceIDSpace, IID_IBOOKMARKCHANGE, kHyperlinksPrefix + 36)
DECLARE_PMID(kInterfaceIDSpace, IID_IDESTINATIONCHANGE, kHyperlinksPrefix + 37)
DECLARE_PMID(kInterfaceIDSpace, IID_ISOURCECHANGE, kHyperlinksPrefix + 38)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWHYPERLINKTEXTDESTCMDDATA, kHyperlinksPrefix + 39)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTDESTINATIONMARKER, kHyperlinksPrefix + 40)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTSOURCEDATA, kHyperlinksPrefix + 41)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKLINKUTILS, kHyperlinksPrefix + 42)
DECLARE_PMID(kInterfaceIDSpace, IID_ILINKRESOURCEPERSISTUIDDATA, kHyperlinksPrefix + 43)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWHYPERLINKPAGEDESTCMDDATA, kHyperlinksPrefix + 44)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWHLEXTERNPAGEDESTCMDDATA, kHyperlinksPrefix + 45)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWHYPERLINKURLDESTCMDDATA, kHyperlinksPrefix + 46)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTSOURCECMDDATA, kHyperlinksPrefix + 47)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFFORMATCMDDATA, kHyperlinksPrefix + 48)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFFORMAT, kHyperlinksPrefix + 49)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFFORMATCHANGE, kHyperlinksPrefix + 50)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKFACADE, kHyperlinksPrefix + 51)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKUIFACADE, kHyperlinksPrefix + 52)
DECLARE_PMID(kInterfaceIDSpace, IID_IBOOKMARKFACADE, kHyperlinksPrefix + 53)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFINFODATA, kHyperlinksPrefix + 54)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFSTATUSUPDATETABLE, kHyperlinksPrefix + 55)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKLINKOBSERVER, kHyperlinksPrefix + 56)
DECLARE_PMID(kInterfaceIDSpace, IID_IXREFSTATUSDETECTIDLETASK, kHyperlinksPrefix + 57)
DECLARE_PMID(kInterfaceIDSpace, IID_IBOOKUPDATEXREFCMDDATA, kHyperlinksPrefix + 58)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTDESTINATIONSTATE, kHyperlinksPrefix + 59)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKTEXTDESTINATIONSTATE_CHANGED, kHyperlinksPrefix + 60)
DECLARE_PMID(kInterfaceIDSpace, IID_IURLACCESS, kHyperlinksPrefix + 61)
DECLARE_PMID(kInterfaceIDSpace, IID_IDIRECTCHANGE, kHyperlinksPrefix + 62)
DECLARE_PMID(kInterfaceIDSpace, IID_IHYPERLINKREBASECACHE, kHyperlinksPrefix + 63)
DECLARE_PMID(kInterfaceIDSpace, IID_ILINKSOURCEALTDESTINATION, kHyperlinksPrefix + 64)
DECLARE_PMID(kInterfaceIDSpace, IID_PLUGINDATA, kHyperlinksPrefix + 65)
DECLARE_PMID(kInterfaceIDSpace, IID_IEXTERNALDOCCHANGE, kHyperlinksPrefix + 66)


// <Implementation ID>
// Implementation IIDs
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTableImpl, kHyperlinksPrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkImpl, kHyperlinksPrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkScriptImpl, kHyperlinksPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceImpl, kHyperlinksPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemSourceImpl, kHyperlinksPrefix + 5)
//DECLARE_PMID(kImplementationIDSpace, kTextHyperlinkOwnedItemDataImpl, kHyperlinksPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageDestinationImpl, kHyperlinksPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestinationImpl, kHyperlinksPrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkURLDestinationImpl, kHyperlinksPrefix + 9)
DECLARE_PMID(kImplementationIDSpace, kPageItemHyperlinkAdornmentImpl, kHyperlinksPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kTextHyperlinkAdornmentImpl, kHyperlinksPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkCmdDataImpl, kHyperlinksPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkCmdImpl, kHyperlinksPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestinationCmdDataImpl, kHyperlinksPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSourceCmdDataImpl, kHyperlinksPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkTextSourceCmdImpl, kHyperlinksPrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkPgItemSourceCmdImpl, kHyperlinksPrefix + 18)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkURLDestCmdImpl, kHyperlinksPrefix + 19)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkTextDestCmdImpl, kHyperlinksPrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkPageDestCmdImpl, kHyperlinksPrefix + 21)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkCmdImpl, kHyperlinksPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNameDataImpl, kHyperlinksPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkAttrReportImpl, kHyperlinksPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkCmdImpl, kHyperlinksPrefix + 25)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkDestCmdImpl, kHyperlinksPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkSourceCmdImpl, kHyperlinksPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkErrorStringServiceImpl, kHyperlinksPrefix + 28)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemDataImpl, kHyperlinksPrefix + 29)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextMarkerImpl_Obsolete, kHyperlinksPrefix + 30)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkScriptProviderImpl, kHyperlinksPrefix + 32)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteLayoutCSBImpl, kHyperlinksPrefix + 33)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteTextCSBImpl, kHyperlinksPrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteASBImpl, kHyperlinksPrefix + 35)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceDataImpl_Obsolete, kHyperlinksPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemSourceDataImpl, kHyperlinksPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestDataImpl, kHyperlinksPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageDestDataImpl, kHyperlinksPrefix + 39)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceMementoImpl, kHyperlinksPrefix + 40)
DECLARE_PMID(kImplementationIDSpace, kMoveHyperlinksCmdImpl, kHyperlinksPrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kCubitsImpl, kHyperlinksPrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestinationMarkerImpl, kHyperlinksPrefix + 43)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceScriptProviderImpl, kHyperlinksPrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceScriptImpl, kHyperlinksPrefix + 45)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceDataImpl, kHyperlinksPrefix + 46)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemSourceScriptProviderImpl, kHyperlinksPrefix + 47)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemSourceScriptImpl, kHyperlinksPrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kUpdateXRefTextSourceCmdImpl, kHyperlinksPrefix + 49)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestScriptProviderImpl, kHyperlinksPrefix + 50)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestScriptImpl, kHyperlinksPrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkURLDestCmdDataImpl, kHyperlinksPrefix + 52)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageDestScriptProviderImpl, kHyperlinksPrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageDestScriptImpl, kHyperlinksPrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDocResponderImpl, kHyperlinksPrefix + 55)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkURLDestScriptProviderImpl, kHyperlinksPrefix + 56)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkURLDestScriptImpl, kHyperlinksPrefix + 57)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkPgItemSourceCmdImpl, kHyperlinksPrefix + 58)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkTextSourceCmdImpl, kHyperlinksPrefix + 59)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkPageDestCmdImpl, kHyperlinksPrefix + 60)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkTextDestCmdImpl, kHyperlinksPrefix + 61)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkURLDestCmdImpl, kHyperlinksPrefix + 62)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDrawEventHandlerImpl, kHyperlinksPrefix + 63)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDrawEventServiceImpl, kHyperlinksPrefix + 64)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkTextToPageCmdImpl, kHyperlinksPrefix + 65)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageUIDDataImpl, kHyperlinksPrefix + 66)
DECLARE_PMID(kImplementationIDSpace, kDocShowHyperlinksPrefsImpl, kHyperlinksPrefix + 67)
DECLARE_PMID(kImplementationIDSpace, kSessionShowHyperlinksPrefsImpl, kHyperlinksPrefix + 68)
DECLARE_PMID(kImplementationIDSpace, kSetShowHyperlinksPrefsCmdImpl, kHyperlinksPrefix + 69)
DECLARE_PMID(kImplementationIDSpace, kCShowHyperlinksPrefsImpl, kHyperlinksPrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kBookMarkDataImpl, kHyperlinksPrefix + 71)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextMarkerScrapImpl, kHyperlinksPrefix + 72)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageItemSrcScrapImpl, kHyperlinksPrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceScrapImpl, kHyperlinksPrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestScrapImpl, kHyperlinksPrefix + 75)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPageDestScrapImpl, kHyperlinksPrefix + 76)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkURLDestScrapImpl, kHyperlinksPrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkTextDestCmdImpl, kHyperlinksPrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkTextSrcCmdImpl, kHyperlinksPrefix + 79)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkPgItemSrcCmdImpl, kHyperlinksPrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkURLDestCmdImpl, kHyperlinksPrefix + 81)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkPageDestCmdImpl, kHyperlinksPrefix + 82)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkAppearanceDataImpl, kHyperlinksPrefix + 83)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkOpenAppResponderImpl, kHyperlinksPrefix + 84)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkObserverImpl, kHyperlinksPrefix + 85)
DECLARE_PMID(kImplementationIDSpace, kCopyHyperlinkTextMarkerCmdImpl, kHyperlinksPrefix + 88)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkOwnedItemImpl, kHyperlinksPrefix + 89)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkRefConverterImpl, kHyperlinksPrefix + 90)
DECLARE_PMID(kImplementationIDSpace, kDuplicateHyperlinkCmdImpl, kHyperlinksPrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkPgItemSourceCmdImpl, kHyperlinksPrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkScrapImpl, kHyperlinksPrefix + 93)
DECLARE_PMID(kImplementationIDSpace, kUpdateHyperlinkDestinationInfoCmdImpl, kHyperlinksPrefix + 94)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkURLDataImpl, kHyperlinksPrefix + 96)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkTextSourceCmdImpl, kHyperlinksPrefix + 97)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkTextSourceDataImpl, kHyperlinksPrefix + 98)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDeleteCleanupServiceImpl, kHyperlinksPrefix + 99)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkStripCharServiceImpl, kHyperlinksPrefix + 100)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkStartOwnedItemImpl, kHyperlinksPrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestInfoDataImpl, kHyperlinksPrefix + 102)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestOwnedItemImpl, kHyperlinksPrefix + 103)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkEndOwnedItemImpl, kHyperlinksPrefix + 104)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkStrtOwndItmMementoImpl, kHyperlinksPrefix + 105)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkEndOwndItemMementoImpl, kHyperlinksPrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkDestOwndItmMementoImpl, kHyperlinksPrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkPageDestCmdImpl, kHyperlinksPrefix + 108)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExtraScrapDataImpl, kHyperlinksPrefix + 109)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkMarkerTargetStoryUIDDataImpl, kHyperlinksPrefix + 110)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkTextDestCmdImpl, kHyperlinksPrefix + 111)
DECLARE_PMID(kImplementationIDSpace, kPersistIntListImpl, kHyperlinksPrefix + 112)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextDestinationStateImpl, kHyperlinksPrefix + 113)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkEndAttrReportImpl, kHyperlinksPrefix + 114)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTDSM2MListenerImpl, kHyperlinksPrefix + 115)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkPhase2ConversionImpl, kHyperlinksPrefix + 116)
DECLARE_PMID(kImplementationIDSpace, kNameWithPageDataImpl, kHyperlinksPrefix + 117)
DECLARE_PMID(kImplementationIDSpace, kNewBookmarkCmdImpl, kHyperlinksPrefix + 118)
DECLARE_PMID(kImplementationIDSpace, kDeleteBookmarkCmdImpl, kHyperlinksPrefix + 119)
DECLARE_PMID(kImplementationIDSpace, kChangeBookmarkCmdImpl, kHyperlinksPrefix + 120)
DECLARE_PMID(kImplementationIDSpace, kMoveBookmarkCmdImpl, kHyperlinksPrefix + 121)
DECLARE_PMID(kImplementationIDSpace, kBookmarkUtilsImpl, kHyperlinksPrefix + 122)
DECLARE_PMID(kImplementationIDSpace, kLinkedBookmarkDataImpl, kHyperlinksPrefix + 123)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSourceTextRangeItemImpl, kHyperlinksPrefix + 124)
DECLARE_PMID(kImplementationIDSpace, kBookmarkScriptImpl, kHyperlinksPrefix + 125)
DECLARE_PMID(kImplementationIDSpace, kNewHLExternPageDestCmdDataImpl, kHyperlinksPrefix + 126)
DECLARE_PMID(kImplementationIDSpace, kBookmarkScriptProviderImpl, kHyperlinksPrefix + 127)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExternalPageDestinationImpl, kHyperlinksPrefix + 128)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkExternalPageDestCmdImpl, kHyperlinksPrefix + 129)
DECLARE_PMID(kImplementationIDSpace, kDeleteHyperlinkExternalPageDestCmdImpl, kHyperlinksPrefix + 130)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExternalPageDestScrapImpl, kHyperlinksPrefix + 131)
DECLARE_PMID(kImplementationIDSpace, kChangeHyperlinkExternalPageDestCmdImpl, kHyperlinksPrefix + 132)
DECLARE_PMID(kImplementationIDSpace, kDupHyperlinkExternalPageDestCmdImpl, kHyperlinksPrefix + 133)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExternalPageDestScriptImpl, kHyperlinksPrefix + 134)
DECLARE_PMID(kImplementationIDSpace, kCleanUpTextDataImpl, kHyperlinksPrefix + 135)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkExternalPageDestScriptProviderImpl, kHyperlinksPrefix + 136)
DECLARE_PMID(kImplementationIDSpace, kPageIndexDataImpl, kHyperlinksPrefix + 137)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkUtilsImpl, kHyperlinksPrefix + 138)
DECLARE_PMID(kImplementationIDSpace, kSortBookmarksCmdImpl, kHyperlinksPrefix + 139)
DECLARE_PMID(kImplementationIDSpace, kSetOwnedItemCmdImpl, kHyperlinksPrefix + 140)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkConversionProviderImpl, kHyperlinksPrefix + 141)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkTextDestCmdDataImpl, kHyperlinksPrefix + 142)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkLinkUtilsImpl, kHyperlinksPrefix + 143)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkNewLinkConverterImpl, kHyperlinksPrefix + 144)
DECLARE_PMID(kImplementationIDSpace, kNewHyperlinkPageDestCmdDataImpl, kHyperlinksPrefix + 145)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatCmdDataImpl, kHyperlinksPrefix + 146)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatImpl, kHyperlinksPrefix + 147)
DECLARE_PMID(kImplementationIDSpace, kNewXRefFormatCmdImpl, kHyperlinksPrefix + 148)
DECLARE_PMID(kImplementationIDSpace, kDeleteXRefFormatCmdImpl, kHyperlinksPrefix + 149)
DECLARE_PMID(kImplementationIDSpace, kChangeXRefFormatCmdImpl, kHyperlinksPrefix + 150)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkTextSourceCmdDataImpl, kHyperlinksPrefix + 151)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatScriptImpl, kHyperlinksPrefix + 152)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatScriptProviderImpl, kHyperlinksPrefix + 153)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkFacadeImpl, kHyperlinksPrefix + 154)
DECLARE_PMID(kImplementationIDSpace, kXRefBuildingBlockScriptImpl, kHyperlinksPrefix + 155)
DECLARE_PMID(kImplementationIDSpace, kXRefBuildingBlockScriptProviderImpl, kHyperlinksPrefix + 156)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkUIFacadeImpl, kHyperlinksPrefix + 157)
DECLARE_PMID(kImplementationIDSpace, kBookmarkFacadeImpl, kHyperlinksPrefix + 158)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkLinkObjectImpl, kHyperlinksPrefix + 159)
DECLARE_PMID(kImplementationIDSpace, kXRefInfoDataImpl, kHyperlinksPrefix + 160)
DECLARE_PMID(kImplementationIDSpace, kLoadXRefFormatCmdImpl, kHyperlinksPrefix + 161)
DECLARE_PMID(kImplementationIDSpace, kLoadXRefFormatCmdInfoImpl, kHyperlinksPrefix + 162)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatSyncServiceImpl, kHyperlinksPrefix + 163)
DECLARE_PMID(kImplementationIDSpace, kXRefStatusUpdateTableImpl, kHyperlinksPrefix + 164)
DECLARE_PMID(kImplementationIDSpace, kXRefStatusDetectIdleTaskImpl, kHyperlinksPrefix + 165)
DECLARE_PMID(kImplementationIDSpace, kCheckXRefStatusCmdImpl, kHyperlinksPrefix + 166)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkLinkObserverImpl, kHyperlinksPrefix + 167)
DECLARE_PMID(kImplementationIDSpace, kMarkXRefsForStoryChangeCmdImpl, kHyperlinksPrefix + 168)
DECLARE_PMID(kImplementationIDSpace, kMarkXRefNeedStatusCheckCmdImpl, kHyperlinksPrefix + 169)
DECLARE_PMID(kImplementationIDSpace, kXRefFormatContentHandlerImpl, kHyperlinksPrefix + 170)
DECLARE_PMID(kImplementationIDSpace, kBookUpdateXRefCmdImpl, kHyperlinksPrefix + 171)
DECLARE_PMID(kImplementationIDSpace, kBookUpdateXRefCmdDataImpl, kHyperlinksPrefix + 172)
DECLARE_PMID(kImplementationIDSpace, kHyperlinksRIDXNotifierHandlerImpl, kHyperlinksPrefix + 173)
DECLARE_PMID(kImplementationIDSpace, kSaveDocChangeCountCmdImpl, kHyperlinksPrefix + 174)
DECLARE_PMID(kImplementationIDSpace, kTextDestHyperlinkAdornmentImpl, kHyperlinksPrefix + 175)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteLayoutCSBExtImpl,kHyperlinksPrefix + 176)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSuiteTextCSBExtImpl,	kHyperlinksPrefix + 177)
DECLARE_PMID(kImplementationIDSpace, kURLAccessImpl, kHyperlinksPrefix + 178) 
DECLARE_PMID(kImplementationIDSpace, kUpdateXRefStatusCmdImpl,	kHyperlinksPrefix + 179)
DECLARE_PMID(kImplementationIDSpace, kDirectChangeImpl,	kHyperlinksPrefix + 180)
DECLARE_PMID(kImplementationIDSpace, kTextHyperlinkAdornmentForExportImpl, kHyperlinksPrefix + 181)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkRebaseCacheImpl, kHyperlinksPrefix + 182)
DECLARE_PMID(kImplementationIDSpace, kLinkSourceAltDestinationImpl, kHyperlinksPrefix + 183)
DECLARE_PMID(kImplementationIDSpace, kHyperlinkSetIconCmdImpl, kHyperlinksPrefix + 184)
DECLARE_PMID(kImplementationIDSpace, kPluginDataImpl, kHyperlinksPrefix + 185)


// <Service ID>
// Service IDs
DECLARE_PMID(kServiceIDSpace, kHyperlinkStripCharService, kHyperlinksPrefix + 1)

DECLARE_PMID(kServiceIDSpace, kURLDestinationUIService, kHyperlinksPrefix + 2)
DECLARE_PMID(kServiceIDSpace, kTextDestinationUIService, kHyperlinksPrefix + 3)
DECLARE_PMID(kServiceIDSpace, kPageDestinationUIService, kHyperlinksPrefix + 4)
DECLARE_PMID(kServiceIDSpace, kExternalPageDestinationUIService, kHyperlinksPrefix + 5)

DECLARE_PMID(kServiceIDSpace, kTextSourceUIService, kHyperlinksPrefix + 6)
DECLARE_PMID(kServiceIDSpace, kPageItemSourceUIService, kHyperlinksPrefix + 7)

DECLARE_PMID(kServiceIDSpace, kPageItemDestinationUIService, kHyperlinksPrefix + 8)

// <Error ID>
// Error Codes
DECLARE_PMID(kErrorIDSpace, kHyperlinkTargetFileNotSavedError, kHyperlinksPrefix + 1)
DECLARE_PMID(kErrorIDSpace, kHyperlinkTargetAlreadyOpenError, kHyperlinksPrefix + 2)
DECLARE_PMID(kErrorIDSpace, kHyperlinkDestinationInvalid, kHyperlinksPrefix + 3)
DECLARE_PMID(kErrorIDSpace, kHyperlinkSourceInvalid, kHyperlinksPrefix + 4)
DECLARE_PMID(kErrorIDSpace, kHyperlinkWrongDocumentErr, kHyperlinksPrefix + 5)
DECLARE_PMID(kErrorIDSpace, kHyperlinkInvalidNameErr, kHyperlinksPrefix + 6)
DECLARE_PMID(kErrorIDSpace, kHyperlinkObjectInUseErr, kHyperlinksPrefix + 7)
DECLARE_PMID(kErrorIDSpace, kHyperlinkZeroRangeSourceErr, kHyperlinksPrefix + 8)
DECLARE_PMID(kErrorIDSpace, kHyperlinkNoMarkerErr, kHyperlinksPrefix + 9)
DECLARE_PMID(kErrorIDSpace, kHyperlinkDocumentInvalid, kHyperlinksPrefix + 10)
DECLARE_PMID(kErrorIDSpace, kHyperlinkManualNameNotAllowedErr, kHyperlinksPrefix + 11)
DECLARE_PMID(kErrorIDSpace, kBookmarkEmptyListErr, kHyperlinksPrefix + 12)
DECLARE_PMID(kErrorIDSpace, kBookmarkMissingErr, kHyperlinksPrefix + 13)
DECLARE_PMID(kErrorIDSpace, kBookmarkEmptyNameErr, kHyperlinksPrefix + 14)
DECLARE_PMID(kErrorIDSpace, kUpdateHyperlinkDocumentInvalid, kHyperlinksPrefix + 15)
DECLARE_PMID(kErrorIDSpace, kHyperlinkExternalDocsNotOpenErr, kHyperlinksPrefix + 16)
DECLARE_PMID(kErrorIDSpace, kDocumentNotFoundErr, kHyperlinksPrefix + 17)
DECLARE_PMID(kErrorIDSpace, kDocumentNotSavedError, kHyperlinksPrefix + 18)
DECLARE_PMID(kErrorIDSpace, kHyperlinkPageDoesNotExistErr, kHyperlinksPrefix + 19)
DECLARE_PMID(kErrorIDSpace, kDocumentsMayNotMatchError, kHyperlinksPrefix + 20)
DECLARE_PMID(kErrorIDSpace, kDataBaseNotFoundError, kHyperlinksPrefix + 21)
DECLARE_PMID(kErrorIDSpace, kCreatingCircularBookmarkRelationshipErr, kHyperlinksPrefix + 22)
DECLARE_PMID(kErrorIDSpace, kXRefFormatInUseErr, kHyperlinksPrefix + 23)
DECLARE_PMID(kErrorIDSpace, kHiddenDestinationInUseErr, kHyperlinksPrefix + 24)
DECLARE_PMID(kErrorIDSpace, kCanNotChangeParaDestToNewParaErr, kHyperlinksPrefix + 25)
DECLARE_PMID(kErrorIDSpace, kInvalidXRefDestErr, kHyperlinksPrefix + 26)
DECLARE_PMID(kErrorIDSpace, kCharStyleNotFoundErr, kHyperlinksPrefix + 27)
DECLARE_PMID(kErrorIDSpace, kUnknownBuildingBlockErr, kHyperlinksPrefix + 28)
DECLARE_PMID(kErrorIDSpace, kInvalidDelimiterErr, kHyperlinksPrefix + 29)
DECLARE_PMID(kErrorIDSpace, kCannotDeletingLastFormatErr, kHyperlinksPrefix + 30)
DECLARE_PMID(kErrorIDSpace, kInvalidIncludeDelimValueErr, kHyperlinksPrefix + 31)
DECLARE_PMID(kErrorIDSpace, kInvalidXRefFormatStringErr, kHyperlinksPrefix + 32)
DECLARE_PMID(kErrorIDSpace, kNoBuildingBlockErr, kHyperlinksPrefix + 33)
DECLARE_PMID(kErrorIDSpace, kPartialXMLInRangeErr, kHyperlinksPrefix + 34)

// <LinkClient ID>
// LinkClientIDs
DECLARE_PMID(kLinkClientIDSpace, kHyperlinkLinkClientID, kHyperlinksPrefix + 1)

// <Global ID>
//DECLARE_PMID(kActionIDSpace, kXXXXXXXXActionID, kHyperlinksPrefix + 1)

DECLARE_PMID(kWidgetIDSpace, kBookUpdateXRefCompleteAlertWidgetID, kHyperlinksPrefix + 1)


//
//Script Element IDs
//

//Suites
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinksSuiteScriptElement,						kHyperlinksPrefix + 1)

//Objects
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkObjectScriptElement,						kHyperlinksPrefix + 20)
DECLARE_PMID(kScriptInfoIDSpace, kBookmarkObjectScriptElement,						kHyperlinksPrefix + 21)
DECLARE_PMID(kScriptInfoIDSpace, kPageItemSourceObjectScriptElement,				kHyperlinksPrefix + 22)
DECLARE_PMID(kScriptInfoIDSpace, kTextSourceObjectScriptElement,					kHyperlinksPrefix + 23)
DECLARE_PMID(kScriptInfoIDSpace, kTextDestinationObjectScriptElement,				kHyperlinksPrefix + 24)
DECLARE_PMID(kScriptInfoIDSpace, kPageDestinationObjectScriptElement,				kHyperlinksPrefix + 25)
DECLARE_PMID(kScriptInfoIDSpace, kExternalPageDestinationObjectScriptElement,		kHyperlinksPrefix + 26)
DECLARE_PMID(kScriptInfoIDSpace, kURLDestinationObjectScriptElement,				kHyperlinksPrefix + 27)
DECLARE_PMID(kScriptInfoIDSpace, kXRefFormatObjectScriptElement,				kHyperlinksPrefix + 28)
DECLARE_PMID(kScriptInfoIDSpace, kXRefSourceObjectScriptElement,				kHyperlinksPrefix + 29)
DECLARE_PMID(kScriptInfoIDSpace, kXRefBuildingBlockObjectScriptElement,				kHyperlinksPrefix + 30)
DECLARE_PMID(kScriptInfoIDSpace, kParagraphDestinationObjectScriptElement,				kHyperlinksPrefix + 31)

//Events
DECLARE_PMID(kScriptInfoIDSpace, kCreateHyperlinkMethodScriptElement,				kHyperlinksPrefix + 80)
DECLARE_PMID(kScriptInfoIDSpace, kShowSourceMethodScriptElement,						kHyperlinksPrefix + 81)
DECLARE_PMID(kScriptInfoIDSpace, kShowDestinationMethodScriptElement,				kHyperlinksPrefix + 82)
DECLARE_PMID(kScriptInfoIDSpace, kCreateBookmarkMethodScriptElement,					kHyperlinksPrefix + 83)
DECLARE_PMID(kScriptInfoIDSpace, kShowBookmarkMethodScriptElement,					kHyperlinksPrefix + 84)
DECLARE_PMID(kScriptInfoIDSpace, kMoveBookmarkMethodScriptElement,					kHyperlinksPrefix + 85)
DECLARE_PMID(kScriptInfoIDSpace, kCreatePageItemSourceMethodScriptElement,			kHyperlinksPrefix + 86)
DECLARE_PMID(kScriptInfoIDSpace, kCreateTextSourceMethodScriptElement,				kHyperlinksPrefix + 87)
DECLARE_PMID(kScriptInfoIDSpace, kCreateTextDestinationMethodScriptElement,			kHyperlinksPrefix + 88)
DECLARE_PMID(kScriptInfoIDSpace, kCreatePageDestinationMethodScriptElement,			kHyperlinksPrefix + 89)
DECLARE_PMID(kScriptInfoIDSpace, kCreateExternalPageDestinationMethodScriptElement,	kHyperlinksPrefix + 90)
DECLARE_PMID(kScriptInfoIDSpace, kCreateURLDestinationMethodScriptElement,			kHyperlinksPrefix + 91)
DECLARE_PMID(kScriptInfoIDSpace, kCreateXRefFormatMethodScriptElement,			kHyperlinksPrefix + 92)
DECLARE_PMID(kScriptInfoIDSpace, kUpdateXRefSourceMethodScriptElement,			kHyperlinksPrefix + 93)
DECLARE_PMID(kScriptInfoIDSpace, kCreateXRefSourceMethodScriptElement,			kHyperlinksPrefix + 94)
DECLARE_PMID(kScriptInfoIDSpace, kCreateXRefBuildingBlockMethodScriptElement,			kHyperlinksPrefix + 95)
DECLARE_PMID(kScriptInfoIDSpace, kCreateParagraphDestinationMethodScriptElement,		kHyperlinksPrefix + 96)
DECLARE_PMID(kScriptInfoIDSpace, kLoadXRefFormatMethodScriptElement,					kHyperlinksPrefix + 97)
DECLARE_PMID(kScriptInfoIDSpace, kUpdateXRefSourcesMethodScriptElement,					kHyperlinksPrefix + 98)
DECLARE_PMID(kScriptInfoIDSpace, kFindIntersectingHyperlinksMethodScriptElement,			kHyperlinksPrefix + 99)

//Properties
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockIncludeDelimPropertyScriptElement,	kHyperlinksPrefix + 120)
DECLARE_PMID(kScriptInfoIDSpace, kSourcePropertyScriptElement,						kHyperlinksPrefix + 121)
DECLARE_PMID(kScriptInfoIDSpace, kDestinationPropertyScriptElement,					kHyperlinksPrefix + 122)
DECLARE_PMID(kScriptInfoIDSpace, kHighlightPropertyScriptElement,					kHyperlinksPrefix + 123)
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkBorderWidthPropertyScriptElement,		kHyperlinksPrefix + 124)
DECLARE_PMID(kScriptInfoIDSpace, kBorderStylePropertyScriptElement,					kHyperlinksPrefix + 125)
DECLARE_PMID(kScriptInfoIDSpace, kHiddenPropertyScriptElement,						kHyperlinksPrefix + 126)
DECLARE_PMID(kScriptInfoIDSpace, kIndentPropertyScriptElement,						kHyperlinksPrefix + 127)
DECLARE_PMID(kScriptInfoIDSpace, kSourcePageItemPropertyScriptElement,				kHyperlinksPrefix + 128)
DECLARE_PMID(kScriptInfoIDSpace, kSourceTextPropertyScriptElement,					kHyperlinksPrefix + 129)
DECLARE_PMID(kScriptInfoIDSpace, kDestinationTextPropertyScriptElement,				kHyperlinksPrefix + 130)
DECLARE_PMID(kScriptInfoIDSpace, kNameManuallyPropertyScriptElement,				kHyperlinksPrefix + 131)
DECLARE_PMID(kScriptInfoIDSpace, kDestinationPagePropertyScriptElement,				kHyperlinksPrefix + 132)
DECLARE_PMID(kScriptInfoIDSpace, kViewSettingPropertyScriptElement,					kHyperlinksPrefix + 133)
DECLARE_PMID(kScriptInfoIDSpace, kViewBoundsPropertyScriptElement,					kHyperlinksPrefix + 134)
DECLARE_PMID(kScriptInfoIDSpace, kViewPercentagePropertyScriptElement,				kHyperlinksPrefix + 135)
DECLARE_PMID(kScriptInfoIDSpace, kDocumentPathPropertyScriptElement,				kHyperlinksPrefix + 136)
DECLARE_PMID(kScriptInfoIDSpace, kDestinationPageIndexPropertyScriptElement,		kHyperlinksPrefix + 137)
DECLARE_PMID(kScriptInfoIDSpace, kDestinationURLPropertyScriptElement,				kHyperlinksPrefix + 138)
DECLARE_PMID(kScriptInfoIDSpace, kHyperLinkColorPropertyScriptElement,				kHyperlinksPrefix + 139)
DECLARE_PMID(kScriptInfoIDSpace, kBookmarkDestinationPropertyScriptElement,			kHyperlinksPrefix + 140)
DECLARE_PMID(kScriptInfoIDSpace, kAlternativeDestinationPropertyScriptElement,		kHyperlinksPrefix + 141)
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockTypePropertyScriptElement,			kHyperlinksPrefix + 142)
DECLARE_PMID(kScriptInfoIDSpace, kXRefFormatPropertyScriptElement,			kHyperlinksPrefix + 143)
DECLARE_PMID(kScriptInfoIDSpace, kDestUniqueKeyPropertyScriptElement,			kHyperlinksPrefix + 144)
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockCharStylePropertyScriptElement,			kHyperlinksPrefix + 145)
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockCustomTextPropertyScriptElement,			kHyperlinksPrefix + 146)
DECLARE_PMID(kScriptInfoIDSpace, kTextSourceCharStylePropertyScriptElement,			kHyperlinksPrefix + 147)
DECLARE_PMID(kScriptInfoIDSpace, kXRefFormatCharStylePropertyScriptElement,			kHyperlinksPrefix + 148)
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockDelimiterPropertyScriptElement,			kHyperlinksPrefix + 149)

// Metadata
DECLARE_PMID(kScriptInfoIDSpace, kINXIgnoreDefaultValueCheckPolicy1_60MetadataScriptElement,			kHyperlinksPrefix + 150)
DECLARE_PMID(kScriptInfoIDSpace, kINXMatchDestNamePolicy70ScriptElement,			kHyperlinksPrefix + 151)
DECLARE_PMID(kScriptInfoIDSpace, kBuildingBlockINXMatchAvailablePolicy60ScriptElement,			kHyperlinksPrefix + 152)


//Enums
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkAppearanceHighlightEnumScriptElement,	kHyperlinksPrefix + 220)
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkAppearanceWidthEnumScriptElement,		kHyperlinksPrefix + 221)
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkAppearanceStyleEnumScriptElement,		kHyperlinksPrefix + 222)
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkDestPageSettingEnumScriptElement,		kHyperlinksPrefix + 223)
DECLARE_PMID(kScriptInfoIDSpace, kXRefBuildingBlockTypeEnumScriptElement,		kHyperlinksPrefix + 224)
DECLARE_PMID(kScriptInfoIDSpace, kRangeSortOrderEnumScriptElement,				kHyperlinksPrefix + 225)
DECLARE_PMID(kScriptInfoIDSpace, kHyperlinkSourceAltDestinationEnumScriptElement,kHyperlinksPrefix + 226)

#endif // __HyperlinksID__
