//========================================================================================
//  
//  $File: //depot/devtech/14.0/plugin/source/public/interfaces/layout/SpreadID.h $
//  
//  Owner: Robin_Briggs
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/09/10 00:46:19 $
//  
//  $Revision: #2 $
//  
//  $Change: 1031899 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Contains IDs used by the spread item plug-in
//  
//========================================================================================

#ifndef __SpreadID__
#define __SpreadID__

#include "CrossPlatformTypes.h"
#include "IDFactory.h"

#define kSpreadPrefix	 RezLong(0x0500)
#define kSpreadPrefix2	 RezLong(0x022200)

// <Start IDC>
// PluginID
#define kSpreadPluginName 			"Spread"
DECLARE_PMID(kPlugInIDSpace, kSpreadPluginID, kSpreadPrefix + 1)

// <Class ID>
// ClassIDs
DECLARE_PMID(kClassIDSpace, kSpreadBoss, kSpreadPrefix + 1)

DECLARE_PMID(kClassIDSpace, kSetPageSizeCmdBoss, kSpreadPrefix + 2)
DECLARE_PMID(kClassIDSpace, kAdjustSpreadTransformCmdBoss, kSpreadPrefix + 3)

DECLARE_PMID(kClassIDSpace, kSpreadComponentBoss, kSpreadPrefix + 4)

DECLARE_PMID(kClassIDSpace, kNewSpreadCmdBoss, kSpreadPrefix + 5)
DECLARE_PMID(kClassIDSpace, kDeleteSpreadCmdBoss, kSpreadPrefix + 6)
DECLARE_PMID(kClassIDSpace, kMoveSpreadCmdBoss, kSpreadPrefix + 7)
DECLARE_PMID(kClassIDSpace, kNewPageCmdBoss, kSpreadPrefix + 8)
DECLARE_PMID(kClassIDSpace, kDeletePageCmdBoss, kSpreadPrefix + 9)
DECLARE_PMID(kClassIDSpace, kMovePageCmdBoss, kSpreadPrefix + 10)
DECLARE_PMID(kClassIDSpace, kSetSpreadCmdBoss, kSpreadPrefix + 11)

DECLARE_PMID(kClassIDSpace, kSetPageMarginsCmdBoss, kSpreadPrefix + 12)
DECLARE_PMID(kClassIDSpace, kSetPageColumnsCmdBoss, kSpreadPrefix + 13	)
DECLARE_PMID(kClassIDSpace, kSetColumnGutterCmdBoss, kSpreadPrefix + 14	)

DECLARE_PMID(kClassIDSpace, kPageBoss, kSpreadPrefix + 15)

DECLARE_PMID(kClassIDSpace, kPageShapeDrawServicesBoss, kSpreadPrefix + 17)
DECLARE_PMID(kClassIDSpace, kSetPageSetupPrefsCmdBoss, kSpreadPrefix + 18)
DECLARE_PMID(kClassIDSpace, kSetDocSetupPrefsCmdBoss, kSpreadPrefix + 19)
DECLARE_PMID(kClassIDSpace, kPageSizesDynamicDocumentServiceBoss, kSpreadPrefix + 20)

DECLARE_PMID(kClassIDSpace, kMoveColumnGuideCmdBoss, kSpreadPrefix + 21)
DECLARE_PMID(kClassIDSpace, kSetTransformPanelPrefsCmdBoss, kSpreadPrefix + 22)
DECLARE_PMID(kClassIDSpace, kSpreadConversionProviderBoss, kSpreadPrefix + 23)

DECLARE_PMID(kClassIDSpace, kSetGuidePrefsCmdBoss, kSpreadPrefix + 24)
DECLARE_PMID(kClassIDSpace, kSetGridPrefsCmdBoss, kSpreadPrefix + 25)
DECLARE_PMID(kClassIDSpace, kSetZeroPointPrefCmdBoss, kSpreadPrefix + 26)
DECLARE_PMID(kClassIDSpace, kSetZeroPointLockPrefCmdBoss, kSpreadPrefix + 27)
DECLARE_PMID(kClassIDSpace, kSetMarginPrefsCmdBoss, kSpreadPrefix + 28)
DECLARE_PMID(kClassIDSpace, kSetColumnPrefsCmdBoss, kSpreadPrefix + 29)
DECLARE_PMID(kClassIDSpace, kSetSnapToPrefsCmdBoss, kSpreadPrefix + 30)
DECLARE_PMID(kClassIDSpace, kSetBaselineGridPrefsCmdBoss, kSpreadPrefix + 31)
DECLARE_PMID(kClassIDSpace, kPageSizesDPSServiceBoss, kSpreadPrefix + 32)
DECLARE_PMID(kClassIDSpace, kPageSizesCDServiceBoss, kSpreadPrefix + 33)
DECLARE_PMID(kClassIDSpace, kPageSizesMetricHalfServiceBoss, kSpreadPrefix + 34)
DECLARE_PMID(kClassIDSpace, kPageSizesMetricServiceBoss, kSpreadPrefix + 35)
// gap
DECLARE_PMID(kClassIDSpace, kPageSizesStandardServiceBoss, kSpreadPrefix + 37)
DECLARE_PMID(kClassIDSpace, kPageSizesCustomServiceBoss, kSpreadPrefix + 38)

DECLARE_PMID(kClassIDSpace, kSetPageLayoutPrefsCmdBoss, kSpreadPrefix + 39)

DECLARE_PMID(kClassIDSpace, kSpreadNewDocResponderBoss, kSpreadPrefix + 40)
DECLARE_PMID(kClassIDSpace, kDuplicateSpreadResponderBoss, kSpreadPrefix + 41)
DECLARE_PMID(kClassIDSpace, kDuplicateSpreadCmdBoss, kSpreadPrefix + 42)
DECLARE_PMID(kClassIDSpace, kCreateSpreadFromSpreadCmdBoss, kSpreadPrefix + 43)

DECLARE_PMID(kClassIDSpace, kSetPasteboardPrefsCmdBoss, kSpreadPrefix + 44)

DECLARE_PMID(kClassIDSpace, kSetPageBindingCmdBoss, kSpreadPrefix + 45)
DECLARE_PMID(kClassIDSpace, kPrivateNewPageCmdBoss, kSpreadPrefix + 46)
DECLARE_PMID(kClassIDSpace, kPrivateDeletePageCmdBoss, kSpreadPrefix + 47)
DECLARE_PMID(kClassIDSpace, kPrivateMovePageCmdBoss, kSpreadPrefix + 48)
DECLARE_PMID(kClassIDSpace, kShufflePagesCmdBoss, kSpreadPrefix + 49)
DECLARE_PMID(kClassIDSpace, kNewPageSetSpreadCmdBoss, kSpreadPrefix + 50)
DECLARE_PMID(kClassIDSpace, kSetIslandSpreadCmdBoss, kSpreadPrefix + 51)
DECLARE_PMID(kClassIDSpace, kSetBindingLocationCmdBoss, kSpreadPrefix + 52)
DECLARE_PMID(kClassIDSpace, kSetOptionalPageCmdBoss, kSpreadPrefix + 53)
// gap
DECLARE_PMID(kClassIDSpace, kSpreadErrorStringServiceBoss, kSpreadPrefix + 56)
DECLARE_PMID(kClassIDSpace, kSetFrameEdgePrefsCmdBoss, kSpreadPrefix + 57)

DECLARE_PMID(kClassIDSpace, kSetPageCmdBoss, kSpreadPrefix + 58)
DECLARE_PMID(kClassIDSpace, kPageSetupChangeDocResponderBoss, kSpreadPrefix + 59)
DECLARE_PMID(kClassIDSpace, kPageSetupNewDocResponderBoss, kSpreadPrefix + 60)
DECLARE_PMID(kClassIDSpace, kSetAutoTextFramePrefsCmdBoss, kSpreadPrefix + 61)
DECLARE_PMID(kClassIDSpace, kMarginsColumnsNewDocResponderBoss, kSpreadPrefix + 62)
DECLARE_PMID(kClassIDSpace, kPrivateInsertSpreadCmdBoss, kSpreadPrefix + 63)
DECLARE_PMID(kClassIDSpace, kPrivateSetIslandSpreadCmdBoss, kSpreadPrefix + 64)

DECLARE_PMID(kClassIDSpace, kMoveToSpreadCmdBoss, kSpreadPrefix + 65)

DECLARE_PMID(kClassIDSpace, kDuplicateSpreadSignalMgrBoss, kSpreadPrefix + 73)
DECLARE_PMID(kClassIDSpace, kDuplicateSpreadMarColResponderBoss, kSpreadPrefix + 74)

DECLARE_PMID(kClassIDSpace, kOverlapNewDocResponderBoss, kSpreadPrefix + 75)
DECLARE_PMID(kClassIDSpace, kOverlapOpenDocResponderBoss, kSpreadPrefix + 76)
DECLARE_PMID(kClassIDSpace, kPrivateRemoveItemsFromSpreadCmdBoss, kSpreadPrefix + 77)
DECLARE_PMID(kClassIDSpace, kPrivateAddItemsToSpreadCmdBoss, kSpreadPrefix + 78)
DECLARE_PMID(kClassIDSpace, kPrivateMovePageInHierarchyCmdBoss, kSpreadPrefix + 79)
DECLARE_PMID(kClassIDSpace, kPrivateInsertPagesInSpreadCmdBoss, kSpreadPrefix + 80)

DECLARE_PMID(kClassIDSpace, kSetPageMarginsValidCmdBoss, kSpreadPrefix + 81)
DECLARE_PMID(kClassIDSpace, kSetPageColumnsValidCmdBoss, kSpreadPrefix + 82	)
DECLARE_PMID(kClassIDSpace, kDuplicateSpreadScriptLabelResponderBoss, kSpreadPrefix + 83)
DECLARE_PMID(kClassIDSpace, kkSpreadViewPrefsPhase2ConversionBoss, kSpreadPrefix + 84)
DECLARE_PMID(kClassIDSpace, kBindingLocOpenDocResponderBoss, kSpreadPrefix + 85)
DECLARE_PMID(kClassIDSpace, kDuplicatePageCmdBoss, kSpreadPrefix + 86)
DECLARE_PMID(kClassIDSpace, kCreatePageFromPageCmdBoss, kSpreadPrefix + 87)
DECLARE_PMID(kClassIDSpace, kSchemaBasedSpreadConversionProviderBoss, kSpreadPrefix + 88)
DECLARE_PMID(kClassIDSpace, kDuplicateSpreadColorLabelResponderBoss, kSpreadPrefix + 89)
//gap
DECLARE_PMID(kClassIDSpace, kSpreadScriptProviderBoss, kSpreadPrefix + 95)
DECLARE_PMID(kClassIDSpace, kPageScriptProviderBoss, kSpreadPrefix + 96)

DECLARE_PMID(kClassIDSpace, kPageNumEvenOddnessChangeSignalMgrBoss, kSpreadPrefix + 97)

DECLARE_PMID(kClassIDSpace, kSpreadValidatorBoss, kSpreadPrefix + 98)

DECLARE_PMID(kClassIDSpace, kDocPrefsScriptProviderBoss, kSpreadPrefix + 99)			//jwb 4/30/02 Moved from ScriptingID.h
DECLARE_PMID(kClassIDSpace, kGridPrefsScriptProviderBoss, kSpreadPrefix + 100)			//jwb 4/30/02 Moved from ScriptingID.h
DECLARE_PMID(kClassIDSpace, kPasteboardPrefsScriptProviderBoss, kSpreadPrefix + 101)	//jwb 4/30/02 Moved from ScriptingID.h
DECLARE_PMID(kClassIDSpace, kGuidePrefsScriptProviderBoss, kSpreadPrefix + 102)			//jwb 4/30/02 Moved from ScriptingID.h
DECLARE_PMID(kClassIDSpace, kViewPrefsScriptProviderBoss, kSpreadPrefix + 103)			//jwb 4/30/02 Moved from ScriptingID.h
DECLARE_PMID(kClassIDSpace, kMarginPrefsScriptProviderBoss, kSpreadPrefix + 104)		//jwb 4/30/02 Moved from ScriptingID.h

DECLARE_PMID(kClassIDSpace, kDocStyleBoss, kSpreadPrefix + 105)
DECLARE_PMID(kClassIDSpace, kDocAddStyleCmdBoss, kSpreadPrefix + 106)
DECLARE_PMID(kClassIDSpace, kDocSetStyleNameCmdBoss, kSpreadPrefix + 107)
DECLARE_PMID(kClassIDSpace, kDocDeleteStyleCmdBoss, kSpreadPrefix + 108)
DECLARE_PMID(kClassIDSpace, kDocEditStyleCmdBoss, kSpreadPrefix + 109)
DECLARE_PMID(kClassIDSpace, kDocStyleExportRootBoss, kSpreadPrefix + 110)
DECLARE_PMID(kClassIDSpace, kDocWarningDialogBoss, kSpreadPrefix + 111)
DECLARE_PMID(kClassIDSpace, kDocStyleScriptProviderBoss, kSpreadPrefix + 112)
DECLARE_PMID(kClassIDSpace, kSaveDocumentStyleDataCmdBoss, kSpreadPrefix + 113)
DECLARE_PMID(kClassIDSpace, kDocStyleLockInfoBoss, kSpreadPrefix + 114)
DECLARE_PMID(kClassIDSpace, kDocSetDefaultStyleNameCmdBoss, kSpreadPrefix + 115)
DECLARE_PMID(kClassIDSpace, kDocNewDocUsingStyleCmdBoss, kSpreadPrefix + 116)
DECLARE_PMID(kClassIDSpace, kDocStylesPhase2ConversionResponderBoss, kSpreadPrefix + 117)
DECLARE_PMID(kClassIDSpace, kDocStyleDefaultBoss, kSpreadPrefix + 118)
DECLARE_PMID(kClassIDSpace, kPasteboardPrefsPhase2ConversionBoss, kSpreadPrefix + 119)
DECLARE_PMID(kClassIDSpace, kDeselectSpreadSgnlBoss, kSpreadPrefix + 120)
DECLARE_PMID(kClassIDSpace, kDocStylesNewWSResponderBoss, kSpreadPrefix + 121)
DECLARE_PMID(kClassIDSpace, kSpreadOpenDocResponderBoss, kSpreadPrefix + 122)
DECLARE_PMID(kClassIDSpace, kSetPageColorLabelCmdBoss, kSpreadPrefix + 123)
DECLARE_PMID(kClassIDSpace, kPageSizeM2MListenerServiceBoss, kSpreadPrefix + 124)
DECLARE_PMID(kClassIDSpace, kSpreadHierarchyM2MListenerServiceBoss, kSpreadPrefix + 125)
DECLARE_PMID(kClassIDSpace, kDocPageSizePrefsPhase2ConversionBoss, kSpreadPrefix + 126)
DECLARE_PMID(kClassIDSpace, kPageSizePresetContentHandlerBoss, kSpreadPrefix + 127)
DECLARE_PMID(kClassIDSpace, kSpreadGeometryM2MListenerServiceBoss, kSpreadPrefix + 128)
DECLARE_PMID(kClassIDSpace, kLayoutViewComposerM2MListenerServiceBoss, kSpreadPrefix + 129)
DECLARE_PMID(kClassIDSpace, kSetLayoutPolicyCmdBoss, kSpreadPrefix + 130)
DECLARE_PMID(kClassIDSpace, kSnapshotLayoutCmdBoss, kSpreadPrefix + 131)
DECLARE_PMID(kClassIDSpace, kDeleteLayoutSnapshotCmdBoss, kSpreadPrefix + 132)
DECLARE_PMID(kClassIDSpace, kDeleteAllLayoutSnapshotsCmdBoss, kSpreadPrefix + 133)
DECLARE_PMID(kClassIDSpace, kEnableSnapshotBlendingCmdBoss, kSpreadPrefix + 134)
DECLARE_PMID(kClassIDSpace, kSetLayoutConstraintsCmdBoss, kSpreadPrefix + 135)
DECLARE_PMID(kClassIDSpace, kSetPagesPerSpreadCmdBoss, kSpreadPrefix + 136)
DECLARE_PMID(kClassIDSpace, kPageCustomSizesMigrationBoss, kSpreadPrefix + 137)
DECLARE_PMID(kClassIDSpace, kRecentDocStyleBoss, kSpreadPrefix + 138)
DECLARE_PMID(kClassIDSpace, kDocSetRecentStyleInfoCmdBoss, kSpreadPrefix + 139)
DECLARE_PMID(kClassIDSpace, kSetDocMarginsCmdBoss, kSpreadPrefix + 140)


// <Interface ID>
// IIDs
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADLIST, kSpreadPrefix + 1)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREAD, kSpreadPrefix + 2)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGESIZES, kSpreadPrefix + 3)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGECMDDATA, kSpreadPrefix + 4)
DECLARE_PMID(kInterfaceIDSpace, IID_IMOVEPAGEDATA, kSpreadPrefix + 5)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADOVERLAPMANAGER, kSpreadPrefix + 6)
DECLARE_PMID(kInterfaceIDSpace, IID_IOVERLAPHIERARCHYOBSERVER, kSpreadPrefix + 7)
DECLARE_PMID(kInterfaceIDSpace, IID_IOVERLAPPAGEITEMOBSERVER, kSpreadPrefix + 8)
DECLARE_PMID(kInterfaceIDSpace, IID_IOVERLAPLAYEROBSERVER, kSpreadPrefix + 9)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNLOCKVIEWPREFERENCE, kSpreadPrefix + 10)
DECLARE_PMID(kInterfaceIDSpace, IID_ISNAPTO, kSpreadPrefix + 11)
DECLARE_PMID(kInterfaceIDSpace, IID_IOVERLAPDYNAMICOBSERVER, kSpreadPrefix + 12)
DECLARE_PMID(kInterfaceIDSpace, IID_IGRIDSHOWVIEWPREFERENCE, kSpreadPrefix + 13)
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCSETUPCMDDATA, kSpreadPrefix + 14)
DECLARE_PMID(kInterfaceIDSpace, IID_IDUPLICATESPREADCMDDATA, kSpreadPrefix + 15)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGEMARGINSCMDDATA, kSpreadPrefix + 16)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGECOLUMNSCMDDATA, kSpreadPrefix + 17)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNGUTTERCMDDATA, kSpreadPrefix + 18)
DECLARE_PMID(kInterfaceIDSpace, IID_IMARGINS, kSpreadPrefix + 19)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNS, kSpreadPrefix + 20)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGEPREFERENCES, kSpreadPrefix + 21)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWSPREADCMDDATA, kSpreadPrefix + 22)
DECLARE_PMID(kInterfaceIDSpace, IID_IMOVECOLUMNGUIDECMDDATA, kSpreadPrefix + 23)
DECLARE_PMID(kInterfaceIDSpace, IID_IGUIDEPREFERENCES, kSpreadPrefix + 24)
DECLARE_PMID(kInterfaceIDSpace, IID_IGUIDEPREFSCMDDATA, kSpreadPrefix + 25)
DECLARE_PMID(kInterfaceIDSpace, IID_IGRIDPREFERENCES, kSpreadPrefix + 26)
DECLARE_PMID(kInterfaceIDSpace, IID_IGRIDPREFSCMDDATA, kSpreadPrefix + 27)
DECLARE_PMID(kInterfaceIDSpace, IID_IZEROPOINTPREFERENCES, kSpreadPrefix + 28)
DECLARE_PMID(kInterfaceIDSpace, IID_IZEROPOINTPREFSCMDDATA, kSpreadPrefix + 29)
DECLARE_PMID(kInterfaceIDSpace, IID_IMARGINPREFERENCES, kSpreadPrefix + 30)
DECLARE_PMID(kInterfaceIDSpace, IID_IMARGINPREFSCMDDATA, kSpreadPrefix + 31)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNPREFERENCES, kSpreadPrefix + 32)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNPREFSCMDDATA, kSpreadPrefix + 33)
DECLARE_PMID(kInterfaceIDSpace, IID_ISNAPTOPREFERENCES, kSpreadPrefix + 34)
DECLARE_PMID(kInterfaceIDSpace, IID_ISNAPTOPREFSCMDDATA, kSpreadPrefix + 35)
DECLARE_PMID(kInterfaceIDSpace, IID_IBASELINEGRIDPREFERENCES, kSpreadPrefix + 36)
DECLARE_PMID(kInterfaceIDSpace, IID_IBASELINEGRIDPREFSCMDDATA, kSpreadPrefix + 37)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTSNAPSHOTDATA, kSpreadPrefix + 38)
DECLARE_PMID(kInterfaceIDSpace, IID_IPASTEBOARD, kSpreadPrefix + 39)
DECLARE_PMID(kInterfaceIDSpace, IID_ICURRENTSPREAD, kSpreadPrefix + 40)
DECLARE_PMID(kInterfaceIDSpace, IID_ITRANSFORMPANELPREFERENCES, kSpreadPrefix + 41)
DECLARE_PMID(kInterfaceIDSpace, IID_ITRANSFORMPANELPREFSCMDDATA, kSpreadPrefix + 42)
DECLARE_PMID(kInterfaceIDSpace, IID_IGRIDBACKVIEWPREFERENCE, kSpreadPrefix + 43)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGELIST, kSpreadPrefix + 44)
DECLARE_PMID(kInterfaceIDSpace, IID_IGUIDESHOWVIEWPREFERENCE, kSpreadPrefix + 45)
DECLARE_PMID(kInterfaceIDSpace, IID_ISHUFFLECMDDATA, kSpreadPrefix + 46)
DECLARE_PMID(kInterfaceIDSpace, IID_IISLANDSPREAD, kSpreadPrefix + 47)
DECLARE_PMID(kInterfaceIDSpace, IID_IBINDINGLOCATION, kSpreadPrefix + 48)
DECLARE_PMID(kInterfaceIDSpace, IID_IGUIDELOCKVIEWPREFERENCE, kSpreadPrefix + 49)
DECLARE_PMID(kInterfaceIDSpace, IID_IBASELINEGRIDSHOWVIEWPREFERENCE, kSpreadPrefix + 50)
DECLARE_PMID(kInterfaceIDSpace, IID_IAPPLYMASTERCMDDATA, kSpreadPrefix + 51)
DECLARE_PMID(kInterfaceIDSpace, IID_IFRAMEEDGEPREFERENCES, kSpreadPrefix + 53)
DECLARE_PMID(kInterfaceIDSpace, IID_IFRAMEEDGEPREFSCMDDATA, kSpreadPrefix + 54)
DECLARE_PMID(kInterfaceIDSpace, IID_IITEMCONTEXT, kSpreadPrefix + 55)
DECLARE_PMID(kInterfaceIDSpace, IID_IAUTOTEXTFRAMEPREFERENCES, kSpreadPrefix + 56)
DECLARE_PMID(kInterfaceIDSpace, IID_IAUTOTEXTFRAMEPREFSCMDDATA, kSpreadPrefix + 57)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGELAYOUTPREFERENCES, kSpreadPrefix + 58)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGELAYOUTPREFSCMDDATA, kSpreadPrefix + 59)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTOBJECT, kSpreadPrefix + 60)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTPOLICY, kSpreadPrefix + 61)
DECLARE_PMID(kInterfaceIDSpace, IID_IDELETEINPROGRESS, kSpreadPrefix + 62)
DECLARE_PMID(kInterfaceIDSpace, IID_IDUPLICATESPREADSIGNALDATA, kSpreadPrefix + 63)
DECLARE_PMID(kInterfaceIDSpace, IID_IBASELINEGRIDCLIPITEMLIST, kSpreadPrefix + 64)
DECLARE_PMID(kInterfaceIDSpace, IID_ICOLUMNSCLIPITEMLIST, kSpreadPrefix + 65)
DECLARE_PMID(kInterfaceIDSpace, IID_IMYUIDDATA, kSpreadPrefix + 66)
DECLARE_PMID(kInterfaceIDSpace, IID_IBINDINGSIDE, kSpreadPrefix + 67)
DECLARE_PMID(kInterfaceIDSpace, IID_IITEMSCRAPUIFLAGDATA, kSpreadPrefix + 68)
DECLARE_PMID(kInterfaceIDSpace, IID_INEWDOCCMDCOMPLETE, kSpreadPrefix + 69)
DECLARE_PMID(kInterfaceIDSpace, IID_IDUPLICATEPAGECMDDATA, kSpreadPrefix + 70)
DECLARE_PMID(kInterfaceIDSpace, IID_IREPAGINATEFLAG, kSpreadPrefix + 71)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADUTILS, kSpreadPrefix + 72)
DECLARE_PMID(kInterfaceIDSpace, IID_IPASTEBOARDPREFERENCES, kSpreadPrefix + 73)
DECLARE_PMID(kInterfaceIDSpace, IID_IPASTEBOARDCOLORSDATA, kSpreadPrefix + 75)
DECLARE_PMID(kInterfaceIDSpace, IID_IIGNOREITEMSONPASTEBOARD, kSpreadPrefix + 76)
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCSTYLELISTMGR, kSpreadPrefix + 77)
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCSTYLENAME, kSpreadPrefix + 78)
DECLARE_PMID(kInterfaceIDSpace, IID_ISETSPREADCOMMANDDATA, kSpreadPrefix + 79)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADDEBUGFLAGS, kSpreadPrefix + 80)
DECLARE_PMID(kInterfaceIDSpace, IID_IFRAMEBASELINEGRIDCLIPITEMLIST, kSpreadPrefix + 81)
DECLARE_PMID(kInterfaceIDSpace, IID_IDELETESPREADORMASTEROBSERVER, kSpreadPrefix + 82)
DECLARE_PMID(kInterfaceIDSpace, IID_IITEMSSPREADLAYERLIST, kSpreadPrefix + 83)
DECLARE_PMID(kInterfaceIDSpace, IID_ITRANSFORM_SPREAD_DOCUMENT, kSpreadPrefix + 84)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGECOLORLABEL, kSpreadPrefix + 85)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADFACADE, kSpreadPrefix + 86)
DECLARE_PMID(kInterfaceIDSpace, IID_IFORCELAYOUTVIEWRECOMPOSITION, kSpreadPrefix + 87)
DECLARE_PMID(kInterfaceIDSpace, IID_ITRANSFORM_PAGE_DOCUMENT, kSpreadPrefix + 88)
DECLARE_PMID(kInterfaceIDSpace, IID_IGEOMETRY_PAGE_DOCUMENT, kSpreadPrefix + 89)
DECLARE_PMID(kInterfaceIDSpace, IID_ISPREADPAGESNEEDCOMPOSITION, kSpreadPrefix + 90)
DECLARE_PMID(kInterfaceIDSpace, IID_IFORCEPASTEBOARDSIZERECALCULATION, kSpreadPrefix + 91)
DECLARE_PMID(kInterfaceIDSpace, IID_IGEOMETRY_SPREAD_DOCUMENT, kSpreadPrefix + 92)
DECLARE_PMID(kInterfaceIDSpace, IID_ISETLAYOUTPOLICYCMDDATA, kSpreadPrefix + 93)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTSNAPSHOTCMDDATA, kSpreadPrefix + 94)
DECLARE_PMID(kInterfaceIDSpace, IID_IENABLESNAPSHOTBLENDINGCMDDATA, kSpreadPrefix + 95)
DECLARE_PMID(kInterfaceIDSpace, IID_ITRIGGERAUTOLAYOUT, kSpreadPrefix + 96)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTCONSTRAINTS, kSpreadPrefix + 97)
DECLARE_PMID(kInterfaceIDSpace, IID_ISETLAYOUTCONSTRAINTSCMDDATA, kSpreadPrefix + 98)
DECLARE_PMID(kInterfaceIDSpace, IID_ILAYOUTCONSTRAINTS_DOCUMENT, kSpreadPrefix + 99)
DECLARE_PMID(kInterfaceIDSpace, IID_IOPTIONALPAGE, kSpreadPrefix + 100)
DECLARE_PMID(kInterfaceIDSpace, IID_IPAGESIZELIST, kSpreadPrefix + 101)
DECLARE_PMID(kInterfaceIDSpace, IID_IINTENTLIST, kSpreadPrefix + 102)
DECLARE_PMID(kInterfaceIDSpace, IID_IMASTERPAGESIZECHANGED, kSpreadPrefix + 103)
DECLARE_PMID(kInterfaceIDSpace, IID_ICHECKFORMAXPAGENUMBERDATA, kSpreadPrefix + 104)
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCUIFLAG, kSpreadPrefix + 105)
DECLARE_PMID(kInterfaceIDSpace, IID_IRECENTDOCSTYLELISTMGR, kSpreadPrefix + 106)
DECLARE_PMID(kInterfaceIDSpace, IID_IDOCMARGINSCMDDATA, kSpreadPrefix + 107)
DECLARE_PMID(kInterfaceIDSpace, IID_IMASTERPAGEGRIDRECALC, kSpreadPrefix + 108)

// <Implementation ID>
// ImplementationIDs
DECLARE_PMID(kImplementationIDSpace, kSpreadListImpl, kSpreadPrefix + 1)
DECLARE_PMID(kImplementationIDSpace, kSpreadImpl, kSpreadPrefix + 2)
DECLARE_PMID(kImplementationIDSpace, kCSpreadNodeImpl, kSpreadPrefix + 3)
DECLARE_PMID(kImplementationIDSpace, kPageFillImpl_obsolete, kSpreadPrefix + 4)
DECLARE_PMID(kImplementationIDSpace, kPageShapeImpl, kSpreadPrefix + 5)
DECLARE_PMID(kImplementationIDSpace, kPageItemPageImpl, kSpreadPrefix + 6)
DECLARE_PMID(kImplementationIDSpace, kPageListImpl, kSpreadPrefix + 7)
DECLARE_PMID(kImplementationIDSpace, kOverlapHierarchyObserverImpl, kSpreadPrefix + 8)
DECLARE_PMID(kImplementationIDSpace, kSpreadViewPrefsPhase2ConversionImpl, kSpreadPrefix + 9)
DECLARE_PMID(kImplementationIDSpace, kOverlapPageItemObserverImpl_Obsolete, kSpreadPrefix + 10)
DECLARE_PMID(kImplementationIDSpace, kOverlapTransformObserverImpl_Obsolete, kSpreadPrefix + 11)
DECLARE_PMID(kImplementationIDSpace, kSpreadOverlapManagerImpl_OBSOLETE, kSpreadPrefix + 12)
DECLARE_PMID(kImplementationIDSpace, kSpreadFacadeImpl, kSpreadPrefix + 13)
DECLARE_PMID(kImplementationIDSpace, kNewSpreadCmdImpl, kSpreadPrefix + 14)
DECLARE_PMID(kImplementationIDSpace, kSpreadCmdDataImpl, kSpreadPrefix + 15)
DECLARE_PMID(kImplementationIDSpace, kDeleteSpreadCmdImpl, kSpreadPrefix + 16)
DECLARE_PMID(kImplementationIDSpace, kMoveSpreadCmdImpl, kSpreadPrefix + 17)
DECLARE_PMID(kImplementationIDSpace, kDeletePageCmdImpl, kSpreadPrefix + 18)
DECLARE_PMID(kImplementationIDSpace, kPageCmdDataImpl, kSpreadPrefix + 19)
DECLARE_PMID(kImplementationIDSpace, kMovePageCmdImpl, kSpreadPrefix + 20)
DECLARE_PMID(kImplementationIDSpace, kMovePageDataImpl, kSpreadPrefix + 21)
DECLARE_PMID(kImplementationIDSpace, kNewPageCmdImpl, kSpreadPrefix + 22)
DECLARE_PMID(kImplementationIDSpace, kSetSpreadCmdImpl, kSpreadPrefix + 23)
DECLARE_PMID(kImplementationIDSpace, kSpreadShapeImpl, kSpreadPrefix + 24)
DECLARE_PMID(kImplementationIDSpace, kPageMarginsImpl, kSpreadPrefix + 26)
DECLARE_PMID(kImplementationIDSpace, kOverlapDynamicObserverImpl_Obsolete, kSpreadPrefix + 27)
DECLARE_PMID(kImplementationIDSpace, kPagePageItemScrapImpl, kSpreadPrefix + 28)
DECLARE_PMID(kImplementationIDSpace, kSpreadConversionProviderImpl, kSpreadPrefix + 29)
DECLARE_PMID(kImplementationIDSpace, kPrivateRemoveItemsFromSpreadCmdImpl, kSpreadPrefix + 30)
DECLARE_PMID(kImplementationIDSpace, kPrivateAddItemsToSpreadCmdImpl, kSpreadPrefix + 31)
DECLARE_PMID(kImplementationIDSpace, kSpreadComposerImpl_OBSOLETE, kSpreadPrefix + 32)
DECLARE_PMID(kImplementationIDSpace, kDocSetupCmdDataImpl, kSpreadPrefix + 33)
DECLARE_PMID(kImplementationIDSpace, kSetPageSizeCmdImpl, kSpreadPrefix + 34)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadCmdImpl, kSpreadPrefix + 36)
DECLARE_PMID(kImplementationIDSpace, kAdjustSpreadTransformCmdImpl, kSpreadPrefix + 37)
DECLARE_PMID(kImplementationIDSpace, kSetPageMarginsCmdImpl, kSpreadPrefix + 38)
DECLARE_PMID(kImplementationIDSpace, kPageMarginsCmdDataImpl, kSpreadPrefix + 39)
DECLARE_PMID(kImplementationIDSpace, kPageColumnsImpl, kSpreadPrefix + 40)
DECLARE_PMID(kImplementationIDSpace, kSetPageColumnsCmdImpl, kSpreadPrefix + 41)
DECLARE_PMID(kImplementationIDSpace, kPageColumnsCmdDataImpl, kSpreadPrefix + 42)
DECLARE_PMID(kImplementationIDSpace, kSetColumnGutterCmdImpl, kSpreadPrefix + 43)
DECLARE_PMID(kImplementationIDSpace, kColumnGutterCmdDataImpl, kSpreadPrefix + 44)
DECLARE_PMID(kImplementationIDSpace, kCMarginsImpl, kSpreadPrefix + 45)
DECLARE_PMID(kImplementationIDSpace, kCColumnsImpl, kSpreadPrefix + 46)
DECLARE_PMID(kImplementationIDSpace, kPageShapeDrawServiceImpl, kSpreadPrefix + 47)
DECLARE_PMID(kImplementationIDSpace, kPageShapeDrawHandlerImpl, kSpreadPrefix + 48)
DECLARE_PMID(kImplementationIDSpace, kCPageSetupPrefsImpl, kSpreadPrefix + 49)
DECLARE_PMID(kImplementationIDSpace, kSessionPageSetupPrefsImpl, kSpreadPrefix + 50)
DECLARE_PMID(kImplementationIDSpace, kDocPageSetupPrefsImpl, kSpreadPrefix + 51)
DECLARE_PMID(kImplementationIDSpace, kSetPageSetupPrefsCmdImpl, kSpreadPrefix + 52)
DECLARE_PMID(kImplementationIDSpace, kSetDocSetupPrefsCmdImpl, kSpreadPrefix + 53)
DECLARE_PMID(kImplementationIDSpace, kNewSpreadCmdDataImpl, kSpreadPrefix + 54)
DECLARE_PMID(kImplementationIDSpace, kMoveColumnGuideCmdImpl, kSpreadPrefix + 57)
DECLARE_PMID(kImplementationIDSpace, kMoveColumnGuideCmdDataImpl, kSpreadPrefix + 58)
DECLARE_PMID(kImplementationIDSpace, kCGuidePrefsImpl, kSpreadPrefix + 61)
DECLARE_PMID(kImplementationIDSpace, kSessionGuidePrefsImpl, kSpreadPrefix + 62)
DECLARE_PMID(kImplementationIDSpace, kDocGuidePrefsImpl, kSpreadPrefix + 63)
DECLARE_PMID(kImplementationIDSpace, kSetGuidePrefsCmdImpl, kSpreadPrefix + 64)
DECLARE_PMID(kImplementationIDSpace, kGuidePrefsCmdDataImpl, kSpreadPrefix + 65)
DECLARE_PMID(kImplementationIDSpace, kPageNodeImpl, kSpreadPrefix + 66)
DECLARE_PMID(kImplementationIDSpace, kCGridPrefsImpl, kSpreadPrefix + 67)
DECLARE_PMID(kImplementationIDSpace, kSessionGridPrefsImpl, kSpreadPrefix + 68)
DECLARE_PMID(kImplementationIDSpace, kDocGridPrefsImpl, kSpreadPrefix + 69)
DECLARE_PMID(kImplementationIDSpace, kSetGridPrefsCmdImpl, kSpreadPrefix + 70)
DECLARE_PMID(kImplementationIDSpace, kGridPrefsCmdDataImpl, kSpreadPrefix + 71)
DECLARE_PMID(kImplementationIDSpace, kCZeroPointPrefsImpl, kSpreadPrefix + 72)
DECLARE_PMID(kImplementationIDSpace, kSessionZeroPointPrefsImpl, kSpreadPrefix + 73)
DECLARE_PMID(kImplementationIDSpace, kDocZeroPointPrefsImpl, kSpreadPrefix + 74)
DECLARE_PMID(kImplementationIDSpace, kSetZeroPointPrefCmdImpl, kSpreadPrefix + 75)
DECLARE_PMID(kImplementationIDSpace, kSetZeroPointLockPrefCmdImpl, kSpreadPrefix + 76)
DECLARE_PMID(kImplementationIDSpace, kZeroPointPrefsCmdDataImpl, kSpreadPrefix + 77)
DECLARE_PMID(kImplementationIDSpace, kCMarginPrefsImpl, kSpreadPrefix + 78)
DECLARE_PMID(kImplementationIDSpace, kSessionMarginPrefsImpl, kSpreadPrefix + 79)
DECLARE_PMID(kImplementationIDSpace, kDocMarginPrefsImpl, kSpreadPrefix + 80)
DECLARE_PMID(kImplementationIDSpace, kSetMarginPrefsCmdImpl, kSpreadPrefix + 81)
DECLARE_PMID(kImplementationIDSpace, kMarginPrefsCmdDataImpl, kSpreadPrefix + 82)
DECLARE_PMID(kImplementationIDSpace, kCColumnPrefsImpl, kSpreadPrefix + 83)
DECLARE_PMID(kImplementationIDSpace, kSessionColumnPrefsImpl, kSpreadPrefix + 84)
DECLARE_PMID(kImplementationIDSpace, kDocColumnPrefsImpl, kSpreadPrefix + 85)
DECLARE_PMID(kImplementationIDSpace, kSetColumnPrefsCmdImpl, kSpreadPrefix + 86)
DECLARE_PMID(kImplementationIDSpace, kColumnPrefsCmdDataImpl, kSpreadPrefix + 87)
DECLARE_PMID(kImplementationIDSpace, kCSnapToPrefsImpl, kSpreadPrefix + 88)
DECLARE_PMID(kImplementationIDSpace, kSessionSnapToPrefsImpl, kSpreadPrefix + 89)
DECLARE_PMID(kImplementationIDSpace, kDocSnapToPrefsImpl, kSpreadPrefix + 90)
DECLARE_PMID(kImplementationIDSpace, kSetSnapToPrefsCmdImpl, kSpreadPrefix + 91)
DECLARE_PMID(kImplementationIDSpace, kSnapToPrefsCmdDataImpl, kSpreadPrefix + 92)
DECLARE_PMID(kImplementationIDSpace, kCBaselineGridPrefsImpl, kSpreadPrefix + 93)
DECLARE_PMID(kImplementationIDSpace, kSessionBaselineGridPrefsImpl, kSpreadPrefix + 94)
DECLARE_PMID(kImplementationIDSpace, kDocBaselineGridPrefsImpl, kSpreadPrefix + 95)
DECLARE_PMID(kImplementationIDSpace, kSetBaselineGridPrefsCmdImpl, kSpreadPrefix + 96)
DECLARE_PMID(kImplementationIDSpace, kBaselineGridPrefsCmdDataImpl, kSpreadPrefix + 97)
DECLARE_PMID(kImplementationIDSpace, kLayoutSnapshotDataImpl, kSpreadPrefix + 98)
DECLARE_PMID(kImplementationIDSpace, kLayoutObjectImpl, kSpreadPrefix + 99)
DECLARE_PMID(kImplementationIDSpace, kPasteboardImpl_OBSOLETE, kSpreadPrefix + 100)
DECLARE_PMID(kImplementationIDSpace, kSpreadGeometryImpl, kSpreadPrefix + 101)
DECLARE_PMID(kImplementationIDSpace, kDocGridShowViewPrefDataImpl, kSpreadPrefix + 102)
DECLARE_PMID(kImplementationIDSpace, kDocGridBackViewPrefDataImpl, kSpreadPrefix + 103)
DECLARE_PMID(kImplementationIDSpace, kDocGuideShowViewPrefDataImpl, kSpreadPrefix + 104)
DECLARE_PMID(kImplementationIDSpace, kDocGuideLockViewPrefDataImpl, kSpreadPrefix + 105)
DECLARE_PMID(kImplementationIDSpace, kDocBaselineGridShowPrefDataImpl, kSpreadPrefix + 106)
DECLARE_PMID(kImplementationIDSpace, kDocColumnLockViewPrefDataImpl, kSpreadPrefix + 107)
DECLARE_PMID(kImplementationIDSpace, kCurrentSpreadUIDRefDataImpl, kSpreadPrefix + 108)
DECLARE_PMID(kImplementationIDSpace, kNewDocCmdCompleteImpl, kSpreadPrefix + 109)
DECLARE_PMID(kImplementationIDSpace, kSpreadTransformImpl, kSpreadPrefix + 110)
DECLARE_PMID(kImplementationIDSpace, kSessionColumnLockViewPrefDataImpl, kSpreadPrefix + 111)
DECLARE_PMID(kImplementationIDSpace, kSessionTransformPanelPrefsImpl, kSpreadPrefix + 112)
DECLARE_PMID(kImplementationIDSpace, kDocTransformPanelPrefsImpl, kSpreadPrefix + 113)
DECLARE_PMID(kImplementationIDSpace, kSetTransformPanelPrefsCmdImpl, kSpreadPrefix + 114)
DECLARE_PMID(kImplementationIDSpace, kTransformPanelPrefsCmdDataImpl, kSpreadPrefix + 116)
DECLARE_PMID(kImplementationIDSpace, kOverlapNewDocResponderImpl, kSpreadPrefix + 117)
DECLARE_PMID(kImplementationIDSpace, kOverlapOpenDocResponderImpl, kSpreadPrefix + 118)
DECLARE_PMID(kImplementationIDSpace, kPrivateMovePageInHierarchyCmdImpl, kSpreadPrefix + 119)
DECLARE_PMID(kImplementationIDSpace, kSessionGridShowViewPrefDataImpl, kSpreadPrefix + 120)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadCmdDataImpl, kSpreadPrefix + 121)
DECLARE_PMID(kImplementationIDSpace, kCreateSpreadFromSpreadCmdImpl, kSpreadPrefix + 122)
DECLARE_PMID(kImplementationIDSpace, kMyPersistUIDListDataImpl, kSpreadPrefix + 123)
DECLARE_PMID(kImplementationIDSpace, kSessionGridBackViewPrefDataImpl, kSpreadPrefix + 124)
DECLARE_PMID(kImplementationIDSpace, kColumnGuideToolImpl, kSpreadPrefix + 125) // used for column guide tracking b/c it's not specific to a tool
DECLARE_PMID(kImplementationIDSpace, kSpreadNewDocResponderImpl, kSpreadPrefix + 126)
DECLARE_PMID(kImplementationIDSpace, kSessionGuideShowViewPrefDataImpl, kSpreadPrefix + 127)
DECLARE_PMID(kImplementationIDSpace, kSetPageBindingCmdImpl, kSpreadPrefix + 128)
DECLARE_PMID(kImplementationIDSpace, kPageBindingImpl_obsolete, kSpreadPrefix + 129)
DECLARE_PMID(kImplementationIDSpace, kPrivateNewPageCmdImpl, kSpreadPrefix + 130)
DECLARE_PMID(kImplementationIDSpace, kPrivateDeletePageCmdImpl, kSpreadPrefix + 131)
DECLARE_PMID(kImplementationIDSpace, kPrivateMovePageCmdImpl, kSpreadPrefix + 132)
DECLARE_PMID(kImplementationIDSpace, kShufflePagesCmdImpl, kSpreadPrefix + 133)
DECLARE_PMID(kImplementationIDSpace, kShuffleCmdDataImpl, kSpreadPrefix + 134)
DECLARE_PMID(kImplementationIDSpace, kNewPageSetSpreadCmdImpl, kSpreadPrefix + 135)
DECLARE_PMID(kImplementationIDSpace, kSetIslandSpreadCmdImpl, kSpreadPrefix + 136)
DECLARE_PMID(kImplementationIDSpace, kSetBindingLocationCmdImpl, kSpreadPrefix + 137)
DECLARE_PMID(kImplementationIDSpace, kSessionGuideLockViewPrefDataImpl, kSpreadPrefix + 138)
DECLARE_PMID(kImplementationIDSpace, kSessionBaselineGridShowPrefDataImpl, kSpreadPrefix + 139)
DECLARE_PMID(kImplementationIDSpace, kDeleteInProgressImpl, kSpreadPrefix + 140)
DECLARE_PMID(kImplementationIDSpace, kApplyMasterCmdDataImpl, kSpreadPrefix + 141)
DECLARE_PMID(kImplementationIDSpace, kSpreadErrorStringServiceImpl, kSpreadPrefix + 144)
DECLARE_PMID(kImplementationIDSpace, kCFrameEdgePrefsImpl, kSpreadPrefix + 145)
DECLARE_PMID(kImplementationIDSpace, kSessionFrameEdgePrefsImpl, kSpreadPrefix + 146)
DECLARE_PMID(kImplementationIDSpace, kDocFrameEdgePrefsImpl, kSpreadPrefix + 147)
DECLARE_PMID(kImplementationIDSpace, kSetFrameEdgePrefsCmdImpl, kSpreadPrefix + 148)
DECLARE_PMID(kImplementationIDSpace, kFrameEdgePrefsCmdDataImpl, kSpreadPrefix + 149)
DECLARE_PMID(kImplementationIDSpace, kSetPageCmdImpl, kSpreadPrefix + 150)
DECLARE_PMID(kImplementationIDSpace, kPageSizesDynamicDocumentImpl, kSpreadPrefix + 151)
DECLARE_PMID(kImplementationIDSpace, kSpreadItemContextImpl, kSpreadPrefix + 152)
DECLARE_PMID(kImplementationIDSpace, kPageSetupNewDocResponderImpl, kSpreadPrefix + 153)
DECLARE_PMID(kImplementationIDSpace, kCAutoTextFramePrefsImpl, kSpreadPrefix + 154)
DECLARE_PMID(kImplementationIDSpace, kSessionAutoTextFramePrefsImpl, kSpreadPrefix + 155)
DECLARE_PMID(kImplementationIDSpace, kDocAutoTextFramePrefsImpl, kSpreadPrefix + 156)
DECLARE_PMID(kImplementationIDSpace, kSetAutoTextFramePrefsCmdImpl, kSpreadPrefix + 157)
DECLARE_PMID(kImplementationIDSpace, kAutoTextFramePrefsCmdDataImpl, kSpreadPrefix + 158)
DECLARE_PMID(kImplementationIDSpace, kMarginsColumnsNewDocResponderImpl, kSpreadPrefix + 159)
DECLARE_PMID(kImplementationIDSpace, kPrivateInsertSpreadCmdImpl, kSpreadPrefix + 160)
DECLARE_PMID(kImplementationIDSpace, kPrivateSetIslandSpreadCmdImpl, kSpreadPrefix + 161)
DECLARE_PMID(kImplementationIDSpace, kSpreadSubjectImpl, kSpreadPrefix + 162)
DECLARE_PMID(kImplementationIDSpace, kMoveToSpreadCmdImpl, kSpreadPrefix + 163)
DECLARE_PMID(kImplementationIDSpace, kCPageLayoutPrefsImpl, kSpreadPrefix + 164)
DECLARE_PMID(kImplementationIDSpace, kSessionPageLayoutPrefsImpl, kSpreadPrefix + 165)
DECLARE_PMID(kImplementationIDSpace, kDocPageLayoutPrefsImpl, kSpreadPrefix + 166)
DECLARE_PMID(kImplementationIDSpace, kSetPageLayoutPrefsCmdImpl, kSpreadPrefix + 167)
DECLARE_PMID(kImplementationIDSpace, kPageLayoutPrefsCmdDataImpl, kSpreadPrefix + 168)
DECLARE_PMID(kImplementationIDSpace, kLayoutViewComposerM2MListenerImpl, kSpreadPrefix + 169)
DECLARE_PMID(kImplementationIDSpace, kSpreadGeometryM2MListenerImpl, kSpreadPrefix + 170)
DECLARE_PMID(kImplementationIDSpace, kRecenterLayoutPolicyImpl, kSpreadPrefix + 171)
DECLARE_PMID(kImplementationIDSpace, kRepositionLayoutPolicyImpl, kSpreadPrefix + 172)
DECLARE_PMID(kImplementationIDSpace, kScaleLayoutPolicyImpl, kSpreadPrefix + 173)
DECLARE_PMID(kImplementationIDSpace, kGuideSliceLayoutPolicyImpl, kSpreadPrefix + 174)
DECLARE_PMID(kImplementationIDSpace, kInterpolationLayoutPolicyImpl, kSpreadPrefix + 175)
DECLARE_PMID(kImplementationIDSpace, kPageFlowLayoutPolicyImpl, kSpreadPrefix + 176)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadSignalDataImpl, kSpreadPrefix + 177)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadSignalRespServiceImpl, kSpreadPrefix + 178)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadMarColResponderImpl, kSpreadPrefix + 179)
DECLARE_PMID(kImplementationIDSpace, kPrivateInsertPagesInSpreadCmdImpl, kSpreadPrefix + 180)
DECLARE_PMID(kImplementationIDSpace, kDocOverlapManagerImpl_OBSOLETE, kSpreadPrefix + 181)
DECLARE_PMID(kImplementationIDSpace, kSetPageMarginsValidCmdImpl, kSpreadPrefix + 182)
DECLARE_PMID(kImplementationIDSpace, kSetPageColumnsValidCmdImpl, kSpreadPrefix + 183)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadScriptLabelResponderImpl, kSpreadPrefix + 184)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadResponderImpl, kSpreadPrefix + 185)
DECLARE_PMID(kImplementationIDSpace, kBindingLocOpenDocResponderImpl, kSpreadPrefix + 186)
DECLARE_PMID(kImplementationIDSpace, kDuplicatePageCmdImpl, kSpreadPrefix + 187)
DECLARE_PMID(kImplementationIDSpace, kDuplicatePageCmdDataImpl, kSpreadPrefix + 188)
DECLARE_PMID(kImplementationIDSpace, kCreatePageFromPageCmdImpl, kSpreadPrefix + 189)
DECLARE_PMID(kImplementationIDSpace, kSpreadVisitorHelperImpl, kSpreadPrefix + 190)
DECLARE_PMID(kImplementationIDSpace, kPageVisitorHelperImpl, kSpreadPrefix + 191)
DECLARE_PMID(kImplementationIDSpace, kRepaginateFlagImpl, kSpreadPrefix + 192)
DECLARE_PMID(kImplementationIDSpace, kSpreadHierarchyM2MListenerImpl, kSpreadPrefix + 193)
DECLARE_PMID(kImplementationIDSpace, kDuplicateSpreadColorLabelResponderImpl, kSpreadPrefix + 194)
DECLARE_PMID(kImplementationIDSpace, kDocPageSizePrefsPhase2ConversionImpl, kSpreadPrefix + 195)
DECLARE_PMID(kImplementationIDSpace, kPageSizesCustomXMLImpl, kSpreadPrefix + 196)
DECLARE_PMID(kImplementationIDSpace, kPageSizesCustomForPagesPanelImpl, kSpreadPrefix + 197)
DECLARE_PMID(kImplementationIDSpace, kPageSizePresetContentHandlerImpl, kSpreadPrefix + 198)
DECLARE_PMID(kImplementationIDSpace, kSpreadScriptProviderImpl, kSpreadPrefix + 199)
DECLARE_PMID(kImplementationIDSpace, kSpreadScriptImpl, kSpreadPrefix + 200)
DECLARE_PMID(kImplementationIDSpace, kDocStylesNewWSResponderImpl, kSpreadPrefix + 201)
DECLARE_PMID(kImplementationIDSpace, kPageScriptProviderImpl, kSpreadPrefix + 202)
DECLARE_PMID(kImplementationIDSpace, kPageScriptImpl, kSpreadPrefix + 203)
DECLARE_PMID(kImplementationIDSpace, kPageTransformImpl, kSpreadPrefix + 204)
DECLARE_PMID(kImplementationIDSpace, kSpreadUtilsImpl, kSpreadPrefix + 205)
DECLARE_PMID(kImplementationIDSpace, kSpreadValidatorImpl, kSpreadPrefix + 206)
DECLARE_PMID(kImplementationIDSpace, kSetPasteboardPrefsCmdImpl, kSpreadPrefix + 207)
DECLARE_PMID(kImplementationIDSpace, kSessionPasteboardPrefsImpl, kSpreadPrefix + 208)
DECLARE_PMID(kImplementationIDSpace, kCPasteboardPrefsImpl, kSpreadPrefix + 209)
DECLARE_PMID(kImplementationIDSpace, kDocPasteboardPrefsImpl, kSpreadPrefix + 210)
DECLARE_PMID(kImplementationIDSpace, kDocPrefsScriptProviderImpl, kSpreadPrefix + 211)
DECLARE_PMID(kImplementationIDSpace, kGridPrefsScriptProviderImpl, kSpreadPrefix + 212)
DECLARE_PMID(kImplementationIDSpace, kPasteboardPrefsScriptProviderImpl, kSpreadPrefix + 213)
DECLARE_PMID(kImplementationIDSpace, kGuidePrefsScriptProviderImpl, kSpreadPrefix + 214)
DECLARE_PMID(kImplementationIDSpace, kViewPrefsScriptProviderImpl, kSpreadPrefix + 215)
DECLARE_PMID(kImplementationIDSpace, kMarginPrefsScriptProviderImpl, kSpreadPrefix + 216)
DECLARE_PMID(kImplementationIDSpace, kPageSizesServiceImpl, kSpreadPrefix + 217)
DECLARE_PMID(kImplementationIDSpace, kPageSizesCDImpl, kSpreadPrefix + 218)
DECLARE_PMID(kImplementationIDSpace, kPageSizesMetricHalfImpl, kSpreadPrefix + 219)
DECLARE_PMID(kImplementationIDSpace, kPageSizesMetricImpl, kSpreadPrefix + 220)
DECLARE_PMID(kImplementationIDSpace, kPageGeometryImpl, kSpreadPrefix + 221)
DECLARE_PMID(kImplementationIDSpace, kPageSizesStandardImpl, kSpreadPrefix + 222)
DECLARE_PMID(kImplementationIDSpace, kPasteboardColorsDataImpl, kSpreadPrefix + 223)
DECLARE_PMID(kImplementationIDSpace, kDocStyleNameDataImpl, kSpreadPrefix + 224)
DECLARE_PMID(kImplementationIDSpace, kDocStyleListMgrImpl, kSpreadPrefix + 225)
DECLARE_PMID(kImplementationIDSpace, kDocSetStyleNameCmdImpl, kSpreadPrefix + 226)
DECLARE_PMID(kImplementationIDSpace, kDocAddStyleCmdImpl, kSpreadPrefix + 227)
DECLARE_PMID(kImplementationIDSpace, kDocDeleteStyleCmdImpl, kSpreadPrefix + 228)
DECLARE_PMID(kImplementationIDSpace, kDocEditStyleCmdImpl, kSpreadPrefix + 229)
DECLARE_PMID(kImplementationIDSpace, kSaveDocumentStyleDataCmdImpl, kSpreadPrefix + 230)
DECLARE_PMID(kImplementationIDSpace, kDocStyleLockInfoImpl, kSpreadPrefix + 231)
DECLARE_PMID(kImplementationIDSpace, kDocStyleNameImpl, kSpreadPrefix + 232)
DECLARE_PMID(kImplementationIDSpace, kDocStyleScriptImpl, kSpreadPrefix + 233)
DECLARE_PMID(kImplementationIDSpace, kDocSetDefaultStyleNameCmdImpl, kSpreadPrefix + 234)
DECLARE_PMID(kImplementationIDSpace, kDocNewDocUsingStyleCmdImpl, kSpreadPrefix + 235)
DECLARE_PMID(kImplementationIDSpace, kDocStyleNamePersistImpl, kSpreadPrefix + 236)
DECLARE_PMID(kImplementationIDSpace, kDocStylesPhase2ConversionImpl, kSpreadPrefix + 237)
DECLARE_PMID(kImplementationIDSpace, kFwdPageSetupPrefsImpl, kSpreadPrefix + 238)
DECLARE_PMID(kImplementationIDSpace, kFwdMarginPrefsImpl, kSpreadPrefix + 239)
DECLARE_PMID(kImplementationIDSpace, kFwdColumnPrefsImpl, kSpreadPrefix + 240)
DECLARE_PMID(kImplementationIDSpace, kFwdAutoTextFramePrefsImpl, kSpreadPrefix + 241)
DECLARE_PMID(kImplementationIDSpace, kDocStyleScriptProviderImpl, kSpreadPrefix + 242)
DECLARE_PMID(kImplementationIDSpace, kPasteboardPrefsP2ConversionImpl, kSpreadPrefix + 243)
DECLARE_PMID(kImplementationIDSpace, kSetSpreadCommandDataImpl, kSpreadPrefix + 245)
DECLARE_PMID(kImplementationIDSpace, kSpreadDebugFlagsImpl, kSpreadPrefix + 246)
DECLARE_PMID(kImplementationIDSpace, kFrameBLGListPersistUIDListDataImpl, kSpreadPrefix + 247)
DECLARE_PMID(kImplementationIDSpace, kDeleteSpreadOrMasterObsImpl, kSpreadPrefix + 248)
DECLARE_PMID(kImplementationIDSpace, kRemovedItemSpreadLayerListImpl, kSpreadPrefix + 249)
DECLARE_PMID(kImplementationIDSpace, kIgnoreItemsOnPasteboardImpl, kSpreadPrefix + 250)
DECLARE_PMID(kImplementationIDSpace, kStyleSessionColumnPrefsImpl, kSpreadPrefix + 251)
DECLARE_PMID(kImplementationIDSpace, kStyleSessionMarginPrefsImpl, kSpreadPrefix + 252)
DECLARE_PMID(kImplementationIDSpace, kSetPageColorLabelCmdImpl, kSpreadPrefix + 253)
DECLARE_PMID(kImplementationIDSpace, kPageSizeM2MListenerImpl, kSpreadPrefix + 254)
DECLARE_PMID(kImplementationIDSpace, kPageColorLabelImpl, kSpreadPrefix + 255)

//gap
DECLARE_PMID(kImplementationIDSpace, kPageCustomSizesMigrationImpl, kSpreadPrefix2 + 30)
DECLARE_PMID(kImplementationIDSpace, kSetOptionalPageCmdImpl, kSpreadPrefix2 + 31)
DECLARE_PMID(kImplementationIDSpace, kSetLayoutPolicyCmdImpl, kSpreadPrefix2 + 32)
DECLARE_PMID(kImplementationIDSpace, kSetLayoutPolicyCmdDataImpl, kSpreadPrefix2 + 33)
DECLARE_PMID(kImplementationIDSpace, kLayoutSnapshotCmdDataImpl, kSpreadPrefix2 + 34)
DECLARE_PMID(kImplementationIDSpace, kSnapshotLayoutCmdImpl, kSpreadPrefix2 + 35)
DECLARE_PMID(kImplementationIDSpace, kDeleteLayoutSnapshotCmdImpl, kSpreadPrefix2 + 36)
DECLARE_PMID(kImplementationIDSpace, kDeleteAllLayoutSnapshotsCmdImpl, kSpreadPrefix2 + 37)
DECLARE_PMID(kImplementationIDSpace, kEnableSnapshotBlendingCmdDataImpl, kSpreadPrefix2 + 38)
DECLARE_PMID(kImplementationIDSpace, kEnableSnapshotBlendingCmdImpl, kSpreadPrefix2 + 39)
DECLARE_PMID(kImplementationIDSpace, kLayoutConstraintsImpl, kSpreadPrefix2 + 40)
DECLARE_PMID(kImplementationIDSpace, kSetLayoutConstraintsCmdImpl, kSpreadPrefix2 + 41)
DECLARE_PMID(kImplementationIDSpace, kSetLayoutConstraintsCmdDataImpl, kSpreadPrefix2 + 42)
DECLARE_PMID(kImplementationIDSpace, kPageSizesDPSImpl, kSpreadPrefix2 + 43)
DECLARE_PMID(kImplementationIDSpace, kPageSizeListImpl, kSpreadPrefix2 + 44)
DECLARE_PMID(kImplementationIDSpace, kFwdShowLayoutGridPrefsImpl, kSpreadPrefix2 + 45)
DECLARE_PMID(kImplementationIDSpace, kSetPagesPerSpreadCmdImpl, kSpreadPrefix2 + 46)
DECLARE_PMID(kImplementationIDSpace, kDocUIFlagImpl, kSpreadPrefix2 + 47)
DECLARE_PMID(kImplementationIDSpace, kRecentDocStyleListMgrImpl, kSpreadPrefix2 + 48)
DECLARE_PMID(kImplementationIDSpace, kDocSetRecentStyleInfoCmdImpl, kSpreadPrefix2 + 49)
DECLARE_PMID(kImplementationIDSpace, kSetDocMarginsCmdImpl, kSpreadPrefix2 + 50)
DECLARE_PMID(kImplementationIDSpace, kDocMarginsCmdDataImpl, kSpreadPrefix2 + 51)
DECLARE_PMID(kImplementationIDSpace, kMasterPageGridRecalcImpl, kSpreadPrefix2 + 52)

// <Service ID>
// Service IDs
DECLARE_PMID(kServiceIDSpace, kService_PageSizes, kSpreadPrefix + 1)
DECLARE_PMID(kServiceIDSpace, kDuplicateSpreadSignalResponderService, kSpreadPrefix + 2)
DECLARE_PMID(kServiceIDSpace, kPageNumEvenOddnessChangeSignalResponderService, kSpreadPrefix + 3)

// <Action ID>
// Action IDs

// <Error ID>
// Error Codes
DECLARE_PMID(kErrorIDSpace, kCantExceedPubPageLimitError,		kSpreadPrefix + 1)
DECLARE_PMID(kErrorIDSpace, kCantExceedSpreadPageLimitError,	kSpreadPrefix + 2)
DECLARE_PMID(kErrorIDSpace, kLastSpreadError,					kSpreadPrefix + 3)
DECLARE_PMID(kErrorIDSpace, kCantMoveToSpreadError,				kSpreadPrefix + 4)
DECLARE_PMID(kErrorIDSpace, kLastPageError,						kSpreadPrefix + 5)
DECLARE_PMID(kErrorIDSpace, kCantSetPageSizeError,				kSpreadPrefix + 6)
DECLARE_PMID(kErrorIDSpace, kCantDetermineSpreadError,			kSpreadPrefix + 7)
DECLARE_PMID(kErrorIDSpace, kObjectsNotOnSameSpreadError,		kSpreadPrefix + 8)
DECLARE_PMID(kErrorIDSpace, kCantDeleteObjectBeingDeletedError,	kSpreadPrefix + 9)
DECLARE_PMID(kErrorIDSpace, kPageSizeSmallerThanMarginsAndColumnsError,	kSpreadPrefix + 10)

// <Message ID>
// Message IDs (start at 200)
#define kSpreadMsgPrefix					(kSpreadPrefix + 200)
//DECLARE_PMID(kMessageIDSpace, kPageItemOnSpreadAddedMessage, kSpreadMsgPrefix + 1)	// sent by SpreadOverlapManager::AddGeo() with IID_ISPREADOVERLAPMANAGER
//DECLARE_PMID(kMessageIDSpace, kPageItemOnSpreadRemovedMessage, kSpreadMsgPrefix + 2)	// sent by SpreadOverlapManager::RemoveGeo() with IID_ISPREADOVERLAPMANAGER
DECLARE_PMID(kMessageIDSpace, kPageItemOnSpreadChangedMessage, kSpreadMsgPrefix + 3)	// sent by SpreadOverlapManager::ChangeGeo() with IID_ISPREADOVERLAPMANAGER
DECLARE_PMID(kMessageIDSpace, kParentOfTextFrameChangedMessage, kSpreadMsgPrefix + 4)	// sent by SpreadOverlapManager::ChangeGeo() with IID_ISPREADOVERLAPMANAGER


// These used to be in TransformPanelID.h
DECLARE_PMID(kMessageIDSpace, kPrefShowGlobalChangedMessage, kSpreadMsgPrefix + 5)
DECLARE_PMID(kMessageIDSpace, kPrefShowStrokeBoundsChangedMessage, kSpreadMsgPrefix + 6)
DECLARE_PMID(kMessageIDSpace, kPrefTransformContentChangedMessage, kSpreadMsgPrefix + 7)
DECLARE_PMID(kMessageIDSpace, kPrefShowContentOffsetChangedMessage, kSpreadMsgPrefix + 8)
DECLARE_PMID(kMessageIDSpace, kPrefScaleStrokesChangedMessage, kSpreadMsgPrefix + 9)
DECLARE_PMID(kMessageIDSpace, kPrefScaleUsingLensChangedMessage, kSpreadMsgPrefix + 10)
DECLARE_PMID(kMessageIDSpace, kPrefScaleXPEffectsChangedMessage, kSpreadMsgPrefix + 11)

//
//Script Element IDs
//

//Suites

//Objects
DECLARE_PMID(kScriptInfoIDSpace, kDocPrefsObjectScriptElement,						kSpreadPrefix + 35)
DECLARE_PMID(kScriptInfoIDSpace, kGridPrefsObjectScriptElement,						kSpreadPrefix + 36)
DECLARE_PMID(kScriptInfoIDSpace, kGuidePrefsObjectScriptElement,					kSpreadPrefix + 37)
DECLARE_PMID(kScriptInfoIDSpace, kMarginPrefsObjectScriptElement,					kSpreadPrefix + 38)
DECLARE_PMID(kScriptInfoIDSpace, kPasteboardPrefsObjectScriptElement,				kSpreadPrefix + 39)
DECLARE_PMID(kScriptInfoIDSpace, kViewPrefsObjectScriptElement,						kSpreadPrefix + 40)
DECLARE_PMID(kScriptInfoIDSpace, kSpreadObjectScriptElement,						kSpreadPrefix + 41)
DECLARE_PMID(kScriptInfoIDSpace, kPageObjectScriptElement,							kSpreadPrefix + 42)
DECLARE_PMID(kScriptInfoIDSpace, kDocStyleObjectScriptElement,						kSpreadPrefix + 43)

//Events
DECLARE_PMID(kScriptInfoIDSpace, kMoveSpreadMethodScriptElement,						kSpreadPrefix + 80)
DECLARE_PMID(kScriptInfoIDSpace, kDuplicateSpreadMethodScriptElement,				kSpreadPrefix + 81)
DECLARE_PMID(kScriptInfoIDSpace, kCreateSpreadMethodScriptElement,					kSpreadPrefix + 82)
DECLARE_PMID(kScriptInfoIDSpace, kMovePageMethodScriptElement,						kSpreadPrefix + 83)
DECLARE_PMID(kScriptInfoIDSpace, kDuplicatePageMethodScriptElement,					kSpreadPrefix + 84)
DECLARE_PMID(kScriptInfoIDSpace, kCreatePageMethodScriptElement,						kSpreadPrefix + 85)
DECLARE_PMID(kScriptInfoIDSpace, kSnapshotLayoutMethodScriptElement,				kSpreadPrefix + 86)
DECLARE_PMID(kScriptInfoIDSpace, kDeleteLayoutSnapshotMethodScriptElement,			kSpreadPrefix + 87)
DECLARE_PMID(kScriptInfoIDSpace, kDeleteAllLayoutSnapshotsMethodScriptElement,		kSpreadPrefix + 88)


//Properties
DECLARE_PMID(kScriptInfoIDSpace, kPagePixelDensityPropertyScriptElement,			kSpreadPrefix + 97)
DECLARE_PMID(kScriptInfoIDSpace, kAppliedAlternateLayoutPropertyScriptElement,		kSpreadPrefix + 98)
DECLARE_PMID(kScriptInfoIDSpace, kOptionalPagePropertyScriptElement,				kSpreadPrefix + 99)
DECLARE_PMID(kScriptInfoIDSpace, kDocPrefsPropertyScriptElement,					kSpreadPrefix + 100)
DECLARE_PMID(kScriptInfoIDSpace, kNumPagesPropertyScriptElement,					kSpreadPrefix + 101)
DECLARE_PMID(kScriptInfoIDSpace, kPagesPerSpreadPropertyScriptElement,				kSpreadPrefix + 102)
DECLARE_PMID(kScriptInfoIDSpace, kPageHeightPropertyScriptElement,					kSpreadPrefix + 103)
DECLARE_PMID(kScriptInfoIDSpace, kPageWidthPropertyScriptElement,					kSpreadPrefix + 104)
DECLARE_PMID(kScriptInfoIDSpace, kPageOrientationPropertyScriptElement,				kSpreadPrefix + 105)
DECLARE_PMID(kScriptInfoIDSpace, kPasteRemembersLayersPropertyScriptElement,		kSpreadPrefix + 106)
DECLARE_PMID(kScriptInfoIDSpace, kAllowPageShufflePropertyScriptElement,			kSpreadPrefix + 107)
DECLARE_PMID(kScriptInfoIDSpace, kPreserveLayoutWhenShufflingPropertyScriptElement,	kSpreadPrefix + 108)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineGridRelativeOptionPropertyScriptElement,	kSpreadPrefix + 109)
DECLARE_PMID(kScriptInfoIDSpace, kColumnGuidesColorPropertyScriptElement,			kSpreadPrefix + 110)
DECLARE_PMID(kScriptInfoIDSpace, kMarginGuideColorPropertyScriptElement,			kSpreadPrefix + 111)
DECLARE_PMID(kScriptInfoIDSpace, kKeepTogetherPropertyScriptElement,				kSpreadPrefix + 112)
DECLARE_PMID(kScriptInfoIDSpace, kDocumentOffsetPropertyScriptElement,				kSpreadPrefix + 113)
DECLARE_PMID(kScriptInfoIDSpace, kAppliedSectionPropertyScriptElement,				kSpreadPrefix + 114)
DECLARE_PMID(kScriptInfoIDSpace, kDocBleedInsidePropertyScriptElement,				kSpreadPrefix + 115)
DECLARE_PMID(kScriptInfoIDSpace, kDocBleedTopPropertyScriptElement,					kSpreadPrefix + 116)
DECLARE_PMID(kScriptInfoIDSpace, kDocBleedOutsidePropertyScriptElement,				kSpreadPrefix + 117)
DECLARE_PMID(kScriptInfoIDSpace, kDocBleedBottomPropertyScriptElement,				kSpreadPrefix + 118)
DECLARE_PMID(kScriptInfoIDSpace, kDocSlugInsidePropertyScriptElement,				kSpreadPrefix + 119)
DECLARE_PMID(kScriptInfoIDSpace, kDocSlugTopPropertyScriptElement,					kSpreadPrefix + 120)
DECLARE_PMID(kScriptInfoIDSpace, kDocSlugOutsidePropertyScriptElement,				kSpreadPrefix + 121)
DECLARE_PMID(kScriptInfoIDSpace, kDocSlugBottomPropertyScriptElement,				kSpreadPrefix + 122)
DECLARE_PMID(kScriptInfoIDSpace, kGridPrefsPropertyScriptElement,					kSpreadPrefix + 123)
DECLARE_PMID(kScriptInfoIDSpace, kGridShownPropertyScriptElement,					kSpreadPrefix + 124)
DECLARE_PMID(kScriptInfoIDSpace, kGridSnapToPropertyScriptElement,					kSpreadPrefix + 125)
DECLARE_PMID(kScriptInfoIDSpace, kHorizGridDivisionPropertyScriptElement,			kSpreadPrefix + 126)
DECLARE_PMID(kScriptInfoIDSpace, kVertGridDivisionPropertyScriptElement,			kSpreadPrefix + 127)
DECLARE_PMID(kScriptInfoIDSpace, kHorizGridSubdivisionPropertyScriptElement,		kSpreadPrefix + 128)
DECLARE_PMID(kScriptInfoIDSpace, kVertGridSubdivisionPropertyScriptElement,			kSpreadPrefix + 129)
DECLARE_PMID(kScriptInfoIDSpace, kGridColorPropertyScriptElement,					kSpreadPrefix + 130)
DECLARE_PMID(kScriptInfoIDSpace, kGridsInBackPropertyScriptElement,					kSpreadPrefix + 131)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineGridShownPropertyScriptElement,			kSpreadPrefix + 132)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineStartPropertyScriptElement,				kSpreadPrefix + 133)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineDivisionPropertyScriptElement,			kSpreadPrefix + 134)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineViewThresholdPropertyScriptElement,		kSpreadPrefix + 135)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineColorPropertyScriptElement,				kSpreadPrefix + 136)
DECLARE_PMID(kScriptInfoIDSpace, kGuidePrefsPropertyScriptElement,					kSpreadPrefix + 137)
DECLARE_PMID(kScriptInfoIDSpace, kGuidesInBackPropertyScriptElement,				kSpreadPrefix + 138)
DECLARE_PMID(kScriptInfoIDSpace, kGuidesShownPropertyScriptElement,					kSpreadPrefix + 139)
DECLARE_PMID(kScriptInfoIDSpace, kGuidesLockedPropertyScriptElement,				kSpreadPrefix + 140)
DECLARE_PMID(kScriptInfoIDSpace, kGuidesSnapToPropertyScriptElement,				kSpreadPrefix + 141)
DECLARE_PMID(kScriptInfoIDSpace, kRulerGuidesViewThresholdPropertyScriptElement,	kSpreadPrefix + 142)
DECLARE_PMID(kScriptInfoIDSpace, kRulerGuidesColorPropertyScriptElement,			kSpreadPrefix + 143)
DECLARE_PMID(kScriptInfoIDSpace, kMarginPrefsPropertyScriptElement,					kSpreadPrefix + 144)
DECLARE_PMID(kScriptInfoIDSpace, kColumnCountPropertyScriptElement,					kSpreadPrefix + 145)
DECLARE_PMID(kScriptInfoIDSpace, kColumnGutterPropertyScriptElement,				kSpreadPrefix + 146)
DECLARE_PMID(kScriptInfoIDSpace, kPageBindingPropertyScriptElement,					kSpreadPrefix + 147)
DECLARE_PMID(kScriptInfoIDSpace, kColumnDirectionPropertyScriptElement,				kSpreadPrefix + 148)
DECLARE_PMID(kScriptInfoIDSpace, kPasteboardBorderPropertyScriptElement,			kSpreadPrefix + 149)
DECLARE_PMID(kScriptInfoIDSpace, kPasteboardColorPropertyScriptElement,				kSpreadPrefix + 150)
DECLARE_PMID(kScriptInfoIDSpace, kViewPrefsPropertyScriptElement,					kSpreadPrefix + 151)
DECLARE_PMID(kScriptInfoIDSpace, kGuideSnapToZonePropertyScriptElement,				kSpreadPrefix + 152)
DECLARE_PMID(kScriptInfoIDSpace, kCursorKeyIncrementPropertyScriptElement,			kSpreadPrefix + 153)
DECLARE_PMID(kScriptInfoIDSpace, kHorzMeasurementUnitsPropertyScriptElement,		kSpreadPrefix + 154)
DECLARE_PMID(kScriptInfoIDSpace, kVertMeasurementUnitsPropertyScriptElement,		kSpreadPrefix + 155)
DECLARE_PMID(kScriptInfoIDSpace, kShowMasterItemsPropertyScriptElement,				kSpreadPrefix + 156)
DECLARE_PMID(kScriptInfoIDSpace, kRulerOriginPropertyScriptElement,					kSpreadPrefix + 157)
DECLARE_PMID(kScriptInfoIDSpace, kShowRulersPropertyScriptElement,					kSpreadPrefix + 158)
DECLARE_PMID(kScriptInfoIDSpace, kShowFrameEdgesPropertyScriptElement,				kSpreadPrefix + 159)
DECLARE_PMID(kScriptInfoIDSpace, kTypographicMeasurementUnitsPropertyScriptElement,	kSpreadPrefix + 160)
DECLARE_PMID(kScriptInfoIDSpace, kTextSizeMeasurementUnitsPropertyScriptElement,	kSpreadPrefix + 161)
DECLARE_PMID(kScriptInfoIDSpace, kPrintDialogMeasurementUnitsPropertyScriptElement,	kSpreadPrefix + 162)
DECLARE_PMID(kScriptInfoIDSpace, kLineMeasurementUnitsPropertyScriptElement,		kSpreadPrefix + 163)
DECLARE_PMID(kScriptInfoIDSpace, kPasteboardPrefsPropertyScriptElement,				kSpreadPrefix + 164)
DECLARE_PMID(kScriptInfoIDSpace, kPageCountPropertyScriptElement,					kSpreadPrefix + 165)
DECLARE_PMID(kScriptInfoIDSpace, kBindingLocationPropertyScriptElement,				kSpreadPrefix + 166)
DECLARE_PMID(kScriptInfoIDSpace, kPreviewBackgroundColorPropertyScriptElement,		kSpreadPrefix + 167)
DECLARE_PMID(kScriptInfoIDSpace, kPageTrapStylePropertyScriptElement,				kSpreadPrefix + 168)
DECLARE_PMID(kScriptInfoIDSpace, kTransformContentPropertyScriptElement,			kSpreadPrefix + 169) //XFIssue
DECLARE_PMID(kScriptInfoIDSpace, kDimensionsIncludesStrokePropertyScriptElement,	kSpreadPrefix + 170)
DECLARE_PMID(kScriptInfoIDSpace, kTransformationsAreTotalsPropertyScriptElement,	kSpreadPrefix + 171)
DECLARE_PMID(kScriptInfoIDSpace, kShowContentOffsetPropertyScriptElement,			kSpreadPrefix + 172)
DECLARE_PMID(kScriptInfoIDSpace, kScaleStrokesPropertyScriptElement,				kSpreadPrefix + 173)
DECLARE_PMID(kScriptInfoIDSpace, kWritingDirectionPropertyScriptElement,			kSpreadPrefix + 174)
DECLARE_PMID(kScriptInfoIDSpace, kDocBleedUniformPropertyScriptElement,				kSpreadPrefix + 175)
DECLARE_PMID(kScriptInfoIDSpace, kDocSlugUniformPropertyScriptElement,				kSpreadPrefix + 176)
DECLARE_PMID(kScriptInfoIDSpace, kBleedGuideColorPropertyScriptElement,				kSpreadPrefix + 177)
DECLARE_PMID(kScriptInfoIDSpace, kSlugGuideColorPropertyScriptElement,				kSpreadPrefix + 178)
DECLARE_PMID(kScriptInfoIDSpace, kPointsPerInchPropertyScriptElement,				kSpreadPrefix + 179)
DECLARE_PMID(kScriptInfoIDSpace, kColumnGuidesLockedPropertyScriptElement,			kSpreadPrefix + 180)
DECLARE_PMID(kScriptInfoIDSpace, kHorzCustomPointsPropertyScriptElement,			kSpreadPrefix + 181)
DECLARE_PMID(kScriptInfoIDSpace, kVertCustomPointsPropertyScriptElement,			kSpreadPrefix + 182)
DECLARE_PMID(kScriptInfoIDSpace, kPageSidePropertyScriptElement,					kSpreadPrefix + 183)
DECLARE_PMID(kScriptInfoIDSpace, kHasCustomColumnsPropertyScriptElement,			kSpreadPrefix + 184)
DECLARE_PMID(kScriptInfoIDSpace, kColumnsPositionsPropertyScriptElement,			kSpreadPrefix + 185)
DECLARE_PMID(kScriptInfoIDSpace, kMasterTextFramePropertyScriptElement,				kSpreadPrefix + 186)	// Renamed to Primary Text Frame
DECLARE_PMID(kScriptInfoIDSpace, kPageSizePropertyScriptElement,					kSpreadPrefix + 187)
DECLARE_PMID(kScriptInfoIDSpace, kWhenScalingPropertyScriptElement,					kSpreadPrefix + 188)
DECLARE_PMID(kScriptInfoIDSpace, kPageDescriptorPropertyScriptElement,				kSpreadPrefix + 189)
DECLARE_PMID(kScriptInfoIDSpace, kStrokesScalePropertyScriptElement,				kSpreadPrefix + 190)
DECLARE_PMID(kScriptInfoIDSpace, kSnippetLocationPropertyScriptElement,				kSpreadPrefix + 191)
DECLARE_PMID(kScriptInfoIDSpace, kPageColorLabelPropertyScriptElement,				kSpreadPrefix + 192)
DECLARE_PMID(kScriptInfoIDSpace, kStartPageNumberPropertyScriptElement,				kSpreadPrefix + 193)
DECLARE_PMID(kScriptInfoIDSpace, kDocumentIntentPropertyScriptElement,				kSpreadPrefix + 194)
DECLARE_PMID(kScriptInfoIDSpace, kPageBoundsPropertyScriptElement,					kSpreadPrefix + 195)
DECLARE_PMID(kScriptInfoIDSpace, kPasteboardMarginsPropertyScriptElement,			kSpreadPrefix + 196)
DECLARE_PMID(kScriptInfoIDSpace, kStrokeMeasurementUnitsPropertyScriptElement,		kSpreadPrefix + 197)
DECLARE_PMID(kScriptInfoIDSpace, kPrimaryTextFramePropertyScriptElement,			kSpreadPrefix + 198)	// New name for Master Text Frame
DECLARE_PMID(kScriptInfoIDSpace, kLayoutRulePropertyScriptElement,					kSpreadPrefix + 199)	

//Enums
DECLARE_PMID(kScriptInfoIDSpace, kBindingAlignmentEnumScriptElement,				kSpreadPrefix + 200)
DECLARE_PMID(kScriptInfoIDSpace, kPageOrientationEnumScriptElement,					kSpreadPrefix + 201)
DECLARE_PMID(kScriptInfoIDSpace, kRulerOriginEnumScriptElement,						kSpreadPrefix + 202)
DECLARE_PMID(kScriptInfoIDSpace, kMeasurementUnitsEnumScriptElement,				kSpreadPrefix + 203)
DECLARE_PMID(kScriptInfoIDSpace, kPageBindingEnumScriptElement,						kSpreadPrefix + 204)
DECLARE_PMID(kScriptInfoIDSpace, kBaselineGridRelativeOptionEnumScriptElement,		kSpreadPrefix + 205)
DECLARE_PMID(kScriptInfoIDSpace, kPageSideEnumScriptElement,						kSpreadPrefix + 206)
DECLARE_PMID(kScriptInfoIDSpace, kScalingMethodEnumScriptElement,					kSpreadPrefix + 207)
DECLARE_PMID(kScriptInfoIDSpace, kPageColorEnumScriptElement,						kSpreadPrefix + 208)
DECLARE_PMID(kScriptInfoIDSpace, kDocumentIntentEnumScriptElement,					kSpreadPrefix + 209)
DECLARE_PMID(kScriptInfoIDSpace, kLayoutRuleEnumScriptElement,						kSpreadPrefix + 210)
DECLARE_PMID(kScriptInfoIDSpace, kSnapshotBlendingModeEnumScriptElement,			kSpreadPrefix + 211)

DECLARE_PMID(kScriptInfoIDSpace, kMatchPreviewToThemeColorPropertyScriptElement,	kSpreadPrefix + 212)


//More Properties
DECLARE_PMID(kScriptInfoIDSpace, kSnapshotBlendingPropertyScriptElement,			kSpreadPrefix + 220)
DECLARE_PMID(kScriptInfoIDSpace, kEffectsScalePropertyScriptElement,			kSpreadPrefix + 221)

//GUIDS
// {2407F2DA-4E36-11d1-8047-0060B03C02E4}
#define kSpread_CLSID { 0x2407f2da, 0x4e36, 0x11d1, { 0x80, 0x47, 0x0, 0x60, 0xb0, 0x3c, 0x2, 0xe4 } }
// {2407F2DB-4E36-11d1-8047-0060B03C02E4}
#define kSpreads_CLSID { 0x2407f2db, 0x4e36, 0x11d1, { 0x80, 0x47, 0x0, 0x60, 0xb0, 0x3c, 0x2, 0xe4 } }
// {49173ED6-8B86-11d1-8065-0060B03C02E4}
#define kPage_CLSID { 0x49173ed6, 0x8b86, 0x11d1, { 0x80, 0x65, 0x0, 0x60, 0xb0, 0x3c, 0x2, 0xe4 } }
// {49173ED7-8B86-11d1-8065-0060B03C02E4}
#define kPages_CLSID { 0x49173ed7, 0x8b86, 0x11d1, { 0x80, 0x65, 0x0, 0x60, 0xb0, 0x3c, 0x2, 0xe4 } }
// {EE964063-06C6-11d2-AAC9-00C04FA349C7}
#define kDocPref_CLSID { 0xee964063, 0x6c6, 0x11d2, { 0xaa, 0xc9, 0x0, 0xc0, 0x4f, 0xa3, 0x49, 0xc7 } }
// {EE96406B-06C6-11d2-AAC9-00C04FA349C7}
#define kGridPref_CLSID { 0xee96406b, 0x6c6, 0x11d2, { 0xaa, 0xc9, 0x0, 0xc0, 0x4f, 0xa3, 0x49, 0xc7 } }
// {EE964069-06C6-11d2-AAC9-00C04FA349C7}
#define kGuidePref_CLSID { 0xee964069, 0x6c6, 0x11d2, { 0xaa, 0xc9, 0x0, 0xc0, 0x4f, 0xa3, 0x49, 0xc7 } }
// {EE964073-06C6-11d2-AAC9-00C04FA349C7}
#define kMarginPref_CLSID { 0xee964073, 0x6c6, 0x11d2, { 0xaa, 0xc9, 0x0, 0xc0, 0x4f, 0xa3, 0x49, 0xc7 } }
// {FD8BFE64-6BBB-4381-8F4C-D434627CA358}
#define kPasteboardPref_CLSID {0xfd8bfe64, 0x6bbb, 0x4381, { 0x8f, 0x4c, 0xd4, 0x34, 0x62, 0x7c, 0xa3, 0x58 } }
// {EE964077-06C6-11d2-AAC9-00C04FA349C7}
#define kViewPref_CLSID { 0xee964077, 0x6c6, 0x11d2, { 0xaa, 0xc9, 0x0, 0xc0, 0x4f, 0xa3, 0x49, 0xc7 } }
// {50A1B8D7-8481-4982-9C26-2CAC271A8C39}
#define kDocumentStyle_CLSID { 0x50a1b8d7, 0x8481, 0x4982, { 0x9c, 0x26, 0x2c, 0xac, 0x27, 0x1a, 0x8c, 0x39 } }
// {CAC0FDBA-A897-4663-A9D9-43F4EB8C3118}
#define kDocumentStyles_CLSID { 0xcac0fdba, 0xa897, 0x4663, { 0xa9, 0xd9, 0x43, 0xf4, 0xeb, 0x8c, 0x31, 0x18 } }

#endif // __SpreadID__
